### ISSUE TITLE
Learn more is navigating back to home page in financial blogs and tools

### ISSUE THREAD

**Issue by KhushiTiwarii** [ayush-that/FinVeda#10]
![Screenshot 2024-05-10 125254](https://github.com/ayush-that/FinVeda/assets/137861160/7cb6ea2b-e46a-45cc-b747-2ec5e8746989)

Upon clicking on the learn more the page gets navigated back to the home page and not on the desired page.Please assign me this Under GSSOC'24

**Comment by ayush-that** [comment]
Hi @KhushiTiwarii,
I am assigning this issue to you under gssoc. All the best.

**Comment by KhushiTiwarii** [comment]
Thankyou I'll start contributing to it
