### ISSUE TITLE
Add contact us page to the website 

### ISSUE THREAD

**Issue by rutikakengal** [ayush-that/FinVeda#1003]
@ayush-that assign me i like to work on it Add gssoc-ext,hactoberfast accepted and level to the issue

**Comment by Codersweta7** [comment]
@sampadatiwari30 
Please assign this task to me .

**Comment by Sampadatiwari** [comment]
@Codersweta7 this issue has been already resolved.

**Comment by Codersweta7** [comment]
@Sampadatiwari 
Is there some work I can do on this repo ?? 
I am not able to find something ...
