### ISSUE TITLE
[style]: Enhance the navbar and footer section of the website 

### ISSUE THREAD

**Issue by T-Fathima** [ayush-that/FinVeda#1005]
### What's the style idea?

We need to improve following things:
This issue aims to enhance the user interface of the footer and navbar sections of the application. The following changes have been made:

**Improved Navbar:**
Added a background color to the navbar for better visibility and aesthetics.
Enhanced the spacing and alignment of the navigation items.

**Footer Enhancements:**
Updated the footer layout for a cleaner look.
Ensured consistency with the overall theme of the application.

### Add screenshots

Add screenshots
![image](https://github.com/user-attachments/assets/40922bd7-89a1-4214-ae49-2820cbd98065)

I would like to work on this issue.
Please assign it to me under gssoc-ext'24 and hacktoberfest
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by PriyaKaushik-1** [comment]
assign this project

**Comment by T-Fathima** [comment]
It has been assigned to me. @PriyaKaushik-1

**Comment by T-Fathima** [comment]
@Deekshashakyawal I have made a PR.
Please review.
