### ISSUE TITLE
say hi to finVeda is being displayed on top with big letters on every page 

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [ayush-that/FinVeda#1007]
### What happened?

<img width="958" alt="12" src="https://github.com/user-attachments/assets/6f41fb1a-7bb1-4d13-bdb8-8e63e6b960ac">

### How can we reproduce this bug?

say hi is being visible on every page instead it is highlighted in home page and in other ages the page will be occupied 80 percent and other say hi will be 20 percent

### Desktop Information (Optional)

microsoft,binge

### Urgency (Optional)

High priority

**Comment by AditiKushwaha01** [comment]
Hi, assign this issue to me I will resolve it as required.
