### ISSUE TITLE
Title: In the navbar just change the Login/Register button color on hover

### ISSUE THREAD

**Issue by Hemraj-7** [ayush-that/FinVeda#1021]
### Is your feature request related to a problem? Please describe.

In the navbar just change the Login/Register button color on hover because now when it is hovering it's color is merge on website color so it is looking bad.

![Screenshot 2024-10-08 145244](https://github.com/user-attachments/assets/5b05d9c1-e94c-4033-882e-22334852190e)

### Describe the solution you'd like.

In the navbar just change the Login/Register button color on hover because now when it is hovering it's color is merge on website color so it is looking bad.

### Describe alternatives you've considered.

I want to change hover color and some property to enhance look 

### Add any other context or screenshots about the feature request here.

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Yash-Jadaun** [comment]
plz assign me this issue.
