### ISSUE TITLE
Title: adding dark mode

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ayush-that/FinVeda#1026]
### Is your feature request related to a problem? Please describe.

@ayush-that can i add a dark mode feature to this website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
Not needed
