### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by YadlaMani** [ayush-that/FinVeda#103]
Improving ui by providing underline in the navbar section of the page currently visited
Before
![image](https://github.com/ayush-that/FinVeda/assets/133841094/e49b2a49-2979-4f9c-befd-8938a59bf9ac)
After
![image](https://github.com/ayush-that/FinVeda/assets/133841094/82f4615a-58f1-4649-9aa1-1d9d4124ebda)
my drawing is bad!

**Comment by YadlaMani** [comment]
@ayush-that @sanjay-kv assign me this issue under gssoc'24

**Comment by sanjay-kv** [comment]
I'm not owner of this repo

**Comment by YadlaMani** [comment]
@sanjay-kv sorry bro i have edited it

**Comment by ayush-that** [comment]
> Improving ui by providing underline in the navbar section of the page currently visited Before ![image](https://private-user-images.githubusercontent.com/133841094/330669955-e49b2a49-2979-4f9c-befd-8938a59bf9ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTU2NDMsIm5iZiI6MTcxNTkxNTM0MywicGF0aCI6Ii8xMzM4NDEwOTQvMzMwNjY5OTU1LWU0OWIyYTQ5LTI5NzktNGY5Yy1iZWZkLTg5MzhhNTliZjlhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwMzA5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDcxZjQ1NDY0NmVkYzVkZThhZWJmNjkyYjY3NTVmMDc1YjE1MDM2ZmZkYTJjYTZlY2E4Mzk2N2M4ZTg2Y2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3HoPLFvtw4ju0zaY3g2ZJXwCS_JGsjK7N9t2nbxZ0IM) After ![image](https://private-user-images.githubusercontent.com/133841094/330670242-82f4615a-58f1-4649-9aa1-1d9d4124ebda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTU2NDMsIm5iZiI6MTcxNTkxNTM0MywicGF0aCI6Ii8xMzM4NDEwOTQvMzMwNjcwMjQyLTgyZjQ2MTVhLTU4ZjEtNDY0OS05YWExLTFkOWQ0MTI0ZWJkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwMzA5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTIzMjE3ZmQyMzRiZTA1YTVkMTVlMWFhMzdhOTk2ZjVkYWU1NTUxYTBhMjRkZWRiM2UyNGU2NGJiYTc4MGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-JIsSUoi_y3OpWsHTFAObmBnk2RQcy6rfqCiAL_HvUc) my drawing is bad!

Assigning under gssoc.
Good Luck.

**Comment by YadlaMani** [comment]
@ayush-that  once look into pr again i have mentioned the bug

**Comment by Agarwalvidu** [comment]
It is updated now. Thank you for raising issue, looking for your more inputs. For now I am closing this issue.
