### ISSUE TITLE
improving the navbar

### ISSUE THREAD

**Issue by Devanshu1603** [ayush-that/FinVeda#1031]
### What's the style idea?

We need to improve  the navbar , aligning the icons and option in same line and also improving the login and signup option. @Sampadatiwari  please assign this to me under gssoc-extended .

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Devanshu1603** [comment]
@sampadatiwari30  please add gssoc-ext tag and level to merged PR #1030 , otherwise it will not be counted in my gssoc-ext contribution that will affect my position on leatherboard.

**Comment by Devanshu1603** [comment]
@sampadatiwari30  i am not talking about this issue , instead about issue #970   with PR #1030 , you didn't add levels before merging that PR . In that case i will not get any point in gssoc-ext leaderboard , please review the issue and add the level accordingly.

**Comment by Sampadatiwari** [comment]
@Devanshu1603, don't be tensioned I will do it by evening. Be patience.
