### ISSUE TITLE
[Bug Title here] DARK MODE OPTION NOT AVAILABLE

### ISSUE THREAD

**Issue by HS202022** [ayush-that/FinVeda#1033]
### What happened?

DARK MODE OPTION NOT AVAILABLE

### How can we reproduce this bug?

DARK MODE OPTION NOT AVAILABLE

### Desktop Information (Optional)

microsoft , chrome

### Urgency (Optional)

Medium priority

**Comment by Deekshashakyawal** [comment]
Do add Screenshots to your raised issues as it would be easier for us to assign and look for what you are trying to describe about the problem
