### ISSUE TITLE
features : Added new icons in the contact us section

### ISSUE THREAD

**Issue by SadafKausar2025** [ayush-that/FinVeda#105]
These Icons gives a good look to the Contact Us lines and are understandable to anyone visiting the website

before image

![Screenshot (1740)](https://github.com/ayush-that/FinVeda/assets/137484958/70ad3e0d-277b-4d64-8c02-ac9c3e75dd1f)

after image

![Screenshot (1739)](https://github.com/ayush-that/FinVeda/assets/137484958/86b507b8-3494-4f07-9d28-89ad8089f890)

**Comment by SadafKausar2025** [comment]
Can you please assign this issue to me #105 ?

**Comment by ayush-that** [comment]
@SadafKausar2025 assigned to you under gssoc
Take care the icons align well

**Comment by SadafKausar2025** [comment]
ok I will take care?

**Comment by SadafKausar2025** [comment]
hi @ayush-that 

please I have allign the icons properly 

![Screenshot (1752)](https://github.com/ayush-that/FinVeda/assets/137484958/ac907314-34ae-4a13-a957-1d0b4da78736)

can you please merge PR no #131

**Comment by SadafKausar2025** [comment]
Hi , @ayush-that 
@ can you please reopen the PR #131 so that I can resolve conflicts.

**Comment by Agarwalvidu** [comment]
As PR is already closed I am closing this issue.
