### ISSUE TITLE
Currency dropdown misalignment and textbox size issue in Tools section

### ISSUE THREAD

**Issue by Pragati1466** [ayush-that/FinVeda#1055]
### What happened?

There are a few UI-related issues in the Tools section under the Currency feature that need to be addressed:

1.Text Alignment: The currency labels (INR, USD) are not properly aligned in the center. They should be centered within the text box to improve readability.
2.Text Box Size: The size of the text box is too large. It should be reduced to fit the content appropriately, providing a cleaner and more compact UI.
3.Dropdown Overlap: When the currency dropdown is opened, it overlaps the text box. Instead, the dropdown should appear below the text box to prevent overlapping and maintain proper functionality.

### How can we reproduce this bug?

1.Navigate to the Tools section.
Go to the Currency feature.
Observe that the currency labels (INR, USD) are not centered inside the text box.
Open the dropdown menu and notice that it overlaps with the text box instead of appearing below it.
2.Expected Behavior:
The text in the currency text box (INR, USD) should be centered.
The size of the text box should be small and appropriate to fit the content.
The dropdown menu should appear below the text box without overlapping it.

### Urgency (Optional)

High priority

**Comment by Pragati1466** [comment]
<img width="1226" alt="Screen Shot 2024-10-10 at 1 25 45 AM" src="https://github.com/user-attachments/assets/8828e462-9665-4d21-b2f9-f2d498a39e84">
<img width="884" alt="Screen Shot 2024-10-10 at 1 26 05 AM" src="https://github.com/user-attachments/assets/1f70a11e-688c-4138-bc4f-38dd9f677b67">
@ayush-that@sampadatiwari30 @Deekshashakyawal please assign this issue to me

**Comment by Pragati1466** [comment]
pls label this as well @sampadatiwari30

**Comment by deepeshmlgupta** [comment]
no, update since last week so closing

**Comment by Pragati1466** [comment]
Please bhaiya give me tommorow’s day as my exam are going on

**Comment by Pragati1466** [comment]
I have done pr but some issues were there I will resolve tommoro

**Comment by sampadatiwari30** [comment]
@Pragati1466, this work is already done by another contributor.
