### ISSUE TITLE
[style]: the design of contact us page

### ISSUE THREAD

**Issue by magancodes** [ayush-that/FinVeda#1057]
### What's the style idea?

We need to improve  the basic styling , and add a contact form for the easy user service , and center the navbar

### Add screenshots

Add screenshots 
![image](https://github.com/user-attachments/assets/76d4d963-5096-4520-885c-5e26050cb190)
![image](https://github.com/user-attachments/assets/b3d09fb8-1c23-4b89-87e4-e4c0d276fcdb)
changes like these

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by magancodes** [comment]
@sanjay-kv pls assign this issue to me '

**Comment by sanjay-kv** [comment]
@magancodes sorry im not the admin of this project, i wont be able to assign you. please tag admin or mentor
