### ISSUE TITLE
Title: increasing the size of social icons 

### ISSUE THREAD

**Issue by Aazib-at-hub** [ayush-that/FinVeda#1060]
### Is your feature request related to a problem? Please describe.

i can see at the bottom left there is alot of space.
![Screenshot from 2024-10-10 04-30-49](https://github.com/user-attachments/assets/120a7069-4d9e-4455-be73-3b1892c1645a)

### Describe the solution you'd like.

there i want to add the social media icons and the username sothat if someone wants to follow you later on he can just recall the username.

### Describe alternatives you've considered.

there i want to add the social media icons and the username sothat if someone wants to follow you later on he can just recall the username.

### Add any other context or screenshots about the feature request here.

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by satyamra1** [comment]
Hi , I came across this issue  and found it aligns with my skills and interest. I have experience in adding username  with social icons. I am confident I can contribute effectively to this issue.
Would you mind assigning it to me so I can start working on it? Looking forward to contributing and adding value to the project.
