### ISSUE TITLE
Adding attractive icons

### ISSUE THREAD

**Issue by harikasayani** [ayush-that/FinVeda#107]
I want to add icons to the various sections in navbar.
Please assign this task to me.
I am GSSOC'24 Contributor.

**Comment by ShahHetviIT** [comment]
I'm keen on taking the helm of the FinVeda project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm well-equipped to drive meaningful progress on this initiative. Kindly assign me to this issue through GSSOC.
