### ISSUE TITLE
Title: Add a Dedicated contributors section in the web page

### ISSUE THREAD

**Issue by priyachau12** [ayush-that/FinVeda#1072]
### Is your feature request related to a problem? Please describe.

Recognizing all contributors is challenging, as they aren't displayed in a consolidated view, which could lower community engagement and recognition for individual efforts.

### Describe the solution you'd like.

Add a Contributions Page to the project that lists all contributors with their names, profile pictures, and links to their GitHub profiles. This page would provide an overview of everyone’s contributions and increase community appreciation.

### Describe alternatives you've considered.

An alternative would be adding a contributors section on the homepage or a smaller widget, but a full page offers more visibility and room for future enhancements like filtering or search.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/32347bbc-a115-4807-a29d-f1533ed1533b)

this can look like this :

![image](https://github.com/user-attachments/assets/95af6bc2-97be-4683-8427-b45a188539c8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
@priyachau12 do clearly check the website the contributor page is already present in the website.
