### ISSUE TITLE
Adding icon to email input in footer section

### ISSUE THREAD

**Issue by harikasayani** [ayush-that/FinVeda#108]
I am GSSOC'24 Contributor.
I want to add icon to the input field for email in footer section.
Please assign this task to me.

**Comment by ShahHetviIT** [comment]
I'm keen on taking the helm of the FinVeda project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm well-equipped to drive meaningful progress on this initiative. Kindly assign me to this issue through GSSOC.

**Comment by Azhar-0401** [comment]
*is your feature request related to a problem? Please describe.*
Currently Adding icon to email input  not in footer section

*Describe the solution you'd like
Add icon to email input  in footer section

*Additional context*
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me
