### ISSUE TITLE
fixing Navbar in About Us section 

### ISSUE THREAD

**Issue by AsifQamar** [ayush-that/FinVeda#1092]
### What happened?

Navbar of About us section is not aligned
priority - high  

### How can we reproduce this bug?

i'll fix it

### Desktop Information (Optional)

windows 11 , firefox developer 
<img width="960" alt="Screenshot_140" src="https://github.com/user-attachments/assets/48a28c61-e89d-42a2-a149-886e8b8c1404">

### Urgency (Optional)

High priority

**Comment by fahadshahbaz** [comment]
I want to work on this issue.

**Comment by fahadshahbaz** [comment]
There's too much content on the navbar, which is why it struggles to fit everything in the responsive view on smaller screens. The best way to handle this is to show only the important links or use a dropdown menu.

**Comment by AsifQamar** [comment]
@ayush-that please assign me this issue

**Comment by AsifQamar** [comment]
@Sampadatiwari please tag it with GSSoC and Hacktoberfest

**Comment by AsifQamar** [comment]
@sampadatiwari30 hacktoberfest-accepted too
