### ISSUE TITLE
Create a Refund Policy Page

### ISSUE THREAD

**Issue by Devaki01** [ayush-that/FinVeda#11]
Hello, 
This is Devaki from GGSoC'24. 
I would really love to contribute by adding a refund policy page for FinVeda. Also , I think the finVeda logo on the top left corner would further enhance the site. Can you please assign me this issue.

Thank you

**Comment by ayush-that** [comment]
Hello @Devaki01,
There already exists a refund policy page but it contains irrelevant information. Work on improving it by adding something relevant there(You may use AI tools to generate). I agree a logo in the navbar would look good. I am assigning you to fix these two issues under gssoc. All the best.

**Comment by Devaki01** [comment]
Thank you so much for providing me this opportunity.  Will start working on it today itself.

**Comment by Devaki01** [comment]
> Hello @Devaki01, There already exists a refund policy page but it contains irrelevant information. Work on improving it by adding something relevant there(You may use AI tools to generate). I agree a logo in the navbar would look good. I am assigning you to fix these two issues under gssoc. All the best.

Should I add only this logo or should I design one more small logo to add along with this?
![logo-2](https://github.com/ayush-that/FinVeda/assets/147143243/8cde8c60-df9c-4725-a996-da25090afadb)

**Comment by ayush-that** [comment]
> > Hello @Devaki01, There already exists a refund policy page but it contains irrelevant information. Work on improving it by adding something relevant there(You may use AI tools to generate). I agree a logo in the navbar would look good. I am assigning you to fix these two issues under gssoc. All the best.
> 
> Should I add only this logo or should I design one more small logo to add along with this? ![logo-2](https://private-user-images.githubusercontent.com/147143243/329781787-8cde8c60-df9c-4725-a996-da25090afadb.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzE5MDAsIm5iZiI6MTcxNTQzMTYwMCwicGF0aCI6Ii8xNDcxNDMyNDMvMzI5NzgxNzg3LThjZGU4YzYwLWRmOWMtNDcyNS1hOTk2LWRhMjUwOTBhZmFkYi5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxMjQ2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDExZDViOTBkMTAwM2FiZGIwZjAwZGE4NjNkNTJmZDZhNDE3MmU1YmY4ODliMGQzOWQyMmNiMzU5ZWMyZjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rBlGMuZgn7ypJ4cbTWobCBK0b-8lSdsEJ1ymj3RsgB4)

Please use this logo only.
You may resize it according to your needs.

**Comment by Devaki01** [comment]
ok sure.. thank you
