### ISSUE TITLE
[Bug Title here] Login and Sign-Up Pages Not Opening on Other Pages

### ISSUE THREAD

**Issue by ritiksingh-01** [ayush-that/FinVeda#1106]
### What happened?

he login and sign-up pages are functioning correctly when accessed from the home page, but they do not open properly from other pages on the website. This inconsistency affects user navigation across the site, making it difficult for users to access the login or sign-up functionality from different sections. I will investigate and fix this issue to ensure the login and sign-up pages are accessible from all pages.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

![login and sign up](https://github.com/user-attachments/assets/8ae1ad16-cf7f-4be8-b6b0-7492f0a76da9)

### How can we reproduce this bug?

- Open the website and navigate to the home page.
- Click on the login or sign-up link/button to verify that the pages open correctly.
- Now, navigate to any other page on the website.
- Attempt to open the login or sign-up page from there.
- Observe that the login and sign-up pages do not open or function as expected on these other pages.

### Urgency (Optional)

High priority

**Comment by ishivansmishra** [comment]
I’m interested in working on it. I believe I can contribute effectively and would love to help resolve this issue.

Could you please assign the issue to me if it's still available?

**Comment by Priyanshi0112** [comment]
Hi, @Sampadatiwari 

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

**Comment by ritiksingh-01** [comment]
Hi, @Sampadatiwari 

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.
