### ISSUE TITLE
[style]: Changing subscribe us design

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1110]
### What's the style idea?

We need to improve  background color of the subsribe us box and add hovering effect on subscribe button.

### Add screenshots

Before

https://github.com/user-attachments/assets/f0d1881d-cf1f-4ad0-80c2-50cf33529c44

After

https://github.com/user-attachments/assets/8ba34d30-de82-450d-87da-9a1e26951273

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by AsifQamar** [comment]
@Sampadatiwari please assign me this
