### ISSUE TITLE
to add  a light and dark mode toggle 

### ISSUE THREAD

**Issue by sv410** [ayush-that/FinVeda#1117]
### What's the style idea?

The style idea behind adding a dark and light mode toggle is all about enhancing user experience. By offering a dark mode, you make it easier on the eyes, especially in low-light environments. Conversely, a light mode can be more readable in bright settings. The toggle gives users control to choose the most comfortable and efficient viewing experience for their current environment.

Here's a breakdown of the style components:

User-Friendly Interface: The toggle button should be easily accessible and intuitive, located in a prominent position like the header or a fixed navigation bar.

Smooth Transition: The transition between dark and light modes should be smooth and seamless, using CSS transitions to avoid sudden changes that can be jarring to the eyes.

Consistent Design: Ensure all elements, such as text, background, and buttons, are adjusted for both modes to maintain readability and visual appeal.

### Add screenshots

Add screenshots
![WhatsApp Image 2024-10-12 at 6 03 50 PM](https://github.com/user-attachments/assets/36bf8549-28
![WhatsApp Image 2024-10-12 at 6 02 58 PM](https://github.com/user-attachments/assets/d135ff8f-6381-4883-a0fb-4ee0f9b779f7)
53-4fe6-af04-815871fb5af3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by deepeshmlgupta** [comment]
Already assign to someone else
