### ISSUE TITLE
[Bug] Misalignment of eye button in both Login & Register page

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ayush-that/FinVeda#1124]
### What happened?

![Screenshot 2024-10-12 205233](https://github.com/user-attachments/assets/8c7410cd-f11f-435f-aed5-85af3b04403e)
![Screenshot 2024-10-12 205312](https://github.com/user-attachments/assets/c2a628ca-5dfd-42e1-a516-d87f5432986f)

The eye button in both Login & Register page is not aligned properly, which doesn't looking good. 

I want to fixed it properly in the center. @ayush-that  please assign me this task.

### How can we reproduce this bug?

I want to fixed it properly in the center

### Urgency (Optional)

High priority

**Comment by Subhajit-2023-44** [comment]
@sampadatiwari30 level ??

**Comment by ritiksingh-01** [comment]
Hi, @sampadatiwari30 
I'm already working on this issue #1106 .
