### ISSUE TITLE
Dynamic Mode Toggle: Seamlessly Switch Between Dark and Light Themes

### ISSUE THREAD

**Issue by thevijayshankersharma** [ayush-that/FinVeda#113]
Elevate user experience with our dynamic mode toggle feature, allowing users to effortlessly switch between dark and light themes according to their preference and ambient lighting conditions. With this feature, users can customize their viewing experience, whether they prefer a sleek, modern dark mode for reduced eye strain in low-light environments or a vibrant light mode for enhanced readability during the day. Our intuitive toggle seamlessly adapts the interface, ensuring consistency and comfort across all interactions. Experience versatility in design with our dynamic mode toggle, offering a personalized touch to every user's journey.

**Comment by TiwariRahul16** [comment]
Hi @ayush-that assign this to me under gssoc 2024

**Comment by KhushiSahu0108** [comment]
Please assign this issue to me under gssoc'24
