### ISSUE TITLE
[style]: changing the style of footer elements

### ISSUE THREAD

**Issue by Kritika745** [ayush-that/FinVeda#1132]
### What's the style idea?

We need to improve  the styling of the footer elements.
I think that the footer will look better if the border that appears below each hyperlink will extend up to the text length only and also these social icons are not arranged properly.

### Add screenshots

Add screenshots
![Screenshot 2024-10-12 234544](https://github.com/user-attachments/assets/491d28b0-223a-4997-9c50-f812c6d2d1c1)

I want to work on this @ayush-that please assign it to me.
Also please attach hactoberfest label

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Kritika745** [comment]
hey! @sampadatiwari30 thank you for assigning this issue to me I will soon resolve this and raise a pr.

**Comment by Kritika745** [comment]
hey @ayush-that @sampadatiwari30 I have resolved this issue under pr #1161 please merge my pull request

**Comment by sampadatiwari30** [comment]
@Kritika745 show me your work.

**Comment by Kritika745** [comment]
I have added screenshots in pull request please review
