### ISSUE TITLE
making footer responsive

### ISSUE THREAD

**Issue by akanchha-rani** [ayush-that/FinVeda#1133]
<img width="976" alt="Screenshot 2024-10-13 at 12 00 17 AM" src="https://github.com/user-attachments/assets/ca0bdd4c-316c-4ea2-8466-f9d549d851e1">

i want to update your project footer and make it responsive. 

### **Please assign this issue to me under gssoc '24 and the level of work i will do.**

**Comment by somasekhar774** [comment]
I want to update your project footer and make it responsive.
Please assign this task to me
