### ISSUE TITLE
Adding insurance calculator to tools section

### ISSUE THREAD

**Issue by ChandelAnish** [ayush-that/FinVeda#114]
adding a new feature to tools section --> insurance calculator   :   this  calculator allows quick and easy comparison of insurance plans  
                                                                                                          based on  various parameters. Using an insurance calculator, buyers 
                                                                                                          can quickly evaluate their needs and make an informed decision of 
                                                                                                          choosing an appropriate plan.

**Comment by ChandelAnish** [comment]
I can add this feature flawlessly  to your website,please assign me this issue under gssoc24

**Comment by ayush-that** [comment]
Assigning to @ChandelAnish under gssoc
Have fun!
