### ISSUE TITLE
[Bug Title here] There are two nav bars visible in the header

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1142]
### What happened?

![Screenshot 2024-10-13 115216](https://github.com/user-attachments/assets/0ab0cf11-24b7-4a62-80f8-7555cf96014a)

### How can we reproduce this bug?

I can delete the backside nav bar and fix the upper nav bar correctly

### Urgency (Optional)

High priority

**Comment by AsifQamar** [comment]
@Sampadatiwari assign me this issue
