### ISSUE TITLE
[style]: Improving footer section of about us page

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1144]
### What's the style idea?

We need to improve  the alignment of elements and colors used.

### Add screenshots

![Screenshot 2024-10-13 115534](https://github.com/user-attachments/assets/068a102a-054d-4391-b0c3-1651a266aa03)

@Deekshashakyawal Please assign this issue to me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by AsifQamar** [comment]
@Sampadatiwari assign me this
