### ISSUE TITLE
[style]: Navbar backgroung and element colors are same

### ISSUE THREAD

**Issue by Mayukh-Mandal2005** [ayush-that/FinVeda#1150]
### What's the style idea?

We need to improve the background of navbar and also change the elements colors of the navbar so that they both don't overlap each other. 
Also the style of the navbar overlaps with something weird in its background of the same style and colors.
I would like to improve this too and make the navbar much more attractive, appealing and user-friendly.

Please assign this issue to me @ayush-that 

### Add screenshots

![image](https://github.com/user-attachments/assets/14e9a3bd-5ef3-4a9e-8aed-48284c53960a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by AsifQamar** [comment]
@Sampadatiwari assign me this issue

**Comment by Mayukh-Mandal2005** [comment]
Hey @deepeshmlgupta 
Can you also add a Level tag and HacktoberFest tag to this issue?
