### ISSUE TITLE
[Bug Title here] 2 navbar overlapping in home.html

### ISSUE THREAD

**Issue by srivishnu2805** [ayush-that/FinVeda#1157]
### What happened?

there are 2 navbars in the home.htm which makes the page clumsy and not so beautiful
![image](https://github.com/user-attachments/assets/98d35ddc-1df8-4fd5-8de0-699494449980)

### How can we reproduce this bug?

we can fix it by removing a navbar and giving proper alignments to that home.HTML  to make the website more attractive

### Desktop Information (Optional)

Google Chrome (Windows)

### Urgency (Optional)

Medium priority

**Comment by MasirJafri1** [comment]
issue #1150 already working on this I guess @srivishnu2805

**Comment by srivishnu2805** [comment]
@MasirJafri1 can i solve this issue ?

**Comment by MasirJafri1** [comment]
@srivishnu2805 I am a contributor too kindly go to the mentioned issue and ask @sampadatiwari30
