### ISSUE TITLE
[style]: Navbar Styling Improvement

### ISSUE THREAD

**Issue by FarhanBijapur** [ayush-that/FinVeda#1158]
### What's the style idea?

The current navbar design doesn't blend well with the overall website. I would like to work on restyling it for better visual appeal and functionality.

* Improve the navbar styling to match the overall website theme.
* Ensure responsiveness across different devices.
* Add hover effects, better font selection, and alignment adjustments.

Please assign it me under gssoc-ext and hacktober

### Add screenshots

Add screenshots
![Screenshot 2024-10-13 163127](https://github.com/user-attachments/assets/c94c30aa-146d-40f7-9436-2e056d34d7f5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by FarhanBijapur** [comment]
please assign it under hactober too

**Comment by Kavish-Paraswar** [comment]
i would like to work on this issue, as I have strong expertise in HTML, CSS, and JavaScript.

**Comment by Kavish-Paraswar** [comment]
lookin at the amount of work can  u add level 3 to this task.

**Comment by Kavish-Paraswar** [comment]
this issue is resolved @sampadatiwari30
