### ISSUE TITLE
[style]: UI enhancement

### ISSUE THREAD

**Issue by bhaviya18** [ayush-that/FinVeda#1168]
### What's the style idea?

We need to improve  the UI of the webpage to make it more interactive with the users and make it with modern features to make it more appealing.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by bhaviya18** [comment]
Can you kindly add level tag as well.

**Comment by Sawan-Kushwah** [comment]
@sampadatiwari30 can i work on this !!!
