### ISSUE TITLE
Duplicate Quiz in NavBar of Tool section

### ISSUE THREAD

**Issue by AsifQamar** [ayush-that/FinVeda#1178]
### What happened?

dupliacte quiz in navbar

### How can we reproduce this bug?

in place of two quiz there should be contact 

### Desktop Information (Optional)

windows 11
<img width="960" alt="Screenshot_193" src="https://github.com/user-attachments/assets/d696c435-d42c-46f6-a93d-d70254744bcb">

### Urgency (Optional)

High priority

**Comment by AsifQamar** [comment]
@deepeshmlgupta please assign me this

**Comment by deepeshmlgupta** [comment]
update your code this issue is been already fixed

**Comment by AsifQamar** [comment]
> update your code this issue is been already fixed

ok
