### ISSUE TITLE
Title: Dark mode in help section

### ISSUE THREAD

**Issue by SohamDas00** [ayush-that/FinVeda#1198]
### Is your feature request related to a problem? Please describe.

Dark mode in help section it is light mode and user is facing problem in visiting this page 

### Describe the solution you'd like.

Dark mode in help section it is light mode and user is facing problem in visiting this page 
so i want to add dark mode feature 

### Describe alternatives you've considered.

Dark mode in help section it is light mode and user is facing problem in visiting this page 
so i want to add dark mode feature  that make user to visit this page 

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-10-14 104857](https://github.com/user-attachments/assets/038a63e2-e3a1-4186-b884-c55f99dea5b1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by SohamDas00** [comment]
please assign me this issue

**Comment by AsifQamar** [comment]
@deepeshmlgupta assign me this

**Comment by SohamDas00** [comment]
i have created this issue so i will get assined by the project admin
