### ISSUE TITLE
Adding login/signup page

### ISSUE THREAD

**Issue by harshmishra19** [ayush-that/FinVeda#12]
Hey @ayush-that , I noticed that there's no login page feature on your website. I can add this feature according to the theme of your website. Could you please assign me this issue under GSSOC'24

**Comment by rajkrsingh9** [comment]
Hello, Please assign me this issue, I will add the login and signup page along with forgot password and reset password feature.
It would be completely responsive and it will also match your theme.

**Comment by ChandelAnish** [comment]
Hey @ayush-that ,

I've seen the request to add a login/signup page to the project, a fundamental feature for user authentication and access control. Given my experience in developing authentication systems, I'm keen to contribute to this task.

To address this issue, I'll design and implement a responsive login/signup page using React and integrate it with backend authentication services. Leveraging my expertise in HTML, CSS, and JavaScript, I'll ensure the page is visually appealing and intuitive to use.

Additionally, I'll incorporate form validation to ensure data integrity and security, and provide feedback to users on their login/signup attempts.

I'm excited to collaborate on this essential feature and contribute to enhancing the project's functionality and user experience.

Best,
Anish Singh Chandel

**Comment by ayush-that** [comment]
Same as #20 
I am closing this issue.
