### ISSUE TITLE
Implement Email ID Validation with Domain Verification

### ISSUE THREAD

**Issue by Amruta7203** [ayush-that/FinVeda#120]
Current Behavior:
The current implementation of Email ID validation is under development. It does not verify the credibility of the domain portion of the email address.

Desired Behavior:
The email validation process should include a step to verify the validity of the domain portion (e.g., .com, .org, .edu, .gov, etc.). This can be achieved by checking the domain against a list of approved or recognized top-level domains (TLDs) and ensuring that the domain itself exists and is not a random or invalid string.

![image](https://github.com/ayush-that/FinVeda/assets/116087736/36de38e3-2002-437c-b474-48f3a968d99a)

**Comment by ayush-that** [comment]
> Current Behavior: The current implementation of Email ID validation is under development. It does not verify the credibility of the domain portion of the email address.
> 
> Desired Behavior: The email validation process should include a step to verify the validity of the domain portion (e.g., .com, .org, .edu, .gov, etc.). This can be achieved by checking the domain against a list of approved or recognized top-level domains (TLDs) and ensuring that the domain itself exists and is not a random or invalid string.
> 
> ![image](https://private-user-images.githubusercontent.com/116087736/331292666-36de38e3-2002-437c-b474-48f3a968d99a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTQ1NTgsIm5iZiI6MTcxNTkxNDI1OCwicGF0aCI6Ii8xMTYwODc3MzYvMzMxMjkyNjY2LTM2ZGUzOGUzLTIwMDItNDM3Yy1iNDc0LTQ4ZjNhOTY4ZDk5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwMjUwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjVkZjNiYmYwNzBhNWZiM2FkNTgwNDNmOTdhNGY2OTFkOTRhYTMzZTYxOGJkN2JhMWMxOTM3N2JiMGE3NDU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6JHgmzbnMC7VzLQCMvd8EiE1EaTDI5ozAa88qn0iZPM)

I am assigning it under gssoc
Good Luck implementing!

**Comment by Agarwalvidu** [comment]
Are you working on this @Amruta7203

**Comment by SagarRathore1** [comment]
I would like to work on this issue.

**Comment by Agarwalvidu** [comment]
As previous contributor is not active assigning it to you @SagarRathore1

**Comment by Agarwalvidu** [comment]
@SagarRathore1 Update?

**Comment by harish08102004** [comment]
hey @Agarwalvidu if this issue not resolved I can work on this.
