### ISSUE TITLE
[style]: Changing the alignment of the form and visibility of the text.

### ISSUE THREAD

**Issue by Kritika745** [ayush-that/FinVeda#1203]
### What's the style idea?

We need to improve  the alignment of the feedback form and the visibility of the text above the form..
The text above the feedback form is almost invisible and the form is left aligned which is not looking good.

### Add screenshots

Add screenshots
![Screenshot 2024-10-14 111842](https://github.com/user-attachments/assets/a274caef-69c3-4cb0-85e1-fafb0ac01305)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Amangupta97656** [comment]
Assign me this issue

**Comment by Kritika745** [comment]
hey @ayush-that @sampadatiwari30 here is the preview of the changes.
Please assign this issue to me and add level 2 so that I can raise a pr.
Before
![Screenshot 2024-10-14 111842](https://github.com/user-attachments/assets/f6c57234-23ac-463d-87b1-1f5d2157c062)
After
![Screenshot 2024-10-14 115753](https://github.com/user-attachments/assets/281533ac-8f53-4b58-b86a-fb7fb9f87689)

**Comment by Kritika745** [comment]
hey @ayush-that @sampadatiwari30 @deepeshmlgupta I have solved this issue under pr #1287 please review it and merge
