### ISSUE TITLE
Update Copyright Year Dynamically in Footer

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [ayush-that/FinVeda#121]
Hey @ayush-that . Currently, the copyright year in the footer of our website is hardcoded in all the html files. To ensure that the copyright year is always up-to-date, we need to implement a dynamic solution that automatically updates the year to the current year. This will improve user experience and maintain compliance with copyright regulations. The task involves modifying the existing code to use JavaScript or a server-side language to fetch and display the current year.

**Please assign the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

**Comment by ayush-that** [comment]
> Hey @ayush-that . Currently, the copyright year in the footer of our website is hardcoded in all the html files. To ensure that the copyright year is always up-to-date, we need to implement a dynamic solution that automatically updates the year to the current year. This will improve user experience and maintain compliance with copyright regulations. The task involves modifying the existing code to use JavaScript or a server-side language to fetch and display the current year.
> 
> **Please assign the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

I'm assigning under gssoc
Have Fun!
