### ISSUE TITLE
CSS Problem in Home Page behind "Market Monitoring Real-time" this div

### ISSUE THREAD

**Issue by amitkarmakar07** [ayush-that/FinVeda#122]

**Comment by iamansoni07** [comment]
Hii @ayush-that, i can fix this css issue. Assign me this issue.
![Screenshot 2024-05-17 015441](https://github.com/ayush-that/FinVeda/assets/137559453/6be6e403-2e57-4bf3-9fa5-3995c3266103)

**Comment by iamansoni07** [comment]
Hii ayush that i can fix this css issue, assign me.
![Uploading Screenshot 2024-05-17 015441.png…]()

**Comment by iamansoni07** [comment]
Hii @ayush-that  i can fix this css issue, assign me.

![Screenshot 2024-05-17 015441](https://github.com/ayush-that/FinVeda/assets/137559453/a002d3fb-d874-49e7-88f6-b83955617630)

**Comment by ayush-that** [comment]
> Hii @ayush-that i can fix this css issue, assign me.
> 
> ![Screenshot 2024-05-17 015441](https://private-user-images.githubusercontent.com/137559453/331375114-a002d3fb-d874-49e7-88f6-b83955617630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTQyNjIsIm5iZiI6MTcxNTkxMzk2MiwicGF0aCI6Ii8xMzc1NTk0NTMvMzMxMzc1MTE0LWEwMDJkM2ZiLWQ4NzQtNDllNy04OGY2LWI4Mzk1NTYxNzYzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwMjQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTc0ZGZjZGIyMDE4YjA4YjU1NzRlNDY5NzBiYjg0ODg5ZTk0MWU5YzA0YWJjOTBkYmExNTBhZDljYjQ2MzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4-0T6oi5KVk_PsGV0w2Rfnf33J9S3gjrvqvUdBFAFF0)

The widget being used is from TradingView.
I am assigning this under gssoc.
Have Fun!

**Comment by Agarwalvidu** [comment]
This issue has already been resolved, for the same reason I am closing this issue. Thank you for contributing!
