### ISSUE TITLE
Update Footer Social Links to Redirect to FinVeda's Own Profiles Instead of Official Sites

### ISSUE THREAD

**Issue by anshxika** [ayush-that/FinVeda#1224]
### What happened?

The social links in the footer currently direct users to official pages rather than the respective pages of the site's account. This reduces the opportunity for users to engage directly with the site's specific content, such as social media profiles or dedicated project pages.
@deepeshmlgupta  @Sampadatiwari  please assign me this issue under gssoc-ext and hacktoberfest (along with level as you may)
 
<img width="966" alt="Screenshot 2024-10-14 232126" src="https://github.com/user-attachments/assets/057dffac-2b1a-4513-a582-3c99dc5cc869">

### How can we reproduce this bug?

To reproduce the bug with the footer's social links, navigate to the website's footer and click each social media link. If they redirect you to the official sites instead of the site's own accounts, this confirms the issue.

### Desktop Information (Optional)
NA

**Comment by sampadatiwari30** [comment]
@anshxika you can connect on linkedln or discord.

**Comment by anshxika** [comment]
@sampadatiwari30 please provide the links to add 🥲, sorry but i couldn't get to the links, that's what i was saying previously.

**Comment by Sampadatiwari** [comment]
@anshxika https://www.linkedin.com/in/sampada-tiwari-217123257?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

**Comment by anshxika** [comment]
@Sampadatiwari shall i add on every page if no issue?

**Comment by Sampadatiwari** [comment]
@anshxika no.
