### ISSUE TITLE
[Bug Title here] The feedback form is not in center.

### ISSUE THREAD

**Issue by vivekYadav-asa** [ayush-that/FinVeda#1229]
### What happened?

The feedback form is not aligned in center.

### How can we reproduce this bug?

It'll look better if it is centrally aligned. Can you please assign this to me adding hackoctober tags and gssoc tags.

![image](https://github.com/user-attachments/assets/b62a756f-3421-40b1-a1d3-877d27ff6584)

### Desktop Information (Optional)

Windows

### Urgency (Optional)

High priority

**Comment by Son7c** [comment]
![Screenshot 2024-10-15 020111](https://github.com/user-attachments/assets/cc4fbb79-b644-4de0-84e8-3d8b29eee5a1)
Already fixed @vivekYadav-asa
