### ISSUE TITLE
Fix : Mutltiple Review Cards are highlighted at once 

### ISSUE THREAD

**Issue by iamansoni07** [ayush-that/FinVeda#123]
If a user hovering other than middle review card, the middle card is still highlighted as well as current hovered card 
Instead of this only that review card should be highlighted which is currently hovered by user.

![image](https://github.com/ayush-that/FinVeda/assets/137559453/09881527-1db5-40ce-8224-8f3005020c4c)

**Comment by iamansoni07** [comment]
Assign me this issue under GSSOC 24. I can fix this issue.

**Comment by ayush-that** [comment]
> If a user hovering other than middle review card, the middle card is still highlighted as well as current hovered card Instead of this only that review card should be highlighted which is currently hovered by user.
> 
> ![image](https://private-user-images.githubusercontent.com/137559453/331376275-09881527-1db5-40ce-8224-8f3005020c4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTQ0MjEsIm5iZiI6MTcxNTkxNDEyMSwicGF0aCI6Ii8xMzc1NTk0NTMvMzMxMzc2Mjc1LTA5ODgxNTI3LTFkYjUtNDBjZS04MjI0LThmMzAwNTAyMGM0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwMjQ4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2U1MGJjZjgzMDYzODhlMjc3MTExMzg4M2UwZjhkNzMyNmQzMGJiMWY2NDNhMGZhZjM3YzVmOGM2M2ZlNzE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MX58bmcgn6KwOsPT307f_CsqlHg_9G-ArfnEhkyDGHQ)

I am assigning this to you under gssoc
Good Luck!

**Comment by Agarwalvidu** [comment]
This issue has already been resolved, for the same reason I am closing this issue. Thank you for collaborating!
