### ISSUE TITLE
Tool page ui/ux enhancement 

### ISSUE THREAD

**Issue by Amankr200** [ayush-that/FinVeda#1248]
Tool page ui/ux enhancement , tool page not looking professional @ayush-that mark it level 3

https://github.com/user-attachments/assets/8ce06739-4bfb-4613-acd5-c643196e36ed

**Comment by Amankr200** [comment]
duplicate why

**Comment by sampadatiwari30** [comment]
@Amankr200 This issue was created before you, and now it's solved.
