### ISSUE TITLE
Title:  Add Job Search Functionality to Jobs Page

### ISSUE THREAD

**Issue by DivyaJyothi9** [ayush-that/FinVeda#1262]
### Is your feature request related to a problem? Please describe.

Currently, the Jobs page does not include a search feature, limiting users' ability to find specific job listings. 

### Describe the solution you'd like.

This new feature will add a search bar that allows users to type keywords or job titles to search for jobs. When a user enters a query:

- If jobs matching the search criteria are found, they will be displayed on the page.
- If no jobs match the criteria, a "No jobs found" message will be shown.

### Describe alternatives you've considered.

allowing users to filter jobs by predefined categories by a keyword search.

### Add any other context or screenshots about the feature request here.

![Screenshot (341)](https://github.com/user-attachments/assets/bff8b6de-415b-42d1-9fb1-f15638c520bf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by DivyaJyothi9** [comment]
Thank you ma'am for acknowledging!!

**Comment by vijaychandra1910** [comment]
@sampadatiwari30  assign it to me I want to work on it.

**Comment by DivyaJyothi9** [comment]
@sampadatiwari30 ma'am, I have created a PR #1329.
Kindly check it!!
Thank you @sampadatiwari30 !!

**Comment by DivyaJyothi9** [comment]
@sampadatiwari30 ma'am u haven't assigned me while merging pr https://github.com/ayush-that/FinVeda/pull/1329,, plz ma'am kindly do it..

and level was wrongly labelled instead of level 3 given level 2..kindly look into it!!
