### ISSUE TITLE
Misalignment in Contact Page Form & Unintended Redirect on 'Send Message' Button Click

### ISSUE THREAD

**Issue by Lokesh-Bijarniya** [ayush-that/FinVeda#1265]
### What happened?

1. The contact form on the page has improper alignment issues, causing the labels and input fields to be misaligned across various screen sizes.
2. When the 'Send Message' button is clicked, instead of successfully submitting the form and staying on the same page (or showing a confirmation message), the user is redirected to a new page, which disrupts the form submission process.

https://github.com/user-attachments/assets/d73fb447-865d-497f-9fd9-b6c1baad3e5e

**Expected Behaviour**:
1. The contact form should have properly aligned fields and labels, ensuring a consistent and user-friendly experience.
2. After clicking the 'Send Message' button, the form should: 
    -> Either display a success message or show an error without changing the page.
    -> Not open a new page, as the form should stay on the same page after submission.

### How can we reproduce this bug?

1. Navigate to the contact page on the website.
2. Observe the alignment of the input fields and labels—they are not properly arranged.
3. Fill out the form with valid data.
4. Click on the 'Send Message' button.
5. After clicking the button, you will be redirected to a new page, which should not occur.

### Desktop Information (Optional)

Operating System: [Windows 11, macOS Ventura]
Browser: [Chrome 116.0, Firefox 115.0, Safari]

### Urgency (Optional)

High priority

**Comment by Lokesh-Bijarniya** [comment]
@Sampadatiwari Could u assign me this issue under gssoc & hacktober fest ?

**Comment by ritiksingh-01** [comment]
Hi, @Lokesh-Bijarniya 
Please wait for me to adjust the alignment and layout of the contact page, as I mentioned in my issue #1252 . Once that's done, you can proceed to solve your issue.
The task to work on the misalignment and layout issue has already been assigned to me.

**Comment by Lokesh-Bijarniya** [comment]
This issue has resolved by @ritiksingh-01 .
And i closed now.
