### ISSUE TITLE
[style]: Change color of blog cards

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1275]
### What's the style idea?

We need to improve  The color of cards in blogs section

### Add screenshots

![Screenshot 2024-10-15 170149](https://github.com/user-attachments/assets/553ac0d7-bc67-429a-ae1d-aa343bb61a06)

Assign me this i would try again to make the cards look better.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Sujal942** [comment]
Hey, can you assign it to me? I'd like to work on this.

**Comment by Son7c** [comment]
@Sampadatiwari assign this issue to me
