### ISSUE TITLE
[style]: Matching design of home navbar to all the pages

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1276]
### What's the style idea?

We need to improve  The navbar styling of all the pages except home page.
I would like to contribute in this.

Please consider if its possible to assign level 3 or i can also work with level2 tag

@Sampadatiwari assign this issue to me cause i have designed the home page nav bar. 

### Add screenshots

Home page
![Screenshot 2024-10-15 172032](https://github.com/user-attachments/assets/70b411f4-7f12-4bbf-9b15-00af3aa3b525)

Other pages
![Screenshot 2024-10-15 171741](https://github.com/user-attachments/assets/37467caa-e4d2-455d-8ade-11addc5c401d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by PDGamerSG** [comment]
Hey @Son7c , I am interestedin this issue can you pls assign this issue to me?

**Comment by vijaychandra1910** [comment]
Can you assign it to me. I want to work on it.
@ayush-that

**Comment by Son7c** [comment]
> Can you assign it to me. I want to work on it.
> @ayush-that 

I am already assigned i am working on it have patience
