### ISSUE TITLE
Title: Fix title name in careers page

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1279]
### Is your feature request related to a problem? Please describe.

https://github.com/user-attachments/assets/737a513f-efbb-4865-905b-20a32254db13

### Describe the solution you'd like.

Change the title name of the page

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by sakshi-nimje** [comment]
I would like to work on this issue, can you assign me ?

**Comment by ishivansmishra** [comment]
@sanmarg @sanjay-kv @FaheemOnHub Please assign me this isssue, i can update the title and assign me under the gssoc 24 extended and hacktoberfest

**Comment by FaheemOnHub** [comment]
@ishivansmishra sorry but i dont have the authority to assign.
