### ISSUE TITLE
[style]:  The issue is with the login/register button can be improved by adjusting the button's background, padding, and text color

### ISSUE THREAD

**Issue by REHAN-18** [ayush-that/FinVeda#1288]
### What's the style idea?

We need to **improve** 
1-  Text Contrast
2-Button Padding/Spacing
3- Fix Button Overflow
4-Improve Visibility with Hover/Focus

### Add screenshots

Add screenshots
<img width="1419" alt="Screenshot 2024-10-15 at 8 03 10 PM" src="https://github.com/user-attachments/assets/63931ced-7869-4bf2-afe2-4b605b59da6d">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Sawan-Kushwah** [comment]
@sampadatiwari30 can i work on this please assign me this
