### ISSUE TITLE
[Bug Title here] Log in/ Register button on navbar on home page is out of page

### ISSUE THREAD

**Issue by Rohit72099** [ayush-that/FinVeda#1291]
### What happened?

 Log in/ Register button on navbar on home page is out of page

![image](https://github.com/user-attachments/assets/7f46f6fe-50c5-4a69-88e0-9d31253438fa)

### How can we reproduce this bug?

when we land on home page , Login/Register button on navbar is out of page 
![image](https://github.com/user-attachments/assets/a7ac4ba3-db5b-4a98-9e36-e4a473a02e73)

### Urgency (Optional)

None

**Comment by Anshuln28** [comment]
Hey Ayush, Can I work on this issue...
