### ISSUE TITLE
[Bug Title here] Hamburger button is not working/lagging.

### ISSUE THREAD

**Issue by Rohit72099** [ayush-that/FinVeda#1292]
### What happened?

when we check responsiveness of website in phone  Hamburger button of navbar is not working .
![image](https://github.com/user-attachments/assets/7b2b824f-3ada-423a-9109-a17229a6aa9d)

### How can we reproduce this bug?

when we check responsiveness of website in phone  Hamburger button of navbar is not working .

![image](https://github.com/user-attachments/assets/a41d196d-582a-41cc-8572-b86de0f52a9b)

### Urgency (Optional)

None

**Comment by Anshuln28** [comment]
Hey Ayush can I work on this issue.
