### ISSUE TITLE
Updating the README file

### ISSUE THREAD

**Issue by harshmishra19** [ayush-that/FinVeda#13]
Hey @ayush-that , I noticed that your README file might not be beginner-friendly enough for newcomers to understand and start contributing. I can assure you that I'll update the README file to make it more beginner-friendly. Could you please assign me this issue under GSSOC'24

**Comment by ayush-that** [comment]
Hi @harshmishra19,
Could you please provide some details on the specific improvements you plan to make?

**Comment by anu906** [comment]
hello @ayush-that , can you assign this task to me.

**Comment by ayush-that** [comment]
> Hello @ayush-that , can you assign this task to me.

What improvements would you make the the readme?

**Comment by anu906** [comment]
- Information on how people can contribute to the project.
- Few more descriptions on project idea and steps to fork the repository.
- Also, to beautify the README file a bit along side to make it user friendly.

Kindly add any suggestions, if any.
Thank you.

**Comment by harshmishra19** [comment]
@ayush-that 
I would like to make the following changes:

- Provide a brief overview of the importance of financial literacy and how FinVeda addresses this need.
- Briefly describe each feature, highlighting its purpose and how it benefits users
- Clearly outline the steps for contributing, including forking the repository, making changes, and submitting a pull request

**Comment by harshmishra19** [comment]
@ayush-that I was the first one to address the issue so could you plz assign this issue to me

**Comment by ayush-that** [comment]
The readme already has how to contribute instructions.
You may submit a PR with your changes if you want.
No points will be given for it.
