### ISSUE TITLE
[Bug Title here] Social media icon at place of  copyright message in footer of about us page

### ISSUE THREAD

**Issue by Rohit72099** [ayush-that/FinVeda#1307]
### What happened?

 Social media icon at place of  copyright message in footer of about us page
![image](https://github.com/user-attachments/assets/dd1689bb-c348-4580-8300-7e25540c05d9)

### How can we reproduce this bug?

In About Us page, at the end of the footer there should be a copyright message in place of social media

![image](https://github.com/user-attachments/assets/1336fda6-897f-43ac-a644-098da482b84c)

### Urgency (Optional)

None

**Comment by ishivansmishra** [comment]
@sampadatiwari30 Please Assign me this issue i can fix this issue

**Comment by Rohit72099** [comment]
i will  send another  the pull request

**Comment by ishivansmishra** [comment]
@sampadatiwari30 Please Assign me this issue i can fix this issu

**Comment by Rohit72099** [comment]
this is fixed by me through pull request #1322
