### ISSUE TITLE
multiple login/signup page

### ISSUE THREAD

**Issue by ChauhanAyush04** [ayush-that/FinVeda#1337]
### What happened?

There is different login/signup page in home page and different in contact page

https://github.com/user-attachments/assets/72c97da8-985b-41dd-b6ee-29f415b8e230

### How can we reproduce this bug?

there must be a single login/signup page.

### Urgency (Optional)

High priority

**Comment by ishivansmishra** [comment]
@Sampadatiwari Please assign me this issue i can fix this issue
