### ISSUE TITLE
[Feat]:Back to top button in trends page

### ISSUE THREAD

**Issue by Scrapper700** [ayush-that/FinVeda#134]
![Screenshot (235)](https://github.com/ayush-that/FinVeda/assets/113296663/211cd55b-e1ec-4bd1-a8a5-bd8d04fce148)

**Comment by Scrapper700** [comment]
@sanjay-kv @sid346184 @ayush-that @sonarani1 
can anyone please assign me this task under gssoc'24

**Comment by ayush-that** [comment]
@Scrapper700 If you want to implement it then do it for all pages.
I am assigning it under gssoc. 
Pls don't mention people unnecessarily.

**Comment by Scrapper700** [comment]
@ayush-that It was assigned to me and I even did that . What to do now?

**Comment by Scrapper700** [comment]
@ayush-that there is no smoothness in the back to top button  which you have merged.

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me. gssoc24

**Comment by Agarwalvidu** [comment]
This issue has already been resolved, for the same reason I am closing this issue. Thank you for collaborating!
