### ISSUE TITLE
[Bug] Overflowing Blog page divs

### ISSUE THREAD

**Issue by Shreya-Pandey-01** [ayush-that/FinVeda#1345]
### What happened?

the blog page divs are overflowing
![image](https://github.com/user-attachments/assets/8e5e1ccf-3dfe-47f8-b3f1-43a0619f474e)

I'll fix this issue , efficiently pls. assign this issue to me

### How can we reproduce this bug?

the learn more is either inseide , or half inside , or completely outside , giving irregularity

### Urgency (Optional)

None

**Comment by Son7c** [comment]
Resize your screen

**Comment by Shreya-Pandey-01** [comment]
Thank you for assigning me this issue
I'll complete it quickly
