### ISSUE TITLE
[style]: Login and Sign-Up Page Color Theme Mismatch with Main Theme

### ISSUE THREAD

**Issue by Priyanshi0112** [ayush-that/FinVeda#1348]
### What's the style idea?

We need to improve  the color theme of the login and sign-up page does not align with the main website's overall color scheme. This inconsistency affects the user experience (UX) as it disrupts the visual flow and branding of the website. To maintain consistency, the login and sign-up page should be updated to match the primary color theme of the site, ensuring a cohesive and professional design that enhances UX.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

### Add screenshots

![sign in page](https://github.com/user-attachments/assets/fcd074df-c603-40bf-b160-18c5215e4485)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Priyanshi0112** [comment]
Hi, @sampadatiwari30 
Please respond as soon as possible.

**Comment by Priyanshi0112** [comment]
> Hi, @sampadatiwari30 Please respond as soon as possible.

??

**Comment by sampadatiwari30** [comment]
@Priyanshi0112 don't you think, the previous one is better than this.

**Comment by Priyanshi0112** [comment]
> @Priyanshi0112 don't you think, the previous one is better than this.

yes it is good, but please tell me the correct design you like, so I can implement it quickly and attach it to every page.

**Comment by Priyanshi0112** [comment]
> Hi, @sampadatiwari30
> 
> The sign-up page doesn't exist on the login page, so I request your permission to add it. Also, I have changed the color theme of the login page, so please review it. Additionally, I would like to mention that I can create a new login and sign-up page as well. I will provide you with a sample for that.
> 
> ![login sample](https://private-user-images.githubusercontent.com/137524681/377200600-808a9670-1268-4ff3-b2cb-fb0b0fd80ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjM0NDAsIm5iZiI6MTcyOTIyMzE0MCwicGF0aCI6Ii8xMzc1MjQ2ODEvMzc3MjAwNjAwLTgwOGE5NjcwLTEyNjgtNGZmMy1iMmNiLWZiMGIwZmQ4MGFlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwMzQ1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmNiYjNiYzIyYjY5NzI4NjBjNjliZDUxYTkzZTZlMGRiMjNkYTliMzUzYWE2YzY2OTZmMmFlODRjMTFlYzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jVJeXLml3VQe-Z8RuhzFrvxh4lresIGNejmdoHFjrEM)
> 
> **sample :**
> 
>  login.signup.sample.mp4

??
