### ISSUE TITLE
Fix Scroll Bar

### ISSUE THREAD

**Issue by ayush-that** [ayush-that/FinVeda#135]
![image](https://github.com/ayush-that/FinVeda/assets/110257939/42c69343-30a9-40e2-a0bf-47af08897589)
The rounded edges in the scrollbar don't look good.
We need to fix it.

**Comment by spacedust26** [comment]
hey @ayush-that ! Could you please assign this issue to me. I'd like to work on this. Thank you.

**Comment by SiddharthaArepalli** [comment]
Hey @ayush-that  I want to this task assign me this Issue under GSSOC'24
I am already working this project !!

**Comment by paridhi1509** [comment]
hi @ayush-that 
I would like to work on this issue 
Please assign it to me

**Comment by anagha-chaudhari** [comment]
@ayush-that 
something like this?

![finVeda scroll bar](https://github.com/ayush-that/FinVeda/assets/143149376/47a2d991-ece9-4949-8732-3e742d5899c7)

**Comment by TheNikhilRaj** [comment]
can you please assign it to me, I would like to work on this task.
@ayush-that

**Comment by Ketanop321** [comment]
![Screenshot 2024-05-20 212327](https://github.com/ayush-that/FinVeda/assets/146806880/de9bec97-71b3-40a6-a0d7-85dbbcd73c75)
@ayush-that 
Do you want like this or want some different , i can make it for you🤗

**Comment by Yuvraj960** [comment]
Please assign this issue to me under GSSoC24

**Comment by Deepthi-Ramineni** [comment]
@ayush-that  Can you please assign this to me.....??? I can work on this

**Comment by Ananya-Nair20** [comment]
@ayush-that can you assign this to me under GSSOC'24????

**Comment by ayush-that** [comment]
@anagha-chaudhari @Ketanop321 
Make a PR, any of you.

**Comment by Ketanop321** [comment]
> @anagha-chaudhari @Ketanop321 Make a PR, any of you.

i have created a PR please check it ,and  tell me if you want something more to add on it @anagha-chaudhari
