### ISSUE TITLE
Making Login button to as other in Quiz page

### ISSUE THREAD

**Issue by AsifQamar** [ayush-that/FinVeda#1353]
### What's the style idea?

We need to improve  

### Add screenshots

<img width="960" alt="Screenshot_249" src="https://github.com/user-attachments/assets/5de80f49-0b72-4964-a2dd-01a9ed7bebe1">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by AsifQamar** [comment]
@Sampadatiwari please assign me this

**Comment by Son7c** [comment]
I already got this
