### ISSUE TITLE
[style]: Texts not visible in light mode

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1357]
### What's the style idea?

We need to improve  Text visibility

### Add screenshots

https://github.com/user-attachments/assets/d24ffff6-3ed9-45b1-8470-6351aecaba2b

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by AsifQamar** [comment]
i got this issue assign blud

**Comment by Son7c** [comment]
> i got this issue assign blud

Fix it

**Comment by AsifQamar** [comment]
> > i got this issue assign blud
> 
> Fix it

on my way
