### ISSUE TITLE
About us footer not visible properly

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1358]
### What happened?

![Screenshot 2024-10-16 210823](https://github.com/user-attachments/assets/59672ed8-024f-4b7c-8fff-cdc48873682a)

### How can we reproduce this bug?

Fixing the footer

### Urgency (Optional)

Medium priority

**Comment by sampadatiwari30** [comment]
@Son7c check again and correct all the issues of about us footer.
