### ISSUE TITLE
[style]: Fix careers subscribe button

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1359]
### What's the style idea?

We need to improve  The subscribe letterbox

### Add screenshots

![Screenshot 2024-10-16 211028](https://github.com/user-attachments/assets/4f31ff5e-3f59-465c-8443-d98b69b7f27f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by AsifQamar** [comment]
@Sampadatiwari assign me this
