### ISSUE TITLE
[style]: dark/light theme addition

### ISSUE THREAD

**Issue by shruti9935** [ayush-that/FinVeda#1362]
### What's the style idea?

We need to improve  
dark and light theme

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by sampadatiwari30** [comment]
@shruti9935 add screenshot.

**Comment by deepeshmlgupta** [comment]
not needed
