### ISSUE TITLE
[style]: Navbar section login button is not visible 

### ISSUE THREAD

**Issue by saimohan11** [ayush-that/FinVeda#1363]
### What's the style idea?

We need to improve navbar padding with that we can fix login button.
can you please assign me this task with gssoc-extd hacktoberfest labels

### Add screenshots

Add screenshots
![navbar ](https://github.com/user-attachments/assets/a1256c14-38ad-4c2f-a77d-309eaba98d2f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by AsifQamar** [comment]
resize your screen

**Comment by Son7c** [comment]
Zoom out

**Comment by saimohan11** [comment]
I will improve responsiveness for different screens. assign me this task

**Comment by deepeshmlgupta** [comment]
already solved
