### ISSUE TITLE
No Proper Alignment of Footer in About Us section

### ISSUE THREAD

**Issue by Roshn1** [ayush-that/FinVeda#1377]
### What happened?

Every links in footer is merged together , and there is no proper alignment between the elements as everything is collapsed and in the bottom some of the contents of the footer are repeated again..

![Screenshot 2024-10-17 000550](https://github.com/user-attachments/assets/5526f75f-3dfc-454e-ab7d-09788dac46b4)
![Screenshot 2024-10-17 000606](https://github.com/user-attachments/assets/ab0a20e9-478a-4b20-9d6e-6066df1ea6d0)
![Screenshot 2024-10-17 000616](https://github.com/user-attachments/assets/109167ea-227a-4ed1-917e-631e561e39ec)

### How can we reproduce this bug?

I can fix the footer by making proper alignment between the links.

### Urgency (Optional)

High priority

**Comment by Son7c** [comment]
This issue is already assigned to me

**Comment by Roshn1** [comment]
I have completed the task. Please check it once
