### ISSUE TITLE
Text not visible on blog page 

### ISSUE THREAD

**Issue by Devanshu1603** [ayush-that/FinVeda#1391]
### What happened?

texts including heading and description is not visible on blog page .
![Screenshot 2024-10-17 031936](https://github.com/user-attachments/assets/7393aa50-713f-41f8-a591-c46329a30bb5)

### How can we reproduce this bug?

should change the styling and font color of text .

### Urgency (Optional)

Medium priority

**Comment by Devanshu1603** [comment]
@Sampadatiwari  please assign me this issue under gssoc-extended.

**Comment by ishivansmishra** [comment]
@Sampadatiwari Please assign me this issue
