### ISSUE TITLE
Title: Adding Character Limit Validation to Subject and Message Fields

### ISSUE THREAD

**Issue by ananyag309** [ayush-that/FinVeda#1397]
### Is your feature request related to a problem? Please describe.

The "Subject" and "Message" fields on the contact page should have character limit validation to ensure proper input. A minimum of 10 characters should be required for the "Subject" and at least 20 characters for the "Message." This will prevent overly brief or incomplete entries, ensuring users provide sufficient detail in their submissions.

### Describe the solution you'd like.

 A minimum of 10 characters should be required for the "Subject" and at least 20 characters for the "Message."

### Describe alternatives you've considered.

na

### Add any other context or screenshots about the feature request here.

n/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
not needed
