### ISSUE TITLE
GIving the page a button to switch the theme between dark and light

### ISSUE THREAD

**Issue by TerminatorSS24** [ayush-that/FinVeda#14]
hey @ayush-that, I visited the link, and I thought it would look good if an theme switching button can be added, so can you assign me the task?

**Comment by Abhishek-0899** [comment]
Please assign this issue to me under gssoc'24

**Comment by GAGGZ1** [comment]
Hello @ayush-that 

I've implemented this feature in my previous projects, showcasing my ability to enhance user experience through customization. With my expertise in front-end development, I'm confident I can integrate this feature smoothly into your project.
could you please assign me?

**Comment by debasmi** [comment]
hi have done projects under coursera hoping you would assign it ot me

**Comment by ayush-that** [comment]
Hello @TerminatorSS24 ,
Please implement it properly. I am assigning this to you under gssoc.

@GAGGZ1, @debasmi and @Abhishek-0899 please see other issues.

**Comment by TerminatorSS24** [comment]
> Hello @TerminatorSS24 , Please implement it properly. I am assigning this to you under gssoc.
> 
> @GAGGZ1, @debasmi and @Abhishek-0899 please see other issues.

**Thank You, I'll definitely do that.**

**Comment by GAGGZ1** [comment]
@ayush-that bro i have generated pull request please visit it and give your response its been 2 days
and have added the requirements , kindly look at it and merge it

**Comment by ayush-that** [comment]
> @ayush-that bro i have generated pull request please visit it and give your response its been 2 days and have added the requirements , kindly look at it and merge it

I'm sorry for that but I have a busy schedule.
Please have patience as this is a 3-month long programme.

**Comment by sid346184** [comment]
I have worked on that in my projects so I have experience to do so please assign it to me under GSSOC
