### ISSUE TITLE
Hide/show button not working on sign-in page.

### ISSUE THREAD

**Issue by vansh-m012** [ayush-that/FinVeda#1405]
### What happened?

![Screenshot 2024-10-17 103232](https://github.com/user-attachments/assets/08960bb7-d353-4dc0-a2b0-1973d92288da)

On clicking the eye-button , nothing is happening. 

### How can we reproduce this bug?

Please assign it to me I will fix this bug as soon as possible.

### Urgency (Optional)

None

**Comment by ishivansmishra** [comment]
@Sampadatiwari Please assign me this issue
