### ISSUE TITLE
Fixing footer of about us page 

### ISSUE THREAD

**Issue by AsifQamar** [ayush-that/FinVeda#1408]
### What happened?

Footer of about us page is messed up

### How can we reproduce this bug?

we have fix it

### Desktop Information (Optional)

windows 11
<img width="960" alt="Screenshot_265" src="https://github.com/user-attachments/assets/715b2341-41d9-4440-a1f9-33b6316015be">
<img width="960" alt="Screenshot_266" src="https://github.com/user-attachments/assets/6114e39d-ce84-4d8e-92fe-5115ff0d2658">

### Urgency (Optional)

High priority

**Comment by AsifQamar** [comment]
@Sampadatiwari please assign me this with level 2 or 3

**Comment by Sampadatiwari** [comment]
@AsifQamar already assigned.

**Comment by AsifQamar** [comment]
> @AsifQamar already assigned.

ok
