### ISSUE TITLE
[Bug Title here]: Alignment Issues on the Page

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ayush-that/FinVeda#1415]
### What happened?

The alignment of the elements on the page is inconsistent, leading to a disorganized appearance. Specifically, the sections for "Subscribe Our Newsletter," "Quick Links," and "Contact Us" do not align properly with each other and the overall layout overlap. This affects the user experience and the visual appeal of the site.

![image](https://github.com/user-attachments/assets/48177598-86e2-43ca-900c-6f6677617e03)

### How can we reproduce this bug?

- Navigate to the relevant page.
- Observe the misalignment of the "Subscribe Our Newsletter," "Quick Links," and "Contact Us" sections.

### Urgency (Optional)

High priority

**Comment by deepeshmlgupta** [comment]
already fixed
