### ISSUE TITLE
[style]: Semantic HTML

### ISSUE THREAD

**Issue by xenomancy** [ayush-that/FinVeda#1423]
### What's the style idea?

We need to improve  nhance the structure by using appropriate semantic tags like <header>, <footer>, and <main> for better SEO and accessibility.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Sampadatiwari** [comment]
@xenomancy add screenshot.

**Comment by xenomancy** [comment]
![Screenshot 2024-10-17 203746](https://github.com/user-attachments/assets/a6ef0e10-f4b1-46df-84e0-741ad9d8ff2c)
see the about us section is not properly alligned enhancing the semantic tags

**Comment by sampadatiwari30** [comment]
@xenomancy you're able to make an whole about us footer section ?

**Comment by xenomancy** [comment]
@Sampadatiwari please assign me this

**Comment by sampadatiwari30** [comment]
@xenomancy now it is fixed.
