### ISSUE TITLE
About page UI

### ISSUE THREAD

**Issue by Devanshu1603** [ayush-that/FinVeda#1426]
### What happened?

About page UI is complete broken. 

https://github.com/user-attachments/assets/3768f938-4d57-4b82-a69d-844e1d015e91

### How can we reproduce this bug?

Need to align items properly . and give them a proper styling to enhances User interface.

### Urgency (Optional)

High priority

**Comment by Devanshu1603** [comment]
@Sampadatiwari  please assign me this issue to enhance the about page.

**Comment by ishivansmishra** [comment]
@Sampadatiwari30 Please assign me this issue
