### ISSUE TITLE
[Bug Title here] Accrodions are completely broken in 'career' page

### ISSUE THREAD

**Issue by Suvadip-sana** [ayush-that/FinVeda#1430]
### What happened?

In career page the accrodions are completly broken. Not working as well.

Need to fix this.

![image](https://github.com/user-attachments/assets/642ebc73-9935-4cc8-9ea6-bca4be01d16f)
Here is the demo.

**Please assign me this issue. I want to work on it.**

### How can we reproduce this bug?

Changes on code. And make it better.

### Urgency (Optional)

High priority

**Comment by Suvadip-sana** [comment]
@Sampadatiwari 
Add all the necessary labels under `gssoc-exted` as per guidline

**Comment by Suvadip-sana** [comment]
@sampadatiwari30 Please give me labels for this.
If you give me `labels-2` for this. It will be very good for me.  Please considered this.

**Comment by sampadatiwari30** [comment]
@Suvadip-sana firstly complete your work, then I will give you label.

**Comment by Suvadip-sana** [comment]
Ok
