### ISSUE TITLE
Title: In 'trending page' the navbar is missing. Need UX improvement.

### ISSUE THREAD

**Issue by Suvadip-sana** [ayush-that/FinVeda#1431]
### Is your feature request related to a problem? Please describe.

In 'Trending page' what is the significance to missing the navbar?   This is a major part/page of the website.   There should be nav bar for sure.
 Because for now there only a button that take user to 'Home'  which is very annoying.  because each and every time when the user visit this page except the home page no option to go anywhere. 

Need to fix this.

### Describe the solution you'd like.

I make available the whole navbar at the top of this page. Like others page have.

### Describe alternatives you've considered.

I make available the navbar at the top of the 'Trebding page'   after the navbar  I attached the 'marquee' as it is.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/31cadaab-4ac1-4a32-9bb7-b5bf4216be60)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by Suvadip-sana** [comment]
@Sampadatiwari 

Please add the all necessary labels under `gssoc-exted` as per guideline

**Comment by sampadatiwari30** [comment]
@Suvadip-sana firstly complete the task, then I will give you label.
