### ISSUE TITLE
Title: <UX enhancement> Unnecessary scrolling in 'Home' page as well as 'Blog' page.

### ISSUE THREAD

**Issue by Suvadip-sana** [ayush-that/FinVeda#1433]
### Is your feature request related to a problem? Please describe.

In home page there is unnecessary scrolling for displaying every blogs. The same problem is there in 'Blog' page.
What is the significance for this?  

In feature if many more blogs were added. Then the page would be significantly long which cause of unnecessary scrolling issue. Which is very annoying for User. Also effect the UX of the platform.

### Describe the solution you'd like.

I would like to implement a load more button for both of the case.

Initially it display tow row of the blogs in both place. After clicking on the 'Load more' Button next row will be displayed.

It would be very helpful to add more and more blogs without effect the User Experience.

### Describe alternatives you've considered.

**Please assign me this task. I want to work in this ISSUE.**

### Add any other context or screenshots about the feature request here.

Here is the demo of what I try to say. That I implement on another project -->

https://github.com/user-attachments/assets/401efa3b-70d9-43fb-8560-edee15d440ee

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by sampadatiwari30** [comment]
@Suvadip-sana share screenshot

**Comment by Suvadip-sana** [comment]
@sampadatiwari30 
What is the reason to close this ISSUE?
Could you please elaborate?
