### ISSUE TITLE
ADD: Sustainability in Finance

### ISSUE THREAD

**Issue by shubhagarwal1** [ayush-that/FinVeda#1439]
A section focusing on sustainable and ethical investing, including tips on how to invest responsibly.

**Comment by sampadatiwari30** [comment]
@shubhagarwal1 share screenshot

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 share screenshot

the page will have basic info with design like this below 
<img width="1408" alt="Screenshot 2024-10-17 at 9 11 15 PM" src="https://github.com/user-attachments/assets/7ecaee3a-6008-4774-93f4-4180575d2c02">
something liekthis but improved design
