### ISSUE TITLE
[style]: Design the entire tools page.

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1450]
### What's the style idea?

We need to improve  The design of entire tools page.

### Add screenshots

![Screenshot 2024-10-17 203208](https://github.com/user-attachments/assets/949505ff-54b0-4caf-8029-67bd08b59655)
This design looks pretty basic

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by ishivansmishra** [comment]
@sampadatiwari30 Kindly assign me this issue
