### ISSUE TITLE
Add a dark mode

### ISSUE THREAD

**Issue by paridhi1509** [ayush-that/FinVeda#147]
I would like to add a dark mode for the website so that user can experience according to their comfort. 
Please assign it to me under GSSoC'24.

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me.

**Comment by Agarwalvidu** [comment]
It can not be done due to some issues on our side. Thank you for raising issue, looking for your more inputs. For now I am closing this issue.
