### ISSUE TITLE
[style]: Hero section is added two times in the home page

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1472]
### What's the style idea?

We need to produce only one hero section for the website

### Add screenshots

https://github.com/user-attachments/assets/486bead0-b044-41c8-8007-5252964e7328

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Son7c** [comment]
@Sampadatiwari Assign me this issue

**Comment by Priyanshi0112** [comment]
This issue #1457  is already assigned to me.

**Comment by deepeshmlgupta** [comment]
@Priyanshi0112  already assigned
