### ISSUE TITLE
Title: Improve hovering effect on contributors cards

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1474]
### Is your feature request related to a problem? Please describe.

The hovering effect is irritating.

### Describe the solution you'd like.

I would enhance the hovering effects

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

https://github.com/user-attachments/assets/b55b576e-f9cf-407e-8741-69e0d7d41425

@Sampadatiwari Assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
@Son7c describe more about your idea

**Comment by Son7c** [comment]
> @Son7c describe more about your idea

I would add smoother transitions, add very littile light colours to the card and change the colour(that suits the layouts ) when hovered
