### ISSUE TITLE
Title: DARK MODE 

### ISSUE THREAD

**Issue by xenomancy** [ayush-that/FinVeda#1479]
### Is your feature request related to a problem? Please describe.

Many of the users like to work in dark mode as:-
Reduced Eye Strain: Dark mode is easier on the eyes, especially in low-light conditions.
Improved Battery Life: Dark mode saves battery on OLED/AMOLED screens.
Enhanced Focus: Dark backgrounds help users focus on content by reducing distractions. 

### Describe the solution you'd like.

using html css and js i can add this feature 
@Sampadatiwari please assign me this task

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

N/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
not needed
