### ISSUE TITLE
Title: ADD Hover effect on login pg

### ISSUE THREAD

**Issue by SohamDas00** [ayush-that/FinVeda#1483]
### Is your feature request related to a problem? Please describe.

ADD Hover effect on login pg

### Describe the solution you'd like.

Hover effect on login pg by using hover property

### Describe alternatives you've considered.

Hover effect on login pg by using hover property

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-10-18 000029](https://github.com/user-attachments/assets/49afea65-85e4-46dc-a664-ba61666a6dac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
not needed
