### ISSUE TITLE
Title: ADD hover effect on SIGN UP page

### ISSUE THREAD

**Issue by SohamDas00** [ayush-that/FinVeda#1484]
### Is your feature request related to a problem? Please describe.

ADD hover effect on SIGN UP page

### Describe the solution you'd like.

ADD hover effect on SIGN UP page

### Describe alternatives you've considered.

ADD hover effect on SIGN UP page by using hover property

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-10-18 000029](https://github.com/user-attachments/assets/bc06ac63-d2d9-4075-b367-217ee27c31ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
not needed
