### ISSUE TITLE
[Bug Title here] Contact page

### ISSUE THREAD

**Issue by Priyanshuraj21030** [ayush-that/FinVeda#1491]
### What happened?

there are two contact pages available one is linked with your website which is not opening and second is opening but its n ot linked with your website

### Desktop Information (Optional)

assign me this task under hacktoberfest and gsoc

### Urgency (Optional)

High priority

**Comment by sampadatiwari30** [comment]
@Priyanshuraj21030 share screenshot.

**Comment by Priyanshuraj21030** [comment]
You can check in this there are two contact.html pages and which is also not linked with the website
Screenshot
![Screenshot 2024-10-19 164616](https://github.com/user-attachments/assets/e4a27040-9155-4309-b3f4-f931365d487e)
