### ISSUE TITLE
No learn.md

### ISSUE THREAD

**Issue by chiragHimself** [ayush-that/FinVeda#15]
Please add a learn.md file for the contributors to have a idea about contributing rules. It will make contributions easier and more streamlined for users.

**Comment by ayush-that** [comment]
Hi @chiragHimself,
I am assigning this issue to you under gssoc. Please implement it well. All the best.

**Comment by chiragHimself** [comment]
hey @ayush-that , I have made a PR for the learn.md file, please review . It seem to pass all checks. Further I have included all essential details for contributions as requested by the organizers during GSSOC orientation.
Thanks

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.
