### ISSUE TITLE
[Bug Title here]:NO NAVBAR PRESENT IN TRENDS PAGE

### ISSUE THREAD

**Issue by isimarjitsingh** [ayush-that/FinVeda#1506]
### What happened?

The navbar in your  "trends page " is not present . which causes unable to navigate on another page directly through the " trends page " and it also causes to tough the user experience.

### How can we reproduce this bug?

Go to the trends page and at the  top of the page you simply able to see that navbar is not present at there. which is kind a worrying thing in itself 

### Desktop Information (Optional)

![Screenshot 2024-10-18 104738](https://github.com/user-attachments/assets/10d86efa-e6a6-4294-b2c7-40bc3a10fb9d)

i will able to provide:-
- NAVBAR
- with good designing
- add hover effects
- add transitions
- add new designing which suits your website

### Urgency (Optional)

High priority

**Comment by deepeshmlgupta** [comment]
already assigned
