### ISSUE TITLE
[style]: UI IMPROVEMENT IN CARRERS SECTION

### ISSUE THREAD

**Issue by isimarjitsingh** [ayush-that/FinVeda#1507]
### What's the style idea?

We need to improve  the UI of carrers page as it have ordinary designing which is not that bad but i think  i able do it more interactive, BY giving it some css properties like :-
- hover effects
- by add relevant photos 
- by giving transitions for smooth user experince .
- and many more things which are looking good on page 

### Add screenshots

Add screenshots
![Screenshot 2024-10-18 105010](https://github.com/user-attachments/assets/d423bba6-1cca-49e0-8d8a-b7f4177bcd52)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Sawan-Kushwah** [comment]
@Sampadatiwari  can i work on this !
