### ISSUE TITLE
[Bug Title here]  Duplicate elements in Feedback form

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1515]
### What happened?

![Screenshot 2024-10-18 151005](https://github.com/user-attachments/assets/0e67cc0c-6a93-4651-8f00-48135ad6ead5)

### How can we reproduce this bug?

Scroll to feedback form in home button

@Sampadatiwari Assign me this issue

### Urgency (Optional)

Medium priority

**Comment by dishaagrawalcodes** [comment]
@Sampadatiwari  please assign this issue to me i can solve it today
