### ISSUE TITLE
Title: Add Language Translator to Help Page

### ISSUE THREAD

**Issue by ritiksingh-01** [ayush-that/FinVeda#1522]
### Is your feature request related to a problem? Please describe.

Implemented a language translator on the Help page to enhance accessibility for users speaking different languages. This feature allows users to select their preferred language, improving usability and making the page more inclusive for a global audience. The integration ensures that the help content can be easily translated into multiple languages.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

### Describe the solution you'd like.

NA

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/7528f5c2-f2de-48d3-802a-84ef6e9f9da4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by sampadatiwari30** [comment]
@ritiksingh-01 this issue already assigned to another contributor.
