### ISSUE TITLE
Title: Adding multi language support system✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ayush-that/FinVeda#1523]
### Is your feature request related to a problem? Please describe.

I want to add multi language support system to the website which can help us understand in their native language.
@ayush-that can you assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
already present
