### ISSUE TITLE
[Bug Title here] Inconsistent Placement of "Submit Feedback" Button

### ISSUE THREAD

**Issue by Aazma11** [ayush-that/FinVeda#1524]
### What happened?

I noticed that the "Submit Feedback" button is placed differently in two sections—one is aligned to the left, and the other is centered. This inconsistency might confuse users. It would be better to keep the button placement consistent across all pages to improve the user experience.
@sanjay-kv can you assign this to me under Hacktoberfest.
![finveda](https://github.com/user-attachments/assets/8897d397-d097-4ea4-bb73-9c352bd67cbc)

### How can we reproduce this bug?

1.Navigate to the section/page where the "Submit Feedback" button is aligned to the left.
2. Go to a different section/page where the same "Submit Feedback" button is centered.
3. Compare the button placement across both sections.
![finveda](https://github.com/user-attachments/assets/a0a09b2b-b119-44d4-9284-b7481cc043aa)

### Urgency (Optional)

None

**Comment by sampadatiwari30** [comment]
@Aazma11 this issue has been resolved.
