### ISSUE TITLE
Major: Add a dynamic page that renders the Big MNC's current Stocks and latest news in finance/stock market

### ISSUE THREAD

**Issue by AkshatSharma5** [ayush-that/FinVeda#1528]
### Is your feature request related to a problem? Please describe.

Add a dynamic page that renders the Big MNC's current Stocks and latest news in finance/stock market

### Describe the solution you'd like.

Add a dynamic page that renders the Big MNC's current Stocks and latest news in finance/stock market

### Describe alternatives you've considered.

I will be using a free API to Add a dynamic page that renders the Big MNC's current Stocks and latest news in finance/stock market

### Add any other context or screenshots about the feature request here.

I will be working for it.

**Please assign this labels of hacktoberfest and level-2 of gssoc-ext**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by AkshatSharma5** [comment]
Dear @Sampadatiwari , Kindly assign me this issue.
Please assign labels of hacktoberfest and level-2 of gssoc-ext

**Comment by Sampadatiwari** [comment]
@AkshatSharma5 share screenshot.

**Comment by AkshatSharma5** [comment]
> @AkshatSharma5 share screenshot.

Since I have not completed working on it, so after complete work, I'll be sharing it. 
Moreover, can you provide a [api-key](https://newsapi.org/s/india-business-news-api) that will facilitate my work.

**Comment by Sampadatiwari** [comment]
@AkshatSharma5 there is no api-key, you have to complete your work on your own way. We only guide you.
