### ISSUE TITLE
Missing Navigation Bar for the FAQ Section

### ISSUE THREAD

**Issue by avogadroB** [ayush-that/FinVeda#1530]
### Is your feature request related to a problem? Please describe.

The user navigation throughout the website is uneven as the Nav bar is missing in the FAQ/help us section. The user is only allowed to go to the home page from this page.

### Describe the solution you'd like.

Add the Navigation bar used for other pages to make the UI better and ensure the page structure across the website is uniform.

### Describe alternatives you've considered.

the FAQs can be a part of the home page itself below the feedback section.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/d9c0ce1d-afaf-4545-a9f9-8095f0ee106d)
this the current faq section

![image](https://github.com/user-attachments/assets/8c941d77-7349-4f34-9d0d-bcfe4794fb0c)
this nav bar should be added

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by avogadroB** [comment]
@Sampadatiwari please assign me this

**Comment by avogadroB** [comment]
hey @sampadatiwari30 is it fine if i also add the nav bar to the trends section??

**Comment by avogadroB** [comment]
@sampadatiwari30 i have created a pull request with the changes. please check.

**Comment by avogadroB** [comment]
hi please add the necessary tags for this issue

**Comment by Sampadatiwari** [comment]
@avogadroB I will give you tag, when your issue is solve.

**Comment by avogadroB** [comment]
> @avogadroB I will give you label, when your issue is solve.

Hey! I have solved it and my pr has been approved.
