### ISSUE TITLE
Title: Adding a scroll to top button on the home page

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1537]
### Is your feature request related to a problem? Please describe.

Yes it is a problem because after scrolling to down we have to scroll all the way up to access other pages or features of the webpage.

### Describe the solution you'd like.

I would add a scroll to top button which on pressed will automatically scroll to the top of the webpage

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Snehamanded** [comment]
I would like to work on this ask please do assign me this task

**Comment by Son7c** [comment]
> I would like to work on this ask please do assign me this task

I am already assigned to this issue
