### ISSUE TITLE
[Bug Title here] Improving the navbar as login button not visible fully

### ISSUE THREAD

**Issue by Prizag** [ayush-that/FinVeda#1538]
### What happened?

in the navbar the login/register button is not visible fully lettters are cut. i expected it to be shown clearly
![Screenshot 2024-10-19 002320](https://github.com/user-attachments/assets/0955551b-28a2-4a4e-9dc0-3b0e2f2d584c)

### How can we reproduce this bug?

we can manage navbar styling to make it better

### Urgency (Optional)

Medium priority

**Comment by sampadatiwari30** [comment]
@Prizag this is issue has been resolved.
