### ISSUE TITLE
[Bug Title here] Fix Overflow Issue for 'Accept All Cookies' Button

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ayush-that/FinVeda#1546]
### What happened?

In the cookie box, the "Accept all cookies" button is not contained within the box; it's overflowing outside of the cookie box.
 ### Screenshot
![cookiew](https://github.com/user-attachments/assets/33986e5f-48ab-4024-b397-97367762fe30)

### How can we reproduce this bug?

1. Open the Application: Navigate to the page with the cookie consent box.
2.Locate the Cookie Box: Identify the cookie consent box and the "Accept all cookies" button.
3.Observe Overlap: Check if the "Accept all cookies" button is overflowing outside the cookie box in its normal width.

### Urgency (Optional)

Medium priority

**Comment by sampadatiwari30** [comment]
@biswajit-sarkar-007 this issue is resolved.
