### ISSUE TITLE
Feat: [Backend] for login and register feature. 

### ISSUE THREAD

**Issue by abhiperfect** [ayush-that/FinVeda#155]
### Describe the feature

The backend login and register feature enables users to create new accounts securely and log in to access personalized content or services within an application or platform.

### It should be implemented because

Implementing the backend login and register feature is essential for ensuring secure access control to your application or platform, safeguarding user data, and providing a personalized experience for users.

### Would you like to work on this issue?

Yes

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by ayush-that** [comment]
Assigning this issue to @abhiperfect 
Please implement it well.

**Comment by RamakrushnaBiswal** [comment]
hi @ayush-that i want to work upon it can you assign it to me
