### ISSUE TITLE
Fixing Footer of Home page 

### ISSUE THREAD

**Issue by AsifQamar** [ayush-that/FinVeda#1557]
### What happened?

the quick links are removed 

### How can we reproduce this bug?

have to fix it 

### Desktop Information (Optional)

windows
<img width="960" alt="Screenshot_297" src="https://github.com/user-attachments/assets/a7230dfc-9af4-4179-beb7-65c9029632e3">

### Urgency (Optional)

High priority

**Comment by AsifQamar** [comment]
@Sampadatiwari please assign me this

**Comment by haseenpari** [comment]
Please assign  me this
