### ISSUE TITLE
Feat: Initiate Node.js Express server.

### ISSUE THREAD

**Issue by abhiperfect** [ayush-that/FinVeda#156]
### Describe the feature

The feature involves setting up a Node.js server using the Express framework. This enables handling HTTP requests, defining routes, and implementing middleware, facilitating the development of web applications and APIs.

### It should be implemented because

Implementing the Node.js Express server is crucial because it forms the foundation for building scalable and efficient web applications. It enables rapid development, easy routing, middleware integration, and handling of HTTP requests, ensuring a robust backend infrastructure for the application.

### Would you like to work on this issue?

Yes

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by Agarwalvidu** [comment]
If you want to add this, do you have a plan what you will be doing and how you will be integrating that for website? @abhiperfect

**Comment by Agarwalvidu** [comment]
As no response is sen from the contributor I am closing this issue. Thanks for collaborating.
