### ISSUE TITLE
Duplicate Help Button on Navbar for Contact and Career Pages

### ISSUE THREAD

**Issue by ritiksingh-01** [ayush-that/FinVeda#1565]
### What happened?

Both the Contact and Career pages are displaying two "Help" buttons on the navbar, leading to a cluttered and confusing interface. This inconsistency affects the overall user experience (UX) by making the navigation less clear. A fix is needed to ensure only one "Help" button is displayed, maintaining a clean and professional UI across all pages.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

![image](https://github.com/user-attachments/assets/94bf6a7b-e899-437c-833c-ed468f9189cc)
![image](https://github.com/user-attachments/assets/282d670f-5fe8-4b93-a775-1d51c1e32eac)

### How can we reproduce this bug?

NA

### Urgency (Optional)

High priority

**Comment by ShivangJSS** [comment]
hey @ritiksingh-01 plz assign this issue

**Comment by ShivangJSS** [comment]
hey @Sampadatiwari please assign this issue to me

**Comment by sampadatiwari30** [comment]
@ShivangJSS this issue has been resolved.
