### ISSUE TITLE
[Bug Title here]  SignUp button in login page is not redirecting to Signup page

### ISSUE THREAD

**Issue by Hamza1821** [ayush-that/FinVeda#1569]
### What happened?

SignUp button in login page is not redirecting to Signup page

assing this to me under gssoc-ext

### How can we reproduce this bug?

got to login page try to click on signup button on left side

### Desktop Information (Optional)

Os : windows 11
browser : firefox

### Urgency (Optional)

None

**Comment by tanisha-ac1** [comment]
Please assign me this task.

**Comment by Hamza1821** [comment]
I have raised the issue so assign this to me under gssoc ext

**Comment by ShivangJSS** [comment]
this issue should be closed because i think is have already been fixed
