### ISSUE TITLE
[Bug Title here] Add Footer section on Help Page

### ISSUE THREAD

**Issue by Sudhanshu248** [ayush-that/FinVeda#1578]
### What happened?

The footer section is not present on help page.
Which creates it different from the website.
![Screenshot 2024-10-19 171420](https://github.com/user-attachments/assets/b61902a4-d537-412a-b3a2-433ebc350b9d)

### How can we reproduce this bug?

I would like to add footer section to help page.

### Urgency (Optional)

High priority

**Comment by Sudhanshu248** [comment]
@ayush-that @sampadatiwari30 Kindly assign me the issue under the label of gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-2.

**Comment by ishivansmishra** [comment]
@Sampadatiwari 
Kindly please assign me this issue
