### ISSUE TITLE
Feat: Creating a logo for website.

### ISSUE THREAD

**Issue by abhiperfect** [ayush-that/FinVeda#158]
The logo for the website will be a visual representation of its brand identity, embodying its values, mission, and aesthetic. It will include elements such as colors, typography, and symbols to convey the website's purpose and attractively represent it across various platforms and contexts.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me.I would like to wrok on this issue. #gssoc24

**Comment by nileshsn** [comment]
Assign me, and I will design the best logo for the site. @abhiperfect 

My previous works https://drive.google.com/drive/folders/1xphep8Ov44Kw63kjDfGKcx_WgkISKiSZ?usp=drive_link

**Comment by ayush-that** [comment]
Already exists.
![image](https://github.com/ayush-that/FinVeda/assets/110257939/dd46595d-c6e6-4ded-8591-f81b8134a282)
