### ISSUE TITLE
Title: Linking of website logo with home page.

### ISSUE THREAD

**Issue by sneha056** [ayush-that/FinVeda#1581]
### Is your feature request related to a problem? Please describe.

Hey @ayush-848, I have notice none of page logo is linked with its home page.  For example when you are at blogs page on clicking on website logo it should navigate us to the home page. 

### Describe the solution you'd like.

Every page logo should be linked with its home page.

### Describe alternatives you've considered.

Every page logo should be linked with its home page.

### Add any other context or screenshots about the feature request here.

https://github.com/user-attachments/assets/a18ab520-a686-4ba5-b2e4-3eb4e4ad0960

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by ShivangJSS** [comment]
hey @deepeshmlgupta please assign this issue to me.

**Comment by sneha056** [comment]
Hey @deepeshmlgupta I have raised PR #1640. If possible could you please label this task with some level number.
