### ISSUE TITLE
[Bug Title here]  Scroll to top arrow not visible

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1585]
### What happened?

![Screenshot 2024-10-19 192607](https://github.com/user-attachments/assets/4d8d2a3d-9826-4dd2-ab35-5c3b3b42153e)

### How can we reproduce this bug?

see scroll to top button

### Desktop Information (Optional)

Windows

### Urgency (Optional)

Medium priority

**Comment by ak-0283** [comment]
@ayush-that @Son7c   can you please assign me this issue ?
