### ISSUE TITLE
[Bug Title here] Bubble Animation not visible in home page

### ISSUE THREAD

**Issue by Son7c** [ayush-that/FinVeda#1598]
### What happened?

https://github.com/user-attachments/assets/2cdf8f31-6abb-46bd-be3a-c65a1a9af3da

### How can we reproduce this bug?

Go to home page

### Desktop Information (Optional)

windows

### Urgency (Optional)

High priority

**Comment by Son7c** [comment]
@deepeshmlgupta @Sampadatiwari @Deekshashakyawal Please assign me this issue i will fix it right now

**Comment by deepeshmlgupta** [comment]
reupload the screenshort

**Comment by Son7c** [comment]
done

**Comment by Son7c** [comment]
@deepeshmlgupta i've checked it isn't there in the home page


https://github.com/user-attachments/assets/080aad68-2438-41eb-a79b-4c34a285a1cf

**Comment by Son7c** [comment]
@deepeshmlgupta it cant be possibly be there because i have checked where the problem is.

**Comment by deepeshmlgupta** [comment]
ok, got it start working on it
