### ISSUE TITLE
Button on index.html does not function right.

### ISSUE THREAD

**Issue by chiragHimself** [ayush-that/FinVeda#16]
Major functionality button on home page " Chat with ArthaSathi" does not navigate to the chatbot instead it alert's you to tapping to chat button , which does not server its purpose. I can add the navigation functionality quickly to this button to make it function right. Please assign me so i can work and act quickly.
![image](https://github.com/ayush-that/FinVeda/assets/118044484/60e03c9f-9e8d-427d-94cf-a32fd22d3ec6)

**Comment by pandey079** [comment]
Please assign it to me under GSSOC'24

**Comment by debasmi** [comment]
i have done projects under coursera kindly assign me this under gssoc 24

**Comment by ayush-that** [comment]
@chiragHimself, @debasmi, @pandey079 
ArthSathi is added using Botpress. Will you be able to do it? Are you aware of Botpress chatbots?

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.

**Comment by Soujanya2004** [comment]
hi, I have been following your project and would love to contribute, please assign me the issue.
