### ISSUE TITLE
The Home card are not center aligned on mobile screen.

### ISSUE THREAD

**Issue by ambarmishraa** [ayush-that/FinVeda#1607]
### What happened?

![image](https://github.com/user-attachments/assets/7dcff3c1-43bc-4a33-899c-b9047438b2a8)
The Home cards are not center-aligned on mobile screens. Instead of appearing centered within their container, they may be aligned to the left or displayed unevenly, causing an unbalanced layout.

### How can we reproduce this bug?

To reproduce the bug with the Home cards not being center-aligned on mobile screens, follow these steps:

Open the Application:

Launch the application or website containing the Home page with the cards.
Resize the Browser Window:

If you’re using a desktop, manually resize the browser window to a mobile screen size (e.g., 375px width). Alternatively, you can use the developer tools (usually accessed by pressing F12 or right-clicking and selecting "Inspect") and toggle device mode to simulate mobile screens.
Navigate to the Home Page:

Navigate to the Home page where the cards are displayed.
Observe the Card Alignment:

Look at the alignment of the Home cards. Check if they are aligned to the left or have uneven spacing instead of being centered within their container.
Expected Behavior
You should expect the following behavior:

The Home cards should be perfectly centered within their container when viewed on mobile screens.
Each card should have equal spacing around it, maintaining a balanced layout.
The content within the cards should also be properly aligned (e.g., text should be centered or left-aligned based on the design).

### Urgency (Optional)

High priority

**Comment by ambarmishraa** [comment]
@Sampadatiwari Assign this task i will do it Asap @sampadatiwari30

**Comment by ambarmishraa** [comment]
Mam please add the labels here @sampadatiwari30

**Comment by Sampadatiwari** [comment]
@ambarmishraa I will add the label, when your PR is created.

**Comment by ambarmishraa** [comment]
@Sampadatiwari ok
