### ISSUE TITLE
[Feat]:Add different button for registration and add register page

### ISSUE THREAD

**Issue by theashikagupta** [ayush-that/FinVeda#161]
Website does not have register page like login page and a different button for registration .
A single button for both login and register may create an issue for users.
![Screenshot 2024-05-18 124758](https://github.com/ayush-that/FinVeda/assets/136061047/5bbf60b7-f047-4a66-a3a8-93810262d65d)

**Comment by Rishitatripathi** [comment]
Kindly assign me this issue under GSSoC'24

**Comment by Agarwalvidu** [comment]
Register page already exists and no need of different register button is  there. Thank you for raising issue, looking for your more inputs. For now I am closing this issue.
