### ISSUE TITLE
[FEATURE REQUEST]: Add Search Functionality for FAQs

### ISSUE THREAD

**Issue by PrityanshuSingh** [ayush-that/FinVeda#1612]
### Is your feature request related to a problem? Please describe.

Currently, the search functionality for the Frequently Asked Questions (FAQs) section is not working. This makes it difficult for users to quickly find relevant information, leading to a bad experience when searching for specific topics within the FAQs.

### Describe the solution you'd like.

Implement a real-time search feature for the FAQs section, allowing the search results to dynamically update and render the matching FAQs as the user types in the search bar. This feature should highlight the relevant keywords and display the most closely related results first, providing a seamless and efficient search experience.

### Describe alternatives you've considered.

Adding a filter option where users can categorize FAQs based on topics.

### Add any other context or screenshots about the feature request here.

This feature will significantly improve the user experience by making it easier to find specific information within the FAQs quickly. It will be particularly helpful for users seeking answers to common questions without navigating through multiple pages.

### Video

https://github.com/user-attachments/assets/cfafd614-a338-4c22-968f-ab5f1ca6fd74

@ayush-that @Sampadatiwari Please assign this issue to me under gssoc-ext level3 and hactoberfest-accepted, as I am interested in working on it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by PrityanshuSingh** [comment]
Hi @sampadatiwari30, could you please assign me labels for gssoc-ext level3 and hactoberfest-accepted, before i start working on the issue.

**Comment by PrityanshuSingh** [comment]
@deepeshmlgupta could you add level3 as i will be working on a new feature.

**Comment by deepeshmlgupta** [comment]
> @deepeshmlgupta could you add level3 as i will be working on a new feature.

Sure, I will be adding the level once you create the PR
