### ISSUE TITLE
[Bug Title here] The layout on tools page form alignment issue.

### ISSUE THREAD

**Issue by ambarmishraa** [ayush-that/FinVeda#1613]
### What happened?

![image](https://github.com/user-attachments/assets/b79f3947-2e9a-40ef-8ac6-4e81c9036862)
The text are overlapping making the form appearance unattractive.

### How can we reproduce this bug?

To reproduce the issue of overlapping text in the form, follow these steps:

Open the Application:

Launch the application or website that contains the form with overlapping text.
Navigate to the Form:

Go to the section of the application where the form is located.
Resize the Browser Window:

If you are using a desktop, adjust the browser window size to simulate smaller screens (e.g., 480px width) or view the form on a mobile device.
Fill in the Form:

Start entering text into the form fields. Pay attention to the labels, input fields, and any other text elements.
Observe the Layout:

Look for instances where the text overlaps with other text or form elements, making it difficult to read or interact with the form.

### Urgency (Optional)

High priority

**Comment by Nayanbatman** [comment]
@ayush-that please sir assign this issue to me under gssoc-extd and hacktoberfest. That's humble request to you . I can fix it

**Comment by ambarmishraa** [comment]
@ayush-that Assign me i will do it asap
