### ISSUE TITLE
Adding social media icons

### ISSUE THREAD

**Issue by balimpuramvikasgoud** [ayush-that/FinVeda#162]
As a Gsoc contributor i observed that your website does not have "Social media icons" (GITHUB,INSTAGRAM) .So i want  to add them at the bottom of the page.

**Comment by vctigerrfab** [comment]
I can easily fix this.Please assign this issue to me

**Comment by Azhar-0401** [comment]
*is your feature request related to a problem? Please describe.*
Currently not add social media icon

*Describe the solution you'd like*
Adding social media icon

*Additional context*
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me

**Comment by Rishitatripathi** [comment]
Can you assign me this issue under GSSoC'24 as a contributor

**Comment by Agarwalvidu** [comment]
As this is a professional website there is no need of github and instagram.  Thank you for raising issue, looking for your more inputs. For now I am closing this issue.
