### ISSUE TITLE
Title: Add a leaderboard in quiz section

### ISSUE THREAD

**Issue by Nayanbatman** [ayush-that/FinVeda#1620]
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like.

Add a leader board in quiz section . It will enhance the interest among users for participating in quiz . @ayush-that assign this issue to me under gssoc-extd and hacktoberfest.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
not needed
