### ISSUE TITLE
 [BUG]: FAQ Page Image Misalignment and Partial Visibility

### ISSUE THREAD

**Issue by PrityanshuSingh** [ayush-that/FinVeda#1627]
### What happened?

The image on the FAQ page is not correctly aligned and is partially hidden on the left side of the screen. As a result, the image appears half-cut and is not entirely visible. This misalignment disrupts the visual layout and negatively affects the user experience.
The image should be properly aligned with the FAQ heading, making it fully visible and maintaining a consistent layout across different screen sizes.

###Screenshot:
![image](https://github.com/user-attachments/assets/06b417ef-4cae-4f2e-9a6c-45133e6d9e71)
![image](https://github.com/user-attachments/assets/1509faf5-35a2-4223-8f6a-7b3db0ddf3cf)

### How can we reproduce this bug?

1. Navigate to the FAQ page.
2. Observe the image associated with the FAQ section.
3. Notice that the image is not correctly aligned and is partially hidden on the left side.

### Desktop Information (Optional)

OS: Windows 11
Browser: Chrome, Firefox, Microsoft Edge
Browser Version: Latest

### Urgency (Optional)

Medium priority

@ayush-that @Sampadatiwari Please assign this issue to me under gssoc-ext level2 and hactoberfest-accepted, as I am interested in working on it.

**Comment by PrityanshuSingh** [comment]
Hi @sampadatiwari30 @ayush-that , could you please assign me labels for gssoc-ext level2 and hactoberfest-accepted, before i start working on the issue.

**Comment by Sampadatiwari** [comment]
@PrityanshuSingh I will give you label, once your issue is resolve.
