### ISSUE TITLE
Too Heavy Navbar!

### ISSUE THREAD

**Issue by Kevindua26** [ayush-that/FinVeda#1628]
### We need to improve the NAVBAR as -
- Current navigation bar of the website appears overloaded with multiple links. 
- This affects the overall user experience and makes the website seem cluttered. 
- To improve the UI/UX design, I will refactor the navbar by introducing a dropdown. 
- This change will simplify the interface, reduce visual clutter, and enhance navigation flow for users.

### Add screenshots

![Screenshot 2024-10-20 021727](https://github.com/user-attachments/assets/c01e1a00-81e8-4475-ab30-6cb61a63cc48)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Kevindua26** [comment]
Hey @Sampadatiwari can you please assign assign me the suitable `level` labels and other labels `hacktoberfest-accepted` and `gssoc-ext`

**Comment by Sampadatiwari** [comment]
@Kevindua26 I will give you label after your work is complete.

**Comment by Kevindua26** [comment]
Hey @Sampadatiwari you can close the issue now.
