### ISSUE TITLE
Tools page responsiveness

### ISSUE THREAD

**Issue by amri-tah** [ayush-that/FinVeda#163]
This website looks really cool on its own! But the tools page is not responsive.

![image](https://github.com/ayush-that/FinVeda/assets/111682039/9c53dee1-ae5d-468c-ad3c-a6cd8a622d9c)<img src="https://github.com/ayush-that/FinVeda/assets/111682039/d687d140-181a-4052-ac5d-4e22f6007acc" alt="Image Alt Text"  height="500">

I'd love to work on this, please assign this issue to me under GSSOC 2024 :)

**Comment by sakshiagrawal2711** [comment]
I would like to work ,please assign this work to me

**Comment by Sooraj002** [comment]
I have made Many responsive website, And i Think i can Fix this , Please assign me this issues, I would like to fix this issue.

**Comment by Azhar-0401** [comment]
*is your feature request related to a problem? Please describe.*
Currently tool page is not responsive .

*Describe the solution you'd like*
i can fix this issue 

*Additional context*
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me

**Comment by Agarwalvidu** [comment]
This issue has been already assigned to someone else. Please look into more issues ans raise the same. Thank you for collaborating.
