### ISSUE TITLE
[Bug Title here] The FAQ section links are not visible, Improve alignment

### ISSUE THREAD

**Issue by avogadroB** [ayush-that/FinVeda#1638]
### What happened?

The links are not visible due to clashing blue colors, so change the background colour to a more subtle blue. Align the links and the social media handles horizontally instead of vertically and get them to the center.

### How can we reproduce this bug?

1. Go to the FAQ section
2. scroll down
![image](https://github.com/user-attachments/assets/62442191-9fa2-4ae3-b623-fab0b63c0512)

### Urgency (Optional)

Medium priority

**Comment by avogadroB** [comment]
@sampadatiwari30 please assign me this

**Comment by sampadatiwari30** [comment]
@avogadroB this is issue has been resolved.
