### ISSUE TITLE
feat/ there is absence of login-page in tools page

### ISSUE THREAD

**Issue by drick-infinity** [ayush-that/FinVeda#164]
![Screenshot (57)](https://github.com/ayush-that/FinVeda/assets/116994649/32e7f54c-3c4d-4689-a211-99aa4d620972)

there is a issue 
the colour of sign in button is blue in home page here i resolve this and there is one more issue in which login page is absent in tools tab 
Both issue are resolved
here I resolve in this pull request can you assign this under gssoc'24
I made this change

**Comment by Agarwalvidu** [comment]
It is updated now. Thank you for raising issue, looking for your more inputs. For now I am closing this issue.
