### ISSUE TITLE
Dark mode not applied inside a blog

### ISSUE THREAD

**Issue by AnishaDevi** [ayush-that/FinVeda#1644]
In dark mode enabled also the page is in light mode
![image](https://github.com/user-attachments/assets/5debaa94-6f02-45bd-bb24-1ec8dd937b55)

@Sampadatiwari 
I can work on this

- [x] gsoc contributor
- [x] hacktoberfest contributor

**Comment by AnishaDevi** [comment]
May I know the labels assigned

**Comment by Sampadatiwari** [comment]
@AnishaDevi I will give you the label, when your work is completed.
