### ISSUE TITLE
Title: Add login page 

### ISSUE THREAD

**Issue by pratapVansh** [ayush-that/FinVeda#1655]
### Is your feature request related to a problem? Please describe.

there is option of login but when we click the button there is not any login page .
![finvedaSingup](https://github.com/user-attachments/assets/e98de8d3-9eca-40e6-b6bb-ef51510d7d3e)

### Describe the solution you'd like.

 i will add the login page 

### Describe alternatives you've considered.

i will add the login page and it will have option to move on register page 

### Add any other context or screenshots about the feature request here.

![logindemo](https://github.com/user-attachments/assets/e0afff02-fbaa-48e9-a91a-8e244fcb0fad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
Not needed
