### ISSUE TITLE
[style]: UI IMPROVEMENT IN CONTRIBUTORS SECTION

### ISSUE THREAD

**Issue by isimarjitsingh** [ayush-that/FinVeda#1657]
### What's the style idea?

We need to improve  the designing of "our contributors section" in about page. please assign me this work as i am able to provide:-
- eye catching colors 
- hover effects 
- transitions effect
- smooth user experience
- good designing

### Add screenshots

CURRENT DESIGNING:-
![Screenshot 2024-10-20 164736](https://github.com/user-attachments/assets/c9f234ce-8e57-4b07-9f4c-281c423919f2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Nayanbatman** [comment]
Please sir assign this issue to me under gssoc-extd and hacktoberfest . I can fix it .
