### ISSUE TITLE
Bug: Login Form Appears Behind Other Components When Clicking Subscribe Button

### ISSUE THREAD

**Issue by thevijayshankersharma** [ayush-that/FinVeda#166]
When the "Subscribe" button is clicked, the login form is not displayed in the foreground. Instead, it appears behind other components, making it inaccessible and non-interactive.

Steps to Reproduce:

Navigate to the page containing the "Subscribe" button.
Click on the "Subscribe" button.

The login form should appear in the foreground, overlaying other components to allow users to interact with it.

Actual Behavior:
The login form appears behind other components, rendering it unusable.

Screenshots:

![Screenshot 2024-05-18 185934](https://github.com/ayush-that/FinVeda/assets/109781385/b10d15e1-513c-49ba-96a8-6075650b5e1b)

**Comment by Agarwalvidu** [comment]
It is updated now. Thank you for raising issue, looking for your more inputs. For now I am closing this issue.
