### ISSUE TITLE
Misalignment of Navigation Bar

### ISSUE THREAD

**Issue by Nayanbatman** [ayush-that/FinVeda#1660]
### What happened?

The navigation bar is not properly aligned which affects overall visual harmony and consistency of the design. @ayush-that Please assign this issue to me under gssoc-extd and hacktoberfest . I can fix it .

### How can we reproduce this bug?

NA

### Desktop Information (Optional)

NA

### Urgency (Optional)

None

**Comment by Deekshashakyawal** [comment]
Please add screenshots , it would speed up the assigning process
