### ISSUE TITLE
[Bug Title here] Footer issue 🔴

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ayush-that/FinVeda#1689]
### What happened?

Footer totally messed up, I want to fixed this issue properly...

@ayush-that please assign me this task.

![Screenshot 2024-10-20 201833](https://github.com/user-attachments/assets/39809f0e-f5c8-4a74-84ac-1b871510d25f)

### How can we reproduce this bug?

..

### Urgency (Optional)

None

**Comment by Subhajit-2023-44** [comment]
@Sampadatiwari

**Comment by ayusharyan143** [comment]
please assigne it to me
