### ISSUE TITLE
[BUG] (Contact Us) section of the footer of Tools page needs to be fixed. 

### ISSUE THREAD

**Issue by anubhavvsharma** [ayush-that/FinVeda#1690]
### What happened?

The words have no space between them and need to be properly alligned. 
![Screenshot (388)](https://github.com/user-attachments/assets/016dc27d-7b21-498f-90a2-f3e3bb6170f7)

### How can we reproduce this bug?

@Sampadatiwari @deepeshmlgupta Assign me, I can fix this. 
Thank you.

### Urgency (Optional)

None

**Comment by Subhajit-2023-44** [comment]
Duplicate #1689
