### ISSUE TITLE
Hover Effect on the LOGIN/REGISTER button.

### ISSUE THREAD

**Issue by chakrabortydeep** [ayush-that/FinVeda#170]
There should some hover effect on the login/register button to make it look nice.

**Comment by chakrabortydeep** [comment]
Please assign this task to me. I can change the css of the LOGIN/REGISTER button easily and efficiently as per your requirements.

**Comment by vctigerrfab** [comment]
i can make this change easily,kinly assign this issue to me.

**Comment by Rishitatripathi** [comment]
Kindly assign me this issue under GSSoC'24

**Comment by Agarwalvidu** [comment]
It is updated now. Thank you for raising issue, looking for your more inputs. For now I am closing this issue.
