### ISSUE TITLE
[style]: Loader Looks Boring

### ISSUE THREAD

**Issue by PulkitShubham** [ayush-that/FinVeda#1706]
### What's the style idea?

I want to add a cool animated loader.......kindly assign this task to me

### Add screenshots

![image](https://github.com/user-attachments/assets/9fb6bd71-18f7-4dbc-a5e2-8b9b42e0467a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by PulkitShubham** [comment]
@Sampadatiwari ...Thank u for assigning this issue to me .. I'll complete this by today

**Comment by PulkitShubham** [comment]
@Sampadatiwari please add gssoc-ext and hacktoberfest labels to it

**Comment by Sampadatiwari** [comment]
@PulkitShubham I will add the labels, when your work is complete.

**Comment by PulkitShubham** [comment]
Okayy ....Thank you

**Comment by PulkitShubham** [comment]
@Sampadatiwari Please check my PR #1727
