### ISSUE TITLE
Footer link to website is not working

### ISSUE THREAD

**Issue by AtharvKasar04** [ayush-that/FinVeda#171]
![image](https://github.com/ayush-that/FinVeda/assets/108543702/143ecc98-d90d-4171-9024-26be6e86e9b6)

The links in the contact us of the footer is not working so will make them work and point to the right target where they are supposed to.
@ayush-that Can you please assign me this issue under GSSoC'24. 
Thank You!

**Comment by Azhar-0401** [comment]
*is your feature request related to a problem? Please describe.*
Currently Footer page has not  working and such a good style  .

*Describe the solution you'd like*
Adding routing condept and adding margin, padding and set allginment and change in font and changes according to Footer

*Additional context*
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me

**Comment by Agarwalvidu** [comment]
This issue has already been resolved, for the same reason I am closing this issue. Thank you for collaborating!
