### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [ayush-that/FinVeda#1711]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @ayush-that 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by smog-root** [comment]
Added level3 with gssoc-ext and hacktoberfest-accepted labels! @sampadatiwari30

**Comment by Sampadatiwari** [comment]
@smog-root I will add the label when your work is completed.
