### ISSUE TITLE
Adding directing link to the top stories in trends.html

### ISSUE THREAD

**Issue by sakshiglaze** [ayush-that/FinVeda#172]
Hello @ayush-that,
To improve the user experience when reading top stories, we can add supporting links that direct users to detailed informative pages for each story.
Clicking on a particular story will seamlessly navigate the user to an in-depth page with comprehensive coverage, relevant data, and credible sources related to that specific story.
This feature enhances transparency and understanding by providing easy access to supporting information.
Hope you like this add on feature. I would love to work on that under GSSOC'24.
Thankyou!

**Comment by Agarwalvidu** [comment]
It is already there. Thank you for raising issue, looking for your more inputs. For now I am closing this issue.
