### ISSUE TITLE
[style]: side social icons

### ISSUE THREAD

**Issue by Theboycut05** [ayush-that/FinVeda#1722]
### What's the style idea?

We need to improve  , the side icons on the right of the website will make it interactive and catch the attention of the users and its responsive. 

https://github.com/user-attachments/assets/3b87245c-5f4b-4b6a-9d9f-b789e218f50f

@ayush-that 

### Add screenshots

Add screenshots
![Screenshot (81)](https://github.com/user-attachments/assets/322f1c9b-5432-41da-bc37-e3ee72f63191)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Theboycut05** [comment]
@deepeshmlgupta level !

**Comment by deepeshmlgupta** [comment]
It will be assigned when you will create the PR
