### ISSUE TITLE
Structure the user experience card size

### ISSUE THREAD

**Issue by dharshini2022** [ayush-that/FinVeda#173]
Equalise the user experience card size in the home  page
![Screenshot 2024-05-19 224321](https://github.com/ayush-that/FinVeda/assets/123349807/0201b080-737d-42cb-9a67-c410d53fb913)

**Comment by dharshini2022** [comment]
Pls assign me this issue under Gssoc'24

**Comment by Agarwalvidu** [comment]
This issue is already been solved. Thank you for contributing, looking for more issues from your end. For now I am closing this issue.
