### ISSUE TITLE
Enhance the css of calculators

### ISSUE THREAD

**Issue by dharshini2022** [ayush-that/FinVeda#174]
Enhance the CSS of Mutual funds and EMI calculator
![Screenshot 2024-05-19 224547](https://github.com/ayush-that/FinVeda/assets/123349807/6f5a37db-9779-4fdd-820e-8c2e2bbcbd63)

**Comment by dharshini2022** [comment]
Pls assign me this issue under GSSOC'24

**Comment by soumyaarya** [comment]
Pls assign this issue to me @ayush-that  under GSSOC'24

**Comment by ChaitanyaLonarkar** [comment]
I want to work on the CSS of the both the calculator EMI Calculator and Mutual Fund Investment Calculator. So that the UI looks more attractive to the users.

**Comment by Agarwalvidu** [comment]
@dharshini2022 Go ahead!

**Comment by Agarwalvidu** [comment]
@dharshini2022 update?

**Comment by dharshini2022** [comment]
@Agarwalvidu I'm working on it. I will complete the PR by tomorrow.

**Comment by Devanshu1603** [comment]
please assign this me under gssoc ext
