### ISSUE TITLE
Footer is repeated in Help page.

### ISSUE THREAD

**Issue by anubhavvsharma** [ayush-that/FinVeda#1742]
### What happened?

![Screenshot (9)](https://github.com/user-attachments/assets/fe55e655-b7c0-4f74-a238-8941d52fb108)

### How can we reproduce this bug?

Extra footer needs to be removed. @Sampadatiwari 

### Urgency (Optional)

None

**Comment by ishivansmishra** [comment]
@Sampadatiwari please assign this issue to me
