### ISSUE TITLE
Adding animations in the Navbar

### ISSUE THREAD

**Issue by MHusain22** [ayush-that/FinVeda#175]
I can Add animations to the Page on loading in the Navbar just like in my portfolio website https://mhportfolio.vercel.app/. Please assign me this to add new feature.

I have checked the existing issues *
I have read the Contributing Guidelines *
I have starred the repository *
Working under Gssoc'24

**Comment by ayush-that** [comment]
Hi @MHusain22 
assigning this to you under gssoc
have fun

**Comment by MHusain22** [comment]
@ayush-that the website on my local environment is just loading.
![Uploading loading.png…]()

**Comment by MHusain22** [comment]
![loading](https://github.com/ayush-that/FinVeda/assets/118285713/23736536-2c8d-4745-b664-1713d0f8153a)

**Comment by Yuvraj960** [comment]
@ayush-that Please assign this issue to me under GSSoC24

**Comment by Agarwalvidu** [comment]
No need of animations in Navbar. Thanking you for raising this issue. Looking for more issues from your side.;
