### ISSUE TITLE
Fix CSS of widgets on the homepage

### ISSUE THREAD

**Issue by ashuna-dev** [ayush-that/FinVeda#176]
![image](https://github.com/ayush-that/FinVeda/assets/144206299/aa59ce8e-d8f3-4e15-8712-4f9f35ce1d03)
Problem: The css of the trading view widget on the homepage is bugged.
Assign me this under gssoc so that i can fix it.

**Comment by ayush-that** [comment]
Hi @ashuna-dev 
assigning this issue to you under gssoc
Have fun!

**Comment by ayush-that** [comment]
#177 solved
