### ISSUE TITLE
Title: Fixing Google authentication using Auth js.

### ISSUE THREAD

**Issue by AyushPandey003** [ayush-that/FinVeda#1761]
### Is your feature request related to a problem? Please describe.

In your current site login using google is not working. As a Nextjs developer i had implemented next auth and auth js with facilitaes login with various social account.

### Describe the solution you'd like.

Problem Statement
Currently, the Google login functionality on the site is not working as expected. Users are unable to log in using their Google accounts, which affects the user experience and accessibility of the site.

Desired Solution
I would like the Google login feature to function properly. This includes:

Users should be able to click on the Google login button.
Upon clicking, users should be redirected to the Google authentication page.
After successful authentication, users should be redirected back to the application and granted access.
The application should handle errors gracefully, providing users with clear feedback in case of login failure.

### Describe alternatives you've considered.

Manual OAuth Implementation: Instead of using NextAuth, I considered manually implementing OAuth2 for Google login. However, this approach would require more development time and may introduce security vulnerabilities if not implemented correctly.

Using Another Authentication Provider: I contemplated implementing login using other social providers (like Facebook or Twitter) to ensure users can still access the application. However, this does not address the primary issue with Google login.

Fallback to Email/Password Authentication: Providing a fallback login option using email and password would be an alternative. While this can work, it adds extra complexity and does not leverage the social login feature that users may prefer.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/093f3f97-02b9-41e5-a714-1b0402ad097a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by AyushPandey003** [comment]
can you please assign with labels Gsoc-extd Level and hactoberfest.

**Comment by sampadatiwari30** [comment]
@AyushPandey003 i will add the labels when you task is complete.
