### ISSUE TITLE
[Bug]: Theme Change Button Not Working on Homepage 

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ayush-that/FinVeda#1764]
### What happened?

The theme change button on the homepage is not functioning as expected. Clicking the button does not switch the website's theme (e.g., from light to dark mode). This inconsistency affects user experience, especially for users who prefer different themes.

### How can we reproduce this bug?

1. Open the homepage of the website.
2. Click the button to change the theme.
3. Observe that the theme does not change, or there is no visual feedback.
4. Test the button on other pages to see if it works there.

### Urgency (Optional)

High priority

**Comment by RahulPrasadYadav** [comment]
assign the issue
