### ISSUE TITLE
[style]:  sign in hover add 

### ISSUE THREAD

**Issue by RahulPrasadYadav** [ayush-that/FinVeda#1768]
### What's the style idea?

We need to improve  

### Add screenshots

![Screenshot (372)](https://github.com/user-attachments/assets/22c489d3-e029-4977-b6ec-e38cc0c98926)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by sampadatiwari30** [comment]
@RahulPrasadYadav describe what you want to improve.

**Comment by RahulPrasadYadav** [comment]
@sampadatiwari30 you can also sign in with facebook   and X it is not an add on and also  hovet add to sign button
