### ISSUE TITLE
github icon hover are not working 

### ISSUE THREAD

**Issue by RahulPrasadYadav** [ayush-that/FinVeda#1769]
### What's the style idea?

The hover of the google icon should be the same

### Add screenshots

![Screenshot (373)](https://github.com/user-attachments/assets/65f87efa-c17e-46ee-bf74-01eddde2c03e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by sampadatiwari30** [comment]
@RahulPrasadYadav already resolved.
