### ISSUE TITLE
Navbar of homepage is messed and unwanted text is there.

### ISSUE THREAD

**Issue by anubhavvsharma** [ayush-that/FinVeda#1770]
### What happened?

Unwanted text is appearing in home page and buttons of navbar are also not in order.

### How can we reproduce this bug?

![Screenshot (10)](https://github.com/user-attachments/assets/ae697edd-b2bd-4a79-b02a-b6e4dc1bd083)
Assign me this @Sampadatiwari 

### Urgency (Optional)

None

**Comment by sampadatiwari30** [comment]
@anubhavvsharma this issue has been resolved.
