### ISSUE TITLE
[Bug Title here] Unwanted text on Contact Button

### ISSUE THREAD

**Issue by Dyfintie** [ayush-that/FinVeda#1772]
### What happened?

There is some unwanted text on the contact us button 

### How can we reproduce this bug?

![image](https://github.com/user-attachments/assets/1371f516-b59e-41ff-aa14-1723d2126f48)

### Urgency (Optional)

None

**Comment by sampadatiwari30** [comment]
@Dyfintie already resolved.

**Comment by Dyfintie** [comment]
> @Dyfintie already resolved.

Ma'am actually 2 navbars are loaded at once causing the overlap and making the ui bad . 
I request you to merge my  changes to fix this issue. 
Here is an image of the issue => 
![image](https://github.com/user-attachments/assets/5f11e456-bc20-441d-a83b-c4c6c54ddb32)

**Comment by sampadatiwari30** [comment]
@Dyfintie check again the website.
