### ISSUE TITLE
Title: Existing Blog with Dynamic Content Creation

### ISSUE THREAD

**Issue by Varsha-1605** [ayush-that/FinVeda#1775]
### Is your feature request related to a problem? Please describe.

# Description:
Convert the current static blog page into a dynamic platform that allows for creating and publishing content related to finance. This will enable fresh, relevant content and improve user engagement.

## Key objectives:

- [ ]  Transform static blog into a dynamic content management system.
- [ ]  Enable creation of posts specific to scholarships and job opportunities.
- [ ]  Integrate with existing scholarship and job databases for real-time updates.
- [ ]  Improve user engagement through commenting and sharing features.

### Describe alternatives you've considered.

NA

@ayush-that I would love to work on this task, could you please assign this task to me?

## Screenshots:

![image](https://github.com/user-attachments/assets/f50abf68-07e4-4e44-8552-093a433262ba)

![image](https://github.com/user-attachments/assets/0dacb352-6c2f-40d7-8cf2-2b7a1847e6d2)

![image](https://github.com/user-attachments/assets/58645850-3e8a-4d09-99d4-ee5dea9813b9)

![image](https://github.com/user-attachments/assets/3691c51c-7d40-400a-9a7b-95e572f55ac9)

![image](https://github.com/user-attachments/assets/64116d3c-76a7-4e97-8378-94bec35e9703)

![image](https://github.com/user-attachments/assets/df01965c-be8e-4348-a289-21518b32829a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by sampadatiwari30** [comment]
@Varsha-1605 already assigned.
