### ISSUE TITLE
Adding a README file, Installation and Setup Guide.

### ISSUE THREAD

**Issue by iamkanhaiyakumar** [ayush-that/FinVeda#178]
I've noticed your project lacks a README.md file, Installation and Setup Guide, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully. Can you assign me this task? I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response.

I've done a readme file for another project, you can check my profile, i always give my best.

Can you assign me please.

Thank u @ayush-that

**Comment by ayush-that** [comment]
The readme already has all the necessary details.
