### ISSUE TITLE
[Feature]:  Improvement Needed for Cards in Blog Section ✔

### ISSUE THREAD

**Issue by iarmaanx** [ayush-that/FinVeda#1783]
### What's the style idea?

# Issue Title: Improvement Needed for Cards in Blog Section

### Description:
The design and layout of the cards in the blog section could be improved for better readability and aesthetics. The current cards may lack proper spacing, alignment, or visual hierarchy, making it difficult for users to quickly scan and understand the content. Improving the card design will enhance user engagement and create a more visually appealing interface.

### Type of Issue:
- UI/UX Enhancement

### Proposed Solution:
I can improve the card design in the blog section by adjusting the layout, adding appropriate margins and padding, and enhancing the visual hierarchy. I will ensure that the cards are responsive and visually appealing across different screen sizes.

### Labels Request:
- gssoc
- hacktoberfest
- level: 2

### Screenshot:

![Screenshot (12)](https://github.com/user-attachments/assets/49324c5a-d3a1-4f2d-8575-1452ca98f6bb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by iarmaanx** [comment]
I would love to work on this issue. Consider assigning this to me.

**Comment by iarmaanx** [comment]
Labels Request:
gssoc
hacktoberfest
level: 2

**Comment by sampadatiwari30** [comment]
@iarmaanx i will add the label when your task is complete.
