### ISSUE TITLE
Adding smooth transition for back to top button

### ISSUE THREAD

**Issue by Saimanjari777** [ayush-that/FinVeda#179]
The back to top button directly takes to the top of the website it does not have any transition effect. I would like to add the smooth transition effect to the button and make the button visible only if the screen size is greater than 100.
I am working under GSSoC'24
Please assign this task to me!

**Comment by Agarwalvidu** [comment]
This issue has already been resolved, for the same reason I am closing this issue. Thank you for collaborating!
