### ISSUE TITLE
Enhance CSS styling for Mutual Fund Investment Calculator in Tools Section

### ISSUE THREAD

**Issue by anagha-chaudhari** [ayush-that/FinVeda#18]
I wish to improve the CSS styling for the Mutual Fund Investment Calculator within the Tools section to enhance its visual appeal and user experience. Please assign me with this issue

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by anagha-chaudhari** [comment]
Hi @ayush-that, can you assign me this issue?

**Comment by SuhainaFathimaM** [comment]
@ayush-that Can you assign me this task??

**Comment by ayush-that** [comment]
Same as #89 
Closing this issue.
