### ISSUE TITLE
💡[Bug] - The website takes a lot of time to load

### ISSUE THREAD

**Issue by Priyanshu2743** [ayush-that/FinVeda#180]
### Problem:
The Website takes a lot of time to load that makes a user very uncomfortable and gave them a very bad experience
The Website just loads for 4-5 minutes until full loading which makes it very unfriendly.

### Solution: 
This Problem can be solved if the UI of the website can be code in a way that the content will be loaded first and the images will be going to load 
The UI of the website can also be improved so that it loads fast 
This makes the website very user-friendly 

### Benefits
The websites become user-friendly
A user doesn't have to wait for a long time for the website to open 

### Screenshots

https://github.com/ayush-that/FinVeda/assets/124867297/72fc100f-a879-4360-9dab-e010cb24eaa9

### I can do this if you assign me this under GSSOC2024 and kindly add labels of GSSOC2024 and levels

**Comment by ayush-that** [comment]
Assigning this to you.
Good luck.
