### ISSUE TITLE
Extra text in navbar of home page

### ISSUE THREAD

**Issue by anubhavvsharma** [ayush-that/FinVeda#1808]
### What happened?

![Screenshot (35)](https://github.com/user-attachments/assets/130e9c06-aa94-49a9-8158-1bd571a5719f)

### How can we reproduce this bug?

Assign me this @Sampadatiwari 

### Urgency (Optional)

None

**Comment by Sampadatiwari** [comment]
@anubhavvsharma there is no issue, check again the website.
