### ISSUE TITLE
[Feat]: Add Login with Google page for registration or login

### ISSUE THREAD

**Issue by pulkitgarg04** [ayush-that/FinVeda#182]
Hey @ayush-that, Your website can have a Login with Google page for user registration or login. I would like to add a Login with Google page to your website.
Can you assign me this issue under GSSoC'24 as a contributor?

**Comment by Rishitatripathi** [comment]
Hey @ayush-that
Can you assign me this issue under GSSoC'24 as a contributor

**Comment by ayush-that** [comment]
Same as #155 
Closing
