### ISSUE TITLE
Title: can add finance courses

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [ayush-that/FinVeda#1824]
### Is your feature request related to a problem? Please describe.

some users might find it difficult to go through long blogs so short courses are a better option

### Describe the solution you'd like.

can add courses of various basic finance knowledge to the beginners with no knowledge of finance.( like introduction to blockchain, crypto, basics about investments, banking related terms etc). we will add this in navbar section , which opens up to another web page

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by SanikaBhalerao1345** [comment]
hii @sampadatiwari30 thanks for assigning me.
can u pls add labels of gssoc-extd and level

**Comment by Sampadatiwari** [comment]
@SanikaBhalerao1345 I will add the label when you work is complete.

**Comment by SanikaBhalerao1345** [comment]
@Sampadatiwari i have raised a pr pls check it .
