### ISSUE TITLE
Ui enhancement of terms & conditions and privacy policy 

### ISSUE THREAD

**Issue by adityalaxkar123** [ayush-that/FinVeda#1839]
Ui of privacy policy and terms and conditions is only the text written format. We Enhance the user experience for the section 

Me a GSSOC'24 extended member can you assign it to me

**Comment by adityalaxkar123** [comment]
@deepeshmlgupta  I won't get the level in previous pr mergeing so my gssoc score is not count. At least give level 1 label then you change it by see the progress

**Comment by deepeshmlgupta** [comment]
By adding a level in the issue you will not get the points. You will only get the points when your PR is merged and have valid labels
