### ISSUE TITLE
[Bug Title here] Extra text below socil media link in footer

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ayush-that/FinVeda#1860]
### What happened?

In the contact us section, below the social media handle link, I see the text `feature/copyright` appearing. It is not suitable for this section in the footer.
![extra-text-belo-social](https://github.com/user-attachments/assets/8752b624-e446-4482-acd3-f6040d5eb832)

### How can we reproduce this bug?

Navigate to the footer in the 'Contact Us' section and examine the social media handle link below; you will notice the bug there.

### Urgency (Optional)

Medium priority

**Comment by Abhiiesante** [comment]
Can you please assign this issue to me under 𝗚𝗦𝗦𝗼𝗖 '𝟮𝟰 𝗘𝘅𝘁𝗲𝗻𝗱𝗲𝗱, Hacktoberfest-accepted
