### ISSUE TITLE
[Bug Title here] Overlap of icons

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ayush-that/FinVeda#1865]
### What happened?

in Tools page the scroll up icon and chat icon are overlap with each other 

![overlap-scroltotop](https://github.com/user-attachments/assets/0361f006-4bc0-47f1-a9d5-bed8e91934d6)

### How can we reproduce this bug?

go tp the tool page look at the bottom left 

### Urgency (Optional)

High priority

**Comment by salonijoshi1980** [comment]
hey, assign this to me
