### ISSUE TITLE
tools dropdown in navbar is always opened

### ISSUE THREAD

**Issue by kartik3110** [ayush-that/FinVeda#1871]
### What happened?

the different tools are displayed under the tools section of the navbar constantly, but they should only appear as a drop down under tools when a user clicks on them.
![image](https://github.com/user-attachments/assets/a66077d4-8d97-49a0-ab3d-f9958885f4e2)

### How can we reproduce this bug?

go the home page and look below the tools link of navbar.

**Comment by kartik3110** [comment]
please assign me this issue under hacktoberfest

**Comment by sampadatiwari30** [comment]
@kartik3110 completed.
