### ISSUE TITLE
[Alignment issue in about page] 

### ISSUE THREAD

**Issue by Pradyuman554** [ayush-that/FinVeda#1885]
### What happened?

Alignment issue in the footer of about page:

Before:
![Bug](https://github.com/user-attachments/assets/8ac9c742-5b07-48b6-bc3a-4218ab0a9d19)

After:
![Resolved](https://github.com/user-attachments/assets/845de63e-d061-471d-8901-d6a780fd4dff)

### How can we reproduce this bug?

Assign me this issue @Sampadatiwari @deepeshmlgupta

### Urgency (Optional)

None

**Comment by sampadatiwari30** [comment]
@Pradyuman554 already assigned to another contributor.
