### ISSUE TITLE
[Bug Title here] Alignment fix of footer items

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ayush-that/FinVeda#1887]
### What happened?

the alignment of footer items is not okay in tool page 

https://github.com/user-attachments/assets/42ca9153-eab9-46d3-87d5-2129ea3bf9dc

### How can we reproduce this bug?

go to tool page footer

### Urgency (Optional)

High priority

**Comment by Abhiiesante** [comment]
Can you please assign this issue to me under 𝗚𝗦𝗦𝗼𝗖 '𝟮𝟰 𝗘𝘅𝘁𝗲𝗻𝗱𝗲𝗱, Hacktoberfest-accepted
