### ISSUE TITLE
Adding Slider within the Blogs section

### ISSUE THREAD

**Issue by anagha-chaudhari** [ayush-that/FinVeda#19]
I would love to work on adding the sliders here for the blogs section. Please assign me with this under GSSOC'24

![pic](https://github.com/ayush-that/FinVeda/assets/143149376/8a5ef0c8-4eaa-4da0-bd51-e6b152fd9d6e)

**Comment by ayandip108** [comment]
Could you please assign the issue to me? I'm eager to contribute and help move it forward...

**Comment by ayush-that** [comment]
Assigning under gssoc
HF @anagha-chaudhari
