### ISSUE TITLE
 Add a Quick Scroll-Up Button for Enhanced User Experience.

### ISSUE THREAD

**Issue by smog-root** [ayush-that/FinVeda#1900]
I suggest implementing a quick scroll-up button on the platform to improve navigation, especially for pages with long content. This feature would be highly beneficial for users by allowing them to return to the top of the page with a single click, reducing the need for extensive scrolling.

<br>

**Benefits:**

**Improved User Experience:** Users can easily navigate to the top of the page, making browsing smoother and faster.

**Accessibility:** Particularly helpful for mobile users and those with limited scrolling capability.

**Enhanced Usability:** Makes revisiting top-page content, such as navigation bars or menus, more convenient.

**Aesthetics:** It adds a professional touch to the user interface, making the site feel more intuitive.

<br>

**Feature Details:**

- A small button (typically in the bottom-right corner) that appears after the user scrolls down a certain distance.
- On click, the page scrolls smoothly to the top.

**_Note_**: kindly add level2 (or) level3 for this issue and assign me! @sampadatiwari30 @Sampadatiwari @ayush-that

**Comment by smog-root** [comment]
@sampadatiwari30 add labels!!

**Comment by smog-root** [comment]
@Sampadatiwari @sampadatiwari30 

you have first assigned me to this issue. 

But some other guy raised a issue and not even got assigned. and he committed a PR. and you MERGED it!!! 

Then why you assigned me this issue!!

**issue:** id number is #2014

**My issue:** #1900

why you accepted his PR and merged it!! unmerge it!!

**Comment by smog-root** [comment]
You reverted! but there are still two scroll buttons!

**Comment by smog-root** [comment]
?? @Sampadatiwari @sampadatiwari30

**Comment by Sampadatiwari** [comment]
@you can solve the issue.
