### ISSUE TITLE
ENHANCE AND STRUCTURE THE CONTRIBUTORS SECTION

### ISSUE THREAD

**Issue by alo7lika** [ayush-that/FinVeda#1911]
### Issue Description

The README's current "Contributors" section lacks structure and visual appeal. Enhancing this section will provide better recognition to contributors and encourage more participation. The goal is to make it more engaging, visually appealing, and organized while highlighting the valuable efforts of everyone involved.

**_Expected Outcome_**

- [x] A well-structured and visually appealing "Contributors" section.
- [x] Properly display profile images, usernames, and contribution counts.
- [x] Ensure consistency in the layout and styling of contributor details.
- [x] The section should be more interactive, offering links to contributor profiles.better recognize

### Screenshots or Examples (if applicable)

N/A

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines.
- [X] I have read the Code Of Conduct.
- [X] The changes doesn't break the code

**Comment by alo7lika** [comment]
Assign me the task under GSSOC EXT 24 AND HACKTOBERFEST @ayush-that .

**Comment by alo7lika** [comment]
@sampadatiwari30 add labels here on the issue GSSOC EXT 24 AND HACKTOBERFEST

**Comment by Sampadatiwari** [comment]
@alo7lika I will add the label, when you task is complete.
