### ISSUE TITLE
 Contact Page Opening Differently from Home Page vs Other Pages

### ISSUE THREAD

**Issue by Priyanshi0112** [ayush-that/FinVeda#1914]
### What happened?

When accessed from the home page, the contact page appears differently compared to when it is accessed from other pages. Additionally, the navbar on the contact page differs when opened via the home page. This inconsistency in layout and navigation can confuse users and negatively impact the user experience. This issue needs to be resolved to ensure uniformity across all pages, including the navbar design.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

https://github.com/user-attachments/assets/5cae068a-2054-4653-ac9f-5ec45e764d8f

### How can we reproduce this bug?

NA

### Urgency (Optional)

High priority

**Comment by VanshGarg06** [comment]
Hi! I am eager to contribute to this issue. Please assign this issue to me under hacktoberfest and gssoc-ext with the necessary labels assigned to this issue also.
