### ISSUE TITLE
Career Page Navbar Layout Issue

### ISSUE THREAD

**Issue by ritiksingh-01** [ayush-that/FinVeda#1931]
### What happened?

The layout of the navbar on the Career page has become misaligned, causing elements to appear out of place. This disrupts the user interface and navigation experience. Fixing the navbar layout will restore the intended structure, improving the page's overall usability and visual consistency.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

![image](https://github.com/user-attachments/assets/484eb4ae-dc19-48a8-b4b8-5eb2eabd9359)

### How can we reproduce this bug?

NA

### Urgency (Optional)

Medium priority

**Comment by deepeshmlgupta** [comment]
it is solved
