### ISSUE TITLE
📝[DOCS] add hacktoberfest banner to the read me file

### ISSUE THREAD

**Issue by agarwalbhargavi** [ayush-that/FinVeda#1938]
### Issue Description

i would like to add hacktoberfest banner to the readme file.
@Sampadatiwari  kindly assign me this

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines.
- [X] I have read the Code Of Conduct.
- [X] The changes doesn't break the code

**Comment by agarwalbhargavi** [comment]
can you please add labels gssoc and hacktoberfest @Sampadatiwari

**Comment by Sampadatiwari** [comment]
@agarwalbhargavi I will add the label, when your task is complete.
