### ISSUE TITLE
[Bug Title here] issues on home page 

### ISSUE THREAD

**Issue by Pragati1466** [ayush-that/FinVeda#1939]
### What happened?

basically the nav bar is lost and finveda icon is getting duplicated two times 

### How can we reproduce this bug?

going on the home page
<img width="1792" alt="Screen Shot 2024-10-24 at 1 35 26 AM" src="https://github.com/user-attachments/assets/17b4549f-c84c-44cb-bc2f-e8570d5236bd">
@sampadatiwari30 @dee

### Urgency (Optional)

None

**Comment by Pragati1466** [comment]
@deepeshmlgupta and please add the relevant labels for gssoc'24 and hacktoberfest

**Comment by deepeshmlgupta** [comment]
this is solved
