### ISSUE TITLE
Adding animations to website elements to enrich user experience

### ISSUE THREAD

**Issue by Gresey** [ayush-that/FinVeda#195]
This proposed feature suggests implementing a fade-up animation effect for website elements upon opening to enhance user experience. The animation would gracefully transition elements into view, adding visual appeal and engagement to the website interface.

**Comment by newcodergit** [comment]
Please assign me this issue under Gssoc'24.

**Comment by Gresey** [comment]
@ayush-that  please assign the issue to me as i have opened it and would love to do it

**Comment by Agarwalvidu** [comment]
@Gresey Go ahead!

**Comment by Agarwalvidu** [comment]
Update?

**Comment by Gresey** [comment]
@Agarwalvidu  i am working on it till sunday i will be done
