### ISSUE TITLE
Implementing Multilingual Support

### ISSUE THREAD

**Issue by Anjankumarkamalapur** [ayush-that/FinVeda#196]
On exploring the FinVeda I noticed that it is only available in English. To make it easier for more people to use and understand, I propose developing the website to support multiple languages. This will allow users to choose their preferred language for a better and more accessible experience.
The below image represents that it is only available in English language only
![WhatsApp Image 2024-05-25 at 15 42 28_6ffaebcd](https://github.com/ayush-that/FinVeda/assets/139578011/9cca934a-cba7-4d43-a3cb-d49e01998d45)

**Comment by Agarwalvidu** [comment]
This website can not support multilingual feature. Thank you for raising this issue, looking for more from your side.
