### ISSUE TITLE
[style]: Fixing image

### ISSUE THREAD

**Issue by Pheonixrog** [ayush-that/FinVeda#1977]
### What's the style idea?

We need to improve the image position or we can remove that.

### Add screenshots

![image](https://github.com/user-attachments/assets/1a8a744e-e2e9-4749-bf43-9ebd79fe3511)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by deepeshmlgupta** [comment]
no need
