### ISSUE TITLE
LOGIN & REGISTER

### ISSUE THREAD

**Issue by Rajat-24227** [ayush-that/FinVeda#20]
I CAN CREAETE THE LOGIN AND REGISTER PAGE FOR THE WEBSITE

**Comment by salonii04** [comment]
Hello @ayush-that !
Please assign me this issue, I can make a LOGIN & REGISTER page for the website

**Comment by GAGGZ1** [comment]
Hello, Ayush Singh,

Your open-source project excites me, and I would love to help by improving the registration and login site. using my proficiency with front-end technology. I'm ready to make a meaningful impact. eager to work with you!

Regards, 

Gagan Chauhan

**Comment by sonarani1** [comment]
Hi, Please assign this issue to me.

**Comment by asinha828** [comment]
hello i would really want to work on this issue. can i please.

**Comment by debasmi** [comment]
i have done porjects under coursera kindly assign me thsis under gssoc 24

**Comment by richasriva** [comment]
Hi, I can fix this issue properly. kindly assign it to me.

**Comment by neharika2004** [comment]
hey, I would like to create login and registration page using bootstrap and also authenticate it and I'll keep in mind that it matches  with the ui. So please assign me with the issue.

**Comment by khushikunte** [comment]
Hi .I am khushi plz assign this issue to me .Under Gssoc'24

**Comment by kalyanikhushi** [comment]
![Screenshot 2024-05-14 110126](https://github.com/ayush-that/FinVeda/assets/159093860/5ed35995-6ed6-406c-b0bb-57407889eca9)

@ayush-that assign me this under gssoc'24 i will create login/register page and also add button to navigation bar just like login/register to look more formal

**Comment by ayush-that** [comment]
Assigning this issue to @drick-infinity
Implement it well.
Good Luck.

**Comment by Yuvraj960** [comment]
@ayush-that I can attach the mongoDB for login/register process validation. Please assign this issue to me under GSSoC24

**Comment by ayush-that** [comment]
@Yuvraj960 please check #155 
work on that, I'll give the PR a level3 rating if you implement it well.

**Comment by Yuvraj960** [comment]
@ayush-that #155 Is already assigned to someone else
