### ISSUE TITLE
[Feat]: Add hovering effect to Top Stories Cards on the Home page

### ISSUE THREAD

**Issue by Asymtode712** [ayush-that/FinVeda#201]
Hovering effect is missing for the Top Stories Cards on the Home Page, I would like to add these effects.

@ayush-that please assign me this issue

**Comment by Varsani2520** [comment]
Hey @ayush-that ,
can you assign this issue

**Comment by Asymtode712** [comment]
@Varsani2520 sorry but i have already authored this issue

**Comment by Varsani2520** [comment]
Hey @Asymtode712 ,i can do better than you

**Comment by Asymtode712** [comment]
@Varsani2520 Yaa thats good, but I have already created this issue by myself so you can work on some other issue

Thank you!

**Comment by Asymtode712** [comment]
@ayush-that Please assign me this issue

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.

**Comment by Soujanya2004** [comment]
hi, I have been following your project and would love to contribute, please assign me the issue.
