### ISSUE TITLE
[Bug Title here] Extra space fix in home page

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ayush-that/FinVeda#2011]
### What happened?

in your website in home page there is void space in the bottom of the Fotter , this make the home page not good at all 
![WhatsApp Image 2024-10-24 at 23 28 31_6e3b9773](https://github.com/user-attachments/assets/2b940459-ea90-4e7c-bfee-b3328b78d3d5)

### How can we reproduce this bug?

Go to home page footer look at the bottom

### Desktop Information (Optional)

Chrome

### Urgency (Optional)

Medium priority

**Comment by sampadatiwari30** [comment]
@biswajit-sarkar-007 resolved.
