### ISSUE TITLE
[Bug] : updation required in contact us ad blog page.

### ISSUE THREAD

**Issue by MimanshaKaur** [ayush-that/FinVeda#2017]
### this is the screenshot of CONTACT US page.👇
![Screenshot 2024-10-25 002146](https://github.com/user-attachments/assets/a995ef90-37f6-4bfe-a6c3-784f3015521e)
![Screenshot 2024-10-25 002649](https://github.com/user-attachments/assets/7878b696-8927-402b-8fb4-6fa214839ec3)

- as you can see that the alignment of contact us form is not correct in ContactUs.html file... the form is hiding behind the header ..its margin is not set properly.
- also, in the footer , the background is there that needs to be removed.

### this is the blog page's screenshot👇👇👇
![Screenshot 2024-10-25 002027](https://github.com/user-attachments/assets/653e4c7c-88af-408f-bc80-35ca3fa38819)\
here the image is not supported for one of the blog.. so i want to add a relavant image for it.

### How can we reproduce this bug?

these bugs can be resolved by : 
- in contact us page.. by updating the CSS for contact form and footer of this page.
- for blog page.. a relevant image will be added according to the blog which should be of smaller size in Kb so that page load time is also reduced.

@deepeshmlgupta  please assign me this task with gssoc-ext and hacktoberfest-accepted labels .
i am registered with hacktoberfest and registered gssoc-ext 2024 contributor.
i will be more than happy to work on this issue.😊

### Urgency (Optional)

High priority

**Comment by pameladeysarkar2003** [comment]
@ayush-that please assign me with this task i can solve the issue.

**Comment by MimanshaKaur** [comment]
@deepeshmlgupta thank you for assigning this task to me ....

please also add "hacktoberfest-accepted " and level labels as well

**Comment by deepeshmlgupta** [comment]
Will be added when you raise the PR
