### ISSUE TITLE
[style]: changes required in ABOUT US and TOOLS pages.

### ISSUE THREAD

**Issue by MimanshaKaur** [ayush-that/FinVeda#2020]
### What's the style idea?

We need to improve  :

- here adding the images with no white background ,i.e., if background of these  images are removed and then these same images are added on these cards it will give more enhanced and eye catching look. Also, changing the font color of "financial kit","stock market" and " our team" to black will  increase the viewer's focus and readibility experience ..also it will give these 3 options a little stand-out look from rest of the text.👇👇
![Screenshot 2024-10-25 001628](https://github.com/user-attachments/assets/07304592-1221-4f54-aee2-7696b0461743)

- here, the spacing of left on the internal card or white-container is not proper..so this needs to be adjusted.
![Screenshot 2024-10-25 001936](https://github.com/user-attachments/assets/972f5d8a-7132-4803-9c5d-e3f134ffbf30)

- here ,in these 2 and also in many other such forms on the main website the alignment f "calculate" in calculate button is not correct...this should be in the center properly.
![Screenshot 2024-10-25 001837](https://github.com/user-attachments/assets/9ccfa7b1-7003-4fc1-85c2-c4872156cdce)
![Screenshot 2024-10-25 001827](https://github.com/user-attachments/assets/94bf70ef-7150-4404-9444-adcf03838cdf)

i am interested in working on this issue...
@deepeshmlgupta please assign me this task with gssoc-ext and hactoberfest-accepted and other required labels.
Thank you so much.😊

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by pameladeysarkar2003** [comment]
@ayush-that please assign me with this issue i can solve this

**Comment by MimanshaKaur** [comment]
@deepeshmlgupta thank you for assigning me this task...please also add hacktoberfest-accepted and level labels too.

**Comment by deepeshmlgupta** [comment]
Those levels will be added in your PR
