### ISSUE TITLE
[style]: Login/register button is misplaced/misaligned

### ISSUE THREAD

**Issue by iamsaura8h** [ayush-that/FinVeda#2022]
### What's the style idea?

the issue #1849 doesn't seem to resolve the problem as it is still there as you can see in the screenshot below : 
<img width="427" alt="{71A4CDDA-E162-4B03-A348-EA8E17B547F7}" src="https://github.com/user-attachments/assets/42904cef-e15a-46e3-8e06-bf6efccb6872">

please allow me to resolve this issue here and assign me this issue !

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by iamsaura8h** [comment]
@ayush-that please assign me this issue !

**Comment by sampadatiwari30** [comment]
@iamsaura8h resolved.
