### ISSUE TITLE
[style]: increase the width of tools 

### ISSUE THREAD

**Issue by verma2402** [ayush-that/FinVeda#2031]
### What's the style idea?

We need to improve  the width of the tools to make it look compatible with website's theme. 

### Add screenshots

![image](https://github.com/user-attachments/assets/76c0174e-8a8f-4475-abda-b68975fbf3c5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by verma2402** [comment]
Please assign this issue to me under the gssoc-ext and hactoberfest

**Comment by verma2402** [comment]
Hey @sampadatiwari30 , please add the labels gssoc-ext and hactoberfest-accepted too

**Comment by verma2402** [comment]
Hey @ayush-that please add the labels gssoc-ext and hactoberfest-accepted

**Comment by Sampadatiwari** [comment]
@verma2402 I will add the labels when your task is complete.
