### ISSUE TITLE
[style]: Changing the navbar

### ISSUE THREAD

**Issue by Bhoomysingh10** [ayush-that/FinVeda#2033]
### What's the style idea?

Improve the navbar by enhancing icon consistency, optimizing font size for readability, adding hover effects for better user interaction, and ensuring balanced spacing. Replace informal emojis with professional icons, refine button sizes, and ensure a responsive design for seamless use across devices.

### Add screenshots

![image](https://github.com/user-attachments/assets/088bffa5-846c-4a31-80c9-d176c61b26c0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Bhoomysingh10** [comment]
@ayush-that Pls check !

**Comment by sampadatiwari30** [comment]
@Bhoomysingh10 in which page ?

**Comment by Bhoomysingh10** [comment]
@sampadatiwari30 (for every page)
 The black color of the navbar doesn’t seem to complement the background on each page. I would like to adjust the navbar color to match each page's background and remove the icons for a cleaner appearance.
