### ISSUE TITLE
[style]: Improve FAQ Progress Section ✨

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ayush-that/FinVeda#2038]
### What's the style idea?

The green progress bar line in the FAQ progress section is too thin and does not look visually appealing. The overall design of the section could be enhanced for better aesthetics.

### Add screenshots

![image](https://github.com/user-attachments/assets/9539b838-bc6f-4d80-b960-1316b9bb618a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by sampadatiwari30** [comment]
@AnushkaChouhan25 resolved.
