### ISSUE TITLE
[Bug Title here] Home page susceibe to news letter ssectioon fix

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ayush-that/FinVeda#2042]
### What happened?

On your homepage, the subscribe button and placeholder are overlapping with each other, which makes the website look unprofessional. I would like to fix this error.

![WhatsApp Image 2024-10-25 at 20 48 01_7c5617a2](https://github.com/user-attachments/assets/b10032e1-84ce-4ded-898a-8eb115c839f6)

### How can we reproduce this bug?

go to home suscribe to news letter section

### Urgency (Optional)

High priority

**Comment by sampadatiwari30** [comment]
@biswajit-sarkar-007 resolved.
