### ISSUE TITLE
[Bug Title here] Contact us section in every page is not properly aligned and not responsive

### ISSUE THREAD

**Issue by srivishnu2805** [ayush-that/FinVeda#2045]
### What happened?

The Contact Us section is not properly aligned and not responsive on every page so it needs to be fixed by giving proper alignments, responsive CSS, and some designs to look good.

### How can we reproduce this bug?

We can make the Contact Us section responsive and give proper alignments on every page so this section will be good 
![image](https://github.com/user-attachments/assets/ae67f4a8-b6f5-4218-b6b6-082b2dc9b9a9)
![image](https://github.com/user-attachments/assets/9117a687-f958-4f90-a167-8f49ca612e93)

### Desktop Information (Optional)

Windows Google chrome

### Urgency (Optional)

Medium

**Comment by deepeshmlgupta** [comment]
on which page
