### ISSUE TITLE
Favicon 

### ISSUE THREAD

**Issue by deepeshmlgupta** [ayush-that/FinVeda#2046]
### What happened?

adding a Favicon on all pages of the website. This is the issue which is assigned on first come first serve basis. 
You can comment on this issue and get it assigned

@everyone

### How can we reproduce this bug?

adding a Favicon on all pages of the website. This is the issue which is assigned on first come first serve basis. 
You can comment on this issue and get it assigned

@everyone

### Desktop Information (Optional)

![Screenshot 2024-10-25 214746](https://github.com/user-attachments/assets/03e0368d-4827-4d98-8e91-a62d785b29be)

### Urgency (Optional)

High priority

**Comment by milansamuel609** [comment]
Can you assign me this issue ?

**Comment by deepeshmlgupta** [comment]
@milansamuel609 work on it and make sure to add the fav icon on all of the pages

**Comment by milansamuel609** [comment]
> @milansamuel609 work on it and make sure to add the fav icon on all of the pages

Actually the FinVeda icon is on all pages like its was already there so I have to change it to the default like normal one or please can you specify?

**Comment by deepeshmlgupta** [comment]
@milansamuel609 , 
Actually on some of the pages like AboutUs, Tools, Blogs and some more pages you can also figure out where the favicon is missing so apply on that pages. 
Apply the same favicon that is present on the rest of the pages

**Comment by deepeshmlgupta** [comment]
@milansamuel609 do this changes by today as there are other contributor also who are raising the same issue
So, do it by today else I will assign this to someone else

**Comment by rajdeepchakraborty-rc** [comment]
@deepeshmlgupta I was also going to open the same issue. Can I be assigned if the contributor is unable to do it?

**Comment by deepeshmlgupta** [comment]
> @deepeshmlgupta I was also going to open the same issue. Can I be assigned if the contributor is unable to do it? Since we are instructed not to open another similar issue so I did not open it and am asking in this issue itself.

wait till tomorrow @rajdeepchakraborty-rc  if @milansamuel609 doesn't make the PR till today then I will assign this to you.

**Comment by milansamuel609** [comment]
@deepeshmlgupta  Thank you so much for giving me this opportunity I have fixed the issue and also the PR is merged. Please  kindly close this issue.

**Comment by rajdeepchakraborty-rc** [comment]
@milansamuel609 Congrats! Great job on resolving the issue!

**Comment by milansamuel609** [comment]
> @milansamuel609 Congrats! Great job on resolving the issue!

Thank you @rajdeepchakraborty-rc 😊
