### ISSUE TITLE
Chat and up arrow button are not aligned

### ISSUE THREAD

**Issue by ayush-848** [ayush-that/FinVeda#206]
![image](https://github.com/ayush-that/FinVeda/assets/126975547/18dfc424-2851-4552-b490-0a5d128d13c1)

**Comment by ayush-848** [comment]
@ayush-that please assign this issue to me under GSSoC'24

**Comment by ayush-848** [comment]
@ayush-that where is the button class and class located?

**Comment by PriyanshSrivastava0305** [comment]
hi @ayush-that, pls let me get this sorted quick
