### ISSUE TITLE
[style]: Contact page style 

### ISSUE THREAD

**Issue by pbln** [ayush-that/FinVeda#2083]
### What's the style idea?

Actually I feel that in the light mode contact us should be lighter instead of this dark color that is in the screenshot , 
Also some basic UI fixes like the font family is different in this section which also needs improvement . 

### Add screenshots

![image](https://github.com/user-attachments/assets/2995102b-3b0a-4fa2-a3e9-18fd7dccdea5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by pbln** [comment]
I want to work on the issue for hacktoberfest and gssoc-extd .

**Comment by sampadatiwari30** [comment]
@pbln I will add the label when your work is complete.

**Comment by pbln** [comment]
can you just help me and tell why these pages are not behaving properly in my local forked repo?
![image](https://github.com/user-attachments/assets/2c738b55-f6bc-419a-88c2-a9fbe44aea17)

**Comment by pbln** [comment]
also something like this 
![image](https://github.com/user-attachments/assets/9c3ee866-6be7-447a-bc28-9dfd90126aa0)
