### ISSUE TITLE
[Bug]: Background Color Not Changing on Dark Theme (Trends Page) 🔴

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ayush-that/FinVeda#2088]
### What happened?

The background color on the Trends page does not update correctly when switching to dark theme. Ensure the background adapts to the selected theme to maintain visual consistency across the site.

![image](https://github.com/user-attachments/assets/7d918098-49a7-4bb1-a88d-7149d4011a36)

### How can we reproduce this bug?

1. Navigate to the Trends page.
2. Enable the dark theme using the theme toggle button.
3. Observe the background color of the page.

### Urgency (Optional)

High priority

**Comment by sampadatiwari30** [comment]
@AnushkaChouhan25 i will add the label when you task is complete.
