### ISSUE TITLE
[Feature] Adding EMI Calculator to tools page

### ISSUE THREAD

**Issue by roysammy123** [ayush-that/FinVeda#21]
# Feature: Adding EMI Calculator to tools page

**Issue Description:**
FinVeda website lacks an EMI Calculator feature, essential for users' financial planning.

**Feature Details:**
- Users input loan amount, interest rate, and tenure.
- Accurate calculation algorithm computes EMI.

**Conclusion:**
Adding an EMI Calculator aligns with FinVeda's commitment to comprehensive financial tools.

@ayush-that I would be really thankful if you kindly assign me this issue as I would like to work on it as part of GSSoC'24. Thank you for considering.

**Comment by ChandelAnish** [comment]
Hello @roysammy123 ,

I've noticed the request to add an EMI (Equated Monthly Installment) Calculator to the tools page, a valuable addition that can provide users with financial planning assistance. Given my experience in developing calculators in previous projects, I'm well-equipped to tackle this task effectively.

To address this issue, I propose creating a user-friendly EMI Calculator that allows users to input loan amount, interest rate, and tenure to calculate their monthly installment. Leveraging my expertise in HTML, CSS, React, and JavaScript, I'll design and implement an intuitive interface that guides users through the calculation process seamlessly.

Additionally, I'll ensure that the EMI Calculator is responsive and accessible across various devices, optimizing the user experience for both desktop and mobile users.

Furthermore, I'll incorporate validation checks to ensure that users input valid data and provide clear error messages in case of any discrepancies.

I'm excited about the opportunity to contribute the EMI Calculator to the tools page and provide users with a valuable financial planning tool. I look forward to collaborating with the team to deliver a polished and functional feature.

Best regards,
Anish Singh Chandel

**Comment by roysammy123** [comment]
hi @ChandelAnish, I am a contributor, not a mentor :)

**Comment by ayush-that** [comment]
Hi @roysammy123 and @ChandelAnish,
I am assigning this to you under gssoc. Start working on it. All the best. Please adhere to the styling of FinVeda.

**Comment by roysammy123** [comment]
Thanks @ayush-that for assigning it to me!

**Comment by roysammy123** [comment]
Hi, I have done the work and raised a PR. Please check it @ayush-that

**Comment by roysammy123** [comment]
i am closing this issue as the PR has been merged already
