### ISSUE TITLE
[Bug Title here] Extra text fix

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ayush-that/FinVeda#2100]
### What happened?

extra text appear in tools page
![WhatsApp Image 2024-10-26 at 18 43 50_69e7d13a](https://github.com/user-attachments/assets/47e6f6be-60e2-4ba6-99dc-969cab773192)

### How can we reproduce this bug?

go to the tool page look at the bottom of the footer you will see some extra text will be appear 

### Urgency (Optional)

High priority

**Comment by sampadatiwari30** [comment]
@biswajit-sarkar-007 resolved.
