### ISSUE TITLE
No placeholder for name in feedback form !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [ayush-that/FinVeda#2105]
![image](https://github.com/user-attachments/assets/34fe1a29-eb3e-493a-975e-ccec188c2761)

**Comment by SrijaVuppala295** [comment]
@ayush-that , please assign me under this issue !!

**Comment by sampadatiwari30** [comment]
@SrijaVuppala295 share the issue.

**Comment by sampadatiwari30** [comment]
@SrijaVuppala295 I will add the label when your work is complete.
