### ISSUE TITLE
[Bug Title here] Placeholder overlapping fix

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ayush-that/FinVeda#2107]
### What happened?

in tool page Income tax calculatorthis section the placeholder get outside the box i want to fix this.
![WhatsApp Image 2024-10-26 at 19 19 40_ea8bc263](https://github.com/user-attachments/assets/6e6cefe3-0969-4407-b587-cdb2eea9f006)

### How can we reproduce this bug?

go to tool page and look at the Income tax calculator section you will see the placeholder is overlapping 

### Urgency (Optional)

Medium priority

**Comment by sampadatiwari30** [comment]
@biswajit-sarkar-007 I will add the label when your work is complete.
