### ISSUE TITLE
Misalignment of Chat and Up Arrow Button in Responsive Mode

### ISSUE THREAD

**Issue by TARUN2K3** [ayush-that/FinVeda#211]
The chat box and the up-arrow button should be horizontally and vertically aligned, ensuring a consistent and visually appealing layout across all screen sizes. We will make sure that no horizontal scrolling is required to view the content.

![image](https://github.com/ayush-that/FinVeda/assets/127468524/d4fca5bc-aa23-4df1-9ec4-9d2e30bee89a)

**Comment by ayush-that** [comment]
Same as #206
