### ISSUE TITLE
The social media links are not redirected to the socialmedia pages !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [ayush-that/FinVeda#2110]
![image](https://github.com/user-attachments/assets/9b47f684-55ab-4183-a5db-f828449c4c4c)

**Comment by SrijaVuppala295** [comment]
@ayush-that , please assign me under this issue!!

**Comment by sampadatiwari30** [comment]
@SrijaVuppala295 I will add the label when your task is complete.
