### ISSUE TITLE
DOCUMENTATION ISSUE: ENHANCEMENT OF ABOUT

### ISSUE THREAD

**Issue by shruti110503** [ayush-that/FinVeda#213]
The Readme file's ABOUT section needs to be enhanced. It gives very less information about the app and very less explanation. It should be explained in detailed.
![Screenshot 2024-05-29 202213](https://github.com/ayush-that/FinVeda/assets/118251562/96042afc-88d6-40c5-b408-612150f1f385)

**Comment by shruti110503** [comment]
Please assign me this issue. I am a Gssoc'24 contributor.

**Comment by ayush-that** [comment]
Hi @shruti110503,
Assigning this to you under gssoc.
Write it well.
