### ISSUE TITLE
Title: add password visibility toggle in login and signup form fields

### ISSUE THREAD

**Issue by kartik3110** [ayush-that/FinVeda#2131]
### Is your feature request related to a problem? Please describe.

User should be able to view the password he is typing for improving the experience of the website.

### Describe the solution you'd like.

Add an icon (button) in the password field in the signup/login form which toggles the visibility of the password that the user is typing.

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/a91a4c34-277e-4fbb-a226-f2dd57c548aa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by kartik3110** [comment]
Please assign me this under hacktoberfest, i'll PR by today.

**Comment by sampadatiwari30** [comment]
@kartik3110 already assigned.
