### ISSUE TITLE
Missing Placeholder Text for Name Field in Feedback Form

### ISSUE THREAD

**Issue by sanchitc05** [ayush-that/FinVeda#2137]
### What happened?

- In the feedback form, every field has a placeholder text except for the name field, resulting in an inconsistent user experience.
- I expected all fields in the feedback form, including the name field, to have placeholder text to guide users on what information to enter.

### How can we reproduce this bug?

- Navigate to the feedback form on the website.
- Observe the fields displayed in the form.
- Note that the name field is missing its placeholder text while other fields are not.

### Desktop Information (Optional)

![image](https://github.com/user-attachments/assets/4fe02974-522a-40cb-9fea-9f683a2343f7)

I would like to work on adding the placeholder text for the name field to ensure consistency across the feedback form.
### Urgency (Optional)

High priority

**Comment by sampadatiwari30** [comment]
@sanchitc05 already assigned.
