### ISSUE TITLE
[Bug] Social Media Headings Not Visible on Contact Page

### ISSUE THREAD

**Issue by PrityanshuSingh** [ayush-that/FinVeda#2143]
### What happened?

The headings for email, LinkedIn, and other social media links on the contact page are not visible because they are displayed in white text, blending in with the background. The social media headings to be clearly visible without needing to hover over them, allowing users to easily identify and access these links.

### Screenshot
![image](https://github.com/user-attachments/assets/70e6911a-2cbf-4b21-9ff9-611d5b830e46)

### How can we reproduce this bug?

1. Navigate to the Contact page of the website.
2. Look for the email, LinkedIn, and other social media headings.
3. Observe their visibility without hovering.

### Urgency (Optional)

Medium priority

@ayush-that please assign me this issue under gssoc-ext level2 and hacktoberfest-accepted.

**Comment by sampadatiwari30** [comment]
@PrityanshuSingh already assigned.
