### ISSUE TITLE
[Bug] Inconsistent UI of Our Contributers Image in About Us

### ISSUE THREAD

**Issue by PrityanshuSingh** [ayush-that/FinVeda#2144]
### What happened?

The image of the our contirbuters section in about us page does not maintain a consistent size or alignment across our contributers heading, leading to a disjointed user experience.

### Screenshot
![image](https://github.com/user-attachments/assets/bb3207bc-1ac1-4605-bac0-d57d81a1ded5)

### How can we reproduce this bug?

1. Navigate to the About us page of the website.
2. Observe the misaligned image in the our contributers section.

### Urgency (Optional)

Medium priority

@ayush-that please assign me this issue under gssoc-ext level2 and hacktoberfest-accepted.

**Comment by sampadatiwari30** [comment]
@PrityanshuSingh I will add the label when your task is complete.
