### ISSUE TITLE
Title: Apply Consistent UI Enhancements to Terms of Service and Licensing Pages

### ISSUE THREAD

**Issue by neeru24** [ayush-that/FinVeda#2168]
### Is your feature request related to a problem? Please describe.

Following the recent updates to the Privacy Policy and Refund pages, I would like to apply similar UI improvements to the Terms of Service and Licensing pages to ensure a consistent and user-friendly experience across all policy-related pages. The current dense layout on these pages makes the information difficult to navigate, and enhancing the layout will improve readability and user engagement.

### Describe the solution you'd like.

- **Consistent Layout Design:** Implement a structured layout using card designs or collapsible sections (accordion) similar to the updated Privacy Policy and Refund pages.
- **Improved Readability:** Break up text into easily digestible sections, making it more approachable for users.
- **Clear Visual Hierarchy:** Enhance headers, subheaders, and spacing to provide a clear hierarchy and separation of information.

### Expected Outcome
A cohesive and visually consistent layout for the Terms of Service and Licensing pages, aligned with the recently updated policy pages, making it easier for users to navigate and understand the content.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/7468715b-c4f3-4a2a-a023-9cbe378181f1)
![image](https://github.com/user-attachments/assets/e94dd426-ecd5-4d37-9010-f0e9fc6c553d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by neeru24** [comment]
I'm creating only one issue for these 2 pages, so kindly assign me level 2 or 3.

**Comment by sampadatiwari30** [comment]
@neeru24 I will add he label when your task is complete.
