### ISSUE TITLE
Favicon not displaying on specific pages of the website

### ISSUE THREAD

**Issue by Raj-banerjee25** [ayush-that/FinVeda#2181]
### What happened?

The favicon appears correctly on other parts of the site but does not show up on these specific pages. This may affect the user experience, as the favicon helps with brand recognition and quick identification of open tabs.
1.About Us Page
![fin1](https://github.com/user-attachments/assets/fa468e5d-1242-4ea4-bef4-48d22eaae06f)
2. Tools
![fin2](https://github.com/user-attachments/assets/f2d665fc-d7f9-4531-8ee1-ce7c1e052f8e)
3.Blogs
![fin3](https://github.com/user-attachments/assets/7020f82c-6766-4594-9b79-14dfa1f0071a)
4. Career
![fin4](https://github.com/user-attachments/assets/0dc5a9f7-c873-4895-8960-2a8ea001cd27)
5. Contact
![fin5](https://github.com/user-attachments/assets/11cfc4ad-4e1b-46ac-a44d-5429809ba844)
6.  FAQ
![fin6](https://github.com/user-attachments/assets/d9b9641b-17dd-44c0-8237-499b981e0f63)
 
Please assign me this issue.

### How can we reproduce this bug?

Go to the specific pages.
Look at the browser tab where the favicon should appear.
Notice that the favicon is missing.
Expected Behavior : The favicon should be visible on all pages across the website, providing a consistent user experience

### Desktop Information (Optional)

OS : Windows 11
Browser : Chrome

### Urgency (Optional)

None

**Comment by deepeshmlgupta** [comment]
Already assigned to someone else
