### ISSUE TITLE
Add customised scrollbar

### ISSUE THREAD

**Issue by Sneha123-zudo** [ayush-that/FinVeda#22]
I want to add customised scrollbar to the website , please assign me this issue under GSSOC'24.

**Comment by GAGGZ1** [comment]
Hi @ayush-that 

I propose adding a customized scrollbar to enhance user experience. With my front-end skills, I can seamlessly integrate this feature. Let's elevate your project together!

Best,
GAGAN CHAUHAN

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by Sneha123-zudo** [comment]
I want add this feature as an enhancement of the website . As , I opened this issue , please assign me this issue under GSSOC'24.

**Comment by ayush-that** [comment]
Hi @Sneha123-zudo 
I am assigning this issue to you under gssoc.
Implement it well!

@Rish-tech1, @GAGGZ1 - please check other issues.

**Comment by Rish-tech1** [comment]
👍
