### ISSUE TITLE
Social Media, Quick Links & Resources logos missing in footer of subpages

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [ayush-that/FinVeda#2204]
### What happened?

The social media logos are present in the home page:
![image](https://github.com/user-attachments/assets/239105d5-b223-4ba1-b0e8-18b06a461445)
In many of the webpages the logos are missing:
![image](https://github.com/user-attachments/assets/8f1a6731-55f0-4d85-9b51-118c92d36944)
also in a few subpages there are different UI for logos:
![image](https://github.com/user-attachments/assets/190f9a97-0b06-4c71-a52d-a7b4f2108472)

For the different logos, let me know if I should change it to the same as home page or should I work on it entirely by self.
I would like to add logos and add hover animation:

- slight zoom
- color change to the respective logo color

Some pages do not have icons before the options on the **Quick Links** and **Resources**. Since I am working on the Footer. I will update the logos on all the pages for the options in **Quick Links** and **Resources**.

Lastly, I will also add Redirects to the social media icons:
For example,
Twitter logo redirects to twitter website
GitHub redirects to this repository

### How can we reproduce this bug?

This is easily visible if you navigate through the footer section of the website(subpages)

### Urgency (Optional)

High priority

**Comment by rajdeepchakraborty-rc** [comment]
@sampadatiwari30 Thanks for assigning the issue. I am working on an issue currently and will start working on this one after finishing the current one.
Also could you please assign the labels to the issue.

**Comment by rajdeepchakraborty-rc** [comment]
Please spare me some time to finish my pending issues. I will try to open a PR by today or at most by tomorrow for sure.

**Comment by sampadatiwari30** [comment]
@rajdeepchakraborty-rc sure.

**Comment by rajdeepchakraborty-rc** [comment]
@sampadatiwari30 I have started working on the issue. I want to ask something: 
If you notice the pictures above in the description, some pages do not have icons before the options on the **Quick Links** and **Resources**. Since I am working on the Footer, do you want me to work on that too? I will update the logos on all the pages for the options in **Quick Links** and **Resources**.

**Comment by Sampadatiwari** [comment]
@rajdeepchakraborty-rc you can work in it.

**Comment by rajdeepchakraborty-rc** [comment]
@Sampadatiwari Also please let me know if I should add redirects to the social icons:
For example,
Twitter logo redirects to twitter website
GitHub redirects to this repository

**Comment by Sampadatiwari** [comment]
@rajdeepchakraborty-rc yes you can add.

**Comment by rajdeepchakraborty-rc** [comment]
@Sampadatiwari, I would like to share something with you. I am working on the pages and noticed a lot of small problems in the footers of different pages. I am resolving them one by one to make the footer look similar on all pages.
Try to ask the contributors to follow the format of other pages and review the code after they have changed it. Some footers have text aligned center whereas the home page footer contents are aligned left. Also, the logo is missing on the footer on some pages. I am trying to resolve any issues I find in the footer section.

**Comment by rajdeepchakraborty-rc** [comment]
I am following the Home page and applying changes to the other pages:

![image](https://github.com/user-attachments/assets/1e7ba6b5-37fa-4236-8bee-bf31a2d668b8)

Screenshots of all the pages once I am done working. I will not provide any video as there are no animation changes that I am making.

**Comment by sampadatiwari30** [comment]
@rajdeepchakraborty-rc remove the logo from all the Footer sections, it's not looking too good. I will add a contributor with you so that your work gets divided and there will be no burden on you and you can share your work with him.

**Comment by rajdeepchakraborty-rc** [comment]
@Sampadatiwari It's not a burden at all! I love contributing and we don't feel a burden in doing what we love to do

**Comment by sampadatiwari30** [comment]
@rajdeepchakraborty-rc  do you need another contributor to help you or not?

**Comment by rajdeepchakraborty-rc** [comment]
@Sampadatiwari Also about removing the logo from the footer, do you want it like this?
![image](https://github.com/user-attachments/assets/c5ca43ac-bc78-40ac-a060-64ff7c4a6d78)

I feel the logo was looking better and removing it is making it look misaligned and less atrractive.

**Comment by rajdeepchakraborty-rc** [comment]
> @Sampadatiwari Also about removing the logo from the footer, do you want it like this?
> 
> * Before
>   ![image](https://private-user-images.githubusercontent.com/68934988/380614445-6c96e3b6-8351-45e9-bb0e-8dd7b24402d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDA5NTMsIm5iZiI6MTczMDEwMDY1MywicGF0aCI6Ii82ODkzNDk4OC8zODA2MTQ0NDUtNmM5NmUzYjYtODM1MS00NWU5LWJiMGUtOGRkN2IyNDQwMmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA3MzA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NWZkMTNhOTg3ZjViNTNmZTk0ZTc4ZTE2ZTY1N2VkNTExZTgyZWU0YzBiMTM2OWRjY2U1ZWVkNTNkMTFmMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RLX6oquRgtnzLvSIG728J1YomQnkIYF7T8LuTdftKvo)
> * After
>   ![image](https://private-user-images.githubusercontent.com/68934988/380612157-c5ca43ac-bc78-40ac-a060-64ff7c4a6d78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDA5NTMsIm5iZiI6MTczMDEwMDY1MywicGF0aCI6Ii82ODkzNDk4OC8zODA2MTIxNTctYzVjYTQzYWMtYmM3OC00MGFjLWEwNjAtNjRmZjdjNGE2ZDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA3MzA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NjdiYWViZTA4MzU2ODQ0NWRkZTViMWJlZmYwMDQ1YTUwZTBlZGNhZTE3MDA5ZDgwZThlOWMzNWZjYmQ2OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eo7GkSnh0EGfL_grlPQ_5eLp4gqRJ9raM_B4vT3D1wM)
> 
> I feel the logo was looking better and removing it is making it look misaligned and less atrractive. Let me know your thoughts on this

@Sampadatiwari Let me know your final thoughts on this

**Comment by sampadatiwari30** [comment]
@rajdeepchakraborty-rc leave the logo on.

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc leave the logo on.

Ok, I am going with this as final.
![image](https://github.com/user-attachments/assets/6c96e3b6-8351-45e9-bb0e-8dd7b24402d3)

You can always revamp the site and change the footer according, maybe introduce a new website logo or somthing.

**Comment by Sampadatiwari** [comment]
@rajdeepchakraborty-rc ok

**Comment by rajdeepchakraborty-rc** [comment]
@Sampadatiwari It seems you have changed the footer logo recently. It has caused conflicts in my code. I will resolved and add the new footer logo and open a PR soon

**Comment by rajdeepchakraborty-rc** [comment]
Also the logo is not present in the navbar of some of the pages:
![image](https://github.com/user-attachments/assets/74e9f6a2-06aa-48c5-8cef-22771f9a663a)

Do you want me to add it there too or only update the logo in the footer section?

**Comment by rajdeepchakraborty-rc** [comment]
@Sampadatiwari I have resolved the merge conflicts and opened a PR.
