### ISSUE TITLE
[Bug Title here] Blogs section image fix

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ayush-that/FinVeda#2206]
### What happened?

in your website i have seen that in the home page the blog section  `Mutual Funds 101: A Beginner's Guide to Smart Investing` this blogs images does not showing i want to fix this
![WhatsApp Image 2024-10-27 at 16 32 31_07fcc0bb](https://github.com/user-attachments/assets/392f85cb-d0a6-4e26-a33a-73fad249216d)

### How can we reproduce this bug?

go to home page look at the blog section

### Urgency (Optional)

High priority

**Comment by sampadatiwari30** [comment]
@biswajit-sarkar-007 resolved.
