### ISSUE TITLE
Misaligned newsletter section in mobile devices in all pages

### ISSUE THREAD

**Issue by swathivemula7** [ayush-that/FinVeda#2210]
The newsletter section is not aligned properly in all pages of website in MOBILE VERSION. I would like to fix that...

![Capturebhbh](https://github.com/user-attachments/assets/9297409a-6760-4fb7-83b2-4477a345f7d7)

@ayush-that Kindly assign me this issue with hacktoberfest and gssoc labels

**Comment by sampadatiwari30** [comment]
@swathivemula7 only the size issue in tool page, you can solve.

**Comment by swathivemula7** [comment]
> @swathivemula7 only the size issue in tool page, you can solve.

@sampadatiwari30 in the mobile version or desktop version?please mention

**Comment by sampadatiwari30** [comment]
@swathivemula7 desktop version

**Comment by swathivemula7** [comment]
> @swathivemula7 desktop version

Ok @sampadatiwari30  kindly assign me
