### ISSUE TITLE
[Bug Title here] Navbar text not visible 

### ISSUE THREAD

**Issue by Gauravtb2253** [ayush-that/FinVeda#2211]
### What happened?

The login button text is not properly visible 

### How can we reproduce this bug?

Check the navbar and rightmost button
![image](https://github.com/user-attachments/assets/c8d27577-b04c-4bd6-bcf5-f36c3f064a36)

### Urgency (Optional)

High priority

**Comment by sampadatiwari30** [comment]
@Gauravtb2253 resolved.
