### ISSUE TITLE
Misaligned "share experience" button in mobile version

### ISSUE THREAD

**Issue by swathivemula7** [ayush-that/FinVeda#2214]
The "share experience" button in home page is misaligned in mobile version...I would like to fix this..

![IMG_20241027_181048](https://github.com/user-attachments/assets/63f72c46-c8be-4065-bcb5-1c06401ad774)

@ayush-that Kindly assign me this issue under hacktoberfest and gssoc..

**Comment by sampadatiwari30** [comment]
@swathivemula7  resolved.
