### ISSUE TITLE
[FEAT] Implement 'FAQ' Page in Footer Section

### ISSUE THREAD

**Issue by yashmandi** [ayush-that/FinVeda#224]
This website needs the FAQ Page as it is related to Finance, where some questions and answers that  a user might think should be answered in this page. 
I would like to work on this task under GSSoC '24. Request you to assign this task to me.

**Comment by snehasahu7** [comment]
An FAQ page can help users navigate this website and can improve user experience.
I would like to work on this issue and request you to kindly assign me this task under GSSoC'24.
