### ISSUE TITLE
[style]: Simplify Contact Page Design for Better User Experience

### ISSUE THREAD

**Issue by ritiksingh-01** [ayush-that/FinVeda#2246]
### What's the style idea?

We need to improve  the current Contact page design includes a gradient background, which can distract from the primary purpose of the page and reduce readability. Simplifying the background to a solid, neutral color will provide a more user-friendly experience, allowing visitors to focus on the contact form and essential information without visual interference. This adjustment aims to enhance clarity and accessibility for users on all devices.

### Add screenshots

![image](https://github.com/user-attachments/assets/800310ad-9129-4fdc-bfb2-5302ba0a3526)

Sample : 
![image](https://github.com/user-attachments/assets/b051bf58-da0b-4c21-8d46-c79bdaa492cb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by sampadatiwari30** [comment]
@ritiksingh-01 already assigned to another contributor.
