### ISSUE TITLE
Misalignment of Testimonial Boxes in the User Experience Section

### ISSUE THREAD

**Issue by Samridhi002** [ayush-that/FinVeda#229]
### Description:
There is an issue with the alignment of the testimonial boxes in the "_Users sharing their experience_" section on the Home Page. The boxes are not of the same height, which results in a visually unappealing layout.

### Steps to Reproduce:

1. Navigate to the FinVeda homepage.
2. Scroll down to the "Users sharing their experience" section.
3. Observe the varying heights of the testimonial boxes.

### Expected Behavior:
All testimonial boxes should have the same height to ensure a clean and consistent layout.

### Attachment:

![Screenshot (25)](https://github.com/ayush-that/FinVeda/assets/169380578/efb3ddc1-6192-4e91-b0a3-0b1076455ec0)

@deepeshmlgupta 
I can solve this issue once you assign me under GSSoC'24. Thank You!

**Comment by Sharmaji513** [comment]
@ayush-848  please assign me this issue

**Comment by Samridhi002** [comment]
@deepeshmlgupta 
Please review the updated code and may you please also add the _Level_ label as well.
Thank You!
