### ISSUE TITLE
[style]: UI IMPROVEMENT IN ABOUT US SECTION

### ISSUE THREAD

**Issue by isimarjitsingh** [ayush-that/FinVeda#2290]
### What's the style idea?

We need to improve  UI of about us section as its designing is very ordinary we need to give:-
- gradient colors
- bouncing effects
- new designing

### Add screenshots

CURRENT DESIGNING:-
![Screenshot 2024-10-28 125301](https://github.com/user-attachments/assets/d4480a9e-e271-40f4-afc2-ac8d1e7ab130)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by deepeshmlgupta** [comment]
@isimarjitsingh changing the UI doesn't mean you are changing the background color and creating the PR.
Do something that changes the overall users experience
