### ISSUE TITLE
[style]: UI IMPROVEMENT IN A SECTION WHICH PRESENT IN  ABOUT PAGE

### ISSUE THREAD

**Issue by isimarjitsingh** [ayush-that/FinVeda#2291]
### What's the style idea?

We need to improve  DESIGNING OF this section as we need to give:-
- bouncing effects
- new designing
- new background colors

### Add screenshots

CURRENT DESIGNING
![Screenshot 2024-10-28 130148](https://github.com/user-attachments/assets/9fd6e700-f232-4385-a7ae-551b419c313d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by deepeshmlgupta** [comment]
@isimarjitsingh changing the UI doesn't mean you are changing the background color and creating the PR.
Do something that changes the overall users experience
