### ISSUE TITLE
[style]: UI IMPROVEMENT IN REFUND POLICY

### ISSUE THREAD

**Issue by isimarjitsingh** [ayush-that/FinVeda#2292]
### What's the style idea?

We need to improve  DESIGNING OF refund policy page as we need to give:-
- new font family
- resize the font
- redesign the font color and font size
- implement new designs

### Add screenshots

current designing:-
![Screenshot 2024-10-28 131204](https://github.com/user-attachments/assets/86d8036c-438a-409c-92d6-8bc982ac9f2c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by deepeshmlgupta** [comment]
@isimarjitsingh changing the UI doesn't mean you are changing the background color and creating the PR.
Do something that changes the overall users experience
