### ISSUE TITLE
[style]: ENHANCEMENT IN LICENSING PAGE

### ISSUE THREAD

**Issue by isimarjitsingh** [ayush-that/FinVeda#2295]
### What's the style idea?

We need to improve  DESIGNING OF LICENSING page as we need to give:-
- new font family
- resize the font
- redesign the font color and font size
- implement new designs

### Add screenshots

CURRENT DESIGNING:-
![Screenshot 2024-10-28 133903](https://github.com/user-attachments/assets/aeaf7d54-6bcd-4910-9a35-c1a135384f1b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by deepeshmlgupta** [comment]
@isimarjitsingh changing the UI doesn't mean you are changing the background color and creating the PR.
Do something that changes the overall users experience
