### ISSUE TITLE
Fix input text size of subscription

### ISSUE THREAD

**Issue by rohra-anisha** [ayush-that/FinVeda#23]
1. The email text input overlaps with the subscribe button.
 ![image](https://github.com/ayush-that/FinVeda/assets/150921719/457e8c51-490b-47e9-b976-7cd7da5bc9a9)
2. Also the subscribe button's right side corner are only rounded and left side are sharp, therefore would uniform them.
![image](https://github.com/ayush-that/FinVeda/assets/150921719/6bb12c5d-2412-4a6d-90bb-674d940e748e)

**Comment by salonii04** [comment]
Hello Anisha!
Please assign me this issue

**Comment by salonii04** [comment]
Hello
please assign me this issue

**Comment by ayush-that** [comment]
Hello, @rohra-anisha,
I am assigning this issue to you under gssoc. Please implement it well.

@salonii04 Please check other issues. Thanks.

**Comment by rohra-anisha** [comment]
I would like to change the border color when the text box is selected as it doesn't goes along with theme.
Current color border highlight:
![image](https://github.com/ayush-that/FinVeda/assets/150921719/0f8f71b5-0109-4723-a29a-386cf2b181d5)
Theme color border highlight:
![image](https://github.com/ayush-that/FinVeda/assets/150921719/a9cc0447-99d9-442d-9064-4fc8313a991e)

Can I make the additional change?

**Comment by ayush-that** [comment]
> I would like to change the border color when the text box is selected as it doesn't goes along with theme. Current color border highlight: ![image](https://private-user-images.githubusercontent.com/150921719/329785495-0f8f71b5-0109-4723-a29a-386cf2b181d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDEzMzgsIm5iZiI6MTcxNTQ0MTAzOCwicGF0aCI6Ii8xNTA5MjE3MTkvMzI5Nzg1NDk1LTBmOGY3MWI1LTAxMDktNDcyMy1hMjlhLTM4NmNmMmIxODFkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxNTIzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjM0MTlhMWY1ZThhY2IwYjk1MDQ2ZTIxNTU0MmIyZjQ4MWRmNDNjN2FjYTBjODBmN2NhNjJmOTM0OGFlMDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AEkmS0GzoszdrnonTZ2LR1dBKbQHURq2K0j9AQ-dEyY) Theme color border highlight: ![image](https://private-user-images.githubusercontent.com/150921719/329785688-63ac7580-7e24-41cf-a3ab-513da6445548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDEzMzgsIm5iZiI6MTcxNTQ0MTAzOCwicGF0aCI6Ii8xNTA5MjE3MTkvMzI5Nzg1Njg4LTYzYWM3NTgwLTdlMjQtNDFjZi1hM2FiLTUxM2RhNjQ0NTU0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxNTIzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWY3MWNmYTA1YjhkMDYzYmVkM2ZjYjhkZTgwMzdlN2I0OTcxZjYxM2RmNmQ0MzZiNDhmOTI0Zjk1NjE2ZjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g7Ia5bjoiyezb3z0qsZXumImvEqWZgeiu3i4EB6MpOI)
> 
> Can I make the additional change?

Yes.
