### ISSUE TITLE
Create an FAQ's page for the website 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [ayush-that/FinVeda#233]
I will create an FAQ's page for the website with the help of that user can easily understand the working of the website .

**Comment by nehal1222** [comment]
![Screenshot 2024-06-01 154638](https://github.com/ayush-that/FinVeda/assets/119063830/92ccf306-3a4f-4949-9e27-eda8340720f2)
I can add a FAQ Page like this
Please assign me the issue
Thank you!
