### ISSUE TITLE
BUG:alignment issue

### ISSUE THREAD

**Issue by eshalshaikh07** [ayush-that/FinVeda#2351]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

<img width="961" alt="image" src="https://github.com/user-attachments/assets/c9dfc162-8386-4765-93c5-ba2026379987">
alignment not proper

### Steps to Reproduce

fix alignment nav bar.

### Screenshots/Logs

<img width="961" alt="image" src="https://github.com/user-attachments/assets/21806b0e-184c-469a-a46b-12077755a58f">

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by sampadatiwari30** [comment]
@eshalshaikh07 there is no issue, check again

**Comment by eshalshaikh07** [comment]
add level
