### ISSUE TITLE
BUG: Elements clumped together

### ISSUE THREAD

**Issue by KrishPatel1205** [ayush-that/FinVeda#2353]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

The heading of the tools page if clumped together with the header of the page.

### Steps to Reproduce

Go to the tools page

### Screenshots/Logs

Current view:
<img width="1799" alt="Screenshot 2024-10-29 at 10 34 36 AM" src="https://github.com/user-attachments/assets/53ba49d7-1aca-4ac6-bb5a-32cab755406b">
Proposed view:
<img width="1799" alt="Screenshot 2024-10-29 at 10 34 30 AM" src="https://github.com/user-attachments/assets/e6b13b32-7ee3-405a-92d3-93d928ff1dea">

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by deepeshmlgupta** [comment]
already assigned
