### ISSUE TITLE
BUG: UNABLE TO GO ON COURSES PAGE

### ISSUE THREAD

**Issue by isimarjitsingh** [ayush-that/FinVeda#2391]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

THERE IS THE BUG OCCURS WHEN WE TRY TO NAVIGATE ON "COURSES" PAGE THROUGH THE TOOLS PAGE.

### Steps to Reproduce

- GO TO TOOLS PAGE
- CLICK ON COURSES PAGE
- ERROR 404 OCCURS

### Expected Behavior

IT NEEDS TO NAVIGATE US ON COURSES PAGE

### Screenshots/Logs

![Screenshot 2024-10-29 182752](https://github.com/user-attachments/assets/abd981f6-1c7c-4af9-aa6a-a81f35d0b02d)

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by sampadatiwari30** [comment]
@isimarjitsingh no it's working check again.

**Comment by isimarjitsingh** [comment]
AS I CHECKED BUG OCCURS

**Comment by isimarjitsingh** [comment]
https://github.com/user-attachments/assets/25a14ff6-8770-4a3d-a788-0c2a82a29caa
