### ISSUE TITLE
[style]: Update Discussion Form Styling to Match Website Theme

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ayush-that/FinVeda#2396]
### What's the style idea?

The discussion form on the page does not align with the overall website theme. Adjust the design, including colors, fonts, and layout, to ensure consistency with the rest of the site.
 

  

### Add screenshots

Add screenshots
![image](https://github.com/user-attachments/assets/39db3b38-0270-4fbf-a8f8-69eebe146a1a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by sampadatiwari30** [comment]
@AnushkaChouhan25 resolved.
