### ISSUE TITLE
FEATURE:UI fixed of  Discussion Forum 

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ayush-that/FinVeda#2399]
### Feature Summary

in home page the "Discussion Forum" section the from is not aligned properly and thier should be more styled added
i want to fix thier sizes
aligned them properly
enhanced their styled

### Description

enhanced " Discussion Forum" this form

### Proposed Solution

added some styled , resized , etc

### Screenshots/Logs

![WhatsApp Image 2024-10-29 at 19 22 23_4f317f46](https://github.com/user-attachments/assets/ad7aa7ad-9b68-435f-b4f7-e4b30268d0b4)

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by sampadatiwari30** [comment]
@biswajit-sarkar-007 resolved.
