### ISSUE TITLE
Improve team card section UI

### ISSUE THREAD

**Issue by rohra-anisha** [ayush-that/FinVeda#24]
Add borders to the each developers section to enhance the UI and add hover effect on it too.
Add hover effect for the social media icons.
![image](https://github.com/ayush-that/FinVeda/assets/150921719/60435b20-f5c3-4dcd-97aa-3f2294b304cf)

**Comment by VedaVarxha** [comment]
@ayush-that I would like to work on this issue under GSSOC'24. Please assign it to me.

**Comment by pandey079** [comment]
Please assign it to me under GSSOC'24

**Comment by asinha828** [comment]
i would like to work on this issue. Also there are other places where i can also add hover to make it look cool, like the user experience page.

**Comment by ayush-that** [comment]
Hi @rohra-anisha,
I am assigning this issue to you under gssoc. Implement it well. 

@asinha828 @pandey079 @VedaVarxha Guys please check other issues. This is a minor issue. Thanks.

**Comment by Husan7** [comment]
hello sir, i am husandeep singh here GSSoC  24 Contributor. I would do lot of animation in this part ,you can see in my projects.
so please assign me

**Comment by ayush-that** [comment]
> hello sir, i am husandeep singh here GSSoC 24 Contributor. I would do lot of animation in this part ,you can see in my projects. so please assign me

This is already assigned.
Please check other issues.
