### ISSUE TITLE
[BUG]: User experience cards are of uneven size

### ISSUE THREAD

**Issue by shreya-paul-17** [ayush-that/FinVeda#241]
In User Experience section of FinVeda, the cards are not having equal length. I would like to fix this issue and work on the same.

Below is a screenshot of the above said condition:
![finveda](https://github.com/ayush-that/FinVeda/assets/135226069/326b49ab-5ab4-4a6d-8527-5222a6fb922d)

- [x] _I am a GSSoC 2024 Contributor_
- [x] _I agree to follow the Code Of Conduct_
- [x] _I agree to follow the Contributing guidelines of this project._

**Comment by Ananya-Nair20** [comment]
Hello

I am participating in GSSOC'24. I am interested in resolving this issue Could you please assign this task to me under GSSOC'24 with relevant level labels?

Thank you
