### ISSUE TITLE
BUG: Blog post page is not working properly

### ISSUE THREAD

**Issue by Anshuaman2001** [ayush-that/FinVeda#2421]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

blog cards are not showing at the screen.

### Steps to Reproduce

all blog cards will show properly at screen

### Expected Behavior

they should be visible properly

### Screenshots/Logs

![Screenshot 2024-10-30 010440](https://github.com/user-attachments/assets/9af86711-7dbc-4bcd-85a7-defe52685229)

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by sampadatiwari30** [comment]
@Anshuaman2001 already assigned to another contributor.
