### ISSUE TITLE
[BUG]: Buttons fixing is needed

### ISSUE THREAD

**Issue by shreya-paul-17** [ayush-that/FinVeda#243]
In the blog posts section, the "Learn More" buttons are not place at same alignment. Some are placed high and some at a lower position. I would like to fix that and work on the same.

Below is the attached screenshot of the said condition:
![finveda2](https://github.com/ayush-that/FinVeda/assets/135226069/97c04403-2ee6-4767-9c22-55c1e23cd0e0)

- [x] _I am GSSoC 2024 Contributor_
- [x] _I agree to follow the Code of Conduct_
- [x] _I agree to follow the Contributing guidelines of this project_

**Comment by nehal1222** [comment]
While clicking on Home it's not reaching the home page .. it's showing the site can't be reached
Can I work on this issue? Please assign  me the issue.

**Comment by Agarwalvidu** [comment]
This issue has already been resolved, for the same reason I am closing this issue. Thank you for collaborating!
