### ISSUE TITLE
BUG: Contact Us Page Layout and Styling Errors

### ISSUE THREAD

**Issue by salonijoshi1980** [ayush-that/FinVeda#2431]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

**Description :** 
- The layout and styling of the Contact Us page are not displaying correctly. The structure appears broken, and the styling elements are inconsistent and misaligned. This negatively impacts the user experience and makes it difficult to navigate or use the page effectively.

### Steps to Reproduce

1. Go to the Contact Us page.
2. Observe the layout and styling issues present throughout the page.

**Priority :** 

- Higher

### Expected Behavior

**Expected Result :** 
- The Contact Us page should display a well-structured layout with consistent styling, making it easy for users to view and complete the contact form.

**Actual Result :** 
- The layout is disturbed, with misaligned elements and inconsistent styling that disrupts the overall look and functionality of the page.

**Suggested Fixes :**
 Review and update the CSS and HTML structure for this page to ensure that elements are aligned correctly and the overall design follows a clean, responsive format

### Screenshots/Logs

**Issues Screenshots :**

![Screenshot 2024-10-30 112202](https://github.com/user-attachments/assets/a4e4a247-c1ef-4392-9872-1bad48f2b168)

![Screenshot 2024-10-30 113219](https://github.com/user-attachments/assets/60674a2b-879c-4f6f-8352-2d20f8a07103)

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by salonijoshi1980** [comment]
@deepeshmlgupta @sampadatiwari30 I want to solved this ... I do a pull request directly there you assigned me with the labels!
If this problem isn't solved yet.

**Comment by deepeshmlgupta** [comment]
This problem is solved
