### ISSUE TITLE
BUG: Login & Signup page issue

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ayush-that/FinVeda#2434]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

The borders of these text box doesn't look good, I want to fixed this issue.
PA please assign me

![Screenshot 2024-10-30 023901](https://github.com/user-attachments/assets/53ba080b-67fb-4a50-8ed0-435ec9ef052a)
![Screenshot 2024-10-30 023952](https://github.com/user-attachments/assets/899f8e89-2ea7-4d60-bd92-c619b43e7567)

### Steps to Reproduce

.

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by Subhajit-2023-44** [comment]
@deepeshmlgupta @sampadatiwari30

**Comment by salonijoshi1980** [comment]
@Subhajit-2023-44 hey I'm working on this problem and someone disturbed the layout of sign-up page now..so need to improve the layout of the sign-up page layout also.

**Comment by salonijoshi1980** [comment]
@sampadatiwari30 this one!
