### ISSUE TITLE
Add Sign-In Page ,Dark Mode and Trend Ratio Corrections

### ISSUE THREAD

**Issue by ishap11** [ayush-that/FinVeda#245]
Hello, this is Isha Prajapati,
I hope you're doing well. I'm interested in improving our website's functionality.

Sign-in page with the following key features:
To make signing in easier, clearer and more user-friendly. If someone makes a mistake, we'll let them know what went wrong. Plus, we're adding a "Remember Me" option so users can stay signed in, even if they close the page. These changes aim to make the sign-in process smoother and more convenient for everyone.

Dark Mode Functionality:
Add a switch that lets users choose between light and dark modes.
Make sure the page looks good and is easy to use in both light and dark modes, making it comfortable for everyone.

Accurate Trend Ratios:
Fix the current problem where trend ratios (showing if a trend is going up or down) are incorrect .I It should be fixed.
Make sure the trend ratios show the right direction and amount of change, so the information is reliable and accurate.
https://github.com/ayush-that/FinVeda/assets/128213933/d6e988b8-8529-4b9b-912c-5841986c562f

I am eager to contribute under GSSoC'24 and help enhance our website’s functionality and user experience. Please assign this task to me.
Thank you!

**Comment by Agarwalvidu** [comment]
Dark mode can not be added in this website.
Sign in page is already implemented!
