### ISSUE TITLE
FEATURE:LOGIN BUTTON NEEDED PROPER ALIGNMENT WITH NAVBAR

### ISSUE THREAD

**Issue by likitha-kapu** [ayush-that/FinVeda#2456]
### Feature Summary

The login button currently appears misaligned or positioned outside of the navbar, disrupting the layout's visual coherence and making the interface look unpolished. Properly aligning the login button within the navbar would create a more unified and professional appearance, ensuring it fits seamlessly alongside other menu items. This adjustment improves both the aesthetic and usability of the navbar, allowing users to locate and click the login button effortlessly.
HERE'S A SCREENSHOT OF THE ISSUE:
![Screenshot 2024-10-30 165830](https://github.com/user-attachments/assets/b91246f3-f92e-49d7-9c9e-547ede310587)

### Description

Properly aligning the login button within the navbar is essential as it solves the problem of visual inconsistency and usability issues. A misaligned button can appear disconnected from the navigation, causing confusion and making it harder for users to locate quickly. Aligning it correctly not only enhances the visual appeal but also improves the overall user experience, allowing for a more intuitive, seamless interaction that reflects a well-organized and professional interface.

### Proposed Solution

I propose aligning the login button within the navbar, positioning it consistently alongside other menu items. This would involve adjusting CSS properties to ensure the button is vertically and horizontally centered within the navbar's layout, matching the style, size, and spacing of other elements for a cohesive look.

User Story:
As a user, I want a clearly visible and aligned login button within the navbar so that I can easily locate and access it without confusion.

Use Case:
When users visit the site, they see a sleek, organized navbar with the login button aligned perfectly alongside other options. This alignment provides visual clarity, ensuring users can quickly find the login option whether they are on a desktop or mobile device. The button’s alignment remains consistent, enhancing the experience across different screen sizes and preventing users from overlooking or struggling to find it.

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by likitha-kapu** [comment]
@ayush-that please assign this task to me

**Comment by sampadatiwari30** [comment]
@likitha-kapu there is no issue.

**Comment by likitha-kapu** [comment]
@sampadatiwari30 the issue still persists...the login/register button is still out of the nav bar
![image](https://github.com/user-attachments/assets/ca4738a3-47fe-4fa6-aa36-2949638abd00)
