### ISSUE TITLE
Improving the footer !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [ayush-that/FinVeda#2460]
![image](https://github.com/user-attachments/assets/280676a0-805e-4a8d-9997-4397f2020a50)

**Comment by sampadatiwari30** [comment]
@SrijaVuppala295 in which page ?

**Comment by SrijaVuppala295** [comment]
@sampadatiwari30 , tools page , please assign this issue , i will fix in a short time

**Comment by sampadatiwari30** [comment]
@SrijaVuppala295 
![Screenshot 2024-10-30 191324](https://github.com/user-attachments/assets/03db53e6-58e6-440d-bd9c-96efe81138f1)
there is no issue, no need to change.

**Comment by SrijaVuppala295** [comment]
@sampadatiwari30 , 
![image](https://github.com/user-attachments/assets/bb770af3-f6db-4eea-bcc6-de63384c8799)


The footer is improper !!

**Comment by SrijaVuppala295** [comment]
@sampadatiwari30 , i have opened this from the deployment link , please open this issue !!!
