### ISSUE TITLE
BUG: Sign in page isn't responding

### ISSUE THREAD

**Issue by anjali5Xcode** [ayush-that/FinVeda#2465]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

After filling the credentials the page isn't responding on submission

### Steps to Reproduce

![Screenshot (182)](https://github.com/user-attachments/assets/2922bea5-0fe0-428f-9f59-41c79a592418)

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by sampadatiwari30** [comment]
@anjali5Xcode resolved.
