### ISSUE TITLE
BUG: Misaligned Login/Register Button

### ISSUE THREAD

**Issue by sanchitc05** [ayush-that/FinVeda#2469]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

The Login/Register button on the FinVeda website is misaligned, causing an inconsistent user experience. The button should be centered horizontally on the page.

### Steps to Reproduce

1. Navigate to the FinVeda website.
2. Observe the alignment of the Login/Register button.

### Expected Behavior

The Login/Register button should be centered horizontally with other tabs, aligning with other elements and providing a visually appealing layout.

### Screenshots/Logs

![Screenshot (271)](https://github.com/user-attachments/assets/10ffd7e3-1612-47a6-9ef8-b4834d6635aa)

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by sampadatiwari30** [comment]
@sanchitc05 resolved.
