### ISSUE TITLE
NOT GOOD for mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [ayush-that/FinVeda#248]
The website does no look good in mobile screen.
It should be of proper size to the screen to enahnce the user experience.

![image](https://github.com/ayush-that/FinVeda/assets/124615886/f99b74d6-2815-4498-8cf5-1c2fd0c5105a)

I would love to contribute to it make the user experience better.Please assign this to me.😊

**Comment by Utsavladia** [comment]
Dear @deepeshmlgupta There is some issue with the main branch it is not working... continuous loading screen is coming..
Please check this and if any special setup is needed then assist me with it so that I can start working on the design.
![image](https://github.com/ayush-that/FinVeda/assets/124615886/08425aee-1cd9-4350-904a-fd140feae96a)

**Comment by deepeshmlgupta** [comment]
Hey @Utsavladia , there are no issues in the main branch; it's working fine. You can re-clone it and start working again. You won't encounter any errors.

**Comment by Utsavladia** [comment]
@deepeshmlgupta  Can you please tell me any setup guidance because on running "start index.html" it is continuously loading on screen.

**Comment by Agarwalvidu** [comment]
This issue has already been resolved, for the same reason I am closing this issue. Thank you for collaborating!
