### ISSUE TITLE
FEATURE: Add a Visitor Counter feature 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ayush-that/FinVeda#2487]
### Feature Summary

I want to add a Visitor Counter feature properly in bottom left corner..

PA please assign me this task.

### Description

![Screenshot 2024-10-30 220945](https://github.com/user-attachments/assets/8333aec9-e3f7-473f-a7ab-b9cddc9d506e)

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by Subhajit-2023-44** [comment]
@deepeshmlgupta @sampadatiwari30 please assign me

**Comment by deepeshmlgupta** [comment]
not needed

**Comment by Subhajit-2023-44** [comment]
> not needed

okay
