### ISSUE TITLE
[FEATURE] : Detailed page

### ISSUE THREAD

**Issue by dhruv8433** [ayush-that/FinVeda#249]
@ayush-that 

check this out
![image](https://github.com/ayush-that/FinVeda/assets/114583978/521eae3e-75fd-4cf6-b0b8-457372da827b)

when we click on `Learn more` that redirect to `#`
we can build seperate page for that

**Comment by Agarwalvidu** [comment]
This issue is already been solved. Thank you for contributing, looking for more issues from your end. For now I am closing this issue.
