### ISSUE TITLE
Navbar Alignment : Elements in the navabar are not perfectly aligned.

### ISSUE THREAD

**Issue by SiddharthaArepalli** [ayush-that/FinVeda#25]
![Screenshot 2024-05-11 004405](https://github.com/ayush-that/FinVeda/assets/140429954/76917e8d-e72e-4ea2-9837-df68f2ddaaf5)

I can work on the alignment of the navbar as it is more weighted to the rightside

**Comment by SiddharthaArepalli** [comment]
@ayush-that   I can work on it assign me under GSSOC'24

**Comment by GAGGZ1** [comment]
Hello, Ayush Singh,

I'm eager to assist in rectifying this issue. With my expertise in front-end development and attention to detail, I'm confident I can ensure precise alignment for a polished user experience.

Regards, 

Gagan Chauhan

**Comment by sonarani1** [comment]
Hi, I can fix this issue. Kindly assign this issue to me.

**Comment by ayush-that** [comment]
Hi @SiddharthaArepalli, @GAGGZ1, and @sonarani1
I am assigning this issue to you. It is a minor issue should. Make sure to implement it on all pages properly.

**Comment by SiddharthaArepalli** [comment]
@ayush-that @
![Screenshot 2024-05-11 195317](https://github.com/ayush-that/FinVeda/assets/140429954/d39e6184-7720-4aae-a87b-135e777a103d)

**Comment by SiddharthaArepalli** [comment]
@ayush-that  Not able to to load the page ig there is bug ??

**Comment by ayush-that** [comment]
> @ayush-that Not able to to load the page is there any bug ??

![image](https://github.com/ayush-that/FinVeda/assets/110257939/9e38997e-fd69-4314-9908-a267dd2da940)
Working for me.
Issue should be on your side.
