### ISSUE TITLE
[BUG] : No validation in quiz

### ISSUE THREAD

**Issue by dhruv8433** [ayush-that/FinVeda#250]
@ayush-that

check this out,
when we submit quiz without any answer 
it still got submitted 

![image](https://github.com/ayush-that/FinVeda/assets/114583978/b6d9cc49-5f76-4b74-ac33-80cc77d11702)

we can add validation on that so if user forgot to select any answer
we can display simple error message that `attempting all questions are necessary`

**Comment by Agarwalvidu** [comment]
This issue is already been solved. Thank you for contributing, looking for more issues from your end. For now I am closing this issue.
