### ISSUE TITLE
Feedback button is missing

### ISSUE THREAD

**Issue by ayushkrrana** [ayush-that/FinVeda#253]
I can add feedback at the bottom or at the top or scrollable to whole website in which user can give their ratings
please assign me under Gsooc @ayush-that 
Thank you

**Comment by ayushkrrana** [comment]
@deepeshmlgupta Please assign at least level 2 because with the feedback button , i also need to create feedback born in which user can give their feedback in it

**Comment by ayushkrrana** [comment]
@deepeshmlgupta 
1}FEEDBACK BUTTON
2) FEEDBACK FORM

**Comment by ayushkrrana** [comment]
@deepeshmlgupta When i open the website with live server after fork it just load and did not open i don't know where is the problem

**Comment by deepeshmlgupta** [comment]
Hey @ayushkrrana  , there are no issues in the main branch; it's working fine. You can re-clone it and start working again. You won't encounter any errors.

**Comment by ayushkrrana** [comment]
@deepeshmlgupta I will again try and re clone it , again it shows the same problem you can see it 

https://github.com/ayush-that/FinVeda/assets/160728166/aad453fe-49e5-4d0b-aa38-6bc48ba86fa9

**Comment by Agarwalvidu** [comment]
As no further updates are provided by the contributor I am closing this issue! Looking for more issues from your side. Thank you for contributing!
