### ISSUE TITLE
Implementation of  Multilingual support

### ISSUE THREAD

**Issue by Anjankumarkamalapur** [ayush-that/FinVeda#255]
User can access our website in their preferred language. Below is example of my work.
![Screenshot (991)](https://github.com/ayush-that/FinVeda/assets/139578011/34d63372-0bfe-4205-8e6c-cfbbcb8026e1)
![Screenshot (992)](https://github.com/ayush-that/FinVeda/assets/139578011/9a24f0c1-90e5-4e73-af58-021ca920cf81)

**Comment by Anjankumarkamalapur** [comment]
@ayush-that can u pls check it out

**Comment by Agarwalvidu** [comment]
This website can not support multilingual feature. Thank you for raising this issue. Looking for more issues from your side.
