### ISSUE TITLE
FEATURE: `Career Page` Footer Section is completely disturbed

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ayush-that/FinVeda#2555]
### Feature Summary

![image](https://github.com/user-attachments/assets/bdcb0029-3e9e-4094-842d-6af0dac839e5)

### Description

I will make it similar to home page.
@sampadatiwari30 @deepeshmlgupta  assign me this task

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by sampadatiwari30** [comment]
@Adarsh-Chaubey03 this issue has been resolved.
