### ISSUE TITLE
FEATURE: Dark Theme Not Functioning on "About Us" Page

### ISSUE THREAD

**Issue by neeru24** [ayush-that/FinVeda#2583]
### Feature Summary

The dark theme is currently not being applied to the "About Us" page, resulting in an inconsistent user experience across the platform.

### Description

Users accessing the "About Us" page are presented with a light mode interface, which does not align with the dark theme implemented on other pages. This inconsistency can lead to confusion and detracts from the overall aesthetic of the application, especially for users who prefer or rely on dark mode for better visibility in low-light environments.

### Dark Theme Activation:

-  Ensure that the dark theme styles are correctly applied to the "About Us" page. This includes updating the background colors, text colors, and any other relevant UI elements to match the established dark mode design.

### User Interface Improvements:

- Implement hover effects and focus states for buttons and links to enhance interactivity.
- Ensure that all text is legible and meets accessibility standards against the dark background.
- Review the layout for consistent spacing and alignment with the rest of the application.

### Use Cases

- As a user, I want the "About Us" page to feature a dark theme so that I can enjoy a uniform experience throughout the application.
- As a user, I want the content on the "About Us" page to be clear and easily readable, particularly in low-light conditions.

### Screenshots/Logs

![image](https://github.com/user-attachments/assets/26d01c85-4aa6-469d-aa23-7fa45b2a7f61)

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by sampadatiwari30** [comment]
@neeru24 already assigned to another contributor.
