### ISSUE TITLE
Missing Code of Conduct File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [ayush-that/FinVeda#26]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Please assign this issue to me.

**Comment by ayush-that** [comment]
Hello @suhanipaliwal,
I agree that we need a Code of Conduct. I am assigning this issue to you under gssoc. All the best.

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the task.
