### ISSUE TITLE
Separation between chatbot and drop-down is not visisble

### ISSUE THREAD

**Issue by Garima-149** [ayush-that/FinVeda#263]
![Screenshot (45)](https://github.com/ayush-that/FinVeda/assets/143211271/903ca283-63de-41df-9469-3dd830159152)

@ayush-that .Due to same color of background and chatbot and very less gap between chatbot and drop-down ,separation is almost invisible.This is decreasing user experience.I would like to work upon this issue.

**Comment by ayush-848** [comment]
> ![Screenshot (45)](https://private-user-images.githubusercontent.com/143211271/336106503-903ca283-63de-41df-9469-3dd830159152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjUyMjUsIm5iZiI6MTcxNzQyNDkyNSwicGF0aCI6Ii8xNDMyMTEyNzEvMzM2MTA2NTAzLTkwM2NhMjgzLTYzZGUtNDFkZi05NDY5LTNkZDgzMDE1OTE1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxNDI4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTI0MjA5NjlhNDE0MGIzNGI0OGRlODkzNTFlNGM2YzM5YmZiZWFlOTgyODJhOGEzYjhmY2QyZTM5MWU4OTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pgPAOyVT_7l0Y-YyZQR49AgD-68EDKb7OUbrvAKfUag)
> 
> @ayush-848 .Due to same color of background and chatbot and very less gap between chatbot and drop-down ,separation is almost invisible.This is decreasing user experience.I would like to work upon this issue.

Hey @Garima-149 you have tagged me but I am not the project owner

**Comment by Garima-149** [comment]
@deepeshmlgupta Could you please tell that where could I find this chatbot in component in code.I tried to find through source code too but was unable.

**Comment by Garima-149** [comment]
Could you please reply?

**Comment by Agarwalvidu** [comment]
Already solved!
