### ISSUE TITLE
BUG: Text blends with Bg color

### ISSUE THREAD

**Issue by neeru24** [ayush-that/FinVeda#2646]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

In the courses age, the text below main line blends with the background and is not visible and readable. Would like to fix it with some other changes 

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/d66b63fe-c8d1-47eb-9dce-bb1063ecc2ae)

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by sampadatiwari30** [comment]
@neeru24 already assigned.
