### ISSUE TITLE
Add Cursor Tail Effector in Profile page 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ayush-that/FinVeda#2649]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

I want to add Cursor Tail Effector in Profile page.. Please assign me

https://github.com/user-attachments/assets/be0b653a-cb71-437f-89ed-81cebc8647f1

### Steps to Reproduce

.

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by sampadatiwari30** [comment]
@Subhajit-2023-44 no need.
