### ISSUE TITLE
FEATURE: Adding a "show password" functionality to the login/signup page

### ISSUE THREAD

**Issue by shriyadindi** [ayush-that/FinVeda#2653]
### Feature Summary

Adding a "show password" functionality to the login/signup page

### Description

user authentication by adding a show password functionality.

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by sampadatiwari30** [comment]
@shriyadindi resolved.
