### ISSUE TITLE
Missing register link

### ISSUE THREAD

**Issue by naisargi17** [ayush-that/FinVeda#266]
Frontend 
The register link is not there. I can add toggling of login and signup .
(https://github.com/ayush-that/FinVeda/assets/111778403/0cfddc95-004a-42f1-b72b-e81ad64ab8de)

for now I can suggest somewhat like this 
https://github.com/ayush-that/FinVeda/assets/111778403/c46bf217-5863-4900-92be-e56ba0a6d1c1

**Comment by Agarwalvidu** [comment]
It is updated now. Thank you for raising issue, looking for your more inputs. For now I am closing this issue.
