### ISSUE TITLE
BUG: Not Static Navbar

### ISSUE THREAD

**Issue by sachinggsingh** [ayush-that/FinVeda#2663]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

As we click for the dark mode in navbar the dimensions on the navbar changes and it moves a bit from its position and the shape also gets a bit distorted from the extreme left   like someone has given some border radius of what

### Steps to Reproduce

Will fix the positions and will see the best alternative solution possible for it

### Screenshots/Logs

**In Light mode**
![Screenshot 2024-11-03 120500](https://github.com/user-attachments/assets/fe2db9a2-b02e-4a11-b724-1e2263a56b98)
**In Dark mode**
![Screenshot 2024-11-03 120511](https://github.com/user-attachments/assets/0f1abc57-5242-4f15-8f15-ee68563fa3f2)

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by sachinggsingh** [comment]
Assign me this issue

**Comment by sampadatiwari30** [comment]
@sachinggsingh resolved.
