### ISSUE TITLE
BUG: Text color issue in Feedback section

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ayush-that/FinVeda#2688]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

These input text color blends with background color in feedback section, i want to fixed this issue, please assign me..

https://github.com/user-attachments/assets/8c3c6232-2984-4faf-bf18-980e3c217488

### Steps to Reproduce

.

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by sampadatiwari30** [comment]
@Subhajit-2023-44 resolved.
