### ISSUE TITLE
BUG: multiple fixes 

### ISSUE THREAD

**Issue by adityalaxkar123** [ayush-that/FinVeda#2698]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

in terms and condition and privacy poliicy section navbar is misaligned.

darkMode btn is not working in home page for moblie mac's and ipad.

### Steps to Reproduce

we can fix the issue by adjusting some css and javascript code.

### Expected Behavior

i think css and javascript code is not injected properly or may be css issue for this misalignment.

### Screenshots/Logs

![Screenshot (1115)](https://github.com/user-attachments/assets/c7d028f8-6fa5-405f-8985-0f09ff89c632)
 
navbar of terms and condition and privacy policy misaligned.

![Screenshot (1114)](https://github.com/user-attachments/assets/c3dbdbfa-12d8-4463-9c6c-64e9e43664dd)

darkMode btn is not working in home page for small and medium screen.

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by sampadatiwari30** [comment]
@adityalaxkar123 resolved.
