### ISSUE TITLE
[style]: font on top of the courses section not visible

### ISSUE THREAD

**Issue by PunithaNarasegowda** [ayush-that/FinVeda#2699]
### What's the style idea?

We need to improve  the font weight and its colouring to make it more visble as it is not being able to be read i will align the fons and make it more attractive come helpful ..kindly do assign me this issue @ays

### Add screenshots

![Screenshot 2024-11-03 235002](https://github.com/user-attachments/assets/e5e5a43c-7bc6-4415-a3e4-9a4200ef1c10)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by sampadatiwari30** [comment]
@PunithaNarasegowda already assigned to another contributor.
