### ISSUE TITLE
Augment Quiz Answers: Adding Detailed Explanations for Clarity

### ISSUE THREAD

**Issue by Pratik2401** [ayush-that/FinVeda#27]
I'll enrich the quiz section by providing comprehensive explanations for each answer, enhancing user understanding and learning outcomes. This addition will ensure users grasp the concepts thoroughly and promote a more engaging quiz experience. Assigning this task to me for GSSoC contribution will elevate the educational value of the quiz section
![Screenshot 2024-05-11 080909](https://github.com/ayush-that/FinVeda/assets/105542579/749c2968-da7f-47c9-819c-7a9fa688d34c)

**Comment by ayush-that** [comment]
Hello @Pratik2401,
Feel free to proceed with adding explanations to the quiz section. I am assigning this issue to you under gssoc.

**Comment by Pratik2401** [comment]
![image](https://github.com/ayush-that/FinVeda/assets/105542579/b22030dd-2a5b-4b3a-8b6c-ee6fd366e831)
hey! I am have solved the issue so is there any thing specific to be updated or can send the pr
![image](https://github.com/ayush-that/FinVeda/assets/105542579/39937ae5-a1ba-43cb-9eae-55fe5a1984bd)

**Comment by ayush-that** [comment]
Please send the PR.
I'll take a look.

**Comment by ayush-that** [comment]
@Pratik2401 
https://github.com/ayush-that/FinVeda/pull/43#issuecomment-2109519959

**Comment by Pratik2401** [comment]
Hey can you close these issue i have completed the work
