### ISSUE TITLE
Password is not hidden

### ISSUE THREAD

**Issue by Sailesh3000** [ayush-that/FinVeda#271]
![image](https://github.com/ayush-that/FinVeda/assets/126142666/9abf7cbc-77b0-4acd-a760-ca69d00715bb)
Password is not hidden in the register form . I am a GSSOC'24 Contributor Please assign me this issue

**Comment by Agarwalvidu** [comment]
It is updated now. Thank you for raising issue, looking for your more inputs. For now I am closing this issue.
