### ISSUE TITLE
Adding Social Media Links to the Footer

### ISSUE THREAD

**Issue by nirajsingh015** [ayush-that/FinVeda#273]
As a part of my gssoc contribution i want to integrate social media links into the footer, making it easy for users to connect with us on platforms like Facebook, Twitter, Instagram, and LinkedIn. This will boost our social media presence and encourage user engagement by providing seamless access to our social profiles through interactive icons.

![Screenshot 2024-06-05 121356](https://github.com/ayush-that/FinVeda/assets/115022991/b8c4b65b-0045-4413-a453-158d32cb72b1)

**Comment by Aradhyajha** [comment]
Hii @ayush-that , sir I want to work on that issue for solving this
To add social media links to the website's footer, first decide which platforms to include and obtain their icons. Insert the HTML for these links in the footer section, such as

FacebookTwitterInstagramLinkedIn
. Style the icons with CSS to ensure they are visually appealing and responsive, for example, .social-media {text-align: center; padding: 10px 0;} .social-media a {margin: 0 10px; display: inline-block;} .social-media img {width: 30px; height: 30px; transition: transform 0.3s;} .social-media img:hover {transform: scale(1.1);}, and test the footer on various devices and browsers to ensure functionality and responsiveness.

**Comment by Aradhyajha** [comment]
![Uploading social-media link.jpg…]()

**Comment by Aradhyajha** [comment]
![Uploading link.jpg…]()

**Comment by Aradhyajha** [comment]
![link](https://github.com/ayush-that/FinVeda/assets/130289875/64c6182a-b861-46e0-8460-c2d60db6de92)

**Comment by Agarwalvidu** [comment]
As this is a professional website it is not needed. Thank you for contributing, looking for more issues from your end. For now I am closing this issue. needed.
