### ISSUE TITLE
[style]: FAQ Container alignment issues

### ISSUE THREAD

**Issue by dipak2005** [ayush-that/FinVeda#2790]
### What's the style idea?

We need to fix   the alignment of FAQ section on FAQ page and change the options color combination according FAQ section Theme

### Add screenshots

Add screenshots : 
![Screenshot 2024-11-05 162043](https://github.com/user-attachments/assets/3e76e7f4-3b9f-4b96-9d4b-cbd29f93ff1e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by sampadatiwari30** [comment]
@dipak2005 already assigned to another contributor.
