### ISSUE TITLE
[style]: improve the Ui Design of ADD Blog Page

### ISSUE THREAD

**Issue by dipak2005** [ayush-that/FinVeda#2791]
### What's the style idea?

We need to improve  improve the UI design of ADD Blog page 

### Add screenshots

Add screenshots :
![Screenshot 2024-11-05 162340](https://github.com/user-attachments/assets/db03b654-33f7-4a4e-af40-e105be3b95de)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by sampadatiwari30** [comment]
@dipak2005 already assigned to another contributor.
