### ISSUE TITLE
Form Validation in the Mutual Fund Tool

### ISSUE THREAD

**Issue by gobbledy-gook** [ayush-that/FinVeda#28]
**Issue Description**
Even after entering alphabetical characters in the fields, the form doesn't give any invalid output or warn the user.

**Steps to Reproduce the Error**
1. Go to 'Tools'
2. Enter Alphabetical Values in the tool fields
3. Hit calculate

**Expected Behaviour**
1. The form fields must validate the input
2. The 'Calculate' button must be disabled till the form fields are invalid inputs.

**Screenshots**
![Screenshot 2024-05-11 at 10 34 33 AM](https://github.com/ayush-that/FinVeda/assets/96362727/cacdae36-5fdc-4890-a4c6-77371fd1a51c)

**Additional**
1. I would also like to enhance the UI - the field padding, border coloring etc.

**Comment by gobbledy-gook** [comment]
I would like to request the project manager/mentor to please assign this issue to me under GSSoC 24.

**Comment by ayush-that** [comment]
Hello @gobbledy-gook,
Thank you for reporting this bug. I am assigning this issue to you under gssoc. Please start working on fixing it and all the best.
