### ISSUE TITLE
Ehancing login form and adding register from

### ISSUE THREAD

**Issue by SalehaTabassum** [ayush-that/FinVeda#281]
In login form there is no from validation and no forgot password option.
there should be also an option for "New user Create account"
and register form on clicking it.

currently the form is like this:
![Screenshot 2024-06-06 204853](https://github.com/ayush-that/FinVeda/assets/169278740/c1c1df43-7291-48e0-a8f3-278ba03c8cb3)

I want to make it like this:

![Screenshot 2024-06-02 225422](https://github.com/ayush-that/FinVeda/assets/169278740/9fc1c888-91c8-45e7-b6b0-412fa5294aba)

@ayush-that assign this issue to me under GSSOC and appropriate labels to it

**Comment by kashi-verma** [comment]
Assign this issue to me @ayush-that .

**Comment by Nidhi-Satyapriya** [comment]
is this issue still pending or you are working on it? @kashi-verma 

1) I would like to implement SignUp/Login page with email verification using OAuth/JWT.
2) Implement 'Forgot Password' and "remember me' .
@deepeshmlgupta kindly look into it.

**Comment by Agarwalvidu** [comment]
Already done!
