### ISSUE TITLE
BUG:Changing the text colour and improving meet our team page 

### ISSUE THREAD

**Issue by Pragati1466** [ayush-that/FinVeda#2852]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

The text "Developer" under each team member on the "Meet Our Team" page is not visible due to insufficient contrast. It’s expected that the text is clearly visible, but currently, it blends into the background or is too faint to read easily.

### Steps to Reproduce

Open the "Meet Our Team" page.
Scroll to the section with team members listed (e.g., Manya Singh and Ayush Singh).
Observe the text "Developer" beneath each team member's name.

### Expected Behavior

The role text (e.g., "Developer") should have sufficient contrast against the background to ensure readability on all screen sizes. This should be visible on both light and dark backgrounds.

### Screenshots/Logs

<img width="1769" alt="Screen Shot 2024-11-06 at 2 27 21 PM" src="https://github.com/user-attachments/assets/6d9a90c4-eb46-4f07-9dbf-e02af9af51e3">
pls add hacktoberfest label as well @sampadatiwari30 @deepes

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by Pragati1466** [comment]
@deepeshmlgupta

**Comment by Pragati1466** [comment]
<img width="824" alt="image" src="https://github.com/user-attachments/assets/4f79d762-d848-4d49-8f84-345c9b673027">
somewhat like this I will ensure proper sizing nd all and also improve its ui ux more

**Comment by Pragati1466** [comment]
Pls add relevant labels for gssoc and hacktoberfest'24 @sampadatiwari30

**Comment by sampadatiwari30** [comment]
@Pragati1466 I will add the label when your task is complete.

**Comment by Pragati1466** [comment]
@sampadatiwari30 could you just help me out despite making changes its showing this so should i just send my code here?
<img width="1754" alt="image" src="https://github.com/user-attachments/assets/90857606-9e9f-41e9-bd52-472bd872a90f">

**Comment by Pragati1466** [comment]
https://github.com/user-attachments/assets/58c876d0-fe52-4bdd-959a-206f5affe5bb
