### ISSUE TITLE
BUG: Testimonial card's code are removed!

### ISSUE THREAD

**Issue by gjrahul1** [ayush-that/FinVeda#2854]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

Someone has removed the single testimonial cards from the index.html.

I would like to add those codes back from my fork.

![Screenshot 2024-11-06 143948](https://github.com/user-attachments/assets/63994d17-ecaf-4b63-aa07-66be1205eaeb)

![Screenshot 2024-11-06 144250](https://github.com/user-attachments/assets/074d179c-de51-4b1a-9312-729ce7af2cbf)

@Sampadatiwari assign me the project with the label

### Steps to Reproduce

Visible Check

1. Head over to the deployment
2. Scroll down to testimonials

Console Check
![Screenshot 2024-11-06 144250](https://github.com/user-attachments/assets/1e14db26-1499-401e-96ea-88a17d209a66)

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by sampadatiwari30** [comment]
@gjrahul1 resolved.
