### ISSUE TITLE
[style]: Improve the Text Visibility In Header of Contributors Page

### ISSUE THREAD

**Issue by Arshia-163** [ayush-that/FinVeda#2856]
### What's the style idea?

We need to improve  text contrast by changing the header text color to a bold, high-contrast shade (e.g., dark color) against the background, and consider adding a subtle text shadow for enhanced readability and remove the hover effect of text color.

### Add screenshots

![image](https://github.com/user-attachments/assets/7ffc4f6e-02a8-45dc-8102-cfee837696ad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by LavkushSolanki** [comment]
![Screenshot (422)](https://github.com/user-attachments/assets/d5610386-52c5-4c74-80a8-a4aa76fc56da)
![Screenshot (423)](https://github.com/user-attachments/assets/57632513-8448-42a7-8c7d-88b60566b52c)
![Screenshot (424)](https://github.com/user-attachments/assets/0ce625bd-f0ad-479c-b1d8-764d878891c2)
 I have just changed few lines in the contribution page and it look exactly same just it was present in all pages

**Comment by Arshia-163** [comment]
@ayush-that Please assign me this issue

**Comment by sampadatiwari30** [comment]
@Arshia-163 resolved.
