### ISSUE TITLE
BUG: NewsLetter Banner is not responsive in the mobile phone

### ISSUE THREAD

**Issue by Hemraj-7** [ayush-that/FinVeda#2869]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

Newsletter Banner is not responsive in the mobile phone. It is not looking good in the phone. 
Now this is looking good only on the desktop version. so i want to make it user friendly and responsive for the small devices.

![WhatsApp Image 2024-11-06 at 6 00 50 PM (1)](https://github.com/user-attachments/assets/0a32e2a6-3967-4061-b2a1-5e9cadb8f739)

assign me this issue 
Thank you!

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by LavkushSolanki** [comment]
I want to contribute to this problem

**Comment by LavkushSolanki** [comment]
![Screenshot (425)](https://github.com/user-attachments/assets/d4628bf7-43d0-4fa1-85e9-76802aa0cf19)
![Screenshot (426)](https://github.com/user-attachments/assets/a78e0c72-69fa-42b3-b3f5-2011a9f81f81)
![Screenshot (427)](https://github.com/user-attachments/assets/3a0dc3c8-68f1-4d72-b2e2-7fbe28fcb35f)
I have added media query for all width of devices
