### ISSUE TITLE
Alignment problem

### ISSUE THREAD

**Issue by supriyagaut** [ayush-that/FinVeda#288]
![Screenshot 2024-06-09 224229](https://github.com/ayush-that/FinVeda/assets/141560711/078e8cf8-2d2e-4722-97f5-b2740d376210)

**Comment by supriyagaut** [comment]
i am excited to contributing in this issue please assign me

**Comment by supriyagaut** [comment]
@deepeshmlgupta kindly added level

**Comment by deepeshmlgupta** [comment]
> @deepeshmlgupta kindly added level

level will be added as soon as you will create a pull request
