### ISSUE TITLE
Improve UI for blogs page and quiz page

### ISSUE THREAD

**Issue by Priyal208** [ayush-that/FinVeda#29]
Blogs page and quiz page is very plain and simple , kindly assign me to fix UI and make it more appealing! PS: I love working with UI and fixing it!
@ayush-that

**Comment by khushikunte** [comment]
I am khushi kunte .I am a frontend developer.I would like to work on these issue.plz assign me this .Under Gssoc;24.

**Comment by Hamsikakrishnan** [comment]
Hello, I am Hamsika Krishnan. I would like to work on the UI Can you assign this task to me under GSSOC24.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@Priyal208

**Comment by Yuvraj960** [comment]
@ayush-that Please assign this issue to me under GSSoC24

**Comment by harshcodesit** [comment]
Hi @techmannih
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the UI in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .

**Comment by sakshi261203** [comment]
Hi Ayush , Could you please assign this issue to me..

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.
