### ISSUE TITLE
Interactive Quiz Interface 

### ISSUE THREAD

**Issue by divyansh-2005** [ayush-that/FinVeda#290]
![image](https://github.com/ayush-that/FinVeda/assets/118552563/83a45bb7-c74f-4f2f-a91d-350e3f616a56)
Above is a sample design on new quiz interface. It will make user more Interactive while giving quiz.

**Comment by divyansh-2005** [comment]
I wish to improve design of current quiz. Please assign me this issue

**Comment by Agarwalvidu** [comment]
This issue has been already resolved. Thank you for collaborating, looking for more issues from your side.
