### ISSUE TITLE
FEATURE:Add scroll-up feature on main pages

### ISSUE THREAD

**Issue by Ashmitha2606** [ayush-that/FinVeda#2910]
### Feature Summary

Add scroll-up feature on main pages

### Description

Add scroll-up feature on main pages

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by sampadatiwari30** [comment]
@Ashmitha2606 already assigned.
