### ISSUE TITLE
[style]: Courses heading looks like over-lapping on search functionality!

### ISSUE THREAD

**Issue by veepanshu-kasana** [ayush-that/FinVeda#2911]
### What's the style idea?

We need to improve the spacing between both of them and properly align the search input and search button horizontally.

### Add screenshots

![issue6](https://github.com/user-attachments/assets/a330167b-1a8c-474f-8598-a0a731c742d5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by veepanshu-kasana** [comment]
@ayush-that I want to contribute to this project on this particular issue. Please assign it to me!

**Comment by sampadatiwari30** [comment]
@veepanshu-kasana no there is not issue.
