### ISSUE TITLE
Add "About Us" page/ Button in the Nav Bar

### ISSUE THREAD

**Issue by rohitinu6** [ayush-that/FinVeda#293]
**Feature Description :**

I would like to request the addition of a new "About Us" page to the FinVeda website. This page will include details about the project, its features, and its uses. The content should highlight the purpose and objectives of FinVeda, the key features that make it valuable, and the various ways it can be utilized by users.

**Use Case :**

The "About Us" page will provide users with a clear understanding of what FinVeda is and how it can benefit them. This is particularly useful for new users who may not be familiar with the project and are looking for a concise overview. It will also help in building trust and credibility by presenting the project's mission and vision.

**Benefits :**

- Enhanced User Understanding: Users will have a better grasp of the project's goals and features, which can lead to increased engagement.
- Increased Transparency: Providing detailed information about the project can build trust and transparency.
- Improved Navigation: Having an "About Us" page makes it easier for users to find essential information about the project without having to search through various sections of the website.
- Marketing and Outreach: A well-crafted "About Us" page can serve as a tool for promoting the project and attracting potential collaborators, users, and contributors.

**Add ScreenShots :**

![image](https://github.com/ayush-that/FinVeda/assets/113301503/49cd758e-e8ef-4d9e-8576-5196bfb36cb2)

**Please assign this issue to me under gssoc'24 label**

**Comment by Vibha17** [comment]
Hi I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

**Comment by KomalMaurya** [comment]
@Agarwalvidu Please assign this issue to me.....under GSSoC'24 !

**Comment by Agarwalvidu** [comment]
As no response is seen from previous contributor assigning this issue to you @KomalMaurya !

**Comment by Agarwalvidu** [comment]
Already done!
