### ISSUE TITLE
 [Enhancement]: Footer is not looking good.

### ISSUE THREAD

**Issue by theeayushkumar** [ayush-that/FinVeda#294]
1.Alignment and Spacing
2.Consistent Styling
3.Spacing Around Links

![image](https://github.com/ayush-that/FinVeda/assets/128235540/c81e1fca-8352-46fa-bd83-6c564c0aec36)

**Comment by deepeshmlgupta** [comment]
can you please give a sample idea of design of what you want to make

**Comment by Agarwalvidu** [comment]
As no response is seen from the contributor for so long I am closing this issue. Thank you for collaborating.
