### ISSUE TITLE
BUG: Footer does not follow the structure

### ISSUE THREAD

**Issue by Hemraj-7** [ayush-that/FinVeda#2955]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

BUG: Footer does not follow the structure in the mobile version.

![Screenshot 2024-11-07 170331](https://github.com/user-attachments/assets/45e35473-5c89-418c-a1d4-fadd476da6a1)

I want to work on this issue please assign me 
Thank you;

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by Hemraj-7** [comment]
Who is this Guy Every time he take my issue, this is not fair bro @LavkushSolanki

**Comment by Hemraj-7** [comment]
Hello @deepeshmlgupta this issue is not solved. also this pull #2966 is made extra issue

Check this -> 
![Screenshot 2024-11-07 230448](https://github.com/user-attachments/assets/62425d06-601b-4610-b627-988161fdaab7)

**Comment by Hemraj-7** [comment]
![Screenshot 2024-11-07 234402](https://github.com/user-attachments/assets/57482e74-4d71-41dc-996f-19929579fdb5)

**Comment by Hemraj-7** [comment]
I add less line of code but my code is made impact in the website.

**Comment by LavkushSolanki** [comment]
@Hemraj-7 you have a lot of badges i have none please support small developers

**Comment by Hemraj-7** [comment]
Yeah I will support you @LavkushSolanki !! but this is not a good way to contribute on opensource project. 
it has a process ->
1. first find the issue and create a issue if issue is not created.
2. second the project admin or other collaborator  will assign you
3. Then you go to contribute.

when i started then I was also doing contribution like you 😆
