### ISSUE TITLE
Automatically Comment on Pull Request Raise

### ISSUE THREAD

**Issue by thevijayshankersharma** [ayush-that/FinVeda#296]
This feature involves automatically closing related issues when a pull request (PR) is successfully merged into the project repository. By closing the associated issues upon PR merge, we streamline the issue management process, ensuring that resolved tasks are promptly marked as closed.

**Comment by deepeshmlgupta** [comment]
Already been done

**Comment by thevijayshankersharma** [comment]
@deepeshmlgupta There are other workflows missing to like comment issue or PR close, close old issues or PRs. If you need any of them, I would like to work on it.

**Comment by deepeshmlgupta** [comment]
okh, also automatically closing related issues when a pull request (PR)

**Comment by Agarwalvidu** [comment]
It is already resolved!
