### ISSUE TITLE
Rename sip.html to tools.html 

### ISSUE THREAD

**Issue by shivamm-verma** [ayush-that/FinVeda#30]
# Description:
- Renamed sip.html to tools.html for convenience and better accessing of files.
- changed "sip.html" to "tools.html" from all over the Code.

## Type:
Bug Fixes⚒️

# Screenshots:

## Before
![before sip html](https://github.com/ayush-that/FinVeda/assets/98605616/a404356f-b97f-437b-a33c-00bf14afbdb4)

## after
![after tools html](https://github.com/ayush-that/FinVeda/assets/98605616/55c068bb-abfa-464d-afc1-2a5d65f94e49)

**Comment by shivamm-verma** [comment]
Please assign me this Issue, so that I can start working on it. @ayush-that

**Comment by saurabh-dhakite** [comment]
@ayush-that Please assign me this issue so I can work on it.

**Comment by ayush-that** [comment]
Hi @shivamm-verma,
I understand your issue but I believe that it will create a lot of messup in the codebase. Please find some other issues to work on from the Issues tab. Hope you understand.
