### ISSUE TITLE
Inadequate Form Validation Feedback on Sign-in Form

### ISSUE THREAD

**Issue by aadii2504** [ayush-that/FinVeda#302]
# Issue Description:
When a user attempts to sign up without entering any data in the input fields, the form does not provide appropriate feedback to indicate that the fields are required. Instead of prompting the user to fill out the required fields, it displays  nothing which is confusing and does not accurately reflect the issue. This behavior can lead to user frustration and difficulty in understanding the validation requirements.

# Expected Behavior:
Upon clicking the sign-up button without entering any data in the input fields, the form should display a clear indication that the fields are required and prompt the user to fill them out before submission. This feedback ensures a better user experience by guiding users to provide the necessary information for successful form submission.

# Image 
![Screenshot 2024-06-14 183900](https://github.com/ayush-that/FinVeda/assets/119524954/e0e08a9d-2e63-489c-8eb4-8abaae3e5931)
Steps to Reproduce:

1. Visit the sign-in page.
2. Do not enter any data in the input fields.
3. Click the sign-in button.

# Current Behavior:

The form displays an error message "Name must contain only alphabets" when the user attempts to sign up without entering any data.
There is no indication that the input fields are required.
Proposed Solution:
Implement form validation that provides clear feedback to users when they attempt to submit the form without filling out the required fields. This feedback should include highlighting the required fields and displaying a message prompting the user to complete them before proceeding with the sign-up process.

# Solution Status:
The issue has been resolved locally, and the form now provides appropriate validation feedback when attempting to submit without filling out the required fields.

**Comment by Agarwalvidu** [comment]
This issue is already been solved. Thank you for contributing, looking for more issues from your end. For now I am closing this issue.
