### ISSUE TITLE
Responsive: Sign in and sign up option disappears on small screen and horizontal scroll is there on small screens 

### ISSUE THREAD

**Issue by Garimas10u** [ayush-that/FinVeda#303]
no sign in sign up option in mobile view and there is 
![Uploading Screenshot 2024-06-14 211957.png…]()
a horizontal scroll which can be easily fixed

**Comment by Garimas10u** [comment]
please assign me this issue as I would want to work on it

**Comment by Garimas10u** [comment]
Thank you for assigning me the issue

**Comment by Agarwalvidu** [comment]
As no update is shown by the contributor and the issue is already solved I am closing this issue!
