### ISSUE TITLE
FEATURE: Add a cursor trail effect & Favicon to INVESTMENT STRATEGY GAME page

### ISSUE THREAD

**Issue by neeru24** [ayush-that/FinVeda#3093]
### Feature Summary

Add a cursor trail effect & Favicon to INVESTMENT STRATEGY GAME page

### Description

Add a cursor trail effect & Favicon to INVESTMENT STRATEGY GAME page, creating a subtle, interactive visual trail that follows the user's cursor as they navigate the page.

### Additional Information

- [X] I have searched for existing feature requests
- [X] I am willing to help implement this feature
- [X] I can provide more details or clarification if needed

**Comment by gjrahul1** [comment]
Hello @neeru24,
I am G.J.Rahul from LinkedIn. It's wonderful we are working on the same project.

**Comment by neeru24** [comment]
> Hello @neeru24, I am G.J.Rahul from LinkedIn. It's wonderful we are working on the same project.

@gjrahul1 Oh, Glad to know that!
