### ISSUE TITLE
BUG: scroll button not Working on Contributors Page 

### ISSUE THREAD

**Issue by dipak2005** [ayush-that/FinVeda#3146]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

bottom to top scroll button was not working properly  on Contributors page  

### Steps to Reproduce

improvement of Js code for bottom to top Scroll button  

### Screenshots/Logs

Uploading Screen Recording 2024-11-09 214524.mp4…

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I can provide more details if needed

**Comment by deepeshmlgupta** [comment]
now its working
