### ISSUE TITLE
Feature Improvement

### ISSUE THREAD

**Issue by dsaikiran01** [ayush-that/FinVeda#317]
The user experience panel can be more better, I would like to fix the 
1. size issue of the testimonials which are irregular now
2. improve the hovering effects of the testimonials
3. smooth the back-to-top button transitions

![Screenshot (257)](https://github.com/ayush-that/FinVeda/assets/108150261/606ef3c2-d411-40e3-b3c7-16ab874df681)

I want to work on these issues.
Please assign me this issue under GSSoC'24.

**Comment by deepeshmlgupta** [comment]
Do recheck the website it is already been solved 
![image](https://github.com/ayush-that/FinVeda/assets/108192513/658c82db-1cd5-42f2-84ff-c17d2da11cb4)
