### ISSUE TITLE
[Enhancement] Overall improvement of Finance Tools sections.

### ISSUE THREAD

**Issue by VedaVarxha** [ayush-that/FinVeda#32]
**Description**
There are some issues to be addressed in the tools page:
- Incorrect labeling of maturity value and wealth gained.
  The value at maturity and gains should actually be reversed.
- Calculator takes invalid input.
- Improvement of styling and overall layout of the tools page.
- Redirection to appropriate pages from learn more button of financial blogs & finance tools

@ayush-that I would like to work on this issue under GSSOC'24. Please assign it to me.

**Comment by Harshitazz** [comment]
assign me

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@VedaVarxha

**Comment by Yuvraj960** [comment]
@ayush-that Please assign this issue to me under GSSoC24

**Comment by sakshi261203** [comment]
Hi Ayush , Could you please this issue to me..

**Comment by Agarwalvidu** [comment]
As PR is already closed I am closing this issue.
