### ISSUE TITLE
[Feat] : the quiz section is not interactive and user need to scroll too much for attending whole question.

### ISSUE THREAD

**Issue by VinayLodhi1712** [ayush-that/FinVeda#322]
i can make quiz section interactive and user can attempt one question at a time and submit it. Examples of interactive quizzes
![interactive](https://github.com/ayush-that/FinVeda/assets/135756009/8159845e-72f1-4e5f-b681-d0b6b5c43db1)

![interactive2](https://github.com/ayush-that/FinVeda/assets/135756009/a32fe9e0-9f23-4e61-a762-314a913c8ab9)

**Comment by Agarwalvidu** [comment]
This is already resolved?
