### ISSUE TITLE
BUG: Trends page is Doomed 

### ISSUE THREAD

**Issue by ayush-that** [ayush-that/FinVeda#3259]
### Preliminary Check

- [X] I have searched the existing issues
- [X] This issue is reproducible

### Bug Summary

All the widgets on the trends page are gone and I cannot find the PR which caused this. Can someone please fix that? It looks really bad.

### Steps to Reproduce

Just visit https://www.finveda.xyz/trends.html

### Screenshots/Logs

![{1E6C0317-EF8B-4E16-B318-597A8D32FEAF}](https://github.com/user-attachments/assets/75d35445-061c-4c76-9546-e040f5ff4f62)

### Additional Information

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue
- [ ] I can provide more details if needed

**Comment by Pragati1466** [comment]
I know I can resolve pls assign me

**Comment by Pragati1466** [comment]
@ayush-that
