### ISSUE TITLE
Title:  Hover Effect on Login/Register

### ISSUE THREAD

**Issue by Deepanshi-05** [ayush-that/FinVeda#326]
### Is your feature request related to a problem? Please describe.

May be!!

### Describe the solution you'd like.

I will add a hover effect on the Login/register which helps the user's interaction.

### Describe alternatives you've considered.

Add Hover Effect.

### Add any other context or screenshots about the feature request here.

![Screenshot (22)](https://github.com/ayush-that/FinVeda/assets/158538244/1f32b60a-14a4-4cd6-811f-c518d4ef2397)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GitNinja-bcd** [comment]
kindly add level also of this issue.

**Comment by Deepanshi-05** [comment]
Please assign label 1 or label 2 on this issue please.
