### ISSUE TITLE
[TYPO]: Quick Links instead of Quick Link in Footer Section

### ISSUE THREAD

**Issue by kashvi9** [ayush-that/FinVeda#337]
### What happened?

In the Footer of the webpage, the Quick Link section must be renamed to Quick Links.

Here's a Screenshot,
![image](https://github.com/ayush-that/FinVeda/assets/169376061/779405f5-8986-49b2-8d68-776c12d69957)

### How can we reproduce this bug?

Hey PA @ayush-that 
I can solve this typing error under GSSOC 24.
Thank you 

### Urgency (Optional)

None

**Comment by Agarwalvidu** [comment]
This issue is already been solved. Thank you for contributing, looking for more issues from your end. For now I am closing this issue.
