### ISSUE TITLE
Bug 🐞 : Chatbot is Only Present in Home Page Not in Other Pages

### ISSUE THREAD

**Issue by MastanSayyad** [ayush-that/FinVeda#339]
### What happened?

Hey @ayush-that and @deepeshmlgupta

The chatbot  is currently only available on the Home Page. To provide users with consistent access to the chatbot across the entire website, it is essential to add the chatbot to all pages.

![image](https://github.com/ayush-that/FinVeda/assets/101971980/c30e0916-57d5-4c0d-a482-ceacd6dde107)

![image](https://github.com/ayush-that/FinVeda/assets/101971980/759eafd9-7368-4cf8-833c-651d595434a2)

### How can we reproduce this bug?

1. Go to Home Page, Chatbot is present
2. Go to Pages Other than Home, Chatbot is missing

### Urgency (Optional)

High priority

**Comment by ayush-that** [comment]
We do not plan to add the chatbot to all pages.
Hence closing this issue.
