### ISSUE TITLE
[BUG]: offset() is undefined error in inspect mode

### ISSUE THREAD

**Issue by Ayush-may** [ayush-that/FinVeda#34]
## Define
there is a error in the offset , it is undefined , It can be solved by my changing some values in `main.js`

[Screencast from 11-05-24 05:37:00 PM IST.webm](https://github.com/ayush-that/FinVeda/assets/112775332/bfad2be3-883d-43bc-b879-efa5d0bd7c97)

## Steps to reproduce 
1. Go to website
2. Go to inspect Mode 
3. Open console mode
4. Scroll the window 
5. You can see the error in the error section

**Kindlly assign this issue to me under gssoc and add level label to this**

**Comment by Ayush-may** [comment]
i fixed this issue , assign me this issue under gssoc so i can make a PR

**Comment by ayush-that** [comment]
> i fixed this issue , assign me this issue under gssoc so i can make a PR

Hello @Ayush-may,
I am assigning this issue to you under gssoc.
Make sure the PR has no conflicts if possible.
