### ISSUE TITLE
[improvement] Changing Anime pfp to Actual Pfps

### ISSUE THREAD

**Issue by shivamm-verma** [ayush-that/FinVeda#35]
# Description:
- Changes Anime Pfp to Actual Pfps of the Team in the index.html

## Type:
Improvement✨

# Screenshots:

## Before
![before anime pic](https://github.com/ayush-that/FinVeda/assets/98605616/e9c5cd36-a904-4aeb-8529-63344e083079)

## After
![after actual pfps](https://github.com/ayush-that/FinVeda/assets/98605616/a664b975-1084-4ae9-b089-3114712837db)

**Comment by Ayush-may** [comment]
anime pfp looks good to me

**Comment by ayush-that** [comment]
Hello @Ayush-may,
I am closing this issue.
@manyaigdtuw would not agree to this.

**Comment by ayush-that** [comment]
> > Hello @Ayush-may, I am closing this issue. @manyaigdtuw would not agree to this.
> 
> @ayush-that they were cute, they should be preserved !!!!!!!!

Exactly.
That anime pfp has memories of our Naadaan days. <3

**Comment by manyaigdtuw** [comment]
> > > Hello @Ayush-may, I am closing this issue. @manyaigdtuw would not agree to this.
> > 
> > 
> > @ayush-that they were cute, they should be preserved !!!!!!!!
> 
> Exactly. That anime pfp has memories of our Naadaan days. <3

EXACTLYYYYYYYY, IT WAS NOT SUPPOSED TO BE CHANGED
