### ISSUE TITLE
[improvement]: text not in center

### ISSUE THREAD

**Issue by Ayush-may** [ayush-that/FinVeda#36]
![image](https://github.com/ayush-that/FinVeda/assets/112775332/e37014df-3709-4618-9766-5e4400bee19a)

This text is not at center of the screen ,

ik this is a small issue , assign this issue so i can start working !

**Comment by ayush-that** [comment]
Hello @Ayush-may
There is already an issue raised on fixing the styling of this page already so I am closing this issue.
