### ISSUE TITLE
Title:  adding a feedback section

### ISSUE THREAD

**Issue by solanki505** [ayush-that/FinVeda#361]
### Is your feature request related to a problem? Please describe.

It will help to know the user experience and feedback

### Describe the solution you'd like.

adding a responsive feedback site

### Describe alternatives you've considered.

adding a modal feedback and adding a section showing the users review about this site

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-that** [comment]
Do it @solanki505 
:)

**Comment by aslams2020** [comment]
@ayush-that ,Could you Please assign me this issue. As the contributor has not done yet.
