### ISSUE TITLE
Adding social icons in the footer 

### ISSUE THREAD

**Issue by suhanigupta23** [ayush-that/FinVeda#365]
### Is your feature request related to a problem? Please describe.

Adding social icons in the footer  of all the webpages 

### Describe the solution you'd like.

<img width="537" alt="Screenshot 2024-06-25 at 1 47 44 PM" src="https://github.com/ayush-that/FinVeda/assets/144280247/8ce28e42-8344-403a-a513-e22f4ba03843">

### Describe alternatives you've considered.

Adding social icons will enhance the look of footer.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
This issue is already been solved. Thank you for contributing, looking for more issues from your end. For now I am closing this issue.
