### ISSUE TITLE
Title: Adding animated cursor

### ISSUE THREAD

**Issue by mehrun171** [ayush-that/FinVeda#368]
### Is your feature request related to a problem? Please describe.

we can add a animated cursor customized which can make the UI more effective and using cursor fun

### Describe the solution you'd like.

Animated Cursor

### Describe alternatives you've considered.

nth

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aradhyajha** [comment]
@ayush-that sir.. i want to work on this issue please assigned this issue to me

**Comment by mehrun171** [comment]
Thq for assigning me to the task @deepeshmlgupta ... currently I'm having semester exams ..so i would try my best to complete the task as soon as possible

**Comment by Agarwalvidu** [comment]
This issue is already been solved. Thank you for contributing, looking for more issues from your end. For now I am closing this issue.
