### ISSUE TITLE
[style]: LOGIN AND SIGNUP PAGE

### ISSUE THREAD

**Issue by AbheetHacker4278** [ayush-that/FinVeda#369]
### What's the style idea?

We need to improve  in the Basic Login Pages .

@ayush-that your LOGIN AND SIGNUP page is good but your website might need some of my hands , so i can make your UI more presentable and Asthetic and Elegant , I hope You assign this Issue to Me under Gssoc24.

### Add screenshots

Add screenshots

### BEFORE
![image](https://github.com/ayush-that/FinVeda/assets/114290748/9d27d846-13b8-49e4-b26d-ed00dacd6833)

### (MY WORK)

https://github.com/ayush-that/FinVeda/assets/114290748/708e93af-e4e8-471b-a769-70024279e7b3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Aradhyajha** [comment]
Hii @ayush-that sir.. i want to work on this issue please assigned  this to me .. i will solve this issue as soon as possible for me

**Comment by AbheetHacker4278** [comment]
@Aradhyajha i am working on this issue

**Comment by Aradhyajha** [comment]
Ok ok

**Comment by Agarwalvidu** [comment]
This issue is already been solved. Thank you for contributing, looking for more issues from your end. For now I am closing this issue.
