### ISSUE TITLE
Title: Adding password visibility toggle in login and signup

### ISSUE THREAD

**Issue by Rohitha-pudu** [ayush-that/FinVeda#370]
### Is your feature request related to a problem? Please describe.

password is not visible to check it its correct /not

### Describe the solution you'd like.

Adding password visibility toggle in login and signup

### Describe alternatives you've considered.

Adding password visibility toggle in login and signup

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
This issue is already been solved. Thank you for contributing, looking for more issues from your end. For now I am closing this issue.
