### ISSUE TITLE
Title: Quiz result is messy

### ISSUE THREAD

**Issue by Rohitha-pudu** [ayush-that/FinVeda#371]
### Is your feature request related to a problem? Please describe.

the quiz result is messy ,with no gap between content and showing  wrong answers in red color may have better UX than showing all the answers in same way

### Describe the solution you'd like.

adding spacing between answers and making incorrecct answers differ from right by showing it in different color

### Describe alternatives you've considered.

n/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Already done!
