### ISSUE TITLE
Title:  Add bright & dark mode toggle button

### ISSUE THREAD

**Issue by ananyag309** [ayush-that/FinVeda#380]
### Is your feature request related to a problem? Please describe.

Yes, the absence of a dark/bright mode toggle can lead to eye strain for users who prefer a specific mode based on their lighting conditions or personal preference. Implementing this feature enhances user experience by allowing customization and ensuring comfort during both day and night usage.

### Describe the solution you'd like.

I would like a toggle button that allows users to switch between dark and bright modes seamlessly. This button should be easily accessible on the webpage and should remember the user's preference across sessions. The dark mode should feature a darker color scheme that reduces glare, while the bright mode should offer a lighter, more vibrant color scheme suitable for well-lit environments.

### Describe alternatives you've considered.

1. **Auto-Adjust Mode Based on System Settings**: Instead of a manual toggle, the webpage could automatically switch between dark and bright modes based on the user's system preferences. This ensures the mode matches the user's overall system theme without needing manual adjustment.

2. **Time-Based Mode Switching**: Implement a feature where the mode switches automatically based on the time of day (e.g., bright mode during the day and dark mode at night). This provides a dynamic experience but might not always align with individual user preferences.

3. **No Mode Switching**: Stick with a single mode (either dark or bright) for simplicity. This avoids the complexity of implementing and maintaining multiple themes but doesn't offer the customization that some users may prefer.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
This issue can't be solved because this website doesn't support that. Thank you for contributing, looking for more issues from your end. For now I am closing this issue.
