### ISSUE TITLE
BUG : Mutual fund investment calculator accepts invalid inputs 

### ISSUE THREAD

**Issue by CoderGirl2844** [ayush-that/FinVeda#382]
### What happened?

it accepts negative values 

### How can we reproduce this bug?

![Screenshot 2024-07-03 023722](https://github.com/ayush-that/FinVeda/assets/155231566/a6227f45-9579-4f32-875f-7a330aebaf59)
Please assign this issue to me

### Urgency (Optional)

High priority

**Comment by CoderGirl2844** [comment]
@deepeshmlgupta please assign the level label too

**Comment by deepeshmlgupta** [comment]
Level will be assigned as soon as you raise the Pull Request
