### ISSUE TITLE
Title: Add Content in Footer

### ISSUE THREAD

**Issue by theeayushkumar** [ayush-that/FinVeda#386]
### Is your feature request related to a problem? Please describe.

Navigation Challenges: Users struggle to find important links and information.
Low User Engagement: Users aren't engaging with the site beyond the initial visit.
Lack of Professionalism: The site appears unprofessional or incomplete, reducing trust.
Legal Compliance: Missing visible links to legal documents like privacy policies.
Poor Mobile Experience: Navigation is difficult for mobile users, affecting usability.

### Describe the solution you'd like.

Important Links: Quick links to key pages (e.g., Privacy Policy, Terms of Service).
Contact Information: Email, phone number, and address.
Engagement Elements: Social media links and a newsletter signup form.
Company Information: About us, mission statement, or company details.
Mobile Optimization: Ensure the footer is user-friendly on mobile devices.

### Describe alternatives you've considered.

Header Navigation: Expanding the header to include more links and information.
Sidebar Widgets: Adding widgets for contact info, social media, and quick links in a sidebar.
Pop-up Modals: Using pop-ups to display important information and engage users.
Dedicated Contact Page: Creating a separate, detailed contact and information page.
Sticky Footer: Implementing a sticky footer that remains visible as users scroll.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/ayush-that/FinVeda/assets/128235540/bc1d5420-659b-475e-b031-6aaf86a0be95)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by newcodergit** [comment]
Please assign me this issue.

**Comment by Agarwalvidu** [comment]
Thank you for contributing, looking for more issues from your end. For now I am closing this issue as PR is closed.
