### ISSUE TITLE
Title: Add login with google option 

### ISSUE THREAD

**Issue by heli0707** [ayush-that/FinVeda#387]
### Is your feature request related to a problem? Please describe.

To add a "Login with Google" option, integrate the Google Sign-In API into your application and configure OAuth 2.0 credentials through the Google Developer Console. This allows users to authenticate using their Google accounts seamlessly.

### Describe the solution you'd like.

![ls](https://github.com/ayush-that/FinVeda/assets/95361125/89ec6e0e-0674-4fe2-8e98-f4deba80e6b6)

something looks like this one 

### Describe alternatives you've considered.

Facebook Login: Integrating Facebook Login for users to authenticate with their Facebook accounts.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by newcodergit** [comment]
Please assign me this issue.

**Comment by Khushi-Pushkar** [comment]
@deepeshmlgupta  @Agarwalvidu  please assign this issue to me
