### ISSUE TITLE
[style]: Add some animations to the text.

### ISSUE THREAD

**Issue by gauribahuguna21** [ayush-that/FinVeda#390]
### What's the style idea?

We need to improve the styling and add some animation to the text.

### Add screenshots

below is just a reference.

https://github.com/ayush-that/FinVeda/assets/120307146/81889aa9-ded8-4549-8d1b-b0e984a0aaa5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by deepeshmlgupta** [comment]
not needed
