### ISSUE TITLE
Title:  to add animation to login/register button

### ISSUE THREAD

**Issue by Kavita1928** [ayush-that/FinVeda#393]
### Is your feature request related to a problem? Please describe.

if you point on login/register button then no visible response is seen 

### Describe the solution you'd like.

I would like to add animation in login/register button 

### Describe alternatives you've considered.

![Screenshot 2024-07-06 181807](https://github.com/ayush-that/FinVeda/assets/151850926/121d704a-4cac-43d8-a79a-362dcc4dc552)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
This issue has already been resolved, for the same reason I am closing this issue. Thank you for collaborating!
