### ISSUE TITLE
misalignment and bug

### ISSUE THREAD

**Issue by kairveeehh** [ayush-that/FinVeda#4]
@ayush-that 
alignment disrupted and the middle card is always selected as a bug without hover 
## please assign under gssoc'24
![Screenshot 2024-05-10 173434](https://github.com/ayush-that/FinVeda/assets/145572028/5abad651-a36f-4e02-bfc5-8c781ba6bb7c)

**Comment by Abhishek-0899** [comment]
Please assign this issue to me under gssoc'24

**Comment by ayush-that** [comment]
Hello @kairveeehh,
I am assigning this issue to you and @Abhishek-0899 under gssoc. All the best.

Hi! @Abhishek-0899, This issue has been assigned, please raise a new issue with a bug fix/improvement. Thanks!

**Comment by ayush-that** [comment]
@kairveeehh no update since a week?
I'm closing this issue.
