### ISSUE TITLE
Quiz Section : Clicking on the answer of the quiz is not user friendly

### ISSUE THREAD

**Issue by SiddharthaArepalli** [ayush-that/FinVeda#40]
[
![Screenshot 2024-05-11 202656](https://github.com/ayush-that/FinVeda/assets/140429954/d99b048c-4b5f-4d4f-a73c-7b53fa922eee)
]

**Comment by SiddharthaArepalli** [comment]
@ayush-that assign me this under gssoc'24 I will the hover effect while clicking on the option

**Comment by ayush-that** [comment]
Hello @SiddharthaArepalli,
I have assigned this issue to you under gssoc.
All the best.

**Comment by SiddharthaArepalli** [comment]
@ayush-that   I have made the pull request merge it !!

**Comment by Vaishnavi2445** [comment]
Hello! @ayush-that 
 I'm enthusiastic about contributing to your project by improving the quiz experience. Introducing voice navigation could make selecting quiz answers more user-friendly. Would you consider giving me the chance to contribute to GSSOC?
 
 Thank you!

**Comment by hollermay** [comment]
Hey @ayush-that I can work on this feature as we can use some libraries like tailwind and all. You can see my profile here-https://portfolio-2-0-six-pi.vercel.app/

And I made a quiz app two weeks back you can check that too -https://hollermay.github.io/Quizco/

**Comment by kalyanikhushi** [comment]
![Screenshot 2024-05-14 110126](https://github.com/ayush-that/FinVeda/assets/159093860/2a940d53-b403-4b14-ac3b-4913e76ae750)

**Comment by Agarwalvidu** [comment]
This is already done. For the same reason I am closing this issue. Thank you for contributing, looking for more issues from your side.
