### ISSUE TITLE
[style]: Addition of Animated cursor in the website.

### ISSUE THREAD

**Issue by HishitaGupta** [ayush-that/FinVeda#403]
### What's the style idea?

We need to improve  the styling of cursor.

### Add screenshots

https://github.com/ayush-that/FinVeda/assets/159264060/05023eb5-d0d5-462b-885e-706e5600e28d

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
This issue has already been resolved, for the same reason I am closing this issue. Thank you for collaborating!
