### ISSUE TITLE
[Bug Title here] : Missing of contact us icons in some Pages

### ISSUE THREAD

**Issue by GAVINESHWAR** [ayush-that/FinVeda#407]
### What happened?

In the footer section at contact us container the icons of mail, website and address  are present in some pages but missing in another pages like blog, tools , Trends and more.

### How can we reproduce this bug?

I would like to add icons to the contact us which are missing, adding these icons to all pages makes bugs about the missing icon.

### Desktop Information (Optional)

![image](https://github.com/ayush-that/FinVeda/assets/124431955/baa469e9-da4a-4033-afea-d2bdbce6bd73)
Here present(Home Page)
![image](https://github.com/ayush-that/FinVeda/assets/124431955/30d762b1-6c85-4da2-9e89-9d10980689ce)
here missing (Trends page)

![image](https://github.com/ayush-that/FinVeda/assets/124431955/de4076f1-5055-4355-8d48-b50fd43b71ec)
here missing(Blogs page)

![image](https://github.com/ayush-that/FinVeda/assets/124431955/4a9d4b3c-1937-44bd-a14f-79fb3f823d82)
here also missing(tools page)

@ayush-that , assign me this issue make contribution to the project.

Thank you

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
This issue has already been resolved, for the same reason I am closing this issue. Thank you for collaborating!
