### ISSUE TITLE
Title: Add User Testimonials Section to Increase Credibility

### ISSUE THREAD

**Issue by Swapnilden** [ayush-that/FinVeda#413]
### Is your feature request related to a problem? Please describe.

Users often seek reassurance and credibility before engaging with a service. The current website lacks user testimonials, which can provide social proof and build trust with potential users.

### Describe the solution you'd like.

Add a section that features user testimonials to the existing `About` component. This section will include real feedback from users, showcasing their positive experiences with FinVeda. It will help new users feel more confident about trying the service.

### Describe alternatives you've considered.

- Displaying ratings and reviews from third-party platforms.
- Featuring case studies or success stories in a dedicated section.
- Including video testimonials instead of written ones.

### Add any other context or screenshots about the feature request here.

No additional context or screenshots are provided at this time. However, images of users can be used to enhance the visual appeal of the testimonials section.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
This section already exists in this website. Thank you for collaborating, looking for more issues from your side.
