### ISSUE TITLE
➕Enhancement: Adding Interactive Smooth "Hover Effects" to The Links in Footer.

### ISSUE THREAD

**Issue by aslams2020** [ayush-that/FinVeda#415]
### What's the style idea?

Hey @deepeshmlgupta and @ayush-that 

I want to enhance the Footer in the website **by adding "more styled", "smooth", and "interactive hovering effects" to the footer links.** 
**Additionally**, This update will **apply to the Footer of Each Page on the website** to ensure a consistent and engaging user experience.

![image](https://github.com/ayush-that/FinVeda/assets/131389695/d3a18d9d-49f9-4e2f-b0a8-40b239449cc4)

Please assign this issue to me under GSSoC'24.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by aslams2020** [comment]
@deepeshmlgupta

**Comment by Sagar-03** [comment]
![Home - FinVeda - Google Chrome 7_16_2024 3_01_21 PM](https://github.com/user-attachments/assets/a4b29add-3452-4ce1-be36-a6c74a4b7181)
Hey @ayush-that this footer can be seen more interatice by adding some effects into it as hover effect and pop-up effect 
kindly assign it to me so that i can make it done under GSSOC.
Hope to work with you.

**Comment by aslams2020** [comment]
@Agarwalvidu I want to work on this issue.

**Comment by deepeshmlgupta** [comment]
@aslams2020 can you please elaborate more about your idea

**Comment by aslams2020** [comment]
@deepeshmlgupta Currenty the Links in the footer have a decent hovering effect...
My idea is to Add smooth transitional effect on hovering it, for ex, on hovering there will be a line from left to right etc.
