### ISSUE TITLE
New Tool: Adding a GST calculator in tools

### ISSUE THREAD

**Issue by vidhiisaxena** [ayush-that/FinVeda#416]
### Is your feature request related to a problem? Please describe.

Everything that you purchase, be it a product or a service, is taxed under the GST amount. It’s an advantage to know how much tax is to be paid for the products used. That’s where an Indian GST calculator can be useful. Hence to improve literacy through website, it must have a GST calculator.

### Describe the solution you'd like.

1. GST tax calculator provides with an accurate estimate of the amount of tax you have to pay.
2. It helps in saving time for the calculation of GST.
3. It eliminates the chances of any fraudulent activities if you are an aware consumer who knows his/her taxes.

### Describe alternatives you've considered.

Alternatives would be posting blogs about GST and how to calculate it for the knowledge of users.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by vidhiisaxena** [comment]
@ayush-that Kindly assign me this issue under GSSOC

**Comment by vidhiisaxena** [comment]
This will be a great addition to your existing set of tools. FinVeda will benefit from it as:

- Understanding GST: A GST calculator helps users understand how GST is applied to goods and services. It demonstrates the practical implications of tax policies in everyday transactions.
- Business Tool: For small business owners and freelancers, a GST calculator aids in accurate invoicing and pricing of goods and services.
- Clarity in Pricing: It provides clarity and transparency in pricing, helping consumers see the exact tax amount they are paying.
- Interactive Tool: An interactive GST calculator can enhance user engagement on a financial literacy website, making learning about taxes more engaging and less daunting.

**Comment by Agarwalvidu** [comment]
Go ahead! @vidhiisaxena
