### ISSUE TITLE
Add Commenting System for Blog Posts

### ISSUE THREAD

**Issue by Shreyasaraf01** [ayush-that/FinVeda#419]
Description:
Develop a feature that enables users to comment on blog posts within the FinVeda platform.

Requirements:

Front-End:
Build UI components to display comments and a form for new comment submissions.
Utilize React (or another front-end framework).
Ensure the design is responsive for both mobile and desktop users.

Back-End:
Develop API endpoints for adding (POST /comments) and retrieving comments (GET /comments/:postId).
Use Node.js and Express.js for server-side development.
Implement secure authentication and authorization (e.g., using Passport.js or JWT).

Database:
Create a schema to store comments with references to users and blog posts using MongoDB (or another database).

**Comment by Agarwalvidu** [comment]
Update? @Shreyasaraf01
