### ISSUE TITLE
[style]: Change Font

### ISSUE THREAD

**Issue by EpicNesh26** [ayush-that/FinVeda#423]
### What's the style idea?

I would like to suggest changing the font used in the project from Poppins to Inter. The Inter font offers improved readability and a more modern look that could enhance the overall user experience.

Proposed Changes:

Replace all instances of the Poppins font with the Inter font in our CSS files.
Update any relevant documentation or references to the Poppins font to reflect this change.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
@EpicNesh26 We don't want to change the font, thank you for taking time. We would like more issues from your end. For now I am closing this issue.
