### ISSUE TITLE
The feedback comment button is only present in Home page

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [ayush-that/FinVeda#426]
### What happened?

Hey @ayush-that and @deepeshmlgupta 

The feedback comment button is only present in Home page

![image](https://github.com/ayush-that/FinVeda/assets/163530398/8ff41634-f1b1-4ae8-8ca9-71690fa76b73)

![image](https://github.com/ayush-that/FinVeda/assets/163530398/86906958-acc6-42ca-971b-3bf7d1d641a2)

Could you please assign this issue to me under GSSOC24?

### How can we reproduce this bug?

Check the feedback button in other pages

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
@RadhikaMalpani1702 It is also not working now please check what is the issue with this, also work on this issue.

**Comment by Agarwalvidu** [comment]
@RadhikaMalpani1702 Assigning this to you.
