### ISSUE TITLE
Title:  Make Quiz Section Attractive.

### ISSUE THREAD

**Issue by zalabhavy** [ayush-that/FinVeda#431]
### Is your feature request related to a problem? Please describe.

**This website have not proper UI for Quiz.**

### Describe the solution you'd like.

https://www.loom.com/share/bde4386fd8144938bae991147e919ca2

**I will keep quiz same but use this UI.
This very attractive.**

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by zalabhavy** [comment]
@deepeshmlgupta Can You please assign me this task !

Thank You !

**Comment by Agarwalvidu** [comment]
@zalabhavy 
This issue is already assigned to someone else. Please look more into the project and raise the issue again if you find one. Thank you for your time.
