### ISSUE TITLE
Title:  Adding hovering and border effects to experience cards

### ISSUE THREAD

**Issue by GAVINESHWAR** [ayush-that/FinVeda#432]
### Is your feature request related to a problem? Please describe.

In the main page and users sharing there experience cards , I would like to add the hovering and border effects.

### Describe the solution you'd like.

Adding the hovering effects and border effects  makes better users experience and user interface.

### Describe alternatives you've considered.

Its is an better feature for this section

### Add any other context or screenshots about the feature request here.

![image](https://github.com/ayush-that/FinVeda/assets/124431955/20808a58-5df8-4c8a-b349-e65d2bc38af4)

Adding hovering effects to these cards make better interface.

@ayush-that  and @deepeshmlgupta , assign me this issue to make contribution make contribution to the project.

Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
@GAVINESHWAR Can you please elaborate what hover effects you want to add?

**Comment by GAVINESHWAR** [comment]
> @GAVINESHWAR Can you please elaborate what hover effects you want to add?

![image](https://github.com/user-attachments/assets/56952c2d-5c5e-4725-84b2-df91c33a5bf2)

@Agarwalvidu ,
These kind of hovering and border effects I would like to add to those cards make better user interface and user experience.

Thank you

**Comment by Agarwalvidu** [comment]
Okay go ahead!
