### ISSUE TITLE
Title:  Adding the new Saving calculator in tools page

### ISSUE THREAD

**Issue by GAVINESHWAR** [ayush-that/FinVeda#433]
### Is your feature request related to a problem? Please describe.

Savings Calculator
Purpose: Helps determine how much you need to save to reach a financial goal.
Inputs: Savings goal, current savings, time period, interest rate.

### Describe the solution you'd like.

Adding these calculator make users to about to learn financial awareness.

### Describe alternatives you've considered.

This calculator will consider the future value of money based on an interest rate, using the formula for the future value of a series of payments (annuities).

### Add any other context or screenshots about the feature request here.

![image](https://github.com/ayush-that/FinVeda/assets/124431955/8c2a8c5e-3036-47e0-a3ab-f96077b59768)

adding this calculator makes better feature to the tools page.

@ayush-that  and @deepeshmlgupta , assign me this issue to make contribution to the project.

Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Assigning this to you! @GAVINESHWAR 
Please make sure to sync your fork once.
