### ISSUE TITLE
Title: Direct link to chatbot was missing on clicking Chat with ArthaSathi

### ISSUE THREAD

**Issue by supremeashu** [ayush-that/FinVeda#435]
### Is your feature request related to a problem? Please describe.

I'm frustrated when i click on the Chat with ArthaSathi in the home page as it is not directly linked to the chat bot.
I shows an alert to go through the bottom right button.
<img width="813" alt="image" src="https://github.com/ayush-that/FinVeda/assets/145740067/1730f506-38a4-4a19-b881-7a96cddb5140">

### Describe the solution you'd like.

it can be achieved by simply correcting the onclick function 

### Describe alternatives you've considered.

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
@supremeashu This is done for some reason so we can not assign this as of now. So I am closing this issue. Please look for something else. Thank you for taking your time.
