### ISSUE TITLE
[style]: Quiz page

### ISSUE THREAD

**Issue by Khushi-Pushkar** [ayush-that/FinVeda#439]
### What's the style idea?

On quiz page after submitting the quiz, the UI can be better, also an exciting 
emoji or picture of congratulations can be added

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Assigning this to you !
Please work only to attach the congratulations picture or message. As other contributors are working on UI enhancement.
