### ISSUE TITLE
[style]: Fashionable cursor 

### ISSUE THREAD

**Issue by Khushi-Pushkar** [ayush-that/FinVeda#440]
### What's the style idea?

Fashionable cursor can be used on trends page

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
This is already assigned to Sagar. So closing this issue.
