### ISSUE TITLE
Responsiveness Issue - There is an empty space on right side of webpage in Mobile View.

### ISSUE THREAD

**Issue by vishanurag** [ayush-that/FinVeda#441]
### What happened?

 - There is an empty space on right side of webpage in Mobile View.
 - This issue/bug is on Index page, Blog page & Tools page.

## _Video_

https://github.com/user-attachments/assets/1c7eb0ad-f6bb-4636-b706-8d93364e25a4

### How can we reproduce this bug?

- There should not be any empty space on right side of webpage in Mobile View.
- I can fix this issue using Media Queries in CSS & Bootstrap classes.

### Urgency (Optional)

High priority

**Comment by vishanurag** [comment]
@deepeshmlgupta please assign this issue to me under GSSoC'24

**Comment by Agarwalvidu** [comment]
Assigning it to you. But please first working with Tools Page! @vishanurag
