### ISSUE TITLE
Title: Custom Cursor 

### ISSUE THREAD

**Issue by SagarRathore1** [ayush-that/FinVeda#442]
### Is your feature request related to a problem? Please describe.

I would like to add a custom cursor to the website .

### Describe the solution you'd like.

I would like to add a custom cursor to the website which will make website look more attractive and professional.

### Describe alternatives you've considered.

I can add cursor animation to the cursor animation too if required.

### Add any other context or screenshots about the feature request here.

https://github.com/user-attachments/assets/8aa0f5d9-4707-471e-835c-a8237287a424

https://github.com/user-attachments/assets/6044231a-fc99-43f7-967f-0a269ff356fb

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Assigning this issue to you @SagarRathore1
