### ISSUE TITLE
[style]: Quiz Page UI Improvement

### ISSUE THREAD

**Issue by KomalMaurya** [ayush-that/FinVeda#445]
### What's the style idea?

Quiz Page UI can be more interactive like the below Screenshot of my work!!

Name : Komal Maurya
Role :  Contributor in GSSoC'24
GitHub Profile Link : https://github.com/KomalMaurya

### Add screenshots

![image](https://github.com/user-attachments/assets/1ecaaaac-7db9-4738-bc43-193fc13ea4bc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Assigning this issue to you @KomalMaurya

**Comment by Agarwalvidu** [comment]
As this issue is already resolved I am closing this issue.
