### ISSUE TITLE
Footer issue in Blogs page

### ISSUE THREAD

**Issue by MuraliDharan7** [ayush-that/FinVeda#447]
### What happened?

The footer does not appear properly as home page in Blogs.

### How can we reproduce this bug?

Should be made same as home page.

![image](https://github.com/user-attachments/assets/ef636714-ca39-4143-b0de-91b143598627)

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
Assigning it to you!
Please check in the mobile view also.

**Comment by Agarwalvidu** [comment]
Now this issue is resolved!
