### ISSUE TITLE
[style]: Improvement in Footer tab

### ISSUE THREAD

**Issue by SaLTanaTuruz** [ayush-that/FinVeda#448]
### What's the style idea?

We need to improve  the footer tab by adding icons in it so it will look attractive

### Add screenshots

Add screenshots
![GSSOC](https://github.com/user-attachments/assets/c1530f45-6295-42b8-b707-5c75088bbedf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
@SaLTanaTuruz Icons are there in footer, please look into something else.
