### ISSUE TITLE
[style]: Changing the UI of Tools form

### ISSUE THREAD

**Issue by Vedanshimishra** [ayush-that/FinVeda#450]
### What's the style idea?

improving the UI of the tools form
Kindly assign this project to me under Gssoc'24

### Add screenshots

![image](https://github.com/user-attachments/assets/dcaf9985-b197-4eed-98df-412f6527393a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Assigning this to you!
@Vedanshimishra
