### ISSUE TITLE
Adding arrows in users section

### ISSUE THREAD

**Issue by Jasleen1210** [ayush-that/FinVeda#452]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/28719d8b-9936-4ff5-9507-2314bccef0a9)
There are no arrows to navigate the user review carousel, which makes it harder for user to view all the cards properly

### Describe the solution you'd like.

Id like to add arrow buttons to both sides of the carousel with proper functionality 

### Describe alternatives you've considered.

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Assigning! @Jasleen1210
