### ISSUE TITLE
Title: Color change of login /Register tab on hovering on it

### ISSUE THREAD

**Issue by palak1008jain** [ayush-that/FinVeda#454]
### Is your feature request related to a problem? Please describe.

Login tab does not show any changes when hovering whereas tools , blogs and other shows underline on hovered.

### Describe the solution you'd like.

i would like to change it to colorless when cursor is on it.

### Describe alternatives you've considered.

I have also considered giving uniform style to login tab like home , tools,etc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Assigning! @palak1008jain

**Comment by palak1008jain** [comment]
pr merged #475
