### ISSUE TITLE
Title: Add Contributor page in footer's link

### ISSUE THREAD

**Issue by zalabhavy** [ayush-that/FinVeda#456]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/4860d146-fc3f-42fd-b9a0-ff8449cd2c05)

In this we can add Contributor to dedicate their efforts.

### Describe the solution you'd like.

I will make one page for Contributor and add link in footer.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by zalabhavy** [comment]
@deepeshmlgupta @Agarwalvidu Please assign me this task !

Thank You !

**Comment by deepeshmlgupta** [comment]
@zalabhavy 
Make sure the theme of the page should be same as that of the website
