### ISSUE TITLE
[Bug Title here] Fix margin between chatbot and scroll to top button and add hover effects on INVESTING Expert's views/like/comment.

### ISSUE THREAD

**Issue by zalabhavy** [ayush-that/FinVeda#457]
### What happened?

![image](https://github.com/user-attachments/assets/f12a88f0-65aa-43f6-aae1-76b2f9fae837)

I will give margin top to scroll to top button and give hover effects on views/like/comment.

### How can we reproduce this bug?

NA

### Desktop Information (Optional)

NA

### Urgency (Optional)

Medium priority

**Comment by zalabhavy** [comment]
@deepeshmlgupta @Agarwalvidu Please assign me this task !

Thank You !

**Comment by Agarwalvidu** [comment]
Go ahead! @zalabhavy
