### ISSUE TITLE
Title: Adding Feedback form

### ISSUE THREAD

**Issue by TBorundia** [ayush-that/FinVeda#459]
### Is your feature request related to a problem? Please describe.

Users currently have no direct way to provide feedback on the website. This makes it difficult to gather user opinions, suggestions, or identify issues they might be experiencing.

### Describe the solution you'd like.

I would like to add a feedback form to the website where users can easily submit their feedback, suggestions, or report any issues. This form will include fields such as name, email, feedback type (e.g., suggestion, issue, general feedback), star rating and a text area for detailed feedback.

### Describe alternatives you've considered.

Adding a feedback form will improve the project by:
Providing a direct channel for users to communicate their thoughts and issues.
Helping to identify and fix issues faster based on user input.
Gathering suggestions to improve the user experience and functionality of the website.
Enhancing user engagement and satisfaction by showing that their feedback is valued.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by TBorundia** [comment]
@deepeshmlgupta @Agarwalvidu Please assign this issue to me under GSSoC'24.
Thank You!

**Comment by Agarwalvidu** [comment]
@TBorundia I got the point that you want to add a feedback form but where that form will be submitted? Like will you work on backend?

**Comment by TBorundia** [comment]
@Agarwalvidu Mam,
As I am fronted developer I can add form on fronted part with UI, validation and pop up submission.
But If possible I can try for backend part.
So can you assign the fronted part development of it to me.

**Comment by Agarwalvidu** [comment]
@ayush-that This needs your inputs, if you wanna add it or not?

**Comment by Agarwalvidu** [comment]
As backend is not available for our website and there is no point for feedback page without it, I am closing this issue!
