### ISSUE TITLE
Duplicate Message Icons

### ISSUE THREAD

**Issue by RohithChitrada** [ayush-that/FinVeda#463]
### What happened?

On small screens, two message icons are displayed, creating confusion in the user interface.
![Screenshot 2024-07-14 110527](https://github.com/user-attachments/assets/232be58f-3fea-4351-a581-cb1d188bd7f8)

### How can we reproduce this bug?

1. Open the application in a web browser.
2. Navigate to the section where the message icons are displayed.
4. Observe the icons.

### Urgency (Optional)

None

**Comment by pranay911** [comment]
can you please assign this issue to me, I have already made changes in my local.
