### ISSUE TITLE
[style]: Designing the Tools pages

### ISSUE THREAD

**Issue by ayush-848** [ayush-that/FinVeda#466]
### What's the style idea?

We need to improve  the whole body

### Add screenshots

![image](https://github.com/user-attachments/assets/8ff7df8c-2f92-4ce9-89d7-47253c725f3f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Please sync your fork once it's already done. Thank you @ayush-848
