### ISSUE TITLE
Title: Adding a 'Latest News' part

### ISSUE THREAD

**Issue by ayush-848** [ayush-that/FinVeda#467]
### Is your feature request related to a problem? Please describe.

No it will be an enhancement

### Describe the solution you'd like.

it will have the latest important finance and economy news 

### Describe alternatives you've considered.

We can add link to redirect user to another website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
@ayush-848 We already have the similar section. For the same reason I am closing this issue if you had any other things in your minds please feel free to open more issues. Thank you for taking your time.
