### ISSUE TITLE
Title: Adding of a mode toggle

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#469]
### Is your feature request related to a problem? Please describe.

Many users prefer websites to be in Dark mode, but currently the website has no way to change to dark mode.

### Describe the solution you'd like.

A toggle button like the following will be intuitive for users to toggle mode to their preference.
![image](https://github.com/user-attachments/assets/ca0459eb-6ef9-46e2-bfef-c73bb0062b61)
![image](https://github.com/user-attachments/assets/9182b488-bb55-4239-8c1f-811e4deef9bf)

### Describe alternatives you've considered.

None

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @deepeshmlgupta please assign this issue to me under GSSoC 2024

**Comment by Agarwalvidu** [comment]
Hey, thank you for taking your time but this website can't be operated into dark mode due to something, so I am closing this issue. Please explore more and raise other issues.
