### ISSUE TITLE
Wrong Cursor Behaviour

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#470]
### What happened?

Hovering over the navigation items, the cursor should change either to 'Hand', or remain as 'Arrow'. But it changes to 'Ibean'.
@Agarwalvidu @deepeshmlgupta  please assign this to me under GSSoC 2024

### How can we reproduce this bug?

https://github.com/user-attachments/assets/8e2c80fc-ddd0-4d3b-8a22-ff9c6bf3a561

### Desktop Information (Optional)

OS: Windows
Browser: Firefox and others

### Urgency (Optional)

Low priority

**Comment by Agarwalvidu** [comment]
Go ahead @VijaySamant4368 !

**Comment by Agarwalvidu** [comment]
@VijaySamant4368  It is working fine. Please sync your repository and check.
