### ISSUE TITLE
[Bug Title here] text misalignment  in "test your knowledge section"

### ISSUE THREAD

**Issue by Ridhima10** [ayush-that/FinVeda#476]
### What happened?

 text misalignment  in "test your knowledge section"

### How can we reproduce this bug?

it should be in center
![Screenshot 2024-07-14 180129](https://github.com/user-attachments/assets/5f4e6534-f23f-4b1b-964f-ea245f9a8369)

### Urgency (Optional)

None

**Comment by Agarwalvidu** [comment]
This page is already under development. Please look for more issues @Ridhima10 
Thank you
