### ISSUE TITLE
[style]:  animated cursor

### ISSUE THREAD

**Issue by Ridhima10** [ayush-that/FinVeda#478]
### What's the style idea?

i would like to add an  animated cursor according to the theme of your website

### Add screenshots

https://github.com/user-attachments/assets/b5d5aad4-63d3-454e-a355-c13b708085e7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
We already had our cursor animated @Ridhima10 . Please look for more issues. Thank you for taking your time.
