### ISSUE TITLE
[style]: The Chat with ArthSathi button & Go-to-top button do not have some gap between each other.

### ISSUE THREAD

**Issue by vishanurag** [ayush-that/FinVeda#479]
### What's the style idea?

We need to improve  

- The Chat with ArthSathi button & Go-to-top button do not have some gap between each other.
- These buttons should have some gap (around 5px) between each other.

_Plesase assign me this issue under GSSoC'24_

### Add screenshots

Add screenshots
![Screenshot 2024-07-14 180420](https://github.com/user-attachments/assets/84844f49-4af7-4fd0-b24a-6dd44ae8925c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Go for it! But make sure that you will not disturb other things. @vishanurag
