### ISSUE TITLE
[Feature Request]: Integrating Docker into the project

### ISSUE THREAD

**Issue by Ratangulati** [ayush-that/FinVeda#480]
### Is your feature request related to a problem? Please describe.

Docker is a must for open-source projects nowadays as it has its benefits.

Use Case
Dockerfile has many benefits but consistency and isolation stand out the most.

Docker allows you to package your entire application, including its dependencies, into a single container. That makes sure your application will run across different environments.
another benefit is that it runs in its environment without interfering with other applications or the host system.

### Describe the solution you'd like.

Creating a dockerfile and documentation required by the project

### Describe alternatives you've considered.

docker is the best tool used for containerization 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
@ayush-that This issue needs your consent before assigning.
