### ISSUE TITLE
Wrong Cursor Behavior

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#483]
### What happened?

Hovering over the services title, the cursor should change either to 'Hand', or remain as 'Arrow'. But it changes to 'Ibean'.
@Agarwalvidu @deepeshmlgupta please assign this to me under GSSoC 2024

### How can we reproduce this bug?

Uploading servicesTitle.mp4…

### Desktop Information (Optional)

OS: Windows
Browser: Firefox, Chrome and Opera

### Urgency (Optional)

Low priority

**Comment by VijaySamant4368** [comment]
The video regarding this issue:
https://github.com/user-attachments/assets/f7bb132c-8e76-493f-8fa0-96a51abf6a9b

**Comment by Agarwalvidu** [comment]
@VijaySamant4368 This website has a designer cursor which was added by a contributor. Please sync your PR and check. Also issue is not assinged to you so please don't work on the issues that are not assigned, it will only waste your own time. Thank you for contributing, please find more issues and raise.
