### ISSUE TITLE
[Bug Title here] Signup popup

### ISSUE THREAD

**Issue by Shreyaa173** [ayush-that/FinVeda#485]
### What happened?

want to add popup after signup is completed

### How can we reproduce this bug?

We can add this

### Desktop Information (Optional)

![image](https://github.com/user-attachments/assets/3b711992-6631-46e0-b8cb-31a4abc5aaed)

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
@Shreyaa173 Actually website currently doesn't have any backend for the same reason sign up functionality is not there till now. For the same reason I am closing this issue. Thank you for taking your time. Please look more into the website and find more issues.
