### ISSUE TITLE
Title: Want to add hover effect

### ISSUE THREAD

**Issue by Shreyaa173** [ayush-that/FinVeda#486]
### Is your feature request related to a problem? Please describe.

Hover effect is not available

### Describe the solution you'd like.

want to add hover effect

### Describe alternatives you've considered.

![image](https://github.com/user-attachments/assets/91f7cb10-ac75-461e-b2cf-c465ddc2d4ff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Please sync your PR as this is a old page. @Shreyaa173 For the same reason I am closing this issue.
