### ISSUE TITLE
[Bug Title here] font is not clearly visible

### ISSUE THREAD

**Issue by Shreyaa173** [ayush-that/FinVeda#487]
### What happened?

the font is mixing up with background

### How can we reproduce this bug?

we can change the font color

### Desktop Information (Optional)

![image](https://github.com/user-attachments/assets/c834fcfe-6509-4b88-bc44-b3bc205f0311)

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
@Shreyaa173 Where this is present, can you please elaborate a bit more.
