### ISSUE TITLE
[Bug Title here] alignment issue

### ISSUE THREAD

**Issue by Shreyaa173** [ayush-that/FinVeda#488]
### What happened?

buttons are not well aligned also the top button is of no use so want to remove it

### How can we reproduce this bug?

we can align things

### Desktop Information (Optional)

![image](https://github.com/user-attachments/assets/bfc9a305-dddd-4ce3-96ee-898d78ad2a62)

### Urgency (Optional)

High priority

**Comment by deepeshmlgupta** [comment]
@Shreyaa173 This issue is been already assigned to someone else
