### ISSUE TITLE
quiz result feedback

### ISSUE THREAD

**Issue by Harshitazz** [ayush-that/FinVeda#49]
**better feedback with better ui and correct choice displayed . also add a "better luck next time message"** 
![Screenshot 2024-05-11 223230](https://github.com/ayush-that/FinVeda/assets/118474653/140f31bb-6cab-459d-8028-3b3e5288ca4d)

**Comment by Prachiii8287** [comment]
I want to contribute in this problem.Please assign me this work

**Comment by harshit18-09** [comment]
I am a GSSOC 2024 contributor and I think it will interesting to work on this issue of making a feedback form after the each quiz.
I will using js. This added feature would great to this project.
Kindly assign me this issue under gssoc tag.
Regards
