### ISSUE TITLE
Title: Enhancing MFI and EMI calculator results and making it responsive for mobile view

### ISSUE THREAD

**Issue by vidhiisaxena** [ayush-that/FinVeda#491]
### Is your feature request related to a problem? Please describe.

Yes, after clicking on calculate, it is not scrolling down to the desired results and we have to scroll down.

### Describe the solution you'd like.

 To  increase ease of user, we can directly take them to result after clicking on calculate.

### Describe alternatives you've considered.

Alternatives can be that we alert the result on the top of website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Assigning!

**Comment by Agarwalvidu** [comment]
@vidhiisaxena Update?
