### ISSUE TITLE
add hover effects 

### ISSUE THREAD

**Issue by kairveeehh** [ayush-that/FinVeda#5]
@ayush-that  there are no hover and pointer events under this section 
## please assign under gssoc'24 
![Uploading Screenshot 2024-05-10 173554.png…]()

**Comment by Abhishek-0899** [comment]
Please assign this issue to me under gssoc'24

**Comment by MelissaSequeira** [comment]
I can do it...Plz consider me for the task
https://melissasequeira.github.io/fashionweb.github.io/

**Comment by GAGGZ1** [comment]
@ayush-that Could you please assign me the task of adding hover effects to elements in the project? With my experience in front-end development and UI design, I'm confident in my ability to implement engaging hover effects that enhance user interaction. I'm eager to contribute to this aspect of the project and elevate its overall design.

Thank you for considering my request!

**Comment by SuhainaFathimaM** [comment]
@ayush-that Please assign this issue to me under gssoc'24

**Comment by vanirastogi** [comment]
Can You assign it to me under GSSoC'24 label will complete this project

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.
