### ISSUE TITLE
Enhance SEO with Meta Tags for Various Pages

### ISSUE THREAD

**Issue by shreyasmunge** [ayush-that/FinVeda#501]
### What's the style idea?

I want to add content for the description meta tag and include an author meta tag for the following pages: index, blog, quiz, login, and trends.This enhancement will help improve the SEO performance and provide more detailed metadata for each page. 
@Agarwalvidu assign me this issue as part of GSSoC 2024.

### Add screenshots

In this we can see that description meta tag does not have content and there is no author meta tag.
![WhatsApp Image 2024-07-15 at 1 23 01 PM](https://github.com/user-attachments/assets/6a947127-6788-49f8-9f11-b86cfec626d5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Okay go ahead! @shreyasmunge
