### ISSUE TITLE
Title: improving the navbar in the mobile view.

### ISSUE THREAD

**Issue by AnkitLuhar** [ayush-that/FinVeda#508]
### Is your feature request related to a problem? Please describe.

In the current website, the navbar looks outdated and does not function well in the mobile view. This affects the user experience and may discourage users from navigating the site on their mobile devices.

### Describe the solution you'd like.

I would like to redesign the navbar for the mobile view to ensure it is modern, responsive, and user-friendly. This includes:

1.Implementing a collapsible menu that is easily accessible.
2.Ensuring the navbar items are clearly visible and easily tappable.
3.Enhancing the overall aesthetics to match contemporary design standards.

### Describe alternatives you've considered.

1.Keeping the current design but improving its responsiveness slightly.

### Add any other context or screenshots about the feature request here.

![Screenshot (883)](https://github.com/user-attachments/assets/a37cb657-a972-419b-a6be-97ea4c9bf992)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by AnkitLuhar** [comment]
@ayush-that assign this task under Gssoc'24  ,excited to contribute in your project.

**Comment by Agarwalvidu** [comment]
Go ahead!
