### ISSUE TITLE
[Quiz Section Distured] 

### ISSUE THREAD

**Issue by KomalMaurya** [ayush-that/FinVeda#511]
### What happened?

![Screenshot_2024-07-16-06-31-52-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/545b646a-ae2a-45cd-a1cb-64c5e233f95e)
I'll make the options look better.....as it is disturbed now

Name : Komal Maurya 
GitHub profile link : https://github.com/KomalMaurya
Role : Contributor in GSSoC'24 

### How can we reproduce this bug?

I'll align options so that it won't be out of the box

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
Go ahead @KomalMaurya !
