### ISSUE TITLE
[style]: Changing the text style of NPV calculator and changing the input settings of MFI calc.

### ISSUE THREAD

**Issue by vidhiisaxena** [ayush-that/FinVeda#513]
### What's the style idea?

1. We need to improve the font formatting of NPV calculator to match the aesthetics of the website.  For this I need the permission to -:
- reduce the text and leave the important parts to explain the functionality of the calc.
- changing the font styling of the text

2. The input settings of MFI calculator are such that it takes letters as well. I will change that setting to input amount/numbers for better UX..

### Add screenshots

![image](https://github.com/user-attachments/assets/e027b5aa-6b03-4913-b13f-8fa4ea9c09aa)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Go ahead
