### ISSUE TITLE
[style]: Inconsistent 'Calculate' Button on Tools Page

### ISSUE THREAD

**Issue by Anni299** [ayush-that/FinVeda#514]
### What's the style idea?

We need to improve the styling of the calculate button on the tools page. For some tools the button only says 'Calculate' and for some tools it has 'Calculate EMI' or 'Calculate Insurance'.
Also the width of the calculate button needs to be consistent.This affects the visual uniformity of the UI. 
I want to adjust this for consistency.

### Add screenshots

![image](https://github.com/user-attachments/assets/364a7ecb-86c8-4999-8a7e-8c134b8c2fd6)
![image](https://github.com/user-attachments/assets/1d7ac417-63c3-41a5-9b7d-10364822f9d7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Go ahead!
