### ISSUE TITLE
Changing text color of Button on hovering 

### ISSUE THREAD

**Issue by SagarRathore1** [ayush-that/FinVeda#518]
### What's the style idea?

I would like to change the color of text in button on hovering 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Go ahead!
