### ISSUE TITLE
Title: congratulation animation in quiz

### ISSUE THREAD

**Issue by sohinirathor2004** [ayush-that/FinVeda#519]
### Is your feature request related to a problem? Please describe.

Adding congratulations animation on quiz page after ending of quiz

### Describe the solution you'd like.

Adding congratulations animation on quiz page after ending of quiz .Animation will be added as per it sounds ok

### Describe alternatives you've considered.

i will change according to the requirement 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Assigning!
