### ISSUE TITLE
Footer alignment

### ISSUE THREAD

**Issue by Jasleen1210** [ayush-that/FinVeda#522]
### What happened?

Footer (copyright) is not aligned on all pages.
Id like to make footer on all pages identical to that of blog page (rest are not aligned)

### How can we reproduce this bug?

open site
see footer

### Urgency (Optional)

None

**Comment by Agarwalvidu** [comment]
Assigning!

**Comment by Agarwalvidu** [comment]
Update?

**Comment by Jasleen1210** [comment]
PR made! @Agarwalvidu
