### ISSUE TITLE
[Cursor effect on contact us on quiz html page at hover section 

### ISSUE THREAD

**Issue by Ketanop321** [ayush-that/FinVeda#526]
### What happened?

cursor pointer is not showing at hover at contact us element

### How can we reproduce this bug?

add cursor pointer to it

https://github.com/user-attachments/assets/cc6fce1e-9ef6-486c-ab40-8efbaed46012

### Desktop Information (Optional)

hp 14s (1240p)

### Urgency (Optional)

Low priority

**Comment by Agarwalvidu** [comment]
Please sync your fork once it's updated.

**Comment by Ketanop321** [comment]
> Please sync your fork once it's updated.

@Agarwalvidu  This issue is not resolved🙃 , In your vercel link .

**Comment by Agarwalvidu** [comment]
Go ahead!

**Comment by Agarwalvidu** [comment]
Please sync your fork before it.
