### ISSUE TITLE
Title:  A blog on - Can pocket money turn into investment a guide for teenagers

### ISSUE THREAD

**Issue by Vin205** [ayush-that/FinVeda#528]
### Is your feature request related to a problem? Please describe.

The investment aorgrowth related blogs for adults are available on website but how teenager can make investment whose age is 14-18 also essential information.

### Describe the solution you'd like.

Blog on how to make investment by saving pocket money for minors through a custodial account with a parent or adult's supervision. This will help students to understand how saving money is important and its growth

### Describe alternatives you've considered.

We also add information that this a legal way of investment as it is done under supervision of adults.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-07-16 222400](https://github.com/user-attachments/assets/9662572f-da0f-4883-adfe-98cb74b719ca)
![Screenshot 2024-07-17 115212](https://github.com/user-attachments/assets/ff7532d6-3b26-4fb5-ba9f-ee7e29fc01fd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Go ahead!
