### ISSUE TITLE
Links of navbar does not show active link

### ISSUE THREAD

**Issue by Ridhima10** [ayush-that/FinVeda#53]
Links of navbar does not show active link
![Screenshot 2024-05-12 000913](https://github.com/ayush-that/FinVeda/assets/85826117/9f56505d-7437-46f8-a289-7ad30f17cdd3)

I am here on blogs page but on navbar it shows quiz active. 

Please assign me this issue i will fix it
Best regards

**Comment by drashtigit** [comment]
@ayush-that Can you please assign me this issue. I have previously worked on it in my projects.

**Comment by Ridhima10** [comment]
@ayush-that Kindly review this
