### ISSUE TITLE
Title: ADD CORRECT ANSWER FEATURE IN QUIZ 

### ISSUE THREAD

**Issue by chahal0** [ayush-that/FinVeda#530]
### Is your feature request related to a problem? Please describe.

Adding your answer and correct answers after finishing of quiz below scores ans makes it responsive too 

### Describe the solution you'd like.

Adding your answer and correct answers after finishing of quiz

### Describe alternatives you've considered.

Adding your answer and correct answers after finishing of quiz

### Add any other context or screenshots about the feature request here.

Adding your answer and correct answers after finishing of quiz

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by chahal0** [comment]
Adding your answer and correct answers after finishing of quiz

**Comment by Agarwalvidu** [comment]
It is already assigned!
