### ISSUE TITLE
Title:  Adding a description about quiz questions and marks

### ISSUE THREAD

**Issue by Vanshikachhikara** [ayush-that/FinVeda#532]
### Is your feature request related to a problem? Please describe.

When the user comes on the quiz page they don't really know how many questions will be asked and what marks do they carry!

### Describe the solution you'd like.

I think when the user comes on the quiz page first we should tell them that there will be 10 questions of 5 marks each. This will give user a little idea. Hence we can create a description box above the quiz box. Description box will tell the user about quiz, no. of questions, marks etc.,

### Describe alternatives you've considered.

an alternative can be on each question displayed instead of just showing ques 1 we can write it as ques 1/10 and on extreme right we can write marks of the question

### Add any other context or screenshots about the feature request here.

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by Vanshikachhikara** [comment]
Please assign this issue to me

**Comment by Agarwalvidu** [comment]
Go ahead @Vanshikachhikara !

**Comment by Vanshikachhikara** [comment]
Okay! Thankyou!!
