### ISSUE TITLE
Add Cursor Trail effect Matching to the website design theme to improve UI

### ISSUE THREAD

**Issue by MastanSayyad** [ayush-that/FinVeda#533]
### Is your feature request related to a problem? Please describe.

Hey @Agarwalvidu

I would like to add a cursor trail effect **across all the existing pages of the website** 
The current cursor looks too odd and does not match with website design theme, 

- Home page
- Tools page
- Quiz page
- Blogs page
- Trends
- And all Footer Link Pages 

### Describe the solution you'd like.

**Like this:**

https://github.com/user-attachments/assets/841dd647-f990-43c9-b317-2cff2f3f54d1

### Describe alternatives you've considered.

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
We already have a unique cursor, can you please check it once and Suggest can it be implemented with that?

**Comment by MastanSayyad** [comment]
> We already have a unique cursor, can you please check it once and Suggest can it be implemented with that?

I did check it but I am going to add Trail effect to that cursor also the unique cursor is not looking good

**Comment by MastanSayyad** [comment]
the cursor will stay the same I'll just add a trail effect to it! @Agarwalvidu

**Comment by MastanSayyad** [comment]
@Agarwalvidu There is one more bug in it that the cursor is only present in home page in other several pages it is not present

**Comment by Agarwalvidu** [comment]
Okay go ahead!
