### ISSUE TITLE
Adding more content in About Page

### ISSUE THREAD

**Issue by KomalMaurya** [ayush-that/FinVeda#537]
### What's the style idea?

We need to add more content in "About Page" to make it look more good!!

### Add screenshots

![image](https://github.com/user-attachments/assets/6e435136-9db5-4754-bc6d-650eaf30f312)
Only this content is here!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Go ahead!
