### ISSUE TITLE
Add Client Side User Validation to Login/Register Page 

### ISSUE THREAD

**Issue by MastanSayyad** [ayush-that/FinVeda#538]
### Is your feature request related to a problem? Please describe.

Hey @Agarwalvidu 

I would like to add a client-side user validation to ensure and validate all the necessary fields are present before clicking on login or register 

https://github.com/user-attachments/assets/a2b2b235-aa58-4e4b-a7fd-3272a52a3b42

### Describe the solution you'd like.

I would like to add a client side user validation tk the form

**Like this:**

https://github.com/user-attachments/assets/4fe9dc1a-ff3a-4f76-bc8f-f4ab40bf6e62

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Actually backend is not there for this website. What are you willing to do exactly please elaborate.

**Comment by MastanSayyad** [comment]
> Actually backend is not there for this website. What are you willing to do exactly please elaborate.

Yeah, It's not backend, The login and register form looks dummy and without any functionalities, I am implementing a user validation which shows "please fill out the mandatory fields" whenever someone try to register or login without filling the form to look more real. All frontend login forms has client side user validations! in this one it is missing 

You can refer the screen record I have provided up in the issue, that one is also a login/register page with frontend only! @Agarwalvidu

**Comment by Agarwalvidu** [comment]
Okay go ahead!
