### ISSUE TITLE
UI not visible

### ISSUE THREAD

**Issue by DevGajjar28** [ayush-that/FinVeda#539]
### What happened?

chat button text not properly visible, it's visible while hover though but without hover not visible.
![image](https://github.com/user-attachments/assets/06d5201b-642c-4e49-aa00-6d5346edd007)

### How can we reproduce this bug?

we can add texts colors or may be change color gradient.

### Urgency (Optional)

Medium priority

**Comment by Agarwalvidu** [comment]
Go ahead!
