### ISSUE TITLE
Logo Change : Changing the logo of twitter in the team section

### ISSUE THREAD

**Issue by SiddharthaArepalli** [ayush-that/FinVeda#54]
![Screenshot 2024-05-12 001000](https://github.com/ayush-that/FinVeda/assets/140429954/d955f366-65c4-4730-bd02-3502401592b3)
@ayush-that  assign me this task under the GSSOC'24

**Comment by SiddharthaArepalli** [comment]
@ayush-that  I request u to Assign me !!

**Comment by SiddharthaArepalli** [comment]
![Screenshot 2024-05-12 004110](https://github.com/ayush-that/FinVeda/assets/140429954/c2036d84-5ea0-46e3-acca-868086f2edfa)
I have changed the logo of twiter to X

**Comment by SiddharthaArepalli** [comment]
@ayush-that U can assign me , I will make pullrequest !!

**Comment by Azhar-0401** [comment]
*is your feature request related to a problem? Please describe.*
Currently not Changing the logo of twitter in the team section 

*Describe the solution you'd like*
Changing the logo of twitter in the team section 

*Additional context*
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me
