### ISSUE TITLE
Title: Footer is not responsive.

### ISSUE THREAD

**Issue by zalabhavy** [ayush-that/FinVeda#540]
### Is your feature request related to a problem? Please describe.

Footer is not responsive in small screen device.

![image](https://github.com/user-attachments/assets/af81d70c-0df9-46c2-844a-979e87d10796)

### Describe the solution you'd like.

NA

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by zalabhavy** [comment]
@Agarwalvidu @deepeshmlgupta Please assign me this task !

Thank You !

**Comment by Agarwalvidu** [comment]
Sorry for the inconvenience actually there was some issues with some merged PR. It is fixed now, please check for issues. Thank you for taking your time.
