### ISSUE TITLE
Title: Navbar is not align properly.

### ISSUE THREAD

**Issue by zalabhavy** [ayush-that/FinVeda#541]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/d7feadd4-bd4c-4e2c-bc4f-31513db6a9ef)

**Here you can see navbar is not allign properly and icon is not in same.**

### Describe the solution you'd like.

NA

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by zalabhavy** [comment]
@Agarwalvidu @deepeshmlgupta Please assign me this task !

**Thank You !**

**Comment by Agarwalvidu** [comment]
Go ahead!
