### ISSUE TITLE
[Navbar not visible]

### ISSUE THREAD

**Issue by KomalMaurya** [ayush-that/FinVeda#551]
### What happened?

Navbar is not visible in the mobile screen
![Screenshot_2024-07-18-08-23-12-86_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/9ff31073-c256-4a14-8a11-795914cd6a59)

### How can we reproduce this bug?

I can fix it!

### Desktop Information (Optional)

@Agarwalvidu Please assign this issue to me under gssoc label! 

### Urgency (Optional)

Medium priority

**Comment by deepeshmlgupta** [comment]
@KomalMaurya please check it again it is visible

**Comment by KomalMaurya** [comment]
@deepeshmlgupta But I can't see the Navbar in my mobile screen

**Comment by deepeshmlgupta** [comment]
![Screenshot_2024-07-18-12-28-18-383_com.android.chrome.jpg](https://github.com/user-attachments/assets/5ed0c585-9022-41ac-9364-c67fbaf97533)

@KomalMaurya it is visible

**Comment by KomalMaurya** [comment]
@deepeshmlgupta It is not visible for small mobile screen size....I was saying that itni der se 🥲
![IMG20240718182856](https://github.com/user-attachments/assets/d94d617b-7043-4117-881e-c72722a6aeb1)
