### ISSUE TITLE
Making all the footer of the pages same as of home page 

### ISSUE THREAD

**Issue by gaur8av** [ayush-that/FinVeda#554]
### What happened?

The Footer are different in different pages 

### How can we reproduce this bug?

I will make the footer same as of home page in every page of the website

@deepeshmlgupta please assign me this issue under GSSOC'24

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
You hav to make footer same for all the pages as blogs page and not as home page
 Please keep this in mind. @gaur8av

**Comment by Agarwalvidu** [comment]
I am closing this issue as it is already assigned to some other contributor.
