### ISSUE TITLE
Typo correction

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#558]
@Agarwalvidu  @deepeshmlgupta   At many places in the website it is incorrectly written "Try it free", which doesn't even make sense. Instead it should be either "Try for free" or "Try it for free".
![image](https://github.com/user-attachments/assets/3245efe8-bde5-482b-a458-066469a579d9)

This issue is under GSSoC 2024

**Comment by Agarwalvidu** [comment]
Go ahead!
