### ISSUE TITLE
Title: Adding color to Social Media icons

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#560]
### Is your feature request related to a problem? Please describe.

When we hover over the social media icons, all changes into the same orangish-red color.

### Describe the solution you'd like.

It would look good if the social media icons changes to their respective colors.
For example: Facebook changes to blue blue, Instagram to red and so on.

### Describe alternatives you've considered.

The Twitter logo can also be changed to its new logo

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/23284329-b03c-4448-b7b2-be577f99ce76)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by VijaySamant4368** [comment]
@Agarwalvidu  please assign this to me

**Comment by Agarwalvidu** [comment]
Where are these icons?

**Comment by VijaySamant4368** [comment]
In the bottom of that page.

**Comment by Agarwalvidu** [comment]
Add ss of full page underlining icons!

**Comment by VijaySamant4368** [comment]
@Agarwalvidu 
![image](https://github.com/user-attachments/assets/d6f2b5cb-02cf-485a-9215-aa2f2f36222f)
