### ISSUE TITLE
The Navigation can't be seen in Login page

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#561]
### What happened?

The Nav-titles are being camouflaged by the white color of the background.

### How can we reproduce this bug?

This can be confirmed by viewing the page

![image](https://github.com/user-attachments/assets/844a467a-fa7d-4862-beae-3222fcfdc8c0)

### Urgency (Optional)

Medium priority

**Comment by VijaySamant4368** [comment]
This issue is under GSSoC 2024

**Comment by Agarwalvidu** [comment]
What is this page about?
