### ISSUE TITLE
Title: Display the user's answers and the correct answers

### ISSUE THREAD

**Issue by Khushi-Pushkar** [ayush-that/FinVeda#563]
### Is your feature request related to a problem? Please describe.

In many online quizzes, users only receive a final score at the end, without detailed feedback on which questions they got right or wrong. This lack of detailed feedback can be frustrating and unhelpful for users who want to learn and improve their knowledge.

### Describe the solution you'd like.

To enhance the functionality to display the user's answers, the correct answers, and make the design responsive.

### Describe alternatives you've considered.

At the end of the quiz, display both the correct answers for each question and showing the user's answers

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
#439 This issue needs to be solved before, as it may create conflicts!

**Comment by Agarwalvidu** [comment]
Already assinged to someone else!
