### ISSUE TITLE
[style]: All the buttons text is initially of grey colour that is not clearly visible 

### ISSUE THREAD

**Issue by chahal0** [ayush-that/FinVeda#565]
### What's the style idea?

we can change the color of button to some other color so that visibility of buttons becomes better 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Go ahead!
