### ISSUE TITLE
HOVER effect is not visible for char with ArthaSathi button and missing at homepage. 

### ISSUE THREAD

**Issue by Garima-149** [ayush-that/FinVeda#568]
### What happened?

Chat with ArthaSathi is available on all the pages but missing at home page and is redirecting to homepage instead of chatbot.

### How can we reproduce this bug?

It requires some css fixing.

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
Go ahead!

**Comment by Garima-149** [comment]
@Agarwalvidu Now, hover effect is visible and button is also there at home page

**Comment by Garima-149** [comment]
@Agarwalvidu 
![Screenshot (116)](https://github.com/user-attachments/assets/3a580835-32e0-485f-b52b-2f03fbc72ca4)
Now,it is working properly.I drop screenshot also.May I raise pr?
