### ISSUE TITLE
Coustom Cursor is Degrading the UI

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [ayush-that/FinVeda#569]
### What's the style idea?

Hey @ayush-that , @deepeshmlgupta and @Agarwalvidu 

The cursor trail effect looks good and matches with the website theme but the custom cursor doesn't look good I suggest removing it for a better user experience 

### Add screenshots

Add screenshots

https://github.com/user-attachments/assets/14b49f3d-a82b-431d-91c2-20da5a482eeb

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
I don't think there is any issue with custom cursor. For the same reason closing this issue.
