### ISSUE TITLE
Blog Content need to be fixed 

### ISSUE THREAD

**Issue by KomalMaurya** [ayush-that/FinVeda#570]
### What happened?

![image](https://github.com/user-attachments/assets/4abbc3e4-d201-40ca-b2b5-3fddab2a08cd)
![image](https://github.com/user-attachments/assets/0238c33e-52c9-442a-bbf8-372615ec03b2)
![image](https://github.com/user-attachments/assets/edc934f3-3e57-4d8e-bf35-f6e7384f6fe7)
This Blog content page is disturbed !!

### How can we reproduce this bug?

I'll fix it

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
Go ahead!
