### ISSUE TITLE
Title: Adding hover and border effects to Tech savy section in Home page 

### ISSUE THREAD

**Issue by GAVINESHWAR** [ayush-that/FinVeda#574]
### Is your feature request related to a problem? Please describe.

In the Tech savy team section at home page there is no hover and border effects , I would like to add the border and hovering effects to it.

### Describe the solution you'd like.

Make the section better user interface and user experience.
Make Attractive hover and hovering effects.

### Describe alternatives you've considered.

![image](https://github.com/user-attachments/assets/a3eb5402-5632-414b-a17a-7bdd3077ecf5)

These kind of hovering and border effects can be added

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/67a318f2-5dfb-4900-a270-52a92f2d6a8e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

@ayush-that , assign me this issue to make contribution to the project.

Thank you

**Comment by Agarwalvidu** [comment]
Go ahead!
