### ISSUE TITLE
Title: Make website SEO friendly

### ISSUE THREAD

**Issue by chaanakyaaM** [ayush-that/FinVeda#576]
### Is your feature request related to a problem? Please describe.

I would like to make the website SEO friendly, this feature helps your website to be indexed easily by the search engines.

### Describe the solution you'd like.

I would like to add appropriate meta tags including the OG tags for making the website SEO friendly.

### Describe alternatives you've considered.

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Meta tags addition already done. For the same reason I am closing this issue.
