### ISSUE TITLE
[style]: Changing cursor animation design

### ISSUE THREAD

**Issue by Ayush-may** [ayush-that/FinVeda#580]
### What's the style idea?

We need to improve the cursor animated circles bcoz its not looking cool.

Idea is same , circles follows the cursor , but i will add more smoothness and flowness

### Add screenshots

This is current design

![image](https://github.com/user-attachments/assets/fda2db0b-6126-443c-8192-75b09e48071c)

Im thinking to add this design

![image](https://github.com/user-attachments/assets/f829637e-ad76-4639-8cb2-b0154632f4f5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
I think this one is already looking good and going well with the website, and no more changes are required in the cursor! For the same reason I am closing this issue.
