### ISSUE TITLE
BUG: The Calculator forms are not Responsive in Tools Page

### ISSUE THREAD

**Issue by MastanSayyad** [ayush-that/FinVeda#582]
### What happened?

Hey @deepeshmlgupta and @Agarwalvidu 

There are multiple calculators are present in the Tools page of the website which are used to calculate respective calculations
The forms or sections of those calculators are responsive in mobile view

- Mutual Fund Investment Calculator

![image](https://github.com/user-attachments/assets/3db758a5-5d7e-42fa-a92d-d5f91ebd2d4c)

- EMI Calculator

![image](https://github.com/user-attachments/assets/056a03cc-7133-4428-86d6-7d0e9111ef7f)

- Savings Goal Calculator

![image](https://github.com/user-attachments/assets/b251847d-943c-4bf9-b2a2-c69012b5cd83)

- Insurance Calculator

![image](https://github.com/user-attachments/assets/fd85842f-ac94-490d-bc9c-a26a2c96c21f)

- Net Present Value (NPV) Calculator

![image](https://github.com/user-attachments/assets/7b150be7-d566-4d7c-b255-e1a363b7a803)

- Return on Investment(ROI) Calculator

![image](https://github.com/user-attachments/assets/3a942a39-4a47-414b-890b-4db63629aebf)

Please take a look and review it, thank you!

### How can we reproduce this bug?

Checkout tools page in mobile view or any other view

### Urgency (Optional)

None

**Comment by Agarwalvidu** [comment]
Go ahead!
