### ISSUE TITLE
BUG: Login/Register form is not Updated in Footer Links Pages

### ISSUE THREAD

**Issue by MastanSayyad** [ayush-that/FinVeda#583]
### What happened?

In the footer link pages such as
- Privacy Policy
- Terms and conditions
- Refund Policy
- Licensing
- Our Contributors

The Login/sign up page is not updated, after clicking on it in these above-mentioned page it shows "Feature in development"

![image](https://github.com/user-attachments/assets/621d1329-4bb4-4e98-a16e-54042cd57426)

### How can we reproduce this bug?

Click on the Login/Register nav link in footer link page 

### Desktop Information (Optional)

N/A

### Urgency (Optional)

High priority

**Comment by MastanSayyad** [comment]
@Agarwalvidu @deepeshmlgupta please assign this issue to me

**Comment by Agarwalvidu** [comment]
Go ahead!
