### ISSUE TITLE
BUG: The About Us Page is Not Responsive 

### ISSUE THREAD

**Issue by MastanSayyad** [ayush-that/FinVeda#584]
### What happened?

Hey @deepeshmlgupta and @Agarwalvidu 

The ABout us page is not responsive it overflows the body of the website and goes outside the body in mobile view and other devices view

![image](https://github.com/user-attachments/assets/bf9d69d0-43b1-4cc3-98b4-46ae3890f45c)

![image](https://github.com/user-attachments/assets/5dfd34d2-ffdf-4a3c-b06e-6a7cc735385d)

![image](https://github.com/user-attachments/assets/c827cd5b-9efd-4e04-9b5e-f0f660390ffa)

### How can we reproduce this bug?

Check the responsiveness in about us page

### Desktop Information (Optional)

N/A

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
It is under construction! Some other contributor is already working on this!
