### ISSUE TITLE
Title:  Adding hover and border effects to Blog section in Home page

### ISSUE THREAD

**Issue by GAVINESHWAR** [ayush-that/FinVeda#586]
### Is your feature request related to a problem? Please describe.

In the home page at blog section there is no effective css to the blogs , it is with simple hover no effects to border and hovering. I would like to add better hovering and border effects.

### Describe the solution you'd like.

Adding these hovering and border effects makes the section better user interface and experience.

### Describe alternatives you've considered.

I recently changes many some sections with effects . so I would like add same kind of effects to this section to make similar and make attractive to the section

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/68d4e338-a65d-4d43-b853-24bc090df64c)

 I would like to add these kind of effects to below section make more viewable and attractive.

![image](https://github.com/user-attachments/assets/9a57f2f1-528c-4004-848a-ae83970b9064)

@ayush-that  and @Agarwalvidu , please assign me this issue to make contribution to the project.

Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Go ahead!
