### ISSUE TITLE
[Bug] : Insurance calculator not responsive in mobile view 

### ISSUE THREAD

**Issue by vidhiisaxena** [ayush-that/FinVeda#588]
### What happened?

![Screenshot 2024-07-19 082513](https://github.com/user-attachments/assets/42d3691a-5bb6-407a-9d22-0648487f53bc)

### How can we reproduce this bug?

We have to improve the responsiveness of the calculator and align the text.

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
Go ahead!
