### ISSUE TITLE
[Bug Title here]  repetition of same link in learn more in blog section 

### ISSUE THREAD

**Issue by solanki505** [ayush-that/FinVeda#589]
### What happened?

![Screenshot 2024-07-19 093718](https://github.com/user-attachments/assets/7851a805-bcbe-445c-9780-6901d707c721)

### How can we reproduce this bug?

I will remove one repetition 

### Desktop Information (Optional)

Assign me this issue under GSSOc

### Urgency (Optional)

None

**Comment by Agarwalvidu** [comment]
Already resolved!
