### ISSUE TITLE
HomePage Hamburger button does not work.

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#590]
### What happened?

The hamburger button ,that appears when the website is viewed in mobile devices, does not work.

### How can we reproduce this bug?

When the website is viewed in devices with width less than 991px wide, the hamburger button appears instead of the nav-bar contents. Pressing it doesn't do anything.
![image](https://github.com/user-attachments/assets/96cbac56-31a6-4884-a7ab-3e52dc39a0bf)

### Urgency (Optional)

Medium priority

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @deepeshmlgupta please kindly check this issue.

**Comment by Agarwalvidu** [comment]
Go ahead!
