### ISSUE TITLE
Button Text Color Issue

### ISSUE THREAD

**Issue by pranay911** [ayush-that/FinVeda#591]
### What happened?

The text on the "Try it for free" button is displayed in gray color instead of the expected white color.

### How can we reproduce this bug?

Please follow these steps to reproduce the issue:
- Navigate to the Home Page where the "Try it for free" button is located.
- Observe the text color on the button.

**Expected Behaviour:**
![image](https://github.com/user-attachments/assets/a25d2302-122a-4e28-bec0-48f634a00736)

**Actual Behaviour:**
![image](https://github.com/user-attachments/assets/c44ce4e6-8df7-4302-ab00-0c5e7fed4e25)

### Desktop Information (Optional)

- Operating System: [e.g., Windows 10, macOS Big Sur, etc.]
- Browser: [e.g., Chrome 91.0, Firefox 89.0, etc.]
- Dependency Version: [e.g., React 17.0.2, Bootstrap 5.0.0, etc.]

### Urgency (Optional)

Medium priority

**Comment by Agarwalvidu** [comment]
This issue is already assigned!
