### ISSUE TITLE
Extra Space in Footer

### ISSUE THREAD

**Issue by pranay911** [ayush-that/FinVeda#593]
### What happened?

I expected the footer to be aligned properly without any unnecessary space.

### How can we reproduce this bug?

Please follow these steps to reproduce the issue:
- Navigate to the All pages where the footer is located.
- Observe the footer and note the extra space.

**Screenshots:**
![image](https://github.com/user-attachments/assets/df20cd6e-4d04-4de8-819d-e99b5de26549)

### Urgency (Optional)

Medium priority

**Comment by Agarwalvidu** [comment]
You can work on it. But Please check it must not disturb anything else other than that!
