### ISSUE TITLE
hover for the navbar 

### ISSUE THREAD

**Issue by kairveeehh** [ayush-that/FinVeda#6]
@ayush-that  navbar also lacks any hover features 
##  please assign under gssoc'24
![Screenshot 2024-05-10 173726](https://github.com/ayush-that/FinVeda/assets/145572028/b282584f-4e2b-49f1-9ddd-ab946a332f34)

**Comment by GAGGZ1** [comment]
@ayush-that I'd like to take on the task of implementing hover effects for the navbar in the project. Adding subtle yet visually appealing hover effects can significantly enhance user engagement and navigation experience. With my proficiency in front-end development, I'm well-equipped to craft dynamic hover effects that align with the project's design aesthetic.

Excited to contribute to this aspect of the project!

**Comment by sonarani1** [comment]
Hi, Please assign this issue to me.

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by ayush-that** [comment]
Since this issue is the same as #5 
I am closing this issue. Please check other issues.
