### ISSUE TITLE
No hover option for Footer

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#600]
### What happened?

There are three sections in the footer of the home page, namely 'Quick Links', 'Resources', and 'Contact Us'.
In the first two sections, the links change color when we hover over them, but the third one doesn't change color.

### How can we reproduce this bug?

![image](https://github.com/user-attachments/assets/f43f825a-bc85-4b6c-b2e7-a2255f0a7519)
![image](https://github.com/user-attachments/assets/a1a9e138-e237-4bdb-8f04-fe93ea016014)

### Urgency (Optional)

Low priority

**Comment by Agarwalvidu** [comment]
Go ahead!
