### ISSUE TITLE
Button doesn't work.

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#601]
### What happened?

Out of the three buttons in the side of the home page, the top button doesn't do anything. I checked the element using developer tools, and there is no script bounded to the button. @Agarwalvidu @deepeshmlgupta is there some function of the button that has to be added, or should the button be removed altogether?

### How can we reproduce this bug?

![image](https://github.com/user-attachments/assets/16363bf8-882a-43de-b028-7b11985a16c5)

### Urgency (Optional)

Medium priority

**Comment by Agarwalvidu** [comment]
This is some extra button and this issue is already assigned to someone else!
