### ISSUE TITLE
Unlinked Sign-in button.

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#602]
### What happened?

The Login/Signup button does not link anywhere.

### How can we reproduce this bug?

![image](https://github.com/user-attachments/assets/17d2ad5f-0873-44b7-8542-f733fcabbc30)

Pressing this button doesn't redirect, or reloads the page, or doesn't do anything visually.

### Urgency (Optional)

Medium priority

**Comment by Agarwalvidu** [comment]
Which pages are you talking about? This is not working in the new pages mentioned in footer. And the same issue is assigned to someone else!
