### ISSUE TITLE
Question: Do the pages never load?

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#603]
For some reason I am not able to view the following webpages:
- about.html
- trends.html
- blog.html
- quiz.html

The page just keeps on loading:
![image](https://github.com/user-attachments/assets/14460c52-459f-4a0f-a55e-9c41d24270bb)

I have waited for enough time, I have changed and checked my network and changed my web-browsers(**Firefox**, **Chrome**, **Opera**, **Brave**). I can't check this on a different machine, or a different OS. My current OS is **Windows**.

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @deepeshmlgupta can you please confirm whether this is a problem from my side or not.

**Comment by Agarwalvidu** [comment]
Please sync your fork clone again and try!
There is no issues from our side.
