### ISSUE TITLE
Title: Blog post is transperent make it in card and style it 

### ISSUE THREAD

**Issue by zalabhavy** [ayush-that/FinVeda#605]
### Is your feature request related to a problem? Please describe.

I want to give better style in blogs so it looks like card and add beautifull hover effects.

I will make attractive UI.

![image](https://github.com/user-attachments/assets/17a34d89-8ed6-4976-8781-a715e7f2ec10)

### Describe the solution you'd like.

NA

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by zalabhavy** [comment]
@Agarwalvidu Please assign me this task !

Thank You !

**Comment by Agarwalvidu** [comment]
Adding the effects to blogs card is already assigned to other contributors!
I would suggest please go through the the already assigned issues first and then raise the new one.
Your time is highly appreciated!
