### ISSUE TITLE
Repetition of About Us button in the navbar

### ISSUE THREAD

**Issue by Anni299** [ayush-that/FinVeda#611]
### What happened?

The about us button appears twice in the navbar in the blogs, trends and tools page.

![image](https://github.com/user-attachments/assets/a0a2c7e1-08a0-4b5d-83e4-90c0c3c91c5a)
![image](https://github.com/user-attachments/assets/70404cc8-7ac4-42e7-966c-4611081e4041)
![image](https://github.com/user-attachments/assets/362fee2d-ce3c-4c8e-9b75-90ba8d539f8b)

### How can we reproduce this bug?

Go to blogs or tools or trends page and see the navbar.

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
Go ahead!
