### ISSUE TITLE
[Navbar not visible] 

### ISSUE THREAD

**Issue by KomalMaurya** [ayush-that/FinVeda#613]
### What happened?

Navbar is not visible for small screen sizes.
![IMG20240718182856](https://github.com/user-attachments/assets/bd108fd2-8f27-48b3-8bcb-f7f28add615b)
@Agarwalvidu Please assign this issue to me under gssoc label.

### How can we reproduce this bug?

I'll fix it

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
Go ahead!
