### ISSUE TITLE
Title: Adding Hovering and Border effects to the blog cards in blog Page 

### ISSUE THREAD

**Issue by GAVINESHWAR** [ayush-that/FinVeda#615]
### Is your feature request related to a problem? Please describe.

In the Blog section There is no hovering and border effects to the blog cards, I would like to add the these effects to it.

### Describe the solution you'd like.

Adding these effects make the section better user interface and the user experience.
Making better view to the viewers.

### Describe alternatives you've considered.

Making clear and visible background and border effects.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/e83a429d-06cb-4983-8f9d-67d5808ce436)

@ayush-that and @Agarwalvidu , assign me this issue to make contribution to the project.

Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
This is already done!
