### ISSUE TITLE
Hover Effect to cards

### ISSUE THREAD

**Issue by YUG-1092005** [ayush-that/FinVeda#62]
![Screenshot (11)](https://github.com/ayush-that/FinVeda/assets/167304151/4eee8579-458f-45b7-a994-73489cdeb09b)
Also there is one extra arrow below first card's learn more. Kindly, assign this issue to me under GSSOC 24

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.

**Comment by ayush-that** [comment]
> ![Screenshot (11)](https://private-user-images.githubusercontent.com/167304151/329834918-4eee8579-458f-45b7-a994-73489cdeb09b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzYwNjQsIm5iZiI6MTcxNTY3NTc2NCwicGF0aCI6Ii8xNjczMDQxNTEvMzI5ODM0OTE4LTRlZWU4NTc5LTQ1OGYtNDViNy1hOTk0LTczNDg5Y2RlYjA5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwODM2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGFiZmY5NGQ0OWY2YmQ3ZjJhZWRkNWY0NDVkYmMyMmI2ZWVjN2IyZTczNGY1YTFmNTUzYmFkNTg2MDExODUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NzebQ1HhwT13rq8ZPUM-J0taZnH66bs_LFxVYIpR3eI) Also there is one extra arrow below first card's learn more. Kindly, assign this issue to me under GSSOC 24

I am assigning this to you under gssoc.
Have fun!

**Comment by anushkaaa34** [comment]
@ayush-that  I want to work on this issue. Please assign it to me

**Comment by Agarwalvidu** [comment]
This is already done. For the same reason I am closing this issue. Thank you for contributing, looking for more issues from your side.
