### ISSUE TITLE
[Bug]: GitHub Icon with Contributor Profile is Not Visible on Contributors Page

### ISSUE THREAD

**Issue by AsmitaMishra24** [ayush-that/FinVeda#621]
### What happened?

The GitHub icon next to contributor profiles is not visible on the Contributors page. This issue affects the visibility and functionality of linking to contributors' GitHub profiles.

![Screenshot 2024-07-20 040007](https://github.com/user-attachments/assets/cc988c83-4239-4d72-9453-b269b5ad62a1)

### How can we reproduce this bug?

Each contributor's profile should have a visible GitHub icon that links to their GitHub profile.

### Urgency (Optional)

Low priority

**Comment by Agarwalvidu** [comment]
Go ahead!
