### ISSUE TITLE
Blog redirection

### ISSUE THREAD

**Issue by Jasleen1210** [ayush-that/FinVeda#622]
### What happened?

Get start section> financial blogs> learn more does not redirect to blog page. 

### How can we reproduce this bug?

![image](https://github.com/user-attachments/assets/d04e5b1f-c4f1-4687-9131-ad308be59a9c)
click learn more
does not get redirected to blog page

### Urgency (Optional)

None

**Comment by Agarwalvidu** [comment]
Go ahead!
