### ISSUE TITLE
Quiz Page: Adding skip, prev, next buttons

### ISSUE THREAD

**Issue by Jasleen1210** [ayush-that/FinVeda#623]
### Is your feature request related to a problem? Please describe.

Quiz UI enhancement

### Describe the solution you'd like.

I would like to enhance the quiz page by adding the following 
 
> A skip/pass/see hint button 
> A submit button so the user gets more time to think about the chosen option (avoids accidental submissions too)
> A bar that shows progress (40% test completed etc)

### Describe alternatives you've considered.

-

### Add any other context or screenshots about the feature request here.

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Go ahead!
