### ISSUE TITLE
Add Dark and Light mode theme option.

### ISSUE THREAD

**Issue by kou95shik** [ayush-that/FinVeda#627]
### Is your feature request related to a problem? Please describe.

I will help for user to use in night.

### Describe the solution you'd like.

I will add the feature in nav bar that can switch dark mode to light mode and vice versa.

### Describe alternatives you've considered.

I will add the option in nav bar with logo.

### Add any other context or screenshots about the feature request here.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Can't be added in this website!
