### ISSUE TITLE
The unnecessary button is still there

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#628]
### What happened?

The top button of the three side buttons, that doesn't do anything, is still present in the home page.

### How can we reproduce this bug?

![image](https://github.com/user-attachments/assets/2a1e4d65-c0f0-41e7-8f82-c204a506ed3f)

### Urgency (Optional)

None

**Comment by VijaySamant4368** [comment]
@Agarwalvidu please check

**Comment by Agarwalvidu** [comment]
Already assigned!
