### ISSUE TITLE
Bug in EMI Calculator

### ISSUE THREAD

**Issue by say-het** [ayush-that/FinVeda#63]
**Description**

 - Issue is that clicking on calculate EMI if the input is NaN it stops working and prints NaN.

**How would I solve it?**
 - I will apply strong form validation on it to make it work.

**Other Advancements**
 - I also want to add some nice look in the input field

I would like to work on this issue please assign it to me under GSSoC'24 @ayush-that  

Little about me : I am experienced contributor as I have completed _Hacktoberfest-2020_ and _Hactoberfest-2023_ successfully.

**Comment by vanirastogi** [comment]
Can You assign it to me under GSSoC'24 label will complete this project

**Comment by say-het** [comment]
Hey! @ayush-that can you assign me this issue?

I have fixed it already! So I can raise a PR.
