### ISSUE TITLE
 Double chat buttons

### ISSUE THREAD

**Issue by Garima-149** [ayush-that/FinVeda#631]
### What happened?

![Screenshot (113)](https://github.com/user-attachments/assets/eb08f28f-c546-49ff-8ba2-cc6c821d06ed)
@ayush-that There are 2 chat buttons .One is functional and one is not.Please assign me this issue.

### How can we reproduce this bug?

There is need to eliminate one.

### Urgency (Optional)

High priority

**Comment by Garima-149** [comment]
@Agarwalvidu please assign me this issue?

**Comment by Agarwalvidu** [comment]
Go ahead!
