### ISSUE TITLE
The cards of About Us page are not responsive in mobile-view

### ISSUE THREAD

**Issue by vishanurag** [ayush-that/FinVeda#635]
### What happened?

- The cards of About Us page are not looking responsive in mobile-view.
- These cards are not styled properly in mobile-view.

https://github.com/user-attachments/assets/895f8a62-09be-48a2-8451-96eb8a390426

### How can we reproduce this bug?

- We can resolve this issue using CSS - Media-Queries & Bootstrap classes.

### Urgency (Optional)

High priority

**Comment by vishanurag** [comment]
@Agarwalvidu Please assign this issue to me under GSSoC'24

**Comment by Agarwalvidu** [comment]
Some other contributor is already assigned with the same issue! About page is under construction!
