### ISSUE TITLE
Contact Links Not Working in Footer and Incorrect Title on Quiz Page

### ISSUE THREAD

**Issue by shreyasmunge** [ayush-that/FinVeda#636]
### Is your feature request related to a problem? Please describe.

The following issues have been identified in the project:

1.Non-functional Links:

Mail Link: The mailto link (ayush1337@hotmail.com) is not working.
Company Website Link: The company website link (https://fin-veda.vercel.app/index.html) is not working.
Address Link: The address link to Google Maps for Delhi, India is not working.

2.Incorrect Title:

The title of the Quiz page is showing "Login/Signup" instead of the correct title.

### Describe the solution you'd like.

I will go through the index.html file to identify and correct the errors causing the non-functional links and the incorrect title on the Quiz page. Specifically, I will:

1.Verify and correct the href attributes for the mail, company website, and address links to ensure they are properly formatted.
2.Check for any issues in the CSS/JS libraries that might be affecting the link functionality.
3.Update the title tag in the Quiz page HTML to reflect the appropriate page title.

### Describe alternatives you've considered.

To go through index.html

@Agarwalvidu @deepeshmlgupta Please assign this  task to me.

### Add any other context or screenshots about the feature request here.

Title Error:
![WhatsApp Image 2024-07-20 at 5 52 46 PM](https://github.com/user-attachments/assets/b2f768d5-d5de-4e7f-82cb-a61feea5c2bb)

Link Not Working:

https://github.com/user-attachments/assets/b656ad2d-c8a7-46cb-b65a-9856f6426cfa

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by PATILYASHH** [comment]
Hi, I’d like to take this issue and work on a fix!
