### ISSUE TITLE
Title:  Adding DARK mode

### ISSUE THREAD

**Issue by dhairyagothi** [ayush-that/FinVeda#637]
### Is your feature request related to a problem? Please describe.

adding dark mode in website

### Describe the solution you'd like.

theme toggle

### Describe alternatives you've considered.

Dark theme for website

### Add any other context or screenshots about the feature request here.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Can't be added in this website!
