### ISSUE TITLE
Modification in  dark mode 

### ISSUE THREAD

**Issue by UdayanBanik58** [ayush-that/FinVeda#64]
### **The Issue :**
Buttons  all ,technology etc.. need to be modified  in dark mode ..
![image](https://github.com/ayush-that/FinVeda/assets/119029504/037d60d4-d3ef-4b4c-bb1b-2a8cc872e60f)

**Comment by Prachiii8287** [comment]
I would like to contribute.Please assign me this work

**Comment by prajna321** [comment]
I'd love to work on it,Please assign me this issue! I have done similar work in the past
