### ISSUE TITLE
 Add Dynamic Copyright Year Functionality to Footer

### ISSUE THREAD

**Issue by MastanSayyad** [ayush-that/FinVeda#646]
### Is your feature request related to a problem? Please describe.

Hey @deepeshmlgupta and @Agarwalvidu 

- The current footer of our website does not have a dynamically updating copyright year, 
- And some pages are missing the copyright year altogether. 

This can lead to outdated information and inconsistencies across the site.

### Describe the solution you'd like.

I would like to
- Add a script to dynamically update the copyright year in the footer to the current year.
- Ensure the footer is present and consistent across all HTML pages.

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/8a167588-7b41-487f-abb0-450bb59041c8)

![image](https://github.com/user-attachments/assets/9a480488-de1f-484c-aada-13589cdfac46)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by malik-na** [comment]
Hey!
I can fix this. Please assign it to me.
