### ISSUE TITLE
BUG: Outdated Blogs Posts Pages 

### ISSUE THREAD

**Issue by MastanSayyad** [ayush-that/FinVeda#648]
### What happened?

hey @deepeshmlgupta and @Agarwalvidu 

The blog post details pages (almost every blog post) are outdated 

![image](https://github.com/user-attachments/assets/b4af5540-20b6-4d10-a7d6-8a9b1bd1d4eb)

![image](https://github.com/user-attachments/assets/7480ba20-7c51-4a4a-91d0-c2c0abbc5cc0)

## Things that need to be fixed:
- **Navbar is outdated misses About Us section and the Login/Register form** 

![image](https://github.com/user-attachments/assets/5616b8b8-2f8b-4639-a5a9-df0703a86ae9)

- **Footer is outdated and does not contain updated pages nav links and other functionalities**

![image](https://github.com/user-attachments/assets/7e857cb5-a265-4231-b99f-c0b1c15823cc)

- **Missing Custom cursor and Trail effect** 

- **Missing feedback button**

![image](https://github.com/user-attachments/assets/c15c805c-07db-4087-8f8c-34ada8db4402)

I would like to make enhancements in it and update each blog post and any other modication

### How can we reproduce this bug?

Checkout each blog post

### Urgency (Optional)

High priority

**Comment by deepeshmlgupta** [comment]
@MastanSayyad do recheck the website as some of your issue are been already resolved and some of your issue are been already assigned to other

**Comment by MastanSayyad** [comment]
@deepeshmlgupta i did recheck it, And yes some issues are assign but not to this issues, i have raise the issue for Blog page "POSTS" details pages, you can open them by clicking on each blog cards, and see the pages are outdated! 

Kindly recheck it!

**Comment by deepeshmlgupta** [comment]
@MastanSayyad , Okh Go Ahead and start working
