### ISSUE TITLE
[BUG] Learn Mode Link of the Cards on Homepage is not working

### ISSUE THREAD

**Issue by say-het** [ayush-that/FinVeda#65]
**Description**

 - In the three cards on the homepage the link in Learn More button is not working.
 - Blog Post and Tools Links are not redirecting to their actual page.

I would like to work on this issue please assign it to me under GSSoC'24 @ayush-that  

Little about me : I am experienced contributor as I have completed _Hacktoberfest-2020_ and _Hactoberfest-2023_ successfully.

**Comment by say-het** [comment]
Hey! @ayush-that 
Please Assign me this Issue.

**Comment by ayush-that** [comment]
Same as #10.
I am closing this issue.
