### ISSUE TITLE
Contact Us Page is Not Clickable in Quiz Page  

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [ayush-that/FinVeda#651]
### What happened?

Hey @deepeshmlgupta and @Agarwalvidu 

The contact Us Page is Not Clickable in the Quiz Page  

![image](https://github.com/user-attachments/assets/faa91f45-c8b7-4184-9bce-33306681d9fe)

### How can we reproduce this bug?

N/A

### Urgency (Optional)

Medium priority

**Comment by deepeshmlgupta** [comment]
@RadhikaMalpani1702 This issue is already assign to someone else
