### ISSUE TITLE
[About Page Responsive] 

### ISSUE THREAD

**Issue by KomalMaurya** [ayush-that/FinVeda#663]
### What happened?

![image](https://github.com/user-attachments/assets/986527b1-8abd-4c88-96ef-4f1e57edf2cd)
![image](https://github.com/user-attachments/assets/ab403b82-6a28-4c97-8820-dd453c9d1bd8)
This About page is disturbed...

### How can we reproduce this bug?

@Agarwalvidu Please assign this issue to me!

### Urgency (Optional)

High priority

**Comment by Agarwalvidu** [comment]
Go ahead!
