### ISSUE TITLE
[ENHANCEMENT] Card is not of same length under ( Users sharing their experience ) tab .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [ayush-that/FinVeda#67]
When scroll to Users sharing their experience tab then the leftmost card is of large length then others. 
![Screenshot 2024-05-12 203520](https://github.com/ayush-that/FinVeda/assets/118350936/c353688b-6062-4e28-a444-0aedf936e6af)
I want to work on this under GSSOC'24

**Comment by ayush-that** [comment]
Assigning this under gssoc.
Have fun @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
Hii i want to know which behaviour you want like this is happening due to the leftmost card have a description of very long length then other that's why this is happening so do i have to clip the text after some line or any other you want please describe .

**Comment by Agarwalvidu** [comment]
It is updated now. Thank you for raising issue, looking for your more inputs. For now I am closing this issue.
