### ISSUE TITLE
Title: Better Hamburger Menu

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#670]
### Is your feature request related to a problem? Please describe.

Currently the expanded Hamburger menu does not go well with the rest of the webpage

### Describe the solution you'd like.

Improving of the hamburger's style.

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

The current style:
![image](https://github.com/user-attachments/assets/6c6e3608-20fa-4aa0-bdd3-226283019c3d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @ayush-that  please check

**Comment by deepeshmlgupta** [comment]
@VijaySamant4368 can please share your sample design

**Comment by Agarwalvidu** [comment]
Go ahead!

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @deepeshmlgupta how does this look?
https://github.com/user-attachments/assets/03bb0478-9b9e-4418-81ff-9f5d87f950e9

I have yet to do some minor details, but this is the main part.
I would like to know your opinion before going forward.

**Comment by VijaySamant4368** [comment]
https://github.com/user-attachments/assets/00ee7bce-dfeb-4b72-a2bd-4ed8dc9d704d

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @deepeshmlgupta should I change the design? Or should I proceed with this?

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @deepeshmlgupta should I change the design? Or should I proceed with this?

**Comment by Agarwalvidu** [comment]
How it will look like in mobile view?

**Comment by Agarwalvidu** [comment]
And only with icons one will get confused what page is about what.

**Comment by VijaySamant4368** [comment]
@Agarwalvidu  To be honest, I had different ideas for showing only Emojis in as the links. My idea for nav-bar with full links display are limited. Here is a general one:

https://github.com/user-attachments/assets/8f28aa30-8ba6-46c9-85ba-f43a1aa18f3e

**Comment by Agarwalvidu** [comment]
I think this is same as previous one🥲

**Comment by Agarwalvidu** [comment]
Try this one 
https://codepen.io/zakandaiev/pen/RwwBvrJ

**Comment by VijaySamant4368** [comment]
> I think this is same as previous one🥲
Oh I just noticed it. I am really sorry for the disappointment, I am currently just out of ideas.

**Comment by VijaySamant4368** [comment]
> Try this one https://codepen.io/zakandaiev/pen/RwwBvrJ

On it.

**Comment by VijaySamant4368** [comment]
@Agarwalvidu  please have a look at this:

https://github.com/user-attachments/assets/14d20644-456c-4d06-80e8-4611be082190

The colors and the items in the nav-bar can be changed without much hassle.

**Comment by Agarwalvidu** [comment]
This looks nice to me. Please go ahead with this one. One suggestion you can add a box around the nav items and make it more creative

**Comment by VijaySamant4368** [comment]
All right, I will!!!

**Comment by VijaySamant4368** [comment]
@Agarwalvidu I think that adding a box around the nav-items inside the hamburger-menu, will make it feel very much different than the original menu.
I have this in my mind:

https://github.com/user-attachments/assets/fbe43f50-10ff-4c8b-aaca-e5b830f6293f

**Comment by VijaySamant4368** [comment]
It gives a similar feel as the original nav-bar.

**Comment by Agarwalvidu** [comment]
It looks nice to me just decrease the height it must not take the full height of the sreen

**Comment by VijaySamant4368** [comment]
@Agarwalvidu these are the screenshots for different height:

70%:
![Screenshot 2024-07-26 at 09-58-42 Home - FinVeda](https://github.com/user-attachments/assets/4958b9de-e9ad-43aa-a4e5-de092a89ebd2)

90%:
![Screenshot 2024-07-26 at 09-59-14 Home - FinVeda](https://github.com/user-attachments/assets/6276a3c6-a080-4ee8-aa97-aca5ac493404)

100%:
![Screenshot 2024-07-26 at 10-00-40 Home - FinVeda](https://github.com/user-attachments/assets/2d753536-bfc9-4ba2-82be-62fd0e00267a)

I believe it is better looking at 100%, can you please provide your opinion?
Thanks.

**Comment by VijaySamant4368** [comment]
I took screenshot for comparatively wider width for better visualization.

**Comment by Agarwalvidu** [comment]
Yes 100% one is looking good!
Finally raise the PR.

**Comment by Agarwalvidu** [comment]
Make sure it will not cover the whole width, as it is looking good in this width!

**Comment by VijaySamant4368** [comment]
For less wider screen:
70%:
![Screenshot 2024-07-26 at 10-08-13 Home - FinVeda](https://github.com/user-attachments/assets/a17f63e7-37af-4dc0-b1b5-10b1d1c2e1da)

90%:
![Screenshot 2024-07-26 at 10-07-32 Home - FinVeda](https://github.com/user-attachments/assets/6b495c5f-8995-4a02-abac-54512797c3b9)


100%:
![Screenshot 2024-07-26 at 10-02-50 Home - FinVeda](https://github.com/user-attachments/assets/60890be6-ae54-4934-a27a-92522c0ff742)

**Comment by VijaySamant4368** [comment]
> Make sure it will not cover the whole width, as it is looking good in this width!

Al right!

**Comment by Agarwalvidu** [comment]
Whichever suits you best, I am liking the 70% most!

**Comment by VijaySamant4368** [comment]
Ok, I will make it 70% then.

**Comment by VijaySamant4368** [comment]
I am sorry but there seems to be a problem for height of 70%. For screens with less width, 70% will be quite compact, and a lot of things would have to be adjusted. SO I think we should avoid unnecessary extra fragility to the responsive nature.

**Comment by Agarwalvidu** [comment]
Okay!
