### ISSUE TITLE
BUG: Progress Bar is Missing in Contributors and Licensing Page

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [ayush-that/FinVeda#671]
Hey @deepeshmlgupta and @Agarwalvidu 

On this website the progress bar is missing in contributors and licensing page

![image](https://github.com/user-attachments/assets/d2572632-1652-4b4c-b53c-6fd020418495)

![image](https://github.com/user-attachments/assets/b41e42d1-c0b9-4078-89fc-ba1c0857b7d0)

### How can we reproduce this bug?

N/A

### Urgency (Optional)

Medium priority

**Comment by Agarwalvidu** [comment]
Go ahead!
