### ISSUE TITLE
Title: Add a favicon for the website 

### ISSUE THREAD

**Issue by nikki-05** [ayush-that/FinVeda#676]
### Is your feature request related to a problem? Please describe.

A favicon is a small but crucial aspect of a website's branding. It enhances user experience by providing a recognizable icon in the browser tab, bookmarks, and history. Currently, the FinVeda website lacks a favicon, which can make it harder for users to identify and return to our site easily.

### Describe the solution you'd like.

I would like to add a favicon to the website. This small icon will appear in the browser tab when users visit our site, making it instantly recognizable. The favicon should be designed to reflect the FinVeda brand, possibly incorporating elements of our logo or other distinctive visuals related to finance. 

### Describe alternatives you've considered.

Ensuring that the favicon is optimized for different devices and resolutions to maintain visual clarity.

### Add any other context or screenshots about the feature request here.

![finvedu](https://github.com/user-attachments/assets/d2387bd0-5264-4941-b949-a28ce96ab97e)
![finveda](https://github.com/user-attachments/assets/04ef3c32-3874-4961-a8ec-cdb0f7257839)
these are the samples attached

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by nikki-05** [comment]
@Agarwalvidu May you assist, please.

**Comment by Agarwalvidu** [comment]
These looks okayish to me can you please suggest more creative!

**Comment by nikki-05** [comment]
> These looks okayish to me can you please suggest more creative!

![finveda3](https://github.com/user-attachments/assets/e90ecf14-c8db-4154-9de8-fe3e0db2bfd1)
here's another sample, I think the favicon is too small to add some creativity, Had it been a logo, I would have added some more touches. Please let me know if more designs are needed.

**Comment by Agarwalvidu** [comment]
Try to make it according to the website's theme. I am assigning this to you. Just take the follow ups before commenting a PR
