### ISSUE TITLE
[Feature] Add Net Present Value Calculator to Tools Page.

### ISSUE THREAD

**Issue by Manav173** [ayush-that/FinVeda#68]
### Description

The Net Present Value (NPV) calculator is a powerful financial tool designed to help users evaluate the profitability of an investment by calculating the present value of future cash flows.
Stylish UI: Implement modern CSS styling to improve the aesthetic appeal of the calculator, making it more visually engaging for users.
Responsive Design: Ensure that the NPV calculator is responsive and adapts well to various screen sizes and devices, including desktop computers, tablets, and mobile phones, to cater to a broader audience.

I would be really thankful if you assign me this issue as a part of GSSoC'24 @ayush-that .

**Comment by ayush-that** [comment]
Assigning under gssoc
Have fun!

**Comment by Manav173** [comment]
As the PR is merged, I am closing this issue.
