### ISSUE TITLE
Title:  Want to add the popup at the time of login when user did some mistake 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [ayush-that/FinVeda#680]
### Is your feature request related to a problem? Please describe.

I want to add the pop up to the login signup page where user can see the popup when he is doing something wrong 

### Describe the solution you'd like.

With the help of popup or toast notification the user is able to see what's happening on the website 

### Describe alternatives you've considered.

To Add any other method to inform user 

### Add any other context or screenshots about the feature request here.

https://github.com/user-attachments/assets/e6b68303-ef60-4a26-babc-005c9c124ff4

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
not needed
