### ISSUE TITLE
Model is hallucinating

### ISSUE THREAD

**Issue by hollermay** [ayush-that/FinVeda#69]
I've found that your model is hallucinating and it's not fine-tuned to answer the financial questions in ArthSathi Chatbot. I can help you with fine-tuning this foundational model with proper custom data and providing rules to the model itself

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by ayush-that** [comment]
> I've found that your model is hallucinating and it's not fine-tuned to answer the financial questions in ArthSathi Chatbot. I can help you with fine-tuning this foundational model with proper custom data and providing rules to the model itself

That bot is made using BotPress, do you have experience working with that?

**Comment by hollermay** [comment]
@ayush-that not that much but I can work on it

**Comment by ayush-that** [comment]
> @ayush-that not that much but I can work on it

Always greet the bot first.
If you don't have any experience then it'll be hard buddy.
I'll fix it when I have time. 
If you wish to help, raise an issue and tell me what things should I change/improve.
Closing this issue
