### ISSUE TITLE
[style] : Correct the 0 likes 0 views 0 comments appearing in the video section in home page

### ISSUE THREAD

**Issue by manyaigdtuw** [ayush-that/FinVeda#693]
### What's the style idea?

We need to quantify the numbers, and not set it to zero.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'24 contributor
- [ ] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Go ahead!

**Comment by manyaigdtuw** [comment]
corrected & resolved
