### ISSUE TITLE
Home page buttons

### ISSUE THREAD

**Issue by Jasleen1210** [ayush-that/FinVeda#696]
### What's the style idea?

Buttons "Try it for free" on the home page have no hover styles

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Go ahead!
