### ISSUE TITLE
Chat with ArthSathi buttons

### ISSUE THREAD

**Issue by Jasleen1210** [ayush-that/FinVeda#697]
### What's the style idea?

We need to improve styling for "Chat with ArthSathi" by adding some changes in its hover state

### Add screenshots

![image](https://github.com/user-attachments/assets/64e59433-b577-4fec-b691-8d4a81fb3d54)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Go ahead!
