### ISSUE TITLE
Quiz results

### ISSUE THREAD

**Issue by Jasleen1210** [ayush-that/FinVeda#698]
### Is your feature request related to a problem? Please describe.

At the end of the quiz, the image shown should correspond to the marks scored by user

### Describe the solution you'd like.

I'd like to add multiple images for different score results.

### Describe alternatives you've considered.

-

### Add any other context or screenshots about the feature request here.

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Go ahead!
