### ISSUE TITLE
create a login/signup card 

### ISSUE THREAD

**Issue by kairveeehh** [ayush-that/FinVeda#7]
@ayush-that 
want to create a login/signup card  for the website as a major feature
## please assign under gssoc'24

**Comment by SanjanaBankar** [comment]
Hello, @ayush-that !

I believe the login/signup card can be created, which includes all the details.
 SignUp:  

- Name
- Create password
- Confirm Password
- Signup 
   Already have an account (Login)

Login:

- Name
- Email Id
Don't have an account (SignUp)
SignUp using Email

Please assign under GSSOC'24

Looking forward to contributing to this amazing project.

Regards,
Sanjana

**Comment by ayush-that** [comment]
Same as #20 
I am closing this issue.
