### ISSUE TITLE
Add Tailwind 

### ISSUE THREAD

**Issue by hollermay** [ayush-that/FinVeda#70]
We can refactor most of this codebase with tailwind by either using cdn or npm and most our code will get faster as well as dynamic without worrying about sizes.

**Comment by prajna321** [comment]
@ayush-that
I'd love to work on it. Please assign me this issue!

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.

**Comment by ayush-that** [comment]
> We can refactor most of this codebase with tailwind by either using cdn or npm and most our code will get faster as well as dynamic without worrying about sizes.

The project is made using BootStrap.
What do you want to do exactly?
