### ISSUE TITLE
[style]: Box alignment and Github link

### ISSUE THREAD

**Issue by vidhiisaxena** [ayush-that/FinVeda#700]
### What's the style idea?

We need to improve the alignment of text boxes on About Us and Adding GitHub repo link in contact us bar

### Add screenshots

![image](https://github.com/user-attachments/assets/e8364e45-23d5-47ca-afca-83952ee58e42)
<img width="949" alt="image" src="https://github.com/user-attachments/assets/87778511-828f-4f59-8be7-65667820c54e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Go ahead!
