### ISSUE TITLE
Adding a login/Register page

### ISSUE THREAD

**Issue by Manishar55** [ayush-that/FinVeda#71]
Hii @ayush-that  
When we click on the login/register button it is not working
so I want to add a login/register page 
![Screenshot 2024-05-13 005905](https://github.com/ayush-that/FinVeda/assets/154615478/0d4ec351-af9a-416e-9377-eaaebbea0f76)

Can you please assign this issue to me under gssoc24.

**Comment by drashtigit** [comment]
Can you please assign me this issue @ayush-that. Would be happy to work on it.

**Comment by ayush-that** [comment]
Same as #20 
I am closing this issue.
