### ISSUE TITLE
 Login/Signup button to be added in the new mobile view NavbarTitle: 

### ISSUE THREAD

**Issue by chahal0** [ayush-that/FinVeda#713]
### Is your feature request related to a problem? Please describe.

 Login/Signup button to be added in the new mobile view Navbar

### Describe the solution you'd like.

 Login/Signup button to be added in the new mobile view Navbar

### Describe alternatives you've considered.

 Login/Signup button to be added in the new mobile view Navbar

### Add any other context or screenshots about the feature request here.

 Login/Signup button to be added in the new mobile view Navbar

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Already assigned!
