### ISSUE TITLE
Quiz Page in Mobile view

### ISSUE THREAD

**Issue by Khushi-Pushkar** [ayush-that/FinVeda#717]
### What's the style idea?

In the mobile view on the quiz page, the "Welcome to Quiz Challenge" section needs to be modified as it doesn't look good currently.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Go ahead!
