### ISSUE TITLE
[Bug]: Double Underline on Navbar Hover on Licensing Page 

### ISSUE THREAD

**Issue by AsmitaMishra24** [ayush-that/FinVeda#718]
### What happened?

When hovering over the navbar links on the Licensing page, a double underline appears. This issue is not present on other pages of the site and affects the visual consistency of the navbar.

Screenshot:
![Screenshot 2024-07-26 165420](https://github.com/user-attachments/assets/229cf549-ad06-48d4-aebd-057185e2186f)

### How can we reproduce this bug?

A single underline should appear when hovering over a navbar item, maintaining a clean and consistent look.

### Urgency (Optional)

Low priority

**Comment by Agarwalvidu** [comment]
Go ahead!
