### ISSUE TITLE
[Bug]: Inconsistent Login/Register UI on Trends Page 

### ISSUE THREAD

**Issue by AsmitaMishra24** [ayush-that/FinVeda#719]
### What happened?

The Login/Register section on the Trends page does not match the design and functionality of the Login/Register sections on other pages. This inconsistency affects the user experience and overall visual coherence of the site.

Screenshot:
![Screenshot 2024-07-26 165327](https://github.com/user-attachments/assets/4ae32d76-e613-4f50-9e6d-fb021380991c)

### How can we reproduce this bug?

The Login/Register section on the Trends page should have the same design and functionality as it does on other pages.

### Urgency (Optional)
medium priority

**Comment by Agarwalvidu** [comment]
Go ahead!
