### ISSUE TITLE
Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [ayush-that/FinVeda#72]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

![image](https://github.com/ayush-that/FinVeda/assets/50082154/4c3999c1-da76-4b88-9c81-ce6bc4d66b88)

**Comment by prajna321** [comment]
@ayush-that
I'd love to take on this challenge. Please assign me this issue!

**Comment by ayush-that** [comment]
@sanmarg assigning under gssoc
Try to make it look "good"
HF

**Comment by Agarwalvidu** [comment]
This is already done. For the same reason I am closing this issue. Thank you for contributing, looking for more issues from your side.
