### ISSUE TITLE
Title:  Include Interactive tools such as Quizzes and Assignments

### ISSUE THREAD

**Issue by Vin205** [ayush-that/FinVeda#722]
### Is your feature request related to a problem? Please describe.

Include interactive tools to offer quizzes to test users financial knowledge and provide feedback.

### Describe the solution you'd like.

It will include interactive quizzes and financial quizzes to improve financial knowledge of people to understand how to improve finances.

### Describe alternatives you've considered.

We can also include scores and answers and how to improve your financial knowledge

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-07-17 115212](https://github.com/user-attachments/assets/70999b4b-68dd-46c4-80af-8861f0f40155)
![Screenshot 2024-07-18 214311](https://github.com/user-attachments/assets/e80c78fa-47fb-4c62-a0df-51c83fcf58bc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Quiz is already there?

**Comment by Vin205** [comment]
The blogs and website is designed for all users so the quiz should also be designed accordingly. There should be 3 categories of quiz for teenagers, adults and senior citizens as per their financial knowledge.
