### ISSUE TITLE
Title: Separate division of X(Twitter)and LinkedIn Profile

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#726]
### Is your feature request related to a problem? Please describe.

In the Team Image section, if we hover over the Social Media icons, both X(Twitter) and LinkedIn are being highlighted(their BG color changes).

### Describe the solution you'd like.

I think there can be a separate hover effect for both of them, such that when user hovers over the LinkedIn logo, only the half, with the LinkedIn icon, get highlighted.

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/123a0488-b147-4133-8439-d2816a97111e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by VijaySamant4368** [comment]
@deepeshmlgupta @Agarwalvidu please look into this.

**Comment by Agarwalvidu** [comment]
Go ahead!

**Comment by VijaySamant4368** [comment]
@Agarwalvidu here is the side by side comparison of the new BG separation(left) and the older one(right)

https://github.com/user-attachments/assets/73215455-8465-4cf3-a590-4d9a7c9e865d

**Comment by VijaySamant4368** [comment]
@Agarwalvidu  Pease have a look and tell me whether I should continue with the left one or is there any requirements that should be fulfilled.
Thank you.

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @deepeshmlgupta  kindly tell me your thoughts regarding this.
Thank you.

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @deepeshmlgupta please tell
