### ISSUE TITLE
Title: Adding of arrows to scroll the reviews

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#727]
### Is your feature request related to a problem? Please describe.

Currently the only way to see some other review is to tap on the slick-dots on the bottom of the screen.

### Describe the solution you'd like.

Including of arrows can help navigate between reviews much more easier.

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/65a6b294-9e65-4abb-ada8-f56240513f49)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @deepeshmlgupta please kindly consider this issue.
Thanks.

**Comment by Agarwalvidu** [comment]
This is disturbing all the responsiveness of website. Keep in mind your implementation will not. Go ahead!

**Comment by VijaySamant4368** [comment]
> This is disturbing all the responsiveness of website. Keep in mind your implementation will not. Go ahead!

Thanks for the heads up, I will keep that in my mind.
