### ISSUE TITLE
chat with arthsathi  button improvement

### ISSUE THREAD

**Issue by Kbageja** [ayush-that/FinVeda#73]
on click should not pop up message instead it should just open chat  , i can fix , please assign this to me

**Comment by Ansh101112** [comment]
Hey @ayush-that please assign me this issue I want to work on that

**Comment by ayush-that** [comment]
> on click should not pop up message instead it should just open chat , i can fix , please assign this to me

Remainder: ArthSathi is made using BotPress.
I am assigning this under gssoc.
Good Luck!

**Comment by Agarwalvidu** [comment]
As PR is already closed I am closing this issue.
