### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by tat-tvam-asii** [ayush-that/FinVeda#74]
I would like to add a button in the footer section by clicking which we will be redirected to the top of the page. I will make it animated.
@ayush-that Please assign this to me under GSSOC'24

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.

**Comment by ayush-that** [comment]
Hi @tat-tvam-asii 
Add the back-to-top button that floats on the bottom right of the page but does not coincide with the ArthSathi button on the homepage.
I am assigning this issue to you under gssoc.

@Suruchibharti Please see some other issues.

**Comment by tat-tvam-asii** [comment]
> Hi @tat-tvam-asii Add the back-to-top button that floats on the bottom right of the page but does not coincide with the ArthSathi button on the homepage. I am assigning this issue to you under gssoc.
> 
> @Suruchibharti Please see some other issues.

I can't run it on my local machine, the website just keeps on loading forever
