### ISSUE TITLE
 adding a Expenditure And Savings Calculator Calculates the Savings from your income and expenditure

### ISSUE THREAD

**Issue by Ketanop321** [ayush-that/FinVeda#745]
### Is your feature request related to a problem? Please describe.

Expenditure And Savings Calculator
Calculates the Savings from your income and expenditure

### Describe the solution you'd like.

Expenditure And Savings Calculator
Calculates the Savings from your income and expenditure

### Describe alternatives you've considered.

It will be calculator which will help to calculate the expense and saving from your income

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/64177f9e-e23b-47b3-b02c-2defd38b229a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Ketanop321** [comment]
@deepeshmlgupta can you please add the label?? 🙏🙏🙏

**Comment by Ketanop321** [comment]
@deepeshmlgupta

**Comment by deepeshmlgupta** [comment]
@Ketanop321 the level will be added once you will create the PR
