### ISSUE TITLE
Fix Quiz Container in Mobile view 

### ISSUE THREAD

**Issue by Khushi-Pushkar** [ayush-that/FinVeda#748]
### What's the style idea?

WE need to fix Quiz Container in Mobile view 

### Add screenshots

![image](https://github.com/user-attachments/assets/704ea71f-876c-4e9f-a721-6db5af34a7c5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by deepeshmlgupta** [comment]
Already assigned to someone else
