### ISSUE TITLE
[Bug] Input field for all pages in news latter is not proper ! 

### ISSUE THREAD

**Issue by zalabhavy** [ayush-that/FinVeda#756]
### What happened?

I will make it attractive.
![image](https://github.com/user-attachments/assets/1dddc896-634c-4d23-9196-3ad759be0a4b)

### How can we reproduce this bug?

NA

### Desktop Information (Optional)

NA

### Urgency (Optional)

High priority

**Comment by zalabhavy** [comment]
@deepeshmlgupta @Agarwalvidu Please assign me this task !

Thank You !

**Comment by deepeshmlgupta** [comment]
@zalabhavy also see if could fix the footer too

**Comment by zalabhavy** [comment]
@deepeshmlgupta Ok !
