### ISSUE TITLE
Refactor JavaScript code 

### ISSUE THREAD

**Issue by deepak05kr18** [ayush-that/FinVeda#76]
The JavaScript code in [ajax-contact.js](https://github.com/ayush-that/FinVeda/blob/main/assets/js/ajax-contact.js) uses redundant jQuery wrapping (`$(...)`)  for `form`, `formMessages`, and other jQuery objects. This can lead to inefficiencies and unnecessary code complexity. Additionally, the code does not utilize the `$(function() { ... })` shorthand for executing code after the DOM is fully loaded, which is a recommended practice.

Improvements Proposed:

Remove redundant jQuery wrapping for improved code efficiency and readability.
Use the $(function() { ... }) shorthand for executing code after the DOM is fully loaded, enhancing the script's reliability.

I have raised this issue under GSSOC'24 as part of my contribution to the project. I am eager and committed to making meaningful contributions and enhancing the codebase. I kindly request to be assigned to this issue so that I can actively work on resolving it and contribute effectively to the project.

**Comment by ayush-that** [comment]
Hello @deepak05kr18 
I am assigning this to you under gssoc.
Have fun!
