### ISSUE TITLE
Scrollbar progress is missing

### ISSUE THREAD

**Issue by paulkrishanu4** [ayush-that/FinVeda#77]
want to add a scroll progress bar like this , assign me under gssoc'24

https://github.com/ayush-that/FinVeda/assets/169196836/c3a0cf37-31ff-4135-91a5-9427cc9903ab

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor , I have experienced in HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the issue.

**Comment by ayush-that** [comment]
> want to add a scroll progress bar like this , assign me under gssoc'24
> 
>  scroll_progress.mp4

I am assigning this to you under gssoc. 
Use proper colors and implement them on all pages.

**Comment by Agarwalvidu** [comment]
This is already done. For the same reason I am closing this issue. Thank you for contributing, looking for more issues from your side.
