### ISSUE TITLE
Adding hover effect in nav bar 

### ISSUE THREAD

**Issue by Manishar55** [ayush-that/FinVeda#79]
Hii @ayush-that 
I want to add some light hover effect in the nav bar 
Can you please assign issue to me under gssoc24

![Screenshot 2024-05-13 215552](https://github.com/ayush-that/FinVeda/assets/154615478/a7e87a06-94f8-40cd-8431-5e0fdecf0eb1)

**Comment by Azhar-0401** [comment]
*is your feature request related to a problem? Please describe.*
Currently no hover effect in nav bar

*Describe the solution you'd like*
Adding hover effect in nav bar

*Additional context*
Assign me this work under GSSoc

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me
