### ISSUE TITLE
improve Ui of the quiz result 

### ISSUE THREAD

**Issue by kairveeehh** [ayush-that/FinVeda#8]
@ayush-that the UI is bad here can display the result in a better form 
## please assign under gssoc'24
![Screenshot 2024-05-10 174324](https://github.com/ayush-that/FinVeda/assets/145572028/a9289251-a2a3-4c2a-8278-4b3c7ad1dc29)

**Comment by ayush-that** [comment]
hi @kairveeehh,
What improvements do you plan to make specifically? We already have someone adding a description to the answers in #27

**Comment by kairveeehh** [comment]
@ayush-that  add a better UI center the items and also dsiplay a chart for the result ( pie chart)

**Comment by ayush-that** [comment]
Ok, add a pie chart properly. I am assigning this issue to you under gssoc. Good Luck
