### ISSUE TITLE
[Bug] Unwanted Bullet Points in Footer on Licensing Page

### ISSUE THREAD

**Issue by AsmitaMishra24** [ayush-that/FinVeda#817]
### What happened?

On the licensing page, the footer contains list items (<li>) that are displaying unwanted bullet points. This issue affects the visual consistency and aesthetic of the footer.

### How can we reproduce this bug?

The footer list items should not display bullet points, ensuring a clean and professional appearance.

![Screenshot 2024-07-31 135326](https://github.com/user-attachments/assets/b0235457-3504-4a0e-b7db-21b2e9070780)

### Urgency (Optional)

None

**Comment by vaishnavi-agr** [comment]
I will work on this issue.

 Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by AsmitaMishra24** [comment]
> I will work on this issue.#817
> 
> Record I agree to follow this project's Code of Conduct I'm a GSSOC'24 contributor I want to work on this issue

Please make your own issue.
