### ISSUE TITLE
Footer isn't responsive

### ISSUE THREAD

**Issue by AlaynaShaheen** [ayush-that/FinVeda#818]
### What happened?

Footer doesn't look properly aligned in small screens and is not responsive.
![Screenshot 2024-07-31 183710](https://github.com/user-attachments/assets/d861b3b9-d0b6-40d3-8150-9f4bf15fec95)
![Screenshot 2024-07-31 183718](https://github.com/user-attachments/assets/3cc546ab-b79e-414f-a67b-8550d3af5e57)

### How can we reproduce this bug?

We can change the CSS of the footer and use media queries to make it responsive.
I am a contributor in GSSoC' 24. I can solve this issue by adding proper styling to footer using CSS. I have worked upon similar issues earlier , so I can work upon this to my best.
Please assign this task to me under GSSoC'24,

### Urgency (Optional)

None

**Comment by Agarwalvidu** [comment]
Already assigned
