### ISSUE TITLE
Fix active page in Navbar

### ISSUE THREAD

**Issue by ayush-that** [ayush-that/FinVeda#82]
![image](https://github.com/ayush-that/FinVeda/assets/110257939/77c452f0-a2d5-49d2-b801-3aed2ecee43e)
Fix the issue of the active page in the navbar. The quiz page is highlighted as the active page on all the pages in the navbar. We need to fix this bug.

**Comment by SiddharthaArepalli** [comment]
hey @ayush-that  I want to work on this plz Assign me this under GSSOC'24

**Comment by ayush-that** [comment]
> hey @ayush-that I want to work on this plz Assign me this under GSSOC'24

I am assigning this to you.
Good Luck!

**Comment by SiddharthaArepalli** [comment]
Thanks @ayush-that   On It 🚀

**Comment by SiddharthaArepalli** [comment]
@ayush-that  Done with the task  I have made PR ! 
 You can merge it !!
