### ISSUE TITLE
Title: Add SWP Calculator

### ISSUE THREAD

**Issue by AsmitaMishra24** [ayush-that/FinVeda#822]
### Is your feature request related to a problem? Please describe.

An SWP (Systematic Withdrawal Plan) calculator is a financial tool that helps investors plan and manage the regular withdrawal of funds from their investment corpus, typically mutual funds. SWP is used to generate a steady income stream, often for retirees or those looking to supplement their income.

### Describe the solution you'd like.

I want to add SWP Calculator.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

![349955991-e1f75620-3b6c-4d5a-9db2-9f80b879f0e4](https://github.com/user-attachments/assets/62fe80ec-4703-4d60-a9dc-1e55813f5670)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Agarwalvidu** [comment]
Go ahead!
