### ISSUE TITLE
[style]:  Alignment issue of footer section

### ISSUE THREAD

**Issue by Sourabh782** [ayush-that/FinVeda#828]
### What's the style idea?

We need to improve footer section, as elements in footer are not properly aligned with each other, creating a disbalance in footer  (In about us page)

### Add screenshots

Add screenshots
![Screenshot 2024-08-01 162406](https://github.com/user-attachments/assets/ddefc163-19c9-46f2-a8b3-9e5675d4d663)

(Alignment issue in contect us sectionof footer)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by komalnalage** [comment]
Hi @ayush-that  I would like to work on this issue.Could you assign me this task and add gssoc-ext and hactoberfest-accepted tags?

**Comment by komalnalage** [comment]
Thank you @sampadatiwari30 I will raise the PR once done

**Comment by komalnalage** [comment]
Could you assign me this task and add gssoc-ext and hactoberfest-accepted tags?

**Comment by komalnalage** [comment]
Could you add gssoc-ext and hactoberfest-accepted tags?

**Comment by komalnalage** [comment]
Hi @sampadatiwari30 can you please add level to this PR as it is not counted in the leaderboard.
