### ISSUE TITLE
errros in the whole project

### ISSUE THREAD

**Issue by kairveeehh** [ayush-that/FinVeda#83]
## urgent look into merged prs
the project doesnt open in local copy 
please fix it cause I am not able to work on my issues this way !!
@ayush-that @ayush-that

**Comment by ayush-that** [comment]
> ## urgent look into merged prs
> the project doesnt open in local copy please fix it cause I am not able to work on my issues this way !! @ayush-that @ayush-that

Could you please share screenshots?

**Comment by SiddharthaArepalli** [comment]
@ayush-that  It is working fine !!

**Comment by kairveeehh** [comment]
> > ## urgent look into merged prs
> > the project doesnt open in local copy please fix it cause I am not able to work on my issues this way !! @ayush-that @ayush-that
> 
> Could you please share screenshots?
@ayush-that  after the recent git pull this is what it shows 
![Screenshot 2024-05-14 141126](https://github.com/ayush-that/FinVeda/assets/145572028/b5535e3e-d6d4-4df2-936c-7abc2a123ead)
![Screenshot 2024-05-14 141126](https://github.com/ayush-that/FinVeda/assets/145572028/307dc9fc-e63a-4f44-80fc-71b690c581e5)

**Comment by kairveeehh** [comment]
@SiddharthaArepalli please check after the latest pull into the local repo !!!!

**Comment by SiddharthaArepalli** [comment]
@kairveeehh  It is working fine  U should in a clone the repo  seperate folder
![Uploading Screenshot 2024-05-14 142522.png…]()

**Comment by kairveeehh** [comment]
> @kairveeehh  It is working fine  U should in a clone the repo  seperate folder
> ![Uploading Screenshot 2024-05-14 142522.png…]()
> 

@SiddharthaArepalli your screenshot isn't uploaded and yes I have separate folder for it obv , run git pull and then try as I made a local copy today only so maybe you have a previous one and ot works fine

**Comment by SiddharthaArepalli** [comment]
![Screenshot 2024-05-14 143240](https://github.com/ayush-that/FinVeda/assets/140429954/0f9af349-6641-4fe1-9c80-d4f235b0ea21)
@kairveeehh

**Comment by kairveeehh** [comment]
> ![Screenshot 2024-05-14 143240](https://github.com/ayush-that/FinVeda/assets/140429954/0f9af349-6641-4fe1-9c80-d4f235b0ea21)
> @kairveeehh 

Those 25 problems aren't affecting? In my laptop index.html isn't opening like it's taking forever...@SiddharthaArepalli

**Comment by kairveeehh** [comment]
> > ![Screenshot 2024-05-14 143240](https://github.com/ayush-that/FinVeda/assets/140429954/0f9af349-6641-4fe1-9c80-d4f235b0ea21)
> > @kairveeehh 
> 
> Those 25 problems aren't affecting? In my laptop index.html isn't opening like it's taking forever...@SiddharthaArepalli 

I will try deleting the fork and running the whole thing again from scratch once then

**Comment by ayush-that** [comment]
> > > ![Screenshot 2024-05-14 143240](https://private-user-images.githubusercontent.com/140429954/330359723-0f9af349-6641-4fe1-9c80-d4f235b0ea21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Nzc4MzMsIm5iZiI6MTcxNTY3NzUzMywicGF0aCI6Ii8xNDA0Mjk5NTQvMzMwMzU5NzIzLTBmOWFmMzQ5LTY2NDEtNGZlMS05YzgwLWQ0ZjIzNWIwZWEyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwOTA1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWYyMTJmYTJhMmZhNjNjOWNhMjg5YTVlYTQzNzYyNTM1ZmRjYzJhNmUyYTQyOTJhODc0OGU1NTgyMTQ2Y2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VwtKmhwEdg2EDxIFYQGVdAhWQFMdxoh8VaOH9XYIpA0)
> > > @kairveeehh
> > 
> > 
> > Those 25 problems aren't affecting? In my laptop index.html isn't opening like it's taking forever...@SiddharthaArepalli
> 
> I will try deleting the fork and running the whole thing again from scratch once then

Please do that.
It works for me.

**Comment by kairveeehh** [comment]
> > > > ![Screenshot 2024-05-14 143240](https://private-user-images.githubusercontent.com/140429954/330359723-0f9af349-6641-4fe1-9c80-d4f235b0ea21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Nzc4MzMsIm5iZiI6MTcxNTY3NzUzMywicGF0aCI6Ii8xNDA0Mjk5NTQvMzMwMzU5NzIzLTBmOWFmMzQ5LTY2NDEtNGZlMS05YzgwLWQ0ZjIzNWIwZWEyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwOTA1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWYyMTJmYTJhMmZhNjNjOWNhMjg5YTVlYTQzNzYyNTM1ZmRjYzJhNmUyYTQyOTJhODc0OGU1NTgyMTQ2Y2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VwtKmhwEdg2EDxIFYQGVdAhWQFMdxoh8VaOH9XYIpA0)
> > > > @kairveeehh
> > > 
> > > 
> > > Those 25 problems aren't affecting? In my laptop index.html isn't opening like it's taking forever...@SiddharthaArepalli
> > 
> > I will try deleting the fork and running the whole thing again from scratch once then
> 
> Please do that.
> It works for me.

Sure 
Thanks for helping me out @ayush-that @SiddharthaArepalli 😃😃

**Comment by SiddharthaArepalli** [comment]
@kairveeehh np

**Comment by kdanjana** [comment]
@ayush-that Even I am facing the same problem, I have  forked this repo and cloned into my vscode. When I opened the index.html it is taking forever to load, 
<img width="852" alt="sthg" src="https://github.com/ayush-that/FinVeda/assets/103878831/4a5f3744-ab04-4f30-ae23-aa2f31d4d055">
can you please tell me what to do now.

**Comment by kairveeehh** [comment]
> @ayush-that Even I am facing the same problem, I have forked this repo and cloned into my vscode. When I opened the index.html it is taking forever to load, <img alt="sthg" width="852" src="https://private-user-images.githubusercontent.com/103878831/330384109-4a5f3744-ab04-4f30-ae23-aa2f31d4d055.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODIxMjksIm5iZiI6MTcxNTY4MTgyOSwicGF0aCI6Ii8xMDM4Nzg4MzEvMzMwMzg0MTA5LTRhNWYzNzQ0LWFiMDQtNGYzMC1hZTIzLWFhMmYzMWQ0ZDA1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMDE3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjJiNjlkYzE5NmJmMjU2NTFkNjdmMjBiZGFhM2E4MDEyMGY4Njg3ZjYxYzQ3N2ZlYTU4MDczYjc0NjlhOWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gR7Ev_MEgMgCerBL9JLWYiM9CsyHEKOPI5YA1UZq0A0"> can you please tell me what to do now.

@ayush-that  @kdanjana  +++ facing the same

**Comment by ayush-that** [comment]
@kdanjana 
@kairveeehh 
Have you tried cloning the repo again?

**Comment by kairveeehh** [comment]
@ayush-that yes I did , deleted my forked repo , forked again , cloned again in a new folder still the same error is coming 
![Screenshot 2024-05-14 163315](https://github.com/ayush-that/FinVeda/assets/145572028/772b8d8f-e632-4b80-9518-56318cf08fed)
you can see the time @ayush-that

**Comment by kdanjana** [comment]
@ayush-that 
yes I have.

**Comment by kdanjana** [comment]
@ayush-that 
From what I understood when I changed the path of html and css from 
<link rel="stylesheet" href="assets/css/animate.css" />
to <link rel="stylesheet" href="/assets/css/animate.css" />
it is working partially, i.e I think the path to those files is causing error.

**Comment by kairveeehh** [comment]
> @ayush-that From what I understood when I changed the path of html and css from
> 
> to it is working partially, i.e I think the path to those files is causing error.

@kdanjana  please elaborate so that i can fix it as well

**Comment by kdanjana** [comment]
@kairveeehh 
In our index.html under the styles section the css files are mentioned as
 <link rel="stylesheet" href="assets/css/style.css" />
      <link rel="stylesheet" href="assets/css/quiz.css" />
      <link rel="stylesheet" href="assets/css/popup.css" />
when we got error "could find the css files" in the console, I changed the direction to reflect their heirarchy in project structure like this 
 <link rel="stylesheet" href="/assets/css/style.css" />
      <link rel="stylesheet" href="/assets/css/quiz.css" />
      <link rel="stylesheet" href="/assets/css/popup.css" />
, so now its working partially

**Comment by SiddharthaArepalli** [comment]
@kdanjana @kairveeehh  How I am getting then ??

**Comment by kdanjana** [comment]
@SiddharthaArepalli 
Yeah I think me and @kairveeehh  are the only ones facing this issue.

**Comment by tat-tvam-asii** [comment]
> @SiddharthaArepalli Yeah I think me and @kairveeehh are the only ones facing this issue.

I am also facing the same issue

**Comment by tat-tvam-asii** [comment]
@kairveeehh you found how to fix this ?
