### ISSUE TITLE
[style]: In nav Bar Adding Icon First and title next 

### ISSUE THREAD

**Issue by Saipradyumnagoud** [ayush-that/FinVeda#830]
### What's the style idea?

We need to improve  
in tthe sccren shot the icon should be front and the  nav should be next

### Add screenshots

![image](https://github.com/user-attachments/assets/bdd6b4e4-0fb8-4bda-8b1e-4f194caf12af)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Saipradyumnagoud** [comment]
@ayush-that Can you Please assign me the issue

**Comment by Agarwalvidu** [comment]
Not needed!
