### ISSUE TITLE
Submission behavior of exp and savings calc

### ISSUE THREAD

**Issue by Jasleen1210** [ayush-that/FinVeda#834]
### What happened?

![image](https://github.com/user-attachments/assets/bf067e46-2d12-4b92-90a9-d145457974e5)
Submission on empty fields should be disabled
same behavior exists for other calculators too (Insurance Calculator and EMI Calculator)

### How can we reproduce this bug?

-

### Urgency (Optional)

None

**Comment by istanujbhatia** [comment]
should i start working on this or to be done only if assigned
