### ISSUE TITLE
Overlapping Cards on About Us Page in Mobile View

### ISSUE THREAD

**Issue by Anni299** [ayush-that/FinVeda#837]
### What happened?

The about us page needs to be responsive. The cards on the about us page are overlapping with each other in the mobile view. 
![Screenshot 2024-08-01 212015](https://github.com/user-attachments/assets/6c378580-38d0-41b6-bd04-f598032e5fe0)
![Screenshot 2024-08-01 212023](https://github.com/user-attachments/assets/71aa54d6-979e-4e52-abc5-f2f602529104)

### How can we reproduce this bug?

Go to about us page in mobile view.

### Urgency (Optional)

None

**Comment by Utsavladia** [comment]
I would like to fix it under GSSOC
