### ISSUE TITLE
Add Icons to Footer 

### ISSUE THREAD

**Issue by sailaja-adapa** [ayush-that/FinVeda#859]
### Is your feature request related to a problem? Please describe.

Hello Project Admin
I would like to add icons to Footer
Can you assign me this issue under GSSOC'24 @ayush-848 

### Describe the solution you'd like.

![IMG_20240804_113000](https://github.com/user-attachments/assets/e72eca03-fe56-428d-ba6a-60531882aba0)
I would like to add icons to Footer in an attractive way

### Describe alternatives you've considered.

It will make our website to look Attractive 

### Add any other context or screenshots about the feature request here.

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by ayush-848** [comment]
> ### Is your feature request related to a problem? Please describe.
> Hello Project Admin I would like to add icons to Footer Can you assign me this issue under GSSOC'24 @ayush-848
> 
> ### Describe the solution you'd like.
> ![IMG_20240804_113000](https://private-user-images.githubusercontent.com/161804629/354879564-e72eca03-fe56-428d-ba6a-60531882aba0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NTE2OTcsIm5iZiI6MTcyMjc1MTM5NywicGF0aCI6Ii8xNjE4MDQ2MjkvMzU0ODc5NTY0LWU3MmVjYTAzLWZlNTYtNDI4ZC1iYTZhLTYwNTMxODgyYWJhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQwNjAzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Nzg3N2FlYjJjMmRhMTU3MDk2MDBhNTI5YmMyYjY0MjAwMGRiOGZlY2E3ODZkZDg1NDA4YWU0NzYxNjM2NmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wv3xCS_jvZ4EuFp6-hkeFZ45uMSeQJn75qN1YAXxqxs) I would like to add icons to Footer in an attractive way
> 
> ### Describe alternatives you've considered.
> It will make our website to look Attractive
> 
> ### Add any other context or screenshots about the feature request here.
> .
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have checked the existing issues
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue
> * [x]  I have attached the Screenshort regarding my issue

You have tagged the wrong person 
I am not the maintainer of this project.

**Comment by sailaja-adapa** [comment]
Ohh I am so sorryy @ayush-848

**Comment by sailaja-adapa** [comment]
.

**Comment by ayush-848** [comment]
> Ohh I am so sorryy @ayush-848

no problem

**Comment by sailaja-adapa** [comment]
Thank you ☺️
