### ISSUE TITLE
Icons in 'Contact Us' Section Not Visible in Footer of Blogs

### ISSUE THREAD

**Issue by Anni299** [ayush-that/FinVeda#867]
### What happened?

The location dot, globe and email icon is not visible in the contact us section in the footer of all the blogs.

![Screenshot 2024-08-05 004947](https://github.com/user-attachments/assets/3c42c64f-ac02-4fb1-a73d-422f0d0de76a)

### How can we reproduce this bug?

1) Go to blogs page and open any blog.
2) See the footer

### Urgency (Optional)

None

**Comment by Codewithmeowmeow** [comment]
Kindly assign me this .i would love to work on this issue

**Comment by chaheti89** [comment]
Problem statement-To resolve the issue of missing location, globe, and email icons in the "Contact Us" section,
Solution- I will verify if the icon library is included via the correct local resource, then add or update the library's link in the HTML header, ensuring that the icons can load correctly. 
Can I work on this issue?
