### ISSUE TITLE
Quiz can be submitted without answering a single question

### ISSUE THREAD

**Issue by anmantout** [ayush-that/FinVeda#87]
Issue: The user is able to submit the quize without answering any question. I have attached screenshot for reference.
![image](https://github.com/ayush-that/FinVeda/assets/147123118/0fb009a5-4767-4817-85e1-55900911001c)
Two approaches can be utilized for this:
Approach 1. In Explanation of answers which is currently blank we can add Not Answered.
Approach 2. We can raise an alert indicating that all the questions need to be answered in order for the quiz to be submitted successfully.

I would like to work on this issue. Please assign it to me under GSSOC' 24 @ayush-that . Thanks!

**Comment by ayush-that** [comment]
Assigning this issue to @anmantout 
Have fun!

**Comment by Agarwalvidu** [comment]
This is already done. For the same reason I am closing this issue. Thank you for contributing, looking for more issues from your side.
