### ISSUE TITLE
Currency Converter 

### ISSUE THREAD

**Issue by mahek0620** [ayush-that/FinVeda#873]
### Is your feature request related to a problem? Please describe.

A Currency Converter is an essential tool that provides real-time exchange rates between different currencies. It allows users to quickly and accurately convert one currency into another, making it particularly useful for travelers, international business transactions, and anyone dealing with foreign currencies.

### Describe the solution you'd like.

Input Fields:

Amount: The amount of money to convert.
From Currency: The currency to convert from.
To Currency: The currency to convert to.
Output:

Converted Amount: The equivalent amount in the target currency based on the current exchange rate.

### Describe alternatives you've considered.

Real-Time Exchange Rates: Utilize live exchange rates to ensure accurate conversions.
Historical Data: Access historical exchange rates to see how rates have changed over time.
Multi-Currency Conversion: Convert one amount into multiple currencies at once.
Customizable Settings: Allow users to set a preferred currency or frequently used currency pairs.
Rate Alerts: Notify users when a specific exchange rate is reached.

### Add any other context or screenshots about the feature request here.

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [ ] I have attached the Screenshort regarding my issue

**Comment by mahek0620** [comment]
@ayush-that can you assign this to me

**Comment by nishtha-902** [comment]
@ayush-that could you please assign me this issue under GSSoC'24 Extd.

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @ayush-that

**Comment by nishtha-902** [comment]
@mahek0620 What is the main issue/bug that is assigned to us raised by you?
