### ISSUE TITLE
[style]:  Footer Section issue

### ISSUE THREAD

**Issue by Sourabh782** [ayush-that/FinVeda#877]
### What's the style idea?

We need to improve  the footer section
In footer section whole website is center aligned, but the test content at footer is all the way aligned to the left

### Add screenshots

Add screenshots
![Screenshot 2024-08-05 194343](https://github.com/user-attachments/assets/d661a24a-6ca0-4dd5-9d37-414cb22b1965)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Agarwalvidu** [comment]
Fixed!
