### ISSUE TITLE
[Bug] Footer's Margin not proper in small screen 

### ISSUE THREAD

**Issue by zalabhavy** [ayush-that/FinVeda#879]
### What happened?

![image](https://github.com/user-attachments/assets/cf060d4f-2a68-4050-8a7b-ec8e86290849)

I will give margin left for better look.

### How can we reproduce this bug?

NA

### Desktop Information (Optional)

NA

### Urgency (Optional)

High priority

**Comment by zalabhavy** [comment]
@Agarwalvidu @deepeshmlgupta Please assign me this task !

Thank You !

**Comment by Agarwalvidu** [comment]
Fixed!
