### ISSUE TITLE
FAQ not answers opening 

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#889]
### What happened?

Clicking the FAQ button does not open the FAQ answers min the homepage.

### How can we reproduce this bug?

https://github.com/user-attachments/assets/c7cb10ca-7977-4585-9c51-f4a05504161a

### Urgency (Optional)

Medium priority

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @deepeshmlgupta please check this out.

**Comment by deepeshmlgupta** [comment]
@VijaySamant4368 it's working fine. Do check it again
