### ISSUE TITLE
Improving the UI of the tools page for the 2 calculators

### ISSUE THREAD

**Issue by spacedust26** [ayush-that/FinVeda#89]
I believe the website needs a good UI for the Mutual Fund Investment Calculator and EMI calculator which could enhance the overall look of the page under the tools tab. I'd like to enhance it pertaining to the theme of the website. @ayush-that could you please assign this issue to me? Thank you.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by ayush-that** [comment]
Assigning this issue under gssoc
Implement it well, @spacedust26

**Comment by spacedust26** [comment]
sure @ayush-that , I'll start working on it.

**Comment by Agarwalvidu** [comment]
As PR is already merged I am closing this issue.
