### ISSUE TITLE
Adding a `clear` button on every calculator

### ISSUE THREAD

**Issue by Ketanop321** [ayush-that/FinVeda#898]
### Is your feature request related to a problem? Please describe.

adding clear button on every calculator will make it easy for user to re-enter the details.

### Describe the solution you'd like.

Adding a clear button like GDP calculator

### Describe alternatives you've considered.

Adding a clear button

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/45f4f435-5e0a-4ef0-aa3a-6af590add627)
clear button like thin in GDP calculator

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Ketanop321** [comment]
@deepeshmlgupta

**Comment by Ketanop321** [comment]
@deepeshmlgupta sir do you want this feature

**Comment by deepeshmlgupta** [comment]
Yes, Go ahead and start working on this issue
