### ISSUE TITLE
Interactivity 

### ISSUE THREAD

**Issue by Bhoovi333** [ayush-that/FinVeda#9]
Hey
 I think the site is responsive, also I love the simplicity you put in designs,
But what I feels is to make site:
 More attractive so that more audience gets involved,
designs can be improved,
More colours to be added,

If you select me, then I can add designs,  and enhance the creativity of site by improving css.

**Comment by ayush-that** [comment]
Hi @Bhoovi333,
Could you be more specific about what things are you planning to change?

**Comment by Bhoovi333** [comment]
Oky, so firstly I'll do some work on css and design, something related to economics,money,finance designs,
Then,in tools and other options background can be enhanced,so that it'll be more creative.

**Comment by ayush-that** [comment]
> Oky, so firstly I'll do some work on css and design, something related to economics,money,finance designs, Then, in tools and other options background can be enhanced,so that it'll be more creative.

OK! I am assigning this issue to you.
You may start working, all the best.
Please adhere to our colour scheme.

**Comment by Bhoovi333** [comment]
So, would you send me any mail related to this?

**Comment by ayush-that** [comment]
> So, would you send me any mail related to this?

I have already assigned it to you.
You may start working now.
All the best.

**Comment by Harshitazz** [comment]
i want to contribute too.

**Comment by sid346184** [comment]
Hey, I wanna contribute to it under GSSOC. Please assign
