### ISSUE TITLE
adding icons to footer

### ISSUE THREAD

**Issue by Ketanop321** [ayush-that/FinVeda#926]
### What happened?

adding icons to all footer 

### How can we reproduce this bug?

Only home page have icons in there footer

### Desktop Information (Optional)

window11

### Urgency (Optional)

None

**Comment by deepeshmlgupta** [comment]
@Ketanop321 add the icon in all the pages of the footer similar to the home page footer icon.

**Comment by Codewithmeowmeow** [comment]
Kindly assign it to me i would love to work on this issue.

**Comment by Ketanop321** [comment]
> Kindly assign it to me i would love to work on this issue.

why do you want to contribute into this project , this is now not even part of extd gssoc or hacktoberfest
