### ISSUE TITLE
Feature[Login/Register]

### ISSUE THREAD

**Issue by kalyanikhushi** [ayush-that/FinVeda#93]
@ayush-that assign me this under GSSoC'24 i want to create Login/Register page as i have created a travel website and also have a experience in this 
![Screenshot 2024-05-14 110126](https://github.com/ayush-that/FinVeda/assets/159093860/f05ced80-eb86-4159-a4e1-b05e6b918054)

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by ayush-that** [comment]
Same as #20 
I am closing this issue.
