### ISSUE TITLE
✔️Enhancement: Improving the "Testimonials" Section !

### ISSUE THREAD

**Issue by aslams2020** [ayush-that/FinVeda#931]
### Is your feature request related to a problem? Please describe.

Hey @deepeshmlgupta @Agarwalvidu 

I want to improve the current Testimonials section in the website 
Currently it has several needs of improvement 
- There is no image for the author on testimonials card
- There are no hovering effects to the cards to make it engaging 
- The Testimonials section is not following the website's theme
- The arrows < > present are too big 

I want to make the above changes and some other's as needed to make the testimonials page more engaging and attractive !

Here's the current section : 

![image](https://github.com/user-attachments/assets/f5214cdd-8d8d-4206-ba78-02f16d194b76)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by aslams2020** [comment]
@deepeshmlgupta @Agarwalvidu I want to work on this.

**Comment by deepeshmlgupta** [comment]
@aslams2020 do make sure that your changes does not affect the responsiveness of the website.
Do, checkout the responsiveness of the website before submitting the PR.
