### ISSUE TITLE
Minor style error

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#938]
### What happened?

In the tools page, for small screens, the text are not aligned properly in the buttons.

### How can we reproduce this bug?

![image](https://github.com/user-attachments/assets/d84d624e-9c01-4058-b937-e03e130201a7)

### Urgency (Optional)

Low priority

**Comment by VijaySamant4368** [comment]
@Agarwalvidu @deepeshmlgupta please look into this.

**Comment by nishtha-902** [comment]
Could you please assign me this issue under GSSoC'24 Extd.

**Comment by vaibhavguptahere** [comment]
Assign me this issue, I will sort it
