### ISSUE TITLE
🌟 Improve FAQ Section on the Home Page 

### ISSUE THREAD

**Issue by Tejashri-Taral** [ayush-that/FinVeda#946]
### What's the style idea?

Hey @deepeshmlgupta and @Agarwalvidu  
There are several things need to improve in the current FAQ Page.

-The FAQ section is not following the websites theme.
-The FAQ questions are not following the theme too.
-Also I want to add some more comprehensive questions to the FAQ section.

### Add screenshots

![image](https://github.com/user-attachments/assets/b63ccdc9-8591-4999-8e18-4b6a3fb2e47a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Tejashri-Taral** [comment]
@deepeshmlgupta @Agarwalvidu

**Comment by Shalinis19137** [comment]
In FAQ section we add : 
1. who can use FinVeda ?
2.  How much its trusted population ?
Assign this to me

**Comment by Shalinis19137** [comment]
Thanks sir.
