### ISSUE TITLE
Enhancement: Improve Contact Footer Page

### ISSUE THREAD

**Issue by kalyanikhushi** [ayush-that/FinVeda#95]
![Screenshot 2024-05-14 112905](https://github.com/ayush-that/FinVeda/assets/159093860/f817cced-de1e-42e2-8c6a-7a5031515fe6)
@ayush-that  the contact user in the footer page is not clickable, i will add hyperlink to contact us, 
 which will enhance user experience and when clicked, it should redirect users to the specified page for contacting us.

**Comment by ayush-that** [comment]
> ![Screenshot 2024-05-14 112905](https://private-user-images.githubusercontent.com/159093860/330462870-f817cced-de1e-42e2-8c6a-7a5031515fe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTYwMjIsIm5iZiI6MTcxNTY5NTcyMiwicGF0aCI6Ii8xNTkwOTM4NjAvMzMwNDYyODcwLWY4MTdjY2VkLWRlMWUtNDJlMi04YzZhLTdhNTAzMTUxNWZlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxNDA4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2Y4NDE2MDcxY2E2MGY0NmRiMmJjYmM0M2VkM2IwYTU4MWY2NDdiMGE0MTU3ZGRkN2ZiMmZhODMxMWZlZTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fpH_mRBaNpiy8CggiXz6BZcd3YPXsL-WcKAdMSjbXQw) @ayush-that the contact user in the footer page is not clickable, i will add hyperlink to contact us, which will enhance user experience and when clicked, it should redirect users to the specified page for contacting us.

Assigning this under gssoc
Implement on all pages
Have Fun!

**Comment by kalyanikhushi** [comment]
yuppp :))

**Comment by DNahar74** [comment]
I would like to work on this issue please assign it to me.

**Comment by aryapandeyy22** [comment]
Could you assign this to me under gssoc'24

**Comment by kalyanikhushi** [comment]
@ayush-that you didn't assign me see into that once

**Comment by SiddharthaArepalli** [comment]
Hey @ayush-that  
@kalyanikhushi  is facing some issue in updating the links So , I want u to assign me the issue I have already coded the task,
Once u assign me I can make a pullrequest So , I request u to assign me !!

**Comment by kalyanikhushi** [comment]
![Screenshot 2024-05-15 180815](https://github.com/ayush-that/FinVeda/assets/159093860/bb0e76c7-dbbd-47cb-a7b8-a69bfcef869b)
@ayush-that Email redirection in footer isn't working despite proper setup. Other functionalities are fine, only issue is with email part.

**Comment by Agarwalvidu** [comment]
This issue is already resolved, for the same reason I am closing this issue.
