### ISSUE TITLE
adding icon at login and signup 

### ISSUE THREAD

**Issue by BCA-444-9758-Ketan** [ayush-that/FinVeda#951]
### Is your feature request related to a problem? Please describe.

![Screenshot 2024-08-09 231821](https://github.com/user-attachments/assets/0e1fe989-3782-405b-a9b2-5a7bad3aa7ba)

![Screenshot 2024-08-09 231718](https://github.com/user-attachments/assets/4635848e-1ce0-4303-ad9c-a90c3114bf44)

### Describe the solution you'd like.

icons for login and signup

### Describe alternatives you've considered.

icons for login and signup

### Add any other context or screenshots about the feature request here.

attached above

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Ketanop321** [comment]
@deepeshmlgupta

**Comment by Codewithmeowmeow** [comment]
Hey i would love to work on this issue kindly assign it to me.

**Comment by ragineedarade** [comment]
hy i want to work on this ishue

**Comment by Ketanop321** [comment]
> hy i want to work on this ishue

@ragineedarade why do you want to contribute to this project, this is now not even part of  gssoc-extd. or hacktober fest
