### ISSUE TITLE
clear button in syestamtic withdrawl calc is not working

### ISSUE THREAD

**Issue by Ketanop321** [ayush-that/FinVeda#955]
### What happened?

https://github.com/user-attachments/assets/926a20a4-0f5d-4434-b1cd-712ea77215f9

### How can we reproduce this bug?

make clear btn functional

### Desktop Information (Optional)

chrome

### Urgency (Optional)

None

**Comment by jyothimanoj12** [comment]
Can you assign me me this issue

**Comment by Ketanop321** [comment]
> Can you assign me me this issue

@jyothimanoj12 why do you want to contribute in this , this project is now not even part of gssco extd or hacktober fest
