### ISSUE TITLE
The hover effect on service cards

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#958]
### What happened?

I am not really sure if the hovering effect on the service cards is intentional or not.

### How can we reproduce this bug?

Hovering over the service cards in the home page, we get:
![image](https://github.com/user-attachments/assets/ee42bcea-d462-49aa-852c-a5bc1cc529af)

### Urgency (Optional)

Low priority

**Comment by ayushiu** [comment]
please assign this issue to me
