### ISSUE TITLE
Change Quiz Results: Incorrect Answers Red

### ISSUE THREAD

**Issue by kalyanikhushi** [ayush-that/FinVeda#96]
@ayush-that  assign me this under GSSoC'24 to make wrong answers in quizzes red, not green, which helps users see mistakes, and as both correct and incorrect are in green color, users may get confused to differentiate between correct and incorrect answers
![Screenshot 2024-05-14 194021](https://github.com/ayush-that/FinVeda/assets/159093860/7250000d-6d02-4da0-b879-c7ae63bfd807)

**Comment by ayush-that** [comment]
Already being implemented, check #27
