### ISSUE TITLE
Underlining of the Footer

### ISSUE THREAD

**Issue by VijaySamant4368** [ayush-that/FinVeda#960]
### What happened?

In the footer, the links under "Quick Links" and "Resources" get underlined when hovered, while the links under "Contact Us" do not.

### How can we reproduce this bug?

https://github.com/user-attachments/assets/2e87fb0a-15df-433b-975d-d65a645e91c5

### Urgency (Optional)

Low priority

**Comment by crazyshrut** [comment]
hey @ayush-that , assign this to me.
I will raise the pr on the same day.

**Comment by Pinkigupta05** [comment]
hey @VijaySamant4368 ,assign this to me.

**Comment by nishtha-902** [comment]
Assign me this isssue I will solve this as soon as possible

**Comment by Devanshu1603** [comment]
Assign me this issue I will solve this as soon as possible

**Comment by VijaySamant4368** [comment]
Please assign this to me asap.

**Comment by deepeshmlgupta** [comment]
no, update since last week so closing
