### ISSUE TITLE
Login/Register Modal Not Mobile Responsive

### ISSUE THREAD

**Issue by Anni299** [ayush-that/FinVeda#963]
### What happened?

The Login/Register modal is not mobile responsive and the content is going out of the screen.
![image](https://github.com/user-attachments/assets/bc932a43-9720-4a3e-a2c7-0cca5236657a)

### How can we reproduce this bug?

Click on the Login/Register Button in mobile view.

### Urgency (Optional)

None

**Comment by SHARKSEA16** [comment]
I can fix this login/register issue #963 if you grant me the access
