### ISSUE TITLE
Title:  Help desk Integration

### ISSUE THREAD

**Issue by rachittpatel** [ayush-that/FinVeda#967]
### Is your feature request related to a problem? Please describe.

It is an excellent platform for version control and collaboration, it often lacks a robust system for providing and managing user support. This can lead to scattered conversations, inefficient ticket tracking, and a less than optimal user experience.

### Describe the solution you'd like.

Integrate a comprehensive help desk system into this project. This would provide a centralized platform for users to submit support requests, track their progress, and receive timely assistance.

### Describe alternatives you've considered.

A centralized help desk would provide a better user experience and faster response times.

### Add any other context or screenshots about the feature request here.

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [x] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
no, update since last week so closing

**Comment by rachittpatel** [comment]
[codevita-20241018T142327Z-001.zip](https://github.com/user-attachments/files/17436870/codevita-20241018T142327Z-001.zip)

this is the files for integreated help desk.
