### ISSUE TITLE
[style]: FAQ Section

### ISSUE THREAD

**Issue by rounakdey6** [ayush-that/FinVeda#969]
### What's the style idea?

We need to improve  FAQ section , in Navbar section , there will be a help center button , and FAQ page will be inside the help center

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by arpit74170** [comment]
hi ,please assign this one issue to me as i had build 3 websites ,i am suitable to fix this role more accurately.

**Comment by rounakdey6** [comment]
please level this issue and assign it to me
