### ISSUE TITLE
In tools Calculate button color is not okay and options are not in line

### ISSUE THREAD

**Issue by Chelseasingla1** [ayush-that/FinVeda#97]
I would like to correct this feature:
![image](https://github.com/ayush-that/FinVeda/assets/129886894/3d648407-f804-4107-ab0c-83dddf633622)
this calculate button color is not looking good
![image](https://github.com/ayush-that/FinVeda/assets/129886894/98b70b1e-cb2d-4350-aca7-ce3ae2abbdec)
These are not in proper line
Please assign me this issue under GSSoC'24.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by Agarwalvidu** [comment]
This has already been done. Thank you for raising issue I am closing this, please look more into updated website and raise more.
