### ISSUE TITLE
[style]: Login and Signup section not matching website theme and can redesign

### ISSUE THREAD

**Issue by coderrrx-Brijesh** [ayush-that/FinVeda#971]
### What's the style idea?

We need to improve  login and signup section/page. That page can be further improved as per the current website theme, Currently it doesn't match website theme and seems to be incomplete. I want redesign the login and signup section and wants to add more details in it with some animations. For Ex: It says login to join us... which is not a correct, if someone login they have already joined you. Page is using completely white background but theme should be white along with blue.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Devanshu1603** [comment]
@ayush-that can you assign this to me under gssoc-ext level.will be happy to contribute

**Comment by deepeshmlgupta** [comment]
no, update since last week so closing
