### ISSUE TITLE
Arrows are not looking good in blogs section 

### ISSUE THREAD

**Issue by Chelseasingla1** [ayush-that/FinVeda#98]
I would like to work on feature:
![image](https://github.com/ayush-that/FinVeda/assets/129886894/df49f084-285a-4f44-85a8-e2adc9951731)

Here arrows are not that proper.
Please assign me this issue under GSSoC'24.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by ShahHetviIT** [comment]
I'm keen on taking the helm of the FinVeda project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm well-equipped to drive meaningful progress on this initiative. Kindly assign me to this issue through GSSOC.

**Comment by ayush-that** [comment]
Assigning under gssoc
HF @Chelseasingla1

**Comment by Agarwalvidu** [comment]
As PR is already assigned I am closing this issue.
