### ISSUE TITLE
[Bug Title here] Chatbot Fails to Maintain Conversation Flow

### ISSUE THREAD

**Issue by snehhhcodes** [ayush-that/FinVeda#980]
### What happened?

When interacting with the chatbot, it responds correctly to the first query but greets the user again upon receiving a follow-up query, instead of continuing the conversation. The bot fails to maintain context between messages, leading to a disjointed experience. Additionally, there is no reset button available for the user to manually restart the conversation, causing further inconvenience.

User Difficulties:

1.) The chatbot resets after each message, making it hard for users to have meaningful, continuous conversations.
2.) Lack of a reset button leaves users unable to refresh or restart the chat flow manually.
3.) This can lead to frustration and confusion for users, as they may have to reintroduce themselves or their queries repeatedly.
[screen-capture .webm](https://github.com/user-attachments/assets/5c22a8d0-7725-4118-b771-8951bee7e9cf)

### How can we reproduce this bug?

I don’t have any experience in building chatbots from scratch, but I can create one for you using a tool that I’ve been working with.

I can enhance the conversation flow of the chatbot to ensure it doesn’t greet users repeatedly after each query. By improving how the bot handles user interactions, it will be able to maintain context and provide relevant responses, creating a more natural and engaging experience. This change will significantly reduce user frustration, as they won't have to deal with unnecessary greetings after each question.
Additionally, I will implement a reset button that users can easily access to restart the conversation at any time. This feature will give users greater control over their interactions and make it more convenient for them to reinitiate the chat when desired, further improving the overall user experience.

### Urgency (Optional)

Medium priority

**Comment by snehhhcodes** [comment]
if you find the issue suitable please assign this to me under the appropriate labels and level.

**Comment by ayush-that** [comment]
The bot is made using bot press. It can be improved on. If you can make a bot on botpress then it would be awesome.
