### ISSUE TITLE
Title: Design a logo

### ISSUE THREAD

**Issue by rounakdey6** [ayush-that/FinVeda#981]
### Is your feature request related to a problem? Please describe.

in navbar there is no logo 

### Describe the solution you'd like.

i want to add the logo

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

![image](https://github.com/user-attachments/assets/ce8f0b0a-6f6e-4b73-abc8-0cb0d680a796)
it will look like this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by rounakdey6** [comment]
Please assign this issue to me

**Comment by ayushiu** [comment]
i am a good logo designer so please assign this issue to me under gssoc extended

**Comment by Deekshashakyawal** [comment]
Firstly design the logo to look better and appropriate and comment here with screenshots , the better logo will be chosen.

**Comment by garimabhayanaa** [comment]
Please assign this issue to me under gssoc-ext. A preview of the logo is attached below
<img width="659" alt="logo" src="https://github.com/user-attachments/assets/52a7f616-248d-4740-805b-6ca5310d4210">

**Comment by garimabhayanaa** [comment]
how do i submit the logo since i cannot make a pull request for this?
