### ISSUE TITLE
Title: add horizontal scrollbar

### ISSUE THREAD

**Issue by ritikm31** [ayush-that/FinVeda#985]
### Is your feature request related to a problem? Please describe.

i want to add horizontal scroll on the testimonials when someone hover on it and scroll their trackpad vertically the testimonials scrolls horizontally with them.

### Describe the solution you'd like.

horizontal scroll while scrolling vertical on trackpad.

### Describe alternatives you've considered.

scroller for horizontal scrolling while doing vertical scroll on mouse or trackpad.

### Add any other context or screenshots about the feature request here.

![Screenshot (44)](https://github.com/user-attachments/assets/b651594f-26dd-433a-a302-1eef7238f7f3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by deepeshmlgupta** [comment]
no response, so closing this issue

**Comment by ritikm31** [comment]
hey, i'm here for this sorry for the wait  can you reopen it
