### ISSUE TITLE
[FEATURE] Add 'Scroll-to-Top' Button 

### ISSUE THREAD

**Issue by yashmandi** [ayush-that/FinVeda#99]
**Description:**
Introduce a Scroll-to-Top button to enhance user navigation within our application/website. This feature enables users to swiftly return to the top of lengthy pages.

Would like to work on this task, request you to assign me this issue under GSSoC '24 :)

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by vardhini3103** [comment]
Hi @yashmandi please allow me to work on this issue. Please add the appropriate label GSSoC.
