### ISSUE TITLE
📝[DOCS] <suggestion title>contributing part

### ISSUE THREAD

**Issue by neeru24** [ayush-that/FinVeda#990]
### Issue Description

Here, in the readme.md... This can be made good like separating the text and code which will help to use easily.

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/2d0cc1ca-e59a-4791-8c21-8c7f946bb022)

### Checklist

- [X] I have checked the existing issues.
- [X] I have read the Contributing Guidelines.
- [X] I have read the Code Of Conduct.
- [X] The changes doesn't break the code

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by neeru24** [comment]
> ### Issue Description
> 
> Here, in the readme.md... This can be made good like separating the text and code which will help to use easily.
> 
> ### Screenshots or Examples (if applicable)
> 
> ![image](https://github.com/user-attachments/assets/2d0cc1ca-e59a-4791-8c21-8c7f946bb022)
> 
> 
> ### Checklist
> 
> - [X] I have checked the existing issues.
> - [X] I have read the Contributing Guidelines.
> - [X] I have read the Code Of Conduct.
> - [X] The changes doesn't break the code

@sampadatiwari30 assign labels too please
