### ISSUE TITLE
Title: Dark Mode

### ISSUE THREAD

**Issue by Sadab-Hussain** [ayush-that/FinVeda#992]
### Is your feature request related to a problem? Please describe.

Nowadays, many people experience eye strain, so I would like to add a dark mode feature to help alleviate this issue.

### Describe the solution you'd like.

I want to place a dark mode icon next to the login/register button in the navbar.

### Describe alternatives you've considered.

 Instead of placing the dark mode icon in the navbar, you could place it in the footer of the website.

### Add any other context or screenshots about the feature request here.

---------------------------------------------------------------------------
| Home | About | Trends | Tools | Blogs | Quiz  | Login/Register | 🌓 | 
---------------------------------------------------------------------------

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by Deekshashakyawal** [comment]
Add screenshot of the problem if you have checked the checkbox related to screenshot
