### ISSUE TITLE
[style]: hovering effect on navbar section

### ISSUE THREAD

**Issue by Codewithmeowmeow** [ayush-that/FinVeda#994]
### What's the style idea?

We need to improve  the style of buttons in navbar .adding hovering effect on buttons will make them look more good.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ayush-that/FinVeda/blob/main/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ayush-that/FinVeda/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

**Comment by Deekshashakyawal** [comment]
Star mark the repo and begin with the work
