### ISSUE TITLE
Add Logo 

### ISSUE THREAD

**Issue by adityakr0660** [ayush-that/FinVeda#996]
The logo should be added to clearly convey its primary intention, helping users understand what the brand represents.

![Final](https://github.com/user-attachments/assets/465baa01-c33d-4b35-b1d9-6e694b2125d2)

Please @ayush-that assign this task to me, as I am confident I can improve the logo by giving it a modern and attractive look, making it more visually appealing and professional.

**Comment by Siddhant432** [comment]
tell me if you like this one @sampadatiwari30 
![Screenshot (482)](https://github.com/user-attachments/assets/55fb933f-135e-4315-af33-5b6474b88a3f)
